### ISSUE TITLE
Managed Identity Wallet Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#103]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by OSchlienz** [comment]
**Dynamic Application Security Testing (DAST)**
OWASP ZAP scan assessed by @PiotrStys with following result:
![DAST](https://github.com/eclipse-tractusx/sig-release/assets/133339219/130dcd63-bbd6-4788-9e89-c3167fb0580e)

**Comment by OSchlienz** [comment]
**Container Scan**
[daily scan with trivy](https://github.com/eclipse-tractusx/managed-identity-wallet/actions/workflows/trivy.yml)
**Infrastructure as Code** 
[result KICS scan](https://github.com/eclipse-tractusx/managed-identity-wallet/actions/runs/6898199941)
@scherersebastian could you please confirm? Thanks!

**Comment by scherersebastian** [comment]
@OSchlienz I **no longer** perform QG checks

**Comment by pablosec** [comment]
@kelaja Security assessment/threat modeling was performed on 2023-11-21 without any high or above findings.

**Comment by klaudiaZF** [comment]
**SCA not passed** due to two high findings
<img width="835" alt="Managed-Identity-Wallet" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/60d61a30-2c02-4e45-86a5-35783467de47">

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:
![image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/717495aa-36b2-476a-8bea-4344b865cabd)
-> Secret scanning approved

Best regards
Daniel

**Comment by scherersebastian** [comment]
KICS / IaC passed.
Please check container scan findings

**Comment by kelaja** [comment]
kindly check:
- [ ] SCA
- [ ] SAST
- [ ] DAST

**Comment by RoKrish14** [comment]
@OSchlienz : Hey Oliver, 
regarding the DAST scan that you performed using OWASP ZAP, have you added Authentication check during the scan?

**Comment by klaudiaZF** [comment]
Hi @kelaja, SCA is still not passed. High findings aren't mitigated. 
<img width="837" alt="Managed-Identity-Wallet1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/e6024be1-438b-405d-aa99-e4a718d92d3c">

**Comment by OSchlienz** [comment]
> @OSchlienz : Hey Oliver, regarding the DAST scan that you performed using OWASP ZAP, have you added Authentication check during the scan?

Hi @RoKrish14 , the scan was performed by @PiotrStys

**Comment by klaudiaZF** [comment]
Hi All,

High findings in SCA are mitigated, so **SCA is passed**

**Comment by kelaja** [comment]
@PiotrStys kindly comment on SAST and DAST

**Comment by DnlZF** [comment]
Hi,
there are still no open GitGuardian findings.
-> **Secret scanning passed**

Best regards
Daniel

**Comment by Gitleena** [comment]
@kelaja :

SAST and SCA: **PASS**

**Comment by scherersebastian** [comment]
IaC passed
Container / Trivy passed

**Comment by mabige** [comment]
@kelaja everything seems to be done. Pls. close
