### ISSUE TITLE
Portal Release 23.12 Documentation Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#106]
# Release Documentation 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code** https://github.com/eclipse-tractusx/portal-cd/issues/126
https://github.com/eclipse-tractusx/portal-iam/issues/33

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [x] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [x] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by jjeroch** [comment]
UX approved; @kelaja please update the status

**Comment by jjeroch** [comment]
@vialkoje 
Gateway 4 für Release 23.12. steht wieder an.
Kannst du einen Review der Docu machen?
 
Wichtige Info – final steht die Docu erst mit Q-Gate 5.
Aktueller Content ist zu 90% wie die Docu von 23.09.
 
Was wir noch vor haben: Doku erweitern und die IAM Docu in das IAM Repo umzuziehen. Gerade ist das etwas falsch geplaced. Das hattest du auch im 23.09. Review angemerkt.
 
**Hier die Main Changes - Docus**

- Docu Repos:
https://github.com/eclipse-tractusx/portal-assets/tree/v1.7.0-RC2/developer
https://github.com/eclipse-tractusx/portal-assets/tree/main/docs
 

- Neuer IF Contract (under finalization)
https://github.com/eclipse-tractusx/portal-assets/blob/d960fa12bbf20c58f92add1bb2a126e9622ed5d0/developer/Technical%20Documentation/Interface%20Contracts/BPDM.md
 

- Verbesserte End User Docu IdP
https://github.com/eclipse-tractusx/portal-assets/tree/main/docs/02.%20Technical%20Integration/02.%20Identity%20Provider%20Management
 

- Docu bzgl Upgrade/DB changes with new release
https://github.com/eclipse-tractusx/portal-assets/pull/172/files

**Comment by evegufy** [comment]
# Source code

## Latest released versions for 23.12:

### Portal

Portal Chart: [portal-1.7.0-RC3](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-1.7.0-RC3)

Portal Frontend: [v1.7.0-RC3](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.7.0-RC3)

Portal Backend: [v1.7.0-RC3](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.7.0-RC3)

Portal Assets: [v1.7.0-RC3](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.7.0-RC3)

Portal Frontend Registration: [v1.5.2](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.5.2)

### IAM

CentralIdP: [centralidp-2.0.0-alpha](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.0.0-alpha)

SharedIdP: [sharedidp-2.0.0-alpha](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.0.0-alpha)

## Versions still expected as part of the testing phase (not yet released)

### Portal

Portal Chart: portal-1.7.0-RC4

Portal Frontend: [v1.7.0-RC4](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.7.0-RC4)

Portal Backend: [v1.7.0-RC4](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.7.0-RC4)

Portal Assets: [v1.7.0-RC4](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.7.0-RC4)

Portal Frontend Registration: [v1.5.3](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.5.3)

## Final 23.12 versions (not yet released)

### Portal

Portal Chart: portal-1.7.0

Portal Frontend: [v1.7.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.7.0)

Portal Backend: v[1.7.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.7.0)

Portal Assets: [v1.7.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.7.0)

Portal Frontend Registration: [v1.5.3](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.5.3)

### IAM

CentralIdP: [centralidp-2.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.0.0)

SharedIdP: [sharedidp-2.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.0.0)

**Comment by jjeroch** [comment]
Arc42: https://github.com/eclipse-tractusx/portal-assets/tree/release/v1.7.0-RC4/developer/Technical%20Documentation/Architecture
Interfaces: https://github.com/eclipse-tractusx/portal-assets/tree/release/v1.7.0-RC4/developer/Technical%20Documentation/Interface%20Contracts

**Comment by vialkoje** [comment]
Documentation for Architecture, Interface, User and Admin Doku approved

**Comment by carslen** [comment]
When will final releases be available? Will start QG checks after release of final version to avoid double work.

Will do my QG checks in these issues:
- eclipse-tractusx/portal-cd/issues/125
- eclipse-tractusx/portal-iam/issues/32

**Comment by carslen** [comment]
When will the final version be released, @jjeroch ?

**Comment by msinamci** [comment]
Hi @carslen next week - I will give an update here

**Comment by kelaja** [comment]
@evegufy kindly see comments from @carslen

**Comment by evegufy** [comment]
@carslen our Q4 was already last week, so too early to even have the last release candidate version ready and the testing phase has even been prolonged to next week, so no chance to have the final version ready.
Also, I want to avoid patch versions for the input which is potentially coming from you, as your check is part of the QG process as well.
As per release schedule, the final versions will be available by Dec 8, 2023, including potential changes coming from your comments.
Please check the latest available versions here: https://github.com/eclipse-tractusx/sig-release/issues/106#issuecomment-1812875857

**Comment by carslen** [comment]
_Source Code_ approved.

There are a few left over tickets in repositories with docker images as build artefacts regarding proper image tagging, which are agreed to be implemented until next release.

**Comment by kelaja** [comment]
all Done! Thanks guys! Congratulations for QG-Approval 🎉

**Comment by evegufy** [comment]
@Siegfriedk for writing the changelog: those are the final released versions for 23.12:

## Final 23.12 versions

### Portal

Portal Chart: [portal-1.7.0](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-1.7.0)

Portal Frontend: [v1.7.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.7.0)

Portal Backend: [v1.7.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.7.0)

Portal Assets: [v1.7.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.7.0)

Portal Frontend Registration: [v1.5.4](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.5.4)

### IAM

CentralIdP: [centralidp-2.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.0.0)

SharedIdP: [sharedidp-2.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.0.0)
