### ISSUE TITLE
Portal Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#107]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results** [link](https://github.com/SSIRKC/portal-assets/blob/patch-1/developer/Technical%20Documentation/Architecture/Security-Assessment.md)
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by evegufy** [comment]
## Threat Modelling Analysis results

assessment executed and completed together with @SSIRKC from Security Team on Nov 14, 2023.
documentation is still kept in confluence.

## Veracode UI

![image](https://github.com/eclipse-tractusx/sig-release/assets/46191613/a4b28cf0-2ffa-4185-82db-ee675bec7dc1)

## Invicti

![image](https://github.com/eclipse-tractusx/sig-release/assets/46191613/92776958-5b66-421b-b8ae-3d112b3ff625)

**Comment by SSIRKC** [comment]
Hi, 

Threat Modelling Analysis results
Analysis completed (operations excluded):
-> No additional findings could be identified. The components added do not expose the already known parts of portal.
List of risks generated or updated, rated & actions defined
Risks accepted or mitigation actions implemented and tested
no high threats acceptable
-> No high findings open
Artifact Repository:
risk register (decentral on Catena-X confluence)
-> Created and last updated on Tue 11/14/2023 a GitHub migration is ongoing.
Prime Contacts:
@SSIRKC 
Security Team: SEC0

**Comment by DnlZF** [comment]
![GitGuardian_Portal_17112023](https://github.com/eclipse-tractusx/sig-release/assets/99189503/fce5706f-cb0d-421a-bb0f-fc36349588a2)
No open GitGuardian findings

-> **Secret scanning approved**

**Comment by PiotrStys** [comment]
Hi All,
DAST-wise, Portal has been scanned by both with Invicti and OWASP ZAP and there have been no concerning findings.


![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/da5138b8-7366-4afb-9529-1449684a6f6d)

**DAST tests passed**

Regards,
Piotr

**Comment by klaudiaZF** [comment]
Hi All,

Portal-Backend_Processes-Worker
<img width="843" alt="Portal-Backend_Processes-Worker" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/ec5df916-c968-451a-af6d-71fe2aa671b1">

**SCA Passed**

Portal_Frontend
<img width="844" alt="Portal_Frontend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/f19a336e-75f2-451d-b7db-273bc3a6da78">


**SCA passed**


Registration_Frontend
<img width="843" alt="Registration_Frontend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/5ae97573-ec8e-438e-8128-d9719222d759">


**SCA passed**


Portal_Shared_Components
<img width="846" alt="Portal_Shared_Components" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/ceea0392-5ff2-46c6-810d-54562f012255">


**SCA Passed**

Portal-Backend_Administation-Service
<img width="846" alt="Portal-Backend_Administation-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/18b23f5e-b840-4480-8fea-968288a56a0e">


**SCA Passed**

Portal-Backend_Registration-Service
<img width="844" alt="Portal-Backend_Registration-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/673348ed-825c-46fd-8997-98e4d2d6032f">


**SCA Passed**


Portal-Backend_Notification-Service
<img width="844" alt="Portal-Backend_Notification-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/efc88a4c-2a27-47a2-9bac-0f0943bc8f70">


**SCA Passed**


Portal-Backend_Marketplace-App-Service
<img width="844" alt="Portal-Backend_Marketplace-App-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/35e30544-380f-4800-830b-fc86a0fa14d6">


**SCA Passed**


Portal-Backend_Services-Service
<img width="844" alt="Portal-Backend_Services-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/fb7ac648-e680-4fa2-a9a6-43a809d1ddbf">


**SCA Passed**

Portal-Backend_Portal-Migrations-Service
<img width="844" alt="Portal-Backend_Portal-Migrations-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/5ef0699d-9186-4751-bf07-bde76190d825">


**SCA Passed**

Portal-Backend_Maintenance-Service
<img width="843" alt="Portal-Backend_Maintenance-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/eeb14b04-c060-48b0-b034-c74c69f845bb">


**SCA Passed**


Portal-IAM_Seeding
<img width="842" alt="Portal-IAM_Seeding" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/3aadeaa6-6be0-49b1-8001-436765966f46">


**SCA Passed**

Portal-Backend_Provisioning-Migrations-Service
<img width="841" alt="Portal-Backend_Provisioning-Migrations-Service" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/7bdaa6af-325a-40b8-9147-e86c2a2c19f2">


**SCA Passed**

Portal Assets
<img width="847" alt="Portal Assets" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/89f3a926-5262-461d-b33e-f333f9eb2c41">


**SCA Passed**

Kind Regards,
Klaudia

**Comment by kelaja** [comment]
SAST, ContainerScan & IaC Check open

@PiotrStys kindly check SAST

@scherersebastian, @guenterban kindly check who can do ContainerScan & IaC Check,
The list I received does not seem to be correct any more: [Link for Consortia Members](https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621)

**Comment by PiotrStys** [comment]
Hi @kelaja, if you meant DAST, I have already posted my comment. If you really meant SAST, I believe, this is being done by someone else from the team.

**Comment by scherersebastian** [comment]
> SAST, ContainerScan & IaC Check open
> 
> @PiotrStys kindly check SAST
> 
> @scherersebastian, @guenterban kindly check who can do ContainerScan & IaC Check, The list I received does not seem to be correct any more: [Link for Consortia Members](https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621)

KICS passed. Please check trivy backend findings.

**Comment by kelaja** [comment]
Thanks a lot guys!
