### ISSUE TITLE
SD Factory Release 23.12 Documentation Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#110]
# Release Documentation 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code**

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [x] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [x] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by sharathshivprasad** [comment]
source code:
Latest release - https://github.com/eclipse-tractusx/sd-factory/releases/tag/sdfactory-2.1.8

Architecture Documents:
ARC 42 link - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/docs/ARC42.md

 Administrator`s Guide (User assistance):
Readme Link - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/README.md
install.md link - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/INSTALL.md

End-User Manual:
ARC 42 link - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/docs/ARC42.md
Readme link - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/README.md

 Interfaces Documentation:
OpenAPI spec is available in the repository at - https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.8/src/main/resources/static/SDFactoryApi-vRel3.yml

 UX consistency:
Not Applicable

Please review and approve.

**Comment by jjeroch** [comment]
"UX consistency Style Guideline for User Interfaces" - could not get validated yet. Validation needed after my return on the 30.11.

**Comment by sharathshivprasad** [comment]
hello @jjeroch This ticket is for SD Factory and not SDE. As I know, we don't have UI/UX for SD Factory.
Can you please pour more light on this?

**Comment by vialkoje** [comment]
you just drop me to the root location of the document for all documentations. I am looking for the dedicated documents serving the needs of user, developer, administrator and Interface user. Please at least point me to the right location.

**Comment by MehranRoshandel** [comment]
@dvasunin : can you please guide Jens to the recent changes in the SD-Factory documentation? If there is any changes.

**Comment by dvasunin** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/110#issuecomment-1805821048 has links to each individual document, i.e. arc42, readme, install and openAPI

**Comment by carslen** [comment]
After a first look into the repository, the application release for `2.1.7` is missing (GH release) as well as the Docker image has not been published. The referenced Helm Chart in the first comment won't install.

Has been all relevant code pushed to the upstream repository related to v2.1.7 to simply trigger the release process (build GH release and publish docker image)?

**Comment by MehranRoshandel** [comment]
@dvasunin and @adkumar1 please have a look at it.

**Comment by carslen** [comment]
Finished my QG review. I've found 2 things, for which I've opened issues, but they're not blocking the QG.

**Comment by MehranRoshandel** [comment]
@vialkoje https://github.com/eclipse-tractusx/sig-release/issues/110#issuecomment-1818757738
Can you please check the concrete changes and approve

**Comment by carslen** [comment]
> new PR to be added @almadigabor

I was in charge of doing QG checks for SD-Factory @kelaja. Please do not randomly pick System Team members and assign task. Thank you. I'll take care about eclipse-tractusx/sd-factory#83

**Comment by vialkoje** [comment]
expert approval granted for Architetcure-,Admin, user and interface doku
