### ISSUE TITLE
Digital Twin Registry Release 23.12 Compliance Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#113]
# Release Compliance 23.12

Source in Catena-X Confluence + Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ). (Source only accessible for Catena-X Consortia members in current transition phase)

- [x] **Gaia-X compliance** confirmed by dedicated expert.
  - Obtain approval from CX Gaia-X expert(s), prior to Gate review.
  - Provide info as early as possible; expect optimization loops based on feedback
  => check [linked PDF](https://confluence.catena-x.net/download/attachments/90498572/SD_Data_for_Onboarding.pdf?version=1&modificationDate=1690457195303&api=v2) summary for requirements (Source only accessible for Catena-X Consortia members in current transition phase).

  _Contact:_
     - Release Mangement

- [x] **GDPR compliance** confirmed
  (personal data; Data Protection & Privacy DPP)
  - assessment must be completed via Catena-X [GDPR questionnaire](https://confluence.catena-x.net/download/attachments/90498572/Catena-X%20GDPR%20Declaration%20and%20Requirements_V3.xlsx?version=1&modificationDate=1690457195339&api=v2) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - either the product/service doesn`t process any relevant data,
  - or - in case the assessment reveals potential issues - a more severe "Data Privacy Impact Assessment" shall be conducted (if applicable: robust mitigation actions must be completed)
  Provide evidence for GDPR compliance prior to Gate review. Previous assessments remain valid, as long as approach to handling of personal data was not changed.

   _Contact:_
     - Release Mangement

- [x] **Interoperability Check**

  Acceptance criteria are fulfilled as described in in the following area on confluence: [Interoperability Quality Gate Requirements](https://confluence.catena-x.net/x/DkwjB) (Source only accessible for Catena-X Consortia members in current transition phase.)

  - Approval will be documented centrally by Expert(s)

  - Obtain approval from Interoperability experts prior to Gate review.

  Therefore consult the [regular office hours](https://confluence.catena-x.net/x/fzkAAQ) as early as possible; expect optimization loops based on feedback. (Source only accessible for Catena-X Consortia members in current transition phase.)

  _Contact:_
    - SYSTEM ARCHITECT2

- [x] **Data Sovereignty Check**

  Acceptance criteria are fulfilled as described in in the following area on confluence:
  - [Data Sovereignty Guardrails for Release 3.2](https://confluence.catena-x.net/x/qPTeB) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - Approval will be documented centrally by Expert(s)
  - Obtain approval from Data Sovereignty experts prior to Gate review: Experts will schedule a review with your team.

  Expect optimization loops based on feedback.

  _Contact:_
    - SYSTEM ARCHITECT3,
    - SYSTEM ARCHITECT4

- [x] **Confirmation of _published_ CX Standards**
  
  Product Owner confirms:

  - The FOSS product under review is compliant to all relevant Catena-X Standards which are already published on the [Association website](https://catena-x.net/de/standard-library).
  - Failure to do so may ultimately make the reference implementation useless, as the mandatory CX Certification cannot be accomplished.

- [x] **Verification of _foreseen_ CX Standards**
  
  Product Owner confirms:

  - The content of upcoming CX Standardization Requests (STAN) has been reviewed and feedback was provided to the responsible PCA/BDA. As per current status, the FOSS product under review will be compliant as soon as the CX Standard is published. ([Info here](https://confluence.catena-x.net/x/XtyAAQ)) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - Minimum: PCA/BDA have finalized all release-relevant Standardization Requests (STAN). Those have passed the CX Association`s technical committee (TC4S) and are pre-published on the website. Opt-out period in progress.
  - Best case: Association Board approval available and CX Standard is published on website.

**Comment by bs-sili** [comment]
Release Mangement

- [ ] **Gaia-X compliance **:
No changes since Release 23.09.
Gaia-X compliance is not relevant for the decentral Digital Twin Registry.

**Comment by bs-sili** [comment]
Release Mangement
- [ ] **GDPR compliance**:
No changes since Release 23.09.
[Catena-X GDPR Declaration and Requirements_V23.12_DTR.xlsx](https://github.com/eclipse-tractusx/sig-release/files/13279611/Catena-X.GDPR.Declaration.and.Requirements_V23.12_DTR.xlsx)

**Comment by bs-sili** [comment]
SYSTEM ARCHITECT2
- [ ] **Interoperability Check**:
Interoperability was ensured to Release 23.09. Since then no changes have been made.

**Comment by thomas-henn** [comment]
**Confirmation of published CX Standards**

Yes, confirmation that the Digital Twin Registry under review is compliant to all relevant Catena-X Standards which are already published on the [Association website](https://catena-x.net/de/standard-library), especially the CX-0002.

**Comment by thomas-henn** [comment]
**Verification of foreseen CX Standards**

Yes, confirmation that the content of upcoming CX Standardization Requests (STAN) has been reviewed and feedback was provided to the responsible PCA/BDA. As per current status, the Digital Twin Registry under review will be compliant as soon as the CX Standard is published. ([Info here](https://confluence.catena-x.net/x/XtyAAQ)) (Source only accessible for Catena-X Consortia members in current transition phase.)

**Comment by bs-sili** [comment]
Hi @kelaja,

for the points:

- Interoperability Check
- Data Sovereignty Check
- Confirmation of published CX Standards
- Verification of foreseen CX Standards

The Expert is not defined / Expert Github account is not known, pls forward to expert. Many thanks!

**Comment by kelaja** [comment]
Hi @bs-sili 

Interoperability Check -> @HiHenrik
Data Sovereignty Check -> tbd
Confirmation of published CX Standards -> self assessed, thx @thomas-henn 
Verification of foreseen CX Standards -> self assessed, thx @thomas-henn

**Comment by bs-sili** [comment]
@kelaja 
Data Sovereignty Check has been updated.

**Comment by HiHenrik** [comment]
@kelaja 
Interoperability Check:
Acceptance criteria are fulfilled as described in in the following area on confluence:
https://confluence.catena-x.net/display/PL/Interoperability+Office+Hours+Backlog+-+QGate+Prep
