### ISSUE TITLE
Digital Twin Registry Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#115]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [ ] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by bs-sili** [comment]
@Security Team: SEC0

**Threat Modelling Analysis results:**

risk register for decentral Digital Twin Registry can be found here:
[Security Assessment - Digital Twin Registry](https://confluence.catena-x.net/pages/viewpage.action?pageId=51676105)

(Source only accessible for Catena-X Consortia members in current transition phase)

**Comment by bs-sili** [comment]
@Security Team: SEC1

**Secret scanning:**

Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/gitleaks.yml

**Comment by bs-sili** [comment]
@Security Team: SEC1
**Software Composition Analysis (SCA):**
Please have a look here: https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397650:30762582:30732796:30748446:::::4406303:

**Comment by bs-sili** [comment]
@Security Team: SEC3 SEC4
**Dynamic Application Security Testing (DAST):**
Invicti scan made - the scan result can be seen here: https://www.netsparkercloud.com/scans/report/d6334e3d93124a86927eb0c002e23e90/

**Comment by bs-sili** [comment]
@Security Team: SEC2
** Container Scan conducted:**
currently under clarification as Trivy scan is marking some unresolvable findings.

**Comment by klaudiaZF** [comment]
Hi All,

<img width="843" alt="Digital_Twin_Registry" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/1adb4aed-55f8-4a4e-9d72-dbc1498510f7">

**SCA Passed**

**Comment by PiotrStys** [comment]
Hello,

Regarding DAST, no high/critical findings reported by Invicti.

However, please make sure to validate the potential XSS findings that received the medium category.

**DAST Passed** 

Regards,
Piotr

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:

![Image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/b846bd2a-df80-4e7e-b2dc-2be5359b9832)

-> **Secret scanning approved**

Best regards
Daniel

**Comment by bs-sili** [comment]
Hi together,

I had a quick check in front of the upcoming QG meeting at Monday.
There still some checks open:
- Threat Modelling Analysis results
- Static Application Security Testing (SAST)
- Infrastructure as Code
- Container Scan conducted



Please have a look at that open points.

Many thanks in advance!

Best regards
Simone

**Comment by klaudiaZF** [comment]
Hi All,

**SAST passed**

<img width="833" alt="Digital-Twin-Registry" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/2614dacf-54ae-41b2-a85a-fcbfa59c0e6f">

**Comment by scherersebastian** [comment]
> Container

as stated.
KICS passed

**Comment by scherersebastian** [comment]
> @Security Team: SEC2 **Container Scan conducted:** currently under clarification as Trivy scan is marking some findings which cannot solved at the moment.
> 
> Update (24.11.2023) : As disscussed at the DevSecops meeting this Friday, the finding cannot be mitigated at the moment cause of license check. But as agreed the finding will not be a blocker for QG.

as stated.
KICS passed

**Comment by kelaja** [comment]
@guenterban is Threat Modelling okay?

**Comment by guenterban** [comment]
**Threat Modelling appoved**
