### ISSUE TITLE
Discovery Service (BPN Finder) Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#123]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by bs-sili** [comment]
@Security Team: SEC0

**Threat Modelling Analysis results:**
risk BPN Discovery
[Security Assessment - BPN Discovery](https://confluence.catena-x.net/pages/viewpage.action?pageId=81713190)

**Comment by bs-sili** [comment]
Security Team: SEC1

**Secret scanning:**
Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-bpn-discovery/actions/workflows/gitleaks.yml

**Comment by bs-sili** [comment]
@Security Team: SEC1
**Static Application Security Testing (SAST):**
one medium risk because of the class LocalOAuthConfig.java. -> This class is only used for local development. 
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1739413:30667629:30637860:30653510::5382788

**Comment by bs-sili** [comment]
@Security Team: SEC1
**Software Composition Analysis (SCA):**
The project is scanned and the Third party components are checked, See also:
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1739413:30667629:30637860:30653510:::::5382788:

**Comment by bs-sili** [comment]
Security Team: SEC3 SEC4
** Dynamic Application Security Testing (DAST):**
Invicti scan has been performed - please have a look: https://www.netsparkercloud.com/scans/report/6f74eaaf54bf4363040db0c002e18ea4/

**Comment by bs-sili** [comment]
@Security Team: SEC2
**Container Scan conducted:**
currently under clarification as Trivy scan is marking some unresolvable findings.

**Comment by PiotrStys** [comment]
Hello,

Regarding DAST, no high/critical findings reported by Invicti.



![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/f77a1560-ec29-4547-8cab-bc4c77b27220)



**DAST Passed** 

Regards,
Piotr

**Comment by DnlZF** [comment]
Hi, 
there are no open GitGuardian findings:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/fad62aa2-844f-421a-96c2-7ffef39da18c)


-> **Secret scanning approved**

Best regards
Daniel

**Comment by bs-sili** [comment]
@kelaja , @guenterban 
Hi together,

I had a quick check in front of the upcoming QG meeting at Monday.
There still some checks open:
- Threat Modelling Analysis results
- Static Application Security Testing (SAST)
- Software Composition Analysis (SCA)
- Infrastructure as Code
- Container Scan conducted

Please have a look at that open points.

Many thanks in advance!

Best regards
Simone

**Comment by scherersebastian** [comment]
> @Security Team: SEC2 **Container Scan conducted:** currently under clarification as Trivy scan is marking some findings which cannot solved at the moment.
> 
> > > Update (24.11.2023) : As disscussed at the DevSecops meeting this Friday, the finding cannot be mitigated at the moment cause of license check. But as agreed the finding will not be a blocker for QG.

as stated.
KICS passed
