### ISSUE TITLE
Semantic Hub Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#127]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by bs-sili** [comment]
@Security Team: SEC0

**Threat Modelling Analysis results:**
risk register
[Security Assessment Semantic Hub](https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+Semantic+Hub)
(Source only accessible for Catena-X Consortia members in current transition phase)

**Comment by bs-sili** [comment]
Security Team: SEC1

**Secret scanning:**
Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-semantic-hub/actions/workflows/gitleaks.yml

**Comment by bs-sili** [comment]
@Security Team: SEC1

**Static Application Security Testing (SAST):**
One medium finding which is mitigated - LocalOauthSecurityConfig.java is only used for local development. 
See also: https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1397649:30667647:30637878:30653528::4406299

**Comment by bs-sili** [comment]
@Security Team: SEC1

**Software Composition Analysis (SCA):**
Application is scanned and third-party compnents are scanned: 
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397649:30667647:30637878:30653528:::::4406299:

**Comment by bs-sili** [comment]
@Security Team: SEC2
**Infrastructure as Code**

**Comment by bs-sili** [comment]
Security Team: SEC1
**Static Application Security Testing (SAST):**
one medium finding which is mitigated.
Please have a look: https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1397649:30762585:30732799:30748449::4406299

**Comment by bs-sili** [comment]
**Software Composition Analysis (SCA):**
Please have a look here: https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397649:30762585:30732799:30748449:::::4406299:

**Comment by klaudiaZF** [comment]
Hi All,

<img width="839" alt="Semantic_Hub" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/11489b93-90c9-4e3f-878e-197d2deb670b">
 **SCA Passed**

**Comment by bs-sili** [comment]
@Security Team: SEC3 SEC4
**Dynamic Application Security Testing (DAST):**
Invicti scan has been made - the results can be seen here:  https://www.netsparkercloud.com/scans/report/7894969dc61a46834bf3b0c002e1fd39/

**Comment by bs-sili** [comment]
@Security Team: SEC2
** Container Scan conducted:**
currently under clarification as Trivy scan is marking some unresolvable findings.

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:

![Image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/bde6af11-82df-4fd6-9f98-9ccaaf5be839)

-> **Secret scanning approved**

Best regards
Daniel

**Comment by PiotrStys** [comment]
Hello, 

No critical/high findings reported back by the Invicti scan.

![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/c01b7aad-fdbd-4b4f-8592-6da58286cb97)

Please address the potential XSS medium-severity before the next QG.
**DAST PASSED**

Best regards,
Piotr

**Comment by bs-sili** [comment]
@kelaja , @guenterban 
Hi together,

I had a quick check in front of the upcoming QG meeting at Monday.
There still some checks open:
- Threat Modelling Analysis results
- Static Application Security Testing (SAST)
- Infrastructure as Code

Please have a look at that open points.

Many thanks in advance!

Best regards
Simone
