### ISSUE TITLE
Semantic Hub Release 23.12 Test Results Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#128]
# Release Test Results 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **E2E System Integrations Tests**

  -  To pass the Consortia Gate 4, evidence has to be made available that all test criteria up to and including TRL 4 & TRL 6 have been achieved.
  - Expected evidence = outputs of TRL 4 and TRL 6.
  - Test Management has mapped and described all mandatory tests for Consortia Quality Gates [HERE](https://confluence.catena-x.net/x/WQpHAw)(Source only accessible for Catena-X Consortia members in current transition phase).
  - Please focus on the columns "Derived Criteria" and "Outputs"  
  - Document your test results in Catena-X JIRA XRAY
  - Use the fields “DoD” and “Status” (story & solution level) to approve requirements.
  - Interim test results are required after Tests of each Sprint, this is pre-requisite to participate in E2E test phase

  _Contact:_
    - TEST MANAGEMENT

- [x] **Approval of User Journey**

  - CX Business Owner confirms: All acceptance criteria met (as defined in PI documentation)
  Relevant evidence is available

  _Artifact Repository_
    - [Jira Solution Level](https://jira.catena-x.net/projects/CXSOLUTION/summary)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practise_
    - PO to obtain BO approval prior to Gate review.
    - BO therefore to evaluate progress by participation at iteration demos.
    - BOs provide E2E test cases.
    - BOs welcome to act as tester.
    - BOs expected to participate in System Demo.

  _Contacts:_
    - FOSS Product Owners &
    - CX Business Owners

**Comment by thomas-henn** [comment]
**Approval of User Journey**

As solution owner for Semantics in Catena-X consortium, where "Semantic Hub" belongs to, I confirm that all acceptance criteria are met.

**Comment by bs-sili** [comment]
TEST MANAGEMENT

**E2E System Integrations Tests:**
Last test executions:
[Link to Test](https://jira.catena-x.net/browse/A1SLDT-1426)
[Link to execution](https://jira.catena-x.net/browse/A1SLDT-1427)

**Comment by kelaja** [comment]
@BerndRothbrust kindly check links from @bs-sili

**Comment by BerndRothbrust** [comment]
OK from TM @kelaja
