### ISSUE TITLE
Auto-Logout after 5 min (DEMO issue)

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-release#15]
## Description

If i log in to the Trace-X application, I am automatically logged out after 5 minutest and have to log in again

## Expected behavior

Logging out users should only happen after 24h of inactivity on the page

## How to reproduce

- Log in to Trace-X on the consortia INT environment
- Browse the page for 5 minutes
- The next page reload will redirect you to the login page

### Additional info

I'm using IE 6

**Comment by SebastianBezold** [comment]
Just created an fix in my component repo SystemGuideOrg/guide-demo#68

**Comment by FaGru3n** [comment]
- [ ] a
- [ ] b
- [ ] c
- [ ] d
- [ ]

**Comment by SebastianBezold** [comment]
Closing demo issue to not confuse with actual planning issues
