### ISSUE TITLE
Digital Twin KIT Release 23.12 Development View Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#150]
# Release 23.12 Development View

- [x] **API Specification / Protocols**
  - Documentation for the development view must be available in Eclipse Tractus-X as part of the development view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Responsible for Process: PCA/BDA 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [x] **Sample Data Available in Repository**
  - Sample data must be available in Eclipse Tractus-X as part of the development view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
     - Responsible for Process: PO / BO (from relevant Domain) 
    - Review by: PCA/BDA

- [x] **Reference Implementation**
  - Mandatory, if reference implementation is provided 
  - A reference implementation must follow the FOSS release gates and must be available in the corresponding repository in the Eclipse Tractus-X project. 

  _Best Practice:_
    - https://confluence.catena-x.net/x/IpSmB (Source only accessible for Catena-X Consortia members in current transition phase.)

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Responsible for Process: PO / BO (from relevant Domain) 
    - Consult: SYSTEM_TEAM1
    - Review by: PCA/BDA
 
- [x] **Development-View Architecture Documents in Repository**
  - Mandatory (for Platform Domain / CX ART) 
  - Documentation must be available in Eclipse Tractus-X as part of the development view MD files.

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PCA / BDA 
    - Responsible for Process: EAs 
    - Review by: PCA/BDA

**Comment by arnoweiss** [comment]
- `API Specification / Protocols` --> There's a bunch of [compiled openApi specs](https://eclipse-tractusx.github.io/docs-kits/next/kits/Digital%20Twin%20Kit/Software%20Development%20View/API%20AAS%20Discovery/dotaas-part-2-http-rest-discovery-service-specification) in the DT Kit that are all contextualized by the other views.
- `Sample Data Available in Repository` --> Mostly in [Tutorial](https://eclipse-tractusx.github.io/docs-kits/next/kits/Digital%20Twin%20Kit/Software%20Development%20View/Specification%20Digital%20Twin%20KIT)
- `Reference Implementation` --> [Linked in View](https://eclipse-tractusx.github.io/docs-kits/next/kits/Digital%20Twin%20Kit/Operation%20View%20Digital%20Twin%20Kit#digital-twin-kit).

**Comment by danielmiehle** [comment]
Approved.
