### ISSUE TITLE
BT RUL KIT (Remaining Useful Life) Release 23.12 Adoption View Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#182]
# Release 23.12 KIT Adoption View

- [ ] **KIT Repo in Tractus-X**
  - A KIT must have an own repository in Eclipse Tractus-X. The naming of the repository must have a postfix "-kit" 
  - e.g. "traceability-kit"
  - this applies to all KITs with own source code, test cases, test data etc 

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx)

  _Contacts:_ 
    - Responsible: PCA/BDA 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: Tractus-X Project Leads: KIT-CONTACT2, SYSTEM_TEAM3, SYSTEM_TEAM2

- [ ] **Vision and Mission Documents in Repository**
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/)
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F)

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Business Value Documents in Repository**
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Semantic Model standards submitted and published**
  - KIT Product Owner confirms: 
    - The KIT under review is compliant to all relevant Semantic Model Standards which are already published on the Association website. 
    - The content of upcoming Semantic Model Standardization Requests (STAN) has been reviewed and feedback was provided to the responsible PCA/BDA. 
    - An appendix has been created with a list of certification criteria (e.g., test cases) for the conformity assessment process. 

  _Best Practice:_
    - A KIT must link to the published semantic model standards on the Catena-X Association website.
    - https://catena-x.net/de/standard-library 
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F)
    - Note: Please create and submit standards in time according to process and timeline > The [standardization process](https://confluence.catena-x.net/display/CXSTAN/The+standardization+process) (Source only accessible for Catena-X Consortia members in current transition phase.)
    - Note: Failure to do so may ultimately make the KIT useless, as the mandatory CX Certification cannot be accomplished 

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Responsible for Process: Semantic Team 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Logic / Schema standards submitted and published**
  - KIT Product Owner confirms: 
    - The KIT under review is compliant to all relevant Logic / Schema Standards which are already published on the Association website. 
    - The content of upcoming Logic / Schema Standardization Requests (STAN) has been reviewed and feedback was provided to the responsible PCA/BDA.
    - An appendix has been created with a list of certification criteria (e.g., test cases) for the conformity assessment process. 

  _Best Practice:_
    - A KIT must link to the published logic/schema standards on the CX Website.   
    - https://catena-x.net/de/standard-library
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/)
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 
    - Minimum: PCA/BDA have finalized all release-relevant Standardization Requests (STAN). Those have passed the CX Association`s technical committee (TC4S) and are pre-published on the website. Opt-out period in progress. 
    - Best case: Association Board approval is available and CX Standard is published on website.
    - Note: Please create and submit standards in time according to process and timeline > The [standardization process](https://confluence.catena-x.net/display/CXSTAN/The+standardization+process) (Source only accessible for Catena-X Consortia members in current transition phase.)

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Responsible for Process: PCA/BDA 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Business Process Documentation**
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Architecture Documentation**
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Responsible for Process: EAs 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **Access and Usage Policies Documentation**
  - Mandatory if a use case needs access & usage policies. 
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 
  - Policies must contain: 
    - a human-readable text (aligned with legal) 
    - a technical policy that can be executed by the EDC 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 
    - https://github.com/eclipse-tractusx/edc-legal-policies 

  _Artifact Repository:_
    - [eclipse-tractusx](https://github.com/eclipse-tractusx) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Support for Data Sovereignty: SYSTEM ARCHITECT3
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PO / BO (from relevant Domain)

- [ ] **Tutorials and Documenation**
  - recommended; not mandatory
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

- [ ] **White Paper**
  - recommended; not mandatory
  - Documentation must be available in Eclipse Tractus-X as part of the adoption view MD files. 

  _Best Practice:_
    - [eclipse tractusx-docs-artefacts](https://eclipse-tractusx.github.io/docs/artefacts/) 
    - [How-to-create-a-KIT-website](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F) 

  _Contacts:_ 
    - Responsible: PO/BO (from relevant Domain) 
    - Consult: KIT-CONTACT1, KIT-CONTACT2 
    - Review by: PCA/BDA

**Comment by DennDir** [comment]
RUL KIT remains unchanged from previous release.
No action necessary.

**Comment by kelaja** [comment]
@maximilianong @danielmiehle okay from your side?
@DennDir this KIT is not part of the release management process yet because the "Release Management Status" is not tracked!
