### ISSUE TITLE
Sig-Release/Eclipse-Tractusx: Add a label for the Agents Kit

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-release#204]
## Description

I would be great if you could add an additional label either named "knowledge-agents" or "agents-kit".

this label would tag any overarching feature/discussion/issue to the repos "knowledge-agents", "knowledge-agents-edc" and "knowledge-agents-aas-bridge".

## Impact

Makes tagging of discussions and issues as well as planning release 24.03 easier

Team KA will move its complete planning to tractus-x for PI11/Release 24.03

## Additional information 

- seems like labels can only be managed by the sig-release team. I would propose @FaGru3n to look at this.

**Comment by FaGru3n** [comment]
Hi @drcgjung, 

sure we can add multible label´s, created a general idea on our discussion section to find out which general compnent labels we want to use for all and should be clarified that we are not overwelmed by labels and there colours in our Planning Board.

see the discussion: https://github.com/eclipse-tractusx/sig-release/discussions/205

For that we need also a clear description maybe in the README, which label is used when if Relase Management, CX-ART Planning and Open Planning and Kit-Planning using their own lables.... 😉 

Is it okay if we discuss it further in this section and i can close the issue?

**Comment by FaGru3n** [comment]
additional info: every committer can add/change/modify lables within Eclipse Tractus-X Repositories

> seems like labels can only be managed by the sig-release team. I would propose @FaGru3n to look at this.

https://www.eclipse.org/projects/handbook/#resources-github-access

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

**Comment by drcgjung** [comment]
@FaGru3n thanks for clearing the procedure!
