### ISSUE TITLE
Data Chain Kit Maintenance

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/sig-release#216]
## Description

This Feature will update and maintain the Data Chain Kit on Tractus-X 
## Impact

This has impact only on the item-relationship-project

## Additional information 

- https://eclipse-tractusx.github.io/docs-kits/kits/Data%20Chain%20Kit/Adoption%20View%20Data%20Chain%20Kit

## Linked Stories
- eclipse-tractusx/item-relationship-service#203
- eclipse-tractusx/item-relationship-service#204
- eclipse-tractusx/item-relationship-service#206
- eclipse-tractusx/item-relationship-service#215
- eclipse-tractusx/item-relationship-service#219

**Comment by jzbmw** [comment]
![Image](https://github.com/eclipse-tractusx/sig-release/assets/48311334/561dfff8-34de-4f7d-b9d2-cc72e02cda48)

**Comment by stephanbcbauer** [comment]
@jzbmw , @mkanal This was a feature for milestone 24.03. Is this an ongoing topic? Is it closed? Moved?

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
