### ISSUE TITLE
Integration of further aspect models in asBuilt lifecycle (ECU + Software Aspect )

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/sig-release#221]
## Description

Trace-X wants to integrate the functionality to handle more aspect models, so that we can also handle software and ECU data, which is modelled in aspect models and digital twins.

## Impact
- Trace-X

## Additional information 
- ECU Aspect Model is added to asBuilt and asPlanned lifecycle and is accessible over Trace-X
- Software Aspect Model is added to asBuilt and asPlanned lifecycle and is accessible over Trace-X

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
