### ISSUE TITLE
Add new wiki page for open planning description

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#229]
## Description

A more detailed description for the open refinement/planning is needed. This should be done as a WIKI Page.
The markdown file can be found here -> 
[Open-Refinement-Planning.md](https://github.com/eclipse-tractusx/sig-release/files/12914117/Open-Refinement-Planning.md)

**Comment by FaGru3n** [comment]
Hi @stephanbcbauer thanks for updating the wiki page and edited some typos and add a link to our issue linking discussion

also added into wiki Home-Page and add a little Footer to every Page to evole us together as a Community

see [Wiki-Page](https://github.com/eclipse-tractusx/sig-release/wiki/Open-Refinement-and-Planning-in-Open-Source-Communities)

**Comment by FaGru3n** [comment]
Hi  @stephanbcbauer  i think the initial version is done and can be adopted with more input from the feedback of the planning rounds 😉

**Comment by stephanbcbauer** [comment]
thx for püublishing.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
