### ISSUE TITLE
Adapt milestones within this repository

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#231]
## Description

not sure if it is by purpose (if yes, where does it come from?) or a bug, but the defined milestones seem not be correct.

![image](https://github.com/eclipse-tractusx/sig-release/assets/84396022/8d126e82-e07c-41aa-bcc4-b3261fec239c)

In my opinion it should be 24.03 and 24.06. And a question to "Due by" -> What is it for?

**Comment by FaGru3n** [comment]
Hi @stephanbcbauer was updated, 

<img src="[gif-der-wahl](https://github.com/eclipse-tractusx/sig-release/assets/121097161/b16c458c-e544-42f3-83c2-986af8291a00)" width="200" height="200" />

first editing was directly in the change of the CalVer and Dates was not communicated or know be me... 

also modified the Views in the [Release Board ](https://github.com/orgs/eclipse-tractusx/projects/26/views/8)
![image](https://github.com/eclipse-tractusx/sig-release/assets/121097161/b997e725-6bfe-46ac-90e7-bc14be8eecc0)
