### ISSUE TITLE
Remove Issuer Component from wallet

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#249]
## Description

With the new approach the issuer component shall be separated from the wallet. There is an own feature for the new separate issuer component. The scope of this feature is the removal of the existing issuer component which is currently (R23.09) integrated in the wallet.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
Expectation:

- MIW to exclude the backend business logic for expiry date creation
- MIW to update the credential POST calls by adding inside the request body the property "expiryDate" (see details below)
- MIW to update the credential POST calls backend logic to set the expiry date automatically to 12 month in case no expiry date is getting submitted


Impacted APIs:

- /api/credentials/issuer/membership => add inside request body "expiryDate" format: dd-mm-yyyy
- /api/credentials/issuer/framework => add inside request body "expiryDate" format: dd-mm-yyyy
- /api/credentials/issuer/dismantler => add inside request body "expiryDate" format: dd-mm-yyyy

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
