### ISSUE TITLE
API change for verified presentation

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#250]
## Description

The API has to be changed to enable security enhancements (details see concept work of the SSI Team in Catena-X)

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by borisrizov-zf** [comment]
Is this pertaining to the flow with an STS?

**Comment by stephanbcbauer** [comment]
open planning -> it is covered by #247

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
