### ISSUE TITLE
Connector Management

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#257]
## Description

Bulk Add Connectors to DGK: Registers a set of connectors in DGK at runtime so that the connectors can be managed by DGK 

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by dg-tsy** [comment]
The connector management API specifications are available at https://confluence.catena-x.net/display/CXAR/Data+Governance+KIT%3A+REST+API+of+decentral+components
