### ISSUE TITLE
Asset Management

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#258]
## Description

- Bulk publish assets to EDC(s): Syncs a set of assets to one or more EDCs 
- Sync existing assets from EDC to DGK: Imports assets, that have been published on an EDC without the DGK, into DGK
- View asset catalog by target EDC
- View asset catalog by policy
- Search asset
- Get asset
- Get asset history
- Check conformity 

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by dg-tsy** [comment]
The Asset Management API specifications are available at https://confluence.catena-x.net/display/CXAR/Data+Governance+KIT%3A+REST+API+of+decentral+components
