### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#259]
## Description

- Publish policy to target EDCs
- De-Publish policy from EDCs
- Publish contract to target EDCs
- De-Publish contract from EDCs

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by dg-tsy** [comment]
The Asset publication API specifications are available at https://confluence.catena-x.net/display/CXAR/Data+Governance+KIT%3A+REST+API+of+decentral+components

The Policy and Contract Publication topics will be handled in their own feature tickets.
