### ISSUE TITLE
Dashboard: Upgrade of Maps

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#26]
## Benefit Hypothesis

Currently the Country Risk Apllication uses a generic, low detailed Map with the library React Simple maps.
To further improve the usability of the dashboard it is necessary to upgrade these Maps to include much more details. With this it is easier to check country specific risks or now region specific risks like floods or natural catastrophes.

## Beneficiaries

The main beneficiaries are:
Compliance
Logistics
 
## Requirements:

A good Example for the Map which would be a good fit is: https://www.openstreetmap.de/
While upgrading the Map the current functionalities need to be maintained.

**These functionalities include, but are not limited to:**

- [ ] - Setting markers at Geocoordinates for each available Business Partners
- [ ] - (only shown after certain zoomed in state)
- [ ] - "Colouring" of the countries according to the selected Ranges and Ratings
- [ ] - Hovering over countries reveals relevant Information
- [ ] - Number of Business Partners
- [ ] - Country Score
- [ ] - Country name
- [ ] - Showing the Country names or ISO2 Country Code without hovering
- [ ] - Maneuveriability
- [ ] - Filtering for Countries with Business Partners

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by maximilianong** [comment]
This is historic and a requirement for the country risk reference implementation. The expert group BPDM decided to close this. If it's needed later, will be re-opened.
