### ISSUE TITLE
Asset Type Management

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#261]
## Description

Create asset type    

Creates a template for an asset, e.g. define a type of asset

- define the properties for that asset type
- associate policies templates
- associate contract templates

so that DGK

- can validate incoming and existing assets
- can create contract offers based on associated policy templates and contract templates

Edit asset template    

Modifies an existing asset template:

- modify type of asset
- modify the properties for that asset type
- modify target EDC

so that DGK

- can validate incoming and existing assets
- can create contract offers based on associated policy templates and contract templates
- can publish asset to target EDCs

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by dg-tsy** [comment]
This fearure is no longer planned.
