### ISSUE TITLE
Generic API Implementation and Standardisation

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#262]
## Description

Move from LSA-API (requiring pre-classification) of BPN-Types of provided data records  in legal (L), site (S) or address (A) to a generic API that allows to provide non-classified data records that then will get classified automatically. 

The approach has to cover all possibile business scenarios, as e.g. providing an address before the corresponding legal entity has been provided. 

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by maximilianong** [comment]
As discussed with POs & BOs - the team will update the inbox with updated features. This is not valid anymore.
