### ISSUE TITLE
Data Quality Dashbaord

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#264]
## Description

According to the quality rules for golden record data sets (see standards and corressponding features) a participant shall be enabled to review and inspect the quality of his  data records on a dashboard.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by HeyHardy** [comment]
please close this feature, its not part of the OP. thx

**Comment by maximilianong** [comment]
Discussed with POs and BOs.
