### ISSUE TITLE
Data model for certificates + API reference implementation

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#266]
## Description

https://jira.catena-x.net/browse/CXAR-1100

**Target:**

Making the data model for certificates available via API. So that solution providers can integrate this API and customers can request certificate information like requesting a specific certificate for a legal entity or to check if a legal entity has a valid specific certificate.

With PI10 we aligned on the final data model for now and defined the first API endpoints.

**Target for the next PI (11):**

- Reference implementation for the defined API, needed endpoints
- Writing the standard for 24-3 Release
- (Transfer the data model into a semantic data model)

**Stakeholders:**

Primary users of this will be solution providers / app providers in this area that want to bring a certificate app to the Catena-X marketplace. But also companies that want to use this a validation or information service.

**Technology:**

Same as gate or pool API from the business partner data management use case (REST, Springboot, Kotlin).

**Data model:**

The following data model needs to be transferred into a semantic data model (will be published after IP clearance).

API spec.:

The following API endpoints are needed and will be implemented:

API Calls Use Case 2: Request a specific certificate for Legal Entity by BPNL-Id (or BPNS/BPNA)

API-Call (get): [https://cert-system.net/api/catena/certificate/\](https://cert-system.net/api/catena/certificate/) {bpn}/{certificateType}
Returns requested certificate for a legal entity including all sites assigned to a certificate

API Calls Use Case 3: Simplified API to check if legal entity/site/address has requested certificate

API-Call (get): [https://cert-system.net/api/catena/certificate/simple/\](https://cert-system.net/api/catena/certificate/simple/) {bpn}
/{certificateType}
Returns true/false and certification valid-until, trust level

API Calls Use Case 4: Request a specific certificate document for Legal Entity by BPNL-Id (or BPNS/BPNA) 

API-Call (get): [https://cert-system.net/api/catena/certificate/document/\](https://cert-system.net/api/catena/certificate/document/) {cdID}
Returns requested certificate document (the file) for a legal entity including all sites assigned to a certificate

API Calls Use Case 5: Provide a specific certificate document for Legal Entity by BPNL-Id (or BPNS/BPNA)

API-Call (post): https://cert-system.net/api/catena/certificate/document
Provide a certificate document for a legal entity including all sites assigned to a certificate

Management API:

Mgmt Use Case in BDPM MetadataController to request a list of registered certificate types and also for registering a certificateType

API-Call (get): MetaDataController/api/catena/certificate-types - returns all currently registered certificate types
API-Call (post): MetaDataController/api/catena/create-certificate-type - register certificate type

## Additional information 

Pre-requisite:

- [x] Repository for this product is available --> https://github.com/eclipse-tractusx/bpdm-certificate-management

Tasks / User Stories:

- [x] Create issue with sldt semantic model team for initiating the process of a semantic data model for business partner certificates (https://github.com/eclipse-tractusx/sldt-semantic-models/issues/415)
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/6
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/5
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/4
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/3
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/2
- [ ] Standard for 24.03 Release

**Comment by maximilianong** [comment]
Done :)
