### ISSUE TITLE
Conception (incl. Cross Team/ Portal As Is Analysis) Multi Script 

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#268]
## Description

**Who is the user?**
All users of the Country Risk VAS application.
Motivation why this is needed?
The business would like to market the platform to multiple markets internationally. These markets may operate in different languages in contrast to what languages are currently offered by the platform. The broader adoption of the platform, would increase the value and probability of further development of the platform.

**What is needed?**
Elicit Requirements
Architecture
Confirm exact platform components of the platform required to support this feature (portal etc).
Business
Verify with other sharing members if they have suggestions/experience in how to solve this.
Functionality
Multi-Letter support
Multi-language support
Requirements Specification
Diagrams
Process flow to reduce system behaviour to logic.
Define functional + non-functional requirements.
High level effort estimation based on new understanding of scope.
Validation
Confirmation from business that specification + high level estimation 
Translation of scoping into user stories + prioritisation based upon newly discovered effort and priority.

**Who does what?**
Scoping - Enzio
Business Contact: Sebastian W
Stakeholders: portal team + 'Network of Network-Input'

see https://jira.catena-x.net/browse/CXAR-1080

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> issue could be closed as "not planned"

**Comment by maximilianong** [comment]
Concept work will be done inside the expert group (#124 - in Catena e.V. repo)
