### ISSUE TITLE
Dashboard: General Improvements

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#27]
## Benefit Hypothesis

The goal of this feature is to improve the general usability and user experience when using the Country Risk Dashboard.
This can be achieved through:

- [ ] new filter functionalities
- [ ] new sharing api´s
- [ ] adding new languages
- [ ] increasing readability of markers through hierarchy in L/S/A business partners
 
## Beneficiaries

The beneficiaries would be all users of the apllication

## Requirements:

These improvements would include, but are not limited to:

- Filtering for L/S/A business partners globally in all components
- pagination of loading business partners
- edc connection to pool and gate (when both are available)
- upgrade to newest frontend components provided by CX Portal
- improved filter functionality in the table
- customer
- supplier
- textsearch

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by maximilianong** [comment]
This is historic and a requirement for the country risk reference implementation. The expert group BPDM decided to close this. If it's needed later, will be re-opened.
