### ISSUE TITLE
Refactor Agent Plane-Matchmaking Agent Interface for Enabling Simple Graph Exchange

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#276]
Benefit Hypothesis

    the Simple Graph Exchanger Feature has already been developed in a preview branch of KA-EDC
    It adds the ability to host business data from the RDF Store over the Matchmaking Agent
    The Matchmaking Agent is currently integrated into the Agent Plane container that is bound to be public
    After the refactoring the Matchmaking Agent and RDF Store are in a separate container and Agent Plane and Matchmaking Agent communicate over a (private) network interface

Beneficiaries

    small and medium sized companies which want to directly upload/provide use case data
    security-aware companies who want to separate data storage from public API even for meta-data.

Acceptance Criteria

    Interface definition for Matchmaking Agent
    Matchmaking Agent + Datspace Synchronizer + RDF Store Code transferred to KA-RI
    Deployment of Matchmaking Agent
    Configuration of Matchmaking Endpoint in KA-EDC
    Interfacing the new Interface from KA-EDC

Storys

https://github.com/eclipse-tractusx/knowledge-agents/issues/54
https://github.com/eclipse-tractusx/knowledge-agents/issues/53
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/97

Estimated Story Points:
30 SP

**Comment by drcgjung** [comment]
Remaining Estimation: 15 SP
