### ISSUE TITLE
Testautomation for INT and E2E Tests

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#279]
## Description
see https://jira.catena-x.net/browse/CXAR-1096

https://github.com/eclipse-tractusx/bpdm/tree/main/docs/postman/automated-test

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
@HeyHardy @rybtim can you please update the ticket

**Comment by stephanbcbauer** [comment]
@HeyHardy , @rybtim  This was a feature for milestone 24.03. Is this an ongoing topic? Is it closed? Moved?

**Comment by ma3u** [comment]
@maximilianong Can you bring this into the BPDM Expert Group please?

**Comment by maximilianong** [comment]
Closed, aligned with expert group. Investigations are going on using cucumber. But it should be an acceptance criteria for each development. 

FYI @SujitMBRDI
