### ISSUE TITLE
Supply-Chain Domain Ontology

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#280]
Benefit Hypothesis

    using always digital twin/serial parts information is a too strong requirement for many use cases
    furthermore, the existing "hard-typed" relationships can be flexiblizized level (legal<->site<->address)
    many use cases can be based on purely abstract supply-chain information.
    the supply chain domain ontology will be able to relate the business partners based on a plethora of concrete data sources and diverse taxonomical conventioins.

Beneficiaries

    any use case/use case participant based on supply chain information

Acceptance Criteria

    domain ontology created
    domain ontology valid
    sample data bindings, use case templates
    Demonstration of integration of various level of data

Story

https://github.com/eclipse-tractusx/sig-release/issues/318
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/432

Estimated Story Points:
13 SP

**Comment by drcgjung** [comment]
# Story "Introduce Supply Chain Domain Ontology"

Repository https://github.com/catenax-ng/product-ontology

## Statement 

As an ESS use case developer, I want to have a supply-chain domain ontology such that I can formulate my use case roles, permissions and skills with a vocabulary based on BPN entities paired with abstract material flows.

## Acceptance Criteria

- Domain Ontology Exists
- Domain Ontology Validates

## Estimation 

5 SP

**Comment by drcgjung** [comment]
# Story "Document Supply Chain Domain Ontology"

Repository https://github.com/eclipse-tractusx/eclipse-tractusx.github.io

## Statement 

As an ESS use case developer, I want to have examples of data bindings and skills using the supply-chain domain ontology such that I can build a KIT or standard documentation out of it.

## Acceptance Criteria

- Data Example via CSV/TTL
- Data Binding via Serial Part Data
- Data Binding via Part as Planned Data
- Sample Skill resolving different levels of BPN data (L,S,A)
 
## Estimation 

5 SP

**Comment by FaGru3n** [comment]
> # Story "Introduce Supply Chain Domain Ontology"
> Repository https://github.com/catenax-ng/product-ontology
> 
> ## Statement
> As an ESS use case developer, I want to have a supply-chain domain ontology such that I can formulate my use case roles, permissions and skills with a vocabulary based on BPN entities paired with abstract material flows.
> 
> ## Acceptance Criteria
> * Domain Ontology Exists
> * Domain Ontology Validates
> 
> ## Estimation
> 5 SP

@drcgjung and @igorsvetlov  Please plan further story issues in Eclipse Tractus-X team / component repositories

**Comment by drcgjung** [comment]
done
