### ISSUE TITLE
Dependencies UC ESS & Knowledge Agents (Kit)

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#284]
This is the list of features needed for shipping an Environmental & Social Standards use case based on the Agents Kit for a release 24.03

    Simple Graph Exchanger
        Architecture Revision: Separate Matchmaking Agent from EDC Agent Plane
    Simple Graph Exchanger Frontend
        Extend the SDE for accessing the Matchmaking Agent or
        Have a new "SGE" application
    Abstract Supply Chain Ontology
        Trace Skill should be able to deal with BPNL, BPNS & BPNA
        Trace Skill should be able to deal with "arbitrary" hierarchical taxonomies.

**Comment by drcgjung** [comment]
its a double of the discussion https://github.com/eclipse-tractusx/sig-release/discussions/200
