### ISSUE TITLE
Dependencies Connector & Knowledge Agents Kits

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#285]
This is a placeholder for the topics appearing in the dependency session between the Connector & Agents Kits for release 24.03

    Dismissal of the agent-connector helm charts https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/main/charts in favor to separate agent-plane helm chart (see 

https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/61)

    Registering an additional plane when its pod has started
        Either setup code in the extension OR
        additional wget/curl commands on the pod
    ct test (TRG5) needs a VAULT, a MIW, a keycloak ... will there be some support by tractusx-connector charts?
        MXD mit Terraform

Migration of the v2 Management APIs to the v3 Management APIs

    There seems to have been a switch of "connectorId" and "providerId" between TX EDC Control-Plane 0.5.0 and 0.5.1?
    What about the "StatusChecker" for particular asset types. This currently leads to non-FINISHED transfer processes in 0.5.1
        do we need to extend the control plane to provide additional checkers OR
        will this be configurable (like a property per address type)
        will there be a default checker (NoopChecker or something)
    Should we switch to EDR cache instead of callback (the first will not work with control-plane-memory)
    Should we prefer a Data-Plane Proxy / Gateway approach versus Data-Plane Http Transfer
        asynchronous API
        decoupling of baseUrl and backend system

Future of [auth-jwt](https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/main/common/auth-jwt) (guess its redundant in the meantime) , synch with approach of @ndr-brt

**Comment by drcgjung** [comment]
its a double of the discussion https://github.com/eclipse-tractusx/sig-release/discussions/202
