### ISSUE TITLE
Upgrade to EDC 24.03

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#287]
Benefit Hypothesis

    no confusing deprecation warnings
    usage of the latest deployment features
    better integration & E2E performance

Beneficiaries

    all KA-EDC participants

Acceptance Criteria

    we do not use deprecated features, like the management/v2 anymore
    existing integration & E2E scenarios still work

Stories
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/94
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/95

Estimated Story Points:
10 SP

**Comment by drcgjung** [comment]
# Story "Upgrade to TX EDC 0.6.0"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want the KA Agent Plane to be compiled and deployed against EDC 0.6.0 and being aligned with its latest features such that I can seamlessly replace my existing EDC deployment/KA-enabled EDC deployment with the new version

## Acceptance Criteria

- new version of the helm charts for each variant that EDC provides
- dependencies adapted to TX EDC 0.6.0 / EDC ?0.3.1?
- integration test runs

## Estimation 

3 SP

**Comment by drcgjung** [comment]
# Story "Upgrade to TX EDC 0.X.0"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want the KA Agent Plane to be compiled and deployed against the 24.03 TX EDC and being aligned with its latest features such that I can seamlessly replace my existing EDC deployment/KA-enabled EDC deployment with the new version

## Acceptance Criteria

- new version of the helm charts for each variant that EDC provides
- dependencies adapted to TX EDC 0.X.0 / EDC ?0.4.X?
- integration test runs

## Estimation 

3 SP

**Comment by drcgjung** [comment]
# Story "Improve Agent-EDC Management Interactions"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a KA participant, I want that the KA Agent Plane efficiently communicates with the Control Plane such that negotiations will take place in a shorter, more stable fashion.

## Acceptance Criteria

- analyze the possibilities to use the EDR management API including callbacks.
- implement an improvement

## Estimation 

4 SP

**Comment by FaGru3n** [comment]
Hi @drcgjung and @TomBuchertTSystems could we close this issue? seems that is already done?
