### ISSUE TITLE
Portal Document Management System

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#294]
## Description

Validation of the need of an document management system connection from the portal backend instead of storing the documents inside the portal db

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by MaximilianHauer** [comment]
current assumption is that storage solutions of the used cloud provider would be used.
based on this assumption discussed with @jjeroch  and @evegufy  we do not see any benefit to follow up on this topic as a open source solution would not provide overarching benefits.
