### ISSUE TITLE
Credential revocation and renewal process

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/sig-release#303]
## Description

Extend the issuers capabilities to revoke his issued credentials
- for issuers: revoke issued VCs
- for holders: request the revocation of a VC from the respective issuer

Extend the issuers capabilities concerning the renewal of revoked/expired VCs
- for holders: request the renewal of a expired/revoked credential from the respective issuer

Also to be considered:
https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/M1/credential.issuance.protocol.md#8-vc-revocation

## Impact

MIW & Portal

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
