### ISSUE TITLE
FOSS - VAS Solution communication with Golden Record Service

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#304]
## Description
 see https://jira.catena-x.net/browse/CXAR-1091

Who is the user?

Country Risk Dashboard
Natural Person Screening Dashboard
Data Quality Dashboard
Bank Data Verification Dashboard
Sanction Party Watchlist Dashboard
CX Member System

Requirements:

Some Value Added Services needs to be aware about the Business Partners of the CX Member who subscribes the Value Added Service
We currently do not have a requirement to have a configurable orchestration of different value added services. The only requirement is that a NPS Service (if it was subscribed) can "stop/prevent" that a shared data set gets into golden record process
Technical Users and Roles are needed that manage the permissions, accessing business partner data
Must be developed till 2403?
Relevant for Standardisation 2403 oder 2406? Für 2403 Submitting till mid of november!

Open Questions:

Check Dependencies to orchestrator component?
Do we want that VAS know about business partners of a CX Sharing Member?
Are there alternative ways?
To Do:

create User Stories/User Journeys: 
PoV Value Added Service Anbieter
PoV  Sicht Sharing Member
PoV Sicht Core Service Provider (Cofinity)
PoV Sicht Portal

Motivation why this is needed?

Currently it is unclear if other services like value-added-services should have access to the sharing member gates --> The requirement is that the services must be somehow aware about the relevant business partners (BPNs)
It is also unclear if they should have access, if it is limited to read access or if they have read and write access
It is also unclear if there should be a data exchange between other services and the gates how this exchange and interface should look like 

What is needed?

We need a concept and architectural decision on how value-added-service must or must not interact/integrate against Sharing Member Gates
We also have to differentiate between accessing Sharing Member Gates vs. the hook in into the golden record / orchestrator process

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by maximilianong** [comment]
VAS integration are mentioned in the ARC42 on how to integrate them into the orchestrator component.
