### ISSUE TITLE
Agent AAS Bridge Release

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#306]
Benefit Hypothesis

    The prototype for the AAS bridge was successfully demonstrating how to implement an AAS 1.0 server on top of a SPARQL endpoint/knowledge graph source
    Applications using the AAS Api could thus transparently make use of "virtual" digital twins
    Upgrading to AAS 3.0 will enable to use this feature locally with standard CX logic/applications.
    integrating with the DT/AAS registry (api) and Interfacing with EDC will enable to use this feature in dataspace-wide use cases.

Beneficiaries

    any participant already deploying Knowledge Agent/Semantic Web Technology and wanting to participate in AAS use cases
    any application based on AAS
    any use case based on AAS

Acceptance Criteria

    AAS bridge implements AAS 3.0 (server + submodel, Part1)
    AAS bridge supports and implements AAS 3.0 (registry Part2)
        submodels can be registered in a remote registry
        you could use the builtin registry, alternatively
    AAS bridge can interface EDC and/or DGK to manage assets related to the AAS artifacts

Estimated Story Points:
50 SP

**Comment by drcgjung** [comment]
# Story "Upgrade FAAAST"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- FAAAST release that supports AAS 3.0

## Estimation 

5 SP

**Comment by drcgjung** [comment]
# Story "Upgrade AAS4J"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- AAS4J that supports AAS 3.0

## Estimation 

5 SP

**Comment by drcgjung** [comment]
# Story "Implement interface to AAS registry"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to interface an existing AAS registry

## Acceptance Criteria

- registration scripts and schedule
- deregistration scripts and schedule

## Estimation 

5 SP

**Comment by drcgjung** [comment]
# Story "Interface EDC/DGK"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to interface the EDC and/or the Data Governance Kit.

## Acceptance Criteria

- registration templates and schedule
- deregistration templates and schedule


## Estimation 

5 SP

**Comment by stephanbcbauer** [comment]
was presented in the open planning ⇾ developer and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @TomBuchertTSystems  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @TomBuchertTSystems 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by stephanbcbauer** [comment]
@TomBuchertTSystems, @drcgjung   This was a feature for milestone 24.08. Is this an ongoing topic? Is it closed? Moved?
