### ISSUE TITLE
Feature "Graph/Transfer Policies"

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#308]
Benefit Hypothesis

    These policies will allow to check the access to data structure on a semantic/conceptual level which is far more declarative than defining it on data property level
    These policies will allow to check the read, write, aggregation or purely the traversal of data
    It will be a blueprint for further validation schemes, such as for streaming graphs
    Instead of providing a graph asset/data schema per consumer role, this will give more freedom on tailoring existing graphs/schemas to various access scenarios

Beneficiaries

    any participant wanting to secure their graph assets in a fine-grained fashion.
    any use case developer who could now make such policies part of their use case description

Acceptance Criteria

    prototype (0.x) quality
    parsing of a SPARQL subset
    extensions to the validation context
    additional policy bindings which may need inference over a subset of the CX ontology

Estimated Story Points:
60 SP

**Comment by drcgjung** [comment]
# Story "Extend Policy Engine to Validate against Runtime/Message Context"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want my Control Plane being able to see (transfer/pipeline-dependent) features of the transferred message in the policy validation context such that policies could access those features.

## Acceptance Criteria

- prototype with http-transfer, agent-source
- can be as easy as giving the hashcode of the message body from the transfer

## Estimation 

4 SP

**Comment by drcgjung** [comment]
# Story "Define ODRL Bindings for Graph Policies"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want an extended policy constraint vocabulary such that I can define the reading, writing, traversal and aggregation of ontology-based concepts in by policy definitions.

## Acceptance Criteria

- control plane policy extension
- dummy implementations of the constraints
- vocabulary should use CX ontology terms
- can be put into a standard

## Estimation 

6 SP

**Comment by drcgjung** [comment]
# Story "Policy Implementation"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want an implementation of the constraints which operate on a list of reads, writes, traversals and aggregations with references to CX Ontology sets in the policy context.


## Acceptance Criteria

- unit tests

## Estimation 

10 SP

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
