### ISSUE TITLE
Protocol Compatibility - EDC, DSP, IATP

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#311]
## Description

As Dataspace participant, responsible for hosting an EDC instance, I want to know during the contract negotiation process if both connectors have the required extensions as well as versions in order to get data transferred in the last step.

## Impact

As of now, the whole network has to upgrade their connectors in case of a new release. Further, some partners might choose different additional Extensions (esp. for data-transfer) in future. Therefore a basic compatibility check has to be established between the connectors.

## Additional information 

- DSP Version
- (each Asset) Dataplane Type
- Policies
- IATP Version

- [ ] I'm willing to contribute to this feature

**Comment by stefan-ettl** [comment]
To be updated! @stefan-ettl

**Comment by SebastianOpriel** [comment]
+1

**Comment by ndr-brt** [comment]
Related issue about DSP on upstream: https://github.com/eclipse-edc/Connector/issues/3836

**Comment by lgblaumeiser** [comment]
Done for DSP as part of the protocol. Open for IATP, as this is not part of the protocol. Assets and policies depends on the catalog request, the consumer has to decide whether the provided assets can be consumed. A follow up item for IATP is to be created.

**Comment by lgblaumeiser** [comment]
Follow up issue: https://github.com/eclipse-tractusx/sig-release/issues/697, close this one, as the rest is handled
