### ISSUE TITLE
EDC - MXD - Onboarding a third participant “Trudy”

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#317]
## Description
We need a possibility to onboard a third participant into the dataspace. This does not include any onboarding using Portal or anything, just the necessary modifications in the keycloak config, MIW etc.
It is important to note that this should have “evolutionary character”, meaning the README should show how this works step-by-step. One way to achieve this, is to provide the added code as a patch, or on a separate branch, or as a separate terraform script.

## Additional information 
(https://github.com/eclipse-tractusx/tutorial-resources/issues/81)

- [ ] I'm willing to contribute to this feature

**Comment by paullatzelsperger** [comment]
this is already handled by https://github.com/eclipse-tractusx/tutorial-resources/pull/110
