### ISSUE TITLE
Story "Introduce Supply Chain Domain Ontology"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/sig-release#318]
# Story "Introduce Supply Chain Domain Ontology"

Repository https://github.com/catenax-ng/product-ontology

## Statement 

As an ESS use case developer, I want to have a supply-chain domain ontology such that I can formulate my use case roles, permissions and skills with a vocabulary based on BPN entities paired with abstract material flows.

## Acceptance Criteria

- Domain Ontology Exists
- Domain Ontology Validates

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/280#issuecomment-1770735415_

**Comment by FaGru3n** [comment]
wrong issue place @igorsvetlov could you please raise the issue under https://github.com/catenax-ng/product-ontology

**Comment by igorsvetlov** [comment]
@FaGru3n please re-open for now. We'll discuss with @drcgjung where to place this one and other related stories.
