### ISSUE TITLE
Portal - Locale functionality

### ISSUE THREAD

**Issue by wiegerterik** [eclipse-tractusx/sig-release#32]
## Description

The locale functionality in the portal refers to the ability to tailor the content, design, and user experience to specific geographical regions, languages, and cultural preferences. Implementing a robust locale functionality can have several significant impacts on the success and user experience of the marketplace:

1. Enhanced User Experience: By presenting content in users' native languages and currencies, the locale functionality creates a more personalized and user-friendly experience. Customers feel more comfortable navigating the marketplace, understanding product information, and making purchasing decisions.
2. Increased Conversion Rates: When users can interact with a website in their preferred language and currency, they are more likely to trust the platform and complete transactions. This can lead to higher conversion rates and improved sales for the app provider and service provider.
3. Expanded Global Reach: The locale functionality enables the online marketplace to reach a broader international audience. By catering to users from different countries, the marketplace can tap into new markets and expand its customer base beyond its original geographic region.
4. Currency Conversion and Payment Convenience: By supporting multiple currencies and local payment options, the locale functionality makes it easier for international customers to make purchases without worrying about currency conversion fees or payment barriers.
5. Regulatory Compliance: The locale functionality will allow us to create the basis to adapt to different legal and regulatory requirements in each target country. This helps ensure compliance with local laws, taxation, etc.In summary, implementing a locale functionality in our portal and marketplace can significantly support the international expansion, user engagement, and overall success. By catering to the diverse needs of users in different regions, the marketplace can create a more inclusive and appealing online experience, leading to increased sales and customer loyalty."

## Impact

- Customer Support: Offering multilingual customer support through the locale functionality enables the marketplace to provide assistance to customers in their preferred language. This leads to better customer satisfaction and support experiences.
- Payment integration must adhere to this concept. 

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by FaGru3n** [comment]
Hi @wiegerterik added the Feature custom field for your issue, is there still some questions?
![image](https://github.com/eclipse-tractusx/sig-release/assets/121097161/0fb4a8eb-63fc-41c5-b712-5619bc6fbac4)

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
