### ISSUE TITLE
Story "Create TTL-Based Converters"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/sig-release#323]
# Story "Create TTL-Based Converters"

Repository https://github.com/catenax-ng/product-ontology

## Statement 

As KA participant, I need script(s) that take my dataspace/use case roles as input and derive various artifacts (mapping templates, participant ontologies for query intellisense, contractdefinitions, policies and asset descriptions) in order to have blueprints for my interaction with the dataspace

## Acceptance Criteria

- Python scripts based on online ontology and use cases.
- usage documentation

## Estimation 

10 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/282#issuecomment-1770905783_

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
