### ISSUE TITLE
conception: modification / enrichment of own master data in CX-portal by CX-registred company

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#327]
## Description
 
see https://jira.catena-x.net/browse/CXAR-1085

 a s a CX Portal user want to change/enrich my own data

because there have been changes  which shall be reflected in CX pool (as basis for other use cases and related data consuments)

For this I need a functionality which distributes the changed data content  as data owner from CX portal to service provider along the GR process and feed back the results into the portal (update the data there)

 

Roles / rights: Who is allowed to feed in such changes (VW vs. AUDI, vs. Skoda,..., ALL legal entities?) --> what is the current registration process
Consideration of famliy tree/ relations (which level)
 

BPDM  + e.g. Portal Team or other Frontend --> collecting + alignment of requirements

 

 

Consider the topic of multi language in this context!

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

_note:_ description to use the portal is just an option (maybe there are others)

**Comment by jjeroch** [comment]
Closing due to duplicate to https://github.com/eclipse-tractusx/sig-release/issues/810
