### ISSUE TITLE
KA Release Prep 23.12

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#332]
Benefit Hypothesis

- Fulfill Release guidelines for being part of Release 23.12

Beneficiaries

- Q Gate Team

Stories

https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/105
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/106
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/107

Estimated Story Points:

10pt

**Comment by FaGru3n** [comment]
Hi @TomBuchertTSystems could we close this issue, seems that is already done or?
