### ISSUE TITLE
SSI - Define & implement vault Concept (PK storage) (CX-1037)

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/sig-release#34]
## Description
At the moment Private Keys are AES encrypted stored in the MIW Postgres Database; For the future a vault concept for PK storage should be developed and implemented.

## Impact
Enhance security level

## Additional information 
# MIW - Direct Access
 
- **Save the keys in vault:** MIW retrieves the key of the corresponding tenant/wallet from the vault.
 
## Downsides:
 
- MIW can access all keys directly.
 
## Crypto Service
 
- **Implementation:** Implementing a crypto service that is started for each tenant.
- **Communication:** Wallet communicates via REST with the crypto service to create proofs for VP.
- **Key Retrieval:** Crypto service is able to retrieve the corresponding private key of the tenant/wallet to execute crypto operations.
- **Access Restriction:** MIW has only access to the crypto service and not the vault itself.
- **Security:** Unique secret for the access to the vault for each crypto service.
 
## Variants:
 
1. **Save encryption key and encrypt the private keys in DB:** Current approach, but for each service in personal DB.
2. **Save the actual keys in the vault.**
3. **Use vault for PVC encryption:** Key Management Service needed.

- [ ] I'm willing to contribute to this feature

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
