### ISSUE TITLE
VAS integration to Portal and Marketplace

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#341]
## Description

As a sharing member I want to subscribe to a value added service in the marketplace which will provide me with additional information regarding my business partners. Therefore it is necessary that the value added service is allowed to access my company specific GATEs (technical User) to retrieve the business partners which I am allowed to view. The Golden Record Service and Value Added Service do not necessarily have to be hosted/offered by the same operating companies.

## Acceptance Criteria:
- [ ] Availability of a joint aligned architecture of user and role management between VAS, Golden Record Core and Portal user and authorization management.
- [ ] Availbility to set up technical users for each CX Member Gate with read and write capability
- [ ] Availability to configure technical users for VAS solutions with read and write
- [ ] capability and handling of dependencies of VAS solutions between each other and between a VAS solution and the Gate as part of the Golden Record Core Service.
- [ ] Testing of configured VAS solution user roles while using App Provider Portal was successful

## Additional information 
https://jira.catena-x.net/browse/CXAR-1092 

- [ ] I'm willing to contribute to this feature

**Comment by maximilianong** [comment]
Done
