### ISSUE TITLE
E2E System Integrations Tests

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#352]
To pass the Consortia Gate 4, evidence has to be made available that all test criteria up to and including TRL 4 & TRL 6 have been achieved.
Expected evidence = outputs of TRL 4 and TRL 6.
Test Management has mapped and described all mandatory tests for Consortia Quality Gates [HERE](https://confluence.catena-x.net/x/WQpHAw)(Source only accessible for Catena-X Consortia members in current transition phase).
Please focus on the columns "Derived Criteria" and "Outputs"
Document your test results in Catena-X JIRA XRAY
Use the fields “DoD” and “Status” (story & solution level) to approve requirements.
Interim test results are required after Tests of each Sprint, this is pre-requisite to participate in E2E test phase
Contact:

TEST MANAGEMENT

**Comment by jzbmw** [comment]
Currently the IRS, is not separately participating on the E2E test. See https://confluence.catena-x.net/display/BDPQ/%28E2ETR%29+Test+Scenarios for further information
