### ISSUE TITLE
Created by mistake inside this repository > "Improving the current test cases"

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sig-release#359]
check the commented ".andExpect(content().json(" and adjust them properly to the new model structure e.g. for specificAssetId. At the moment here still the old value from the previous api are checked.-->

Linked to --> https://github.com/eclipse-tractusx/sig-release/issues/347

**Comment by bs-sili** [comment]
Link to #346

**Comment by RazvanZmau** [comment]
We close this ticket because it was created in a wrong repository.
