### ISSUE TITLE
Add release automation workflow

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-release#367]
Currently we are using automation based on [release-drafter](https://github.com/release-drafter/release-drafter), to create GitHub releases. 
We had some issues with this in the past, so I want to try out an alternative, that is working slightly different.
I want to try, if the approach that [release-please](https://github.com/googleapis/release-please) is proposing, could be a better fit. Not only for this repository, but also as potential workflow for other repos, so that manual tasks for committers could be limted.

**Comment by FaGru3n** [comment]
👍🏼  +1  approval

**Comment by SebastianBezold** [comment]
Closing, since there is no follow-up discussion
