### ISSUE TITLE
EDC - Describe Object (Asset) Lifecycle

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#376]
As an EDC operator, I want to know about the lifecycle of EDC Assets. 

On a high-level, the states INITIAL, ACTIVE and ARCHIVED have to be described and related to states of the EDC Statemachine. Overall, the EDC database size should be stable and not growing forever. Therefore there need to be a process to archive/delete deprecated/unvalid or unused objects with references to each other (asset, policy, contract def., agreement, transfer state, etc.).

Follow-Up Feature:
- Guidance about Asset Lifecycle(s) and especially archiving/deleting of assets/objects in the EDC.
- If needed additional functions/methods to trigger those archiving or deleting routines.

**Comment by arnoweiss** [comment]
On a related note: I found Paul's comments here [1] really useful. Reflecting the behavior more explicitly in the objects is great.

[1] https://github.com/eclipse-edc/Connector/discussions/3664

**Comment by saschaisele-zf** [comment]
This issue led to the following discussion:
[Contract Agreement Lifecycle](https://github.com/eclipse-tractusx/tractusx-edc/discussions/1049)
