### ISSUE TITLE
Please close the Release issues that are done

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-release#379]
Hi @kelaja and @RolaH1t 

fist many thanks for your work for the current release "23.12".

second saw that you have moved many issues in your Release Management project board [view](https://github.com/orgs/eclipse-tractusx/projects/26/views/17) to the done section could you also close the issues as well. IMHO then everybody know that the release criteria issues are done... 

Thanks in advance.

**Comment by FaGru3n** [comment]
All Issue View sorted and filted by open issues on the Board: [Issue List to close or verify](https://github.com/orgs/eclipse-tractusx/projects/26/views/12?filterQuery=is%3Aopen++issue-type%3Arelease_ac+&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status)

**Comment by FaGru3n** [comment]
Hi @kelaja @RolaH1t do have any concerns against it?

**Comment by kelaja** [comment]
@FaGru3n all issues closed! Thank you for the reminder 🙌

**Comment by FaGru3n** [comment]
#repost 😉 

Hi @kelaja and @RolaH1t
 
fist many thanks for your work for the current release "24.03".

IMHO then everybody know that the release criteria issues are done...

Filtered issue list:
https://github.com/eclipse-tractusx/sig-release/issues?q=is%3Aopen+is%3Aissue+milestone%3A24.03+R24.03

Thanks in advance.

**Comment by kelaja** [comment]
Thanks for the reminder - done!
