### ISSUE TITLE
Initializing the github client is broken

### ISSUE THREAD

**Issue by netomi** [eclipse-tractusx/sig-release#38]
In the following lines of code

https://github.com/eclipse-tractusx/sig-release/blob/56a63a385e431cc52a6488e308f77418b28a4f44/trg-checks-dashboard/internal/templating/tractusx.go#L183-L190

you initialize a github client. However, when no token is specified in the environment, you create a client without authentication and just afterwards you overwrite that with a client with a non existing token.

An else branch is missing imho.

**Comment by netomi** [comment]
Also using oauth2 is wrong when testing with personal access tokens, you should use this instead:

https://github.com/google/go-github/blob/master/example/tokenauth/main.go#L28C19-L28C33

Its badly documented in go-github imho.

btw. you should be able to just use the normal GITHUB-TOKEN when accessing the repos read-only imho.

**Comment by SebastianBezold** [comment]
HI @netomi,

sorry for the late reply and thanks for pointing out. Already on it :)
