### ISSUE TITLE
TraceX - Ensure BPN determination while user enters company name / data

### ISSUE THREAD

**Issue by wiegerterik** [eclipse-tractusx/sig-release#382]
## Description
definition of BPN not usable, chosen product should already be linked to one or a range of potential partners; supplier number would be an alternative that’s rather available or at least the company name should be enabled
-->

## Impact
- Enhanced usability
- 
## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by jzbmw** [comment]
@wiegerterik I need some more Information regarding this. 
Does that rely to the quality investigations / alert?

**Comment by mkanal** [comment]
Switching to SingleLevelUsageAsBuilt and SingleLevelUsageAsPlanned 3.0.0 the businessParterNumber will be included.

**Comment by mkanal** [comment]
https://github.com/eclipse-tractusx/item-relationship-service/issues/488

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
