### ISSUE TITLE
TraceX - data / file upload for additional information / pictures is needed

### ISSUE THREAD

**Issue by wiegerterik** [eclipse-tractusx/sig-release#383]
## Description
Ensure that additional information can be entered for Quality Alerts and Investigations

## Impact
- Functional demand
- Usability feature

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by jzbmw** [comment]
I think for this the standard regarding quality notification needs to be adapted.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
