### ISSUE TITLE
TraceX - alerts / investigation cannot be forwarded within trace-X but new ones have to be set up (tiresome)

### ISSUE THREAD

**Issue by wiegerterik** [eclipse-tractusx/sig-release#385]
## Description
![image](https://github.com/eclipse-tractusx/sig-release/assets/124060080/8b5838a7-caab-4435-9002-92c90264c397)

Additional requirement to increase the number of users and to allow using tracex even if suppliers are not yet a tracex user.
idea: view via invitation (“share this alert via mail and ask partners to register”)
-->

## Link 
- parent of https://github.com/eclipse-tractusx/traceability-foss/issues/935

## Impact
Scalability and usage enabler

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by mkanal** [comment]
- [ ] Trace-X should support forwarding of notifications in both directions over more tier levels respecting data sovereignty
- [ ] Forwarding has to be acknowledged on each forwarding tier level 
- [ ] Responses for notifications should be forwards as well (acknowledge is required on tier level)

LOP 
- [ ] As Trace-X MUST be interoperable with other solutions, this might this functionality might be standardized

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
