### ISSUE TITLE
Upgrade to EDC 24.05 and Simplify Deployment

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-release#390]
# Benefit Hypothesis

With 24.03, KA comes with its own Agent Plane Image(s) and three complete (=copied) Agent-Connector charts (in-memory, psql-hashicorp, psql-azure-vault). These charts are without helm tests because they are relying on external dependencies [vaults])

For the 24.05  Release we want to ensure 

- compatibility with EDC binaries and images
- no confusing deprecation warnings in the Agent Plane
- usage of the latest deployment features (=charts) and the latest Control Plane(s)
- better integration into alternative EDC deployments (no-psql, other vaults, other data planes)
- helm test configuration using surrogate vaults
- KIT description should reflect the new deployment possibilities

# Beneficiaries

- any participant already deploying an EDC without agent
- any newly onboarding participant unsure which chart to use
- enablement providers who want to offer variants in a more easy fashion

# Acceptance Criteria

- we do not use deprecated features
- existing integration & E2E scenarios still work
- deployment can be done with a separate modular chart with scalable number of data/agent planes
- working helm charts test

# Stories

https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/94
https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/98

# Estimation

5 SP

**Comment by drcgjung** [comment]
# Story "Implement Data-Plane Chart"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want the KA Agent Plane to be deployable alongside EDC charts such that I can seamlessly extend my existing EDC deployment.

## Acceptance Criteria

- find out how the dataplane can register/deregister itself in the control plane
- implement startup/teardown actions in the agent plane deployment
- make the agent plane chart refer to values in the umbrella chart
- extend the ct test 
- remove the old charts

## Estimation 

10 SP

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)
