### ISSUE TITLE
Use the latest version of EDC Management APIs

### ISSUE THREAD

**Issue by dg-tsy** [eclipse-tractusx/sig-release#395]
## Description
As a Data Governance Kit Team,
We need to adapt to the latest EDC Managment API version
So that we are compatible with latest EDC changes.

## Stories
- [ ] https://github.com/eclipse-tractusx/sig-release/issues/465
- [ ] https://github.com/eclipse-tractusx/sig-release/issues/466

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
