### ISSUE TITLE
Ensure that Sites (BPNS) can only be shared by Site owner

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#403]
## User Journey
 
As Catena-X I want to ensure that Sites (BPNS) can only be created/updated by its owner. This is necessary as sites combine several BPNAs and cannot be checked against official registers. If there is no restriction there might be a data quality problem.
I as a sharing member want that site information about a sharing member can only be updated by the respective sharing member to ensure data quality.
If it is not possible to technologically or procedurally (idea: community site acknowlegement process) verify that a BPNS belongs to a BPNL, it needs to be evaluated which impact possible error cases or malicious intent have. How is it ensured that a claimed BPNS is verified?
Description potential Site acknoledgement process: Another member can confirm that a sharing member is the data owner and thus is allowed to create or upload this data. See LinkedIn skill endorsement process. (buzz words: decentral, community approach)

## Impact

If possible, please provide insight in what and how many components and teams might be affected or give a hint, if the feature implementation might result in breaking changes.
If there are dependencies to other features please name it.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by maximilianong** [comment]
Outdated - will reopen if necessary
