### ISSUE TITLE
BPDM Data Sovereignity 24.05

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#404]
## Description

Define Frame Conditions for Data sharing in accordance to Data Sovereignity QG Criteria 

## Impact

If possible, please provide insight in what and how many components and teams might be affected or give a hint, if the feature implementation might result in breaking changes.
If there are dependencies to other features please name it.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by zygokaktus** [comment]
Done
