### ISSUE TITLE
Additional BPN Endpoint in Gate

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#405]
## Description

Provide an additional endpoint in the gate from which the Value Added Service can retrieve unique BPNLs, BPNSs and BPNAs

User Journey:
[ADR-0014: Value Added Service connection to Gate - CX Core ART - Confluence (catena-x.net)](https://confluence.catena-x.net/display/CORE/ADR-0014%3A+Value+Added+Service+connection+to+Gate)

## Impact

If possible, please provide insight in what and how many components and teams might be affected or give a hint, if the feature implementation might result in breaking changes.
If there are dependencies to other features please name it.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by zygokaktus** [comment]
@nicoprow : Ist this done ? Please update / close this issue. THX

**Comment by nicoprow** [comment]
@zygokaktus This feature was created, deprioritized and I think now does not have any stakeholders anymore. 

I will close it. In case some use case has any demand for this, we can reopen it again.
