### ISSUE TITLE
Concept for clearing point for classification proposals LSA and for GR change proposals in general

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#406]
## User Journey:

To further improve the golden record service there should be the possibility to receive input from the sharing member in case of uncertainties. E.g. if a business partner is uploaded to the gate via the generic endpoint, the operator needs to make a typisation if the data set is L or A. In case the operator cannot make a typisation with a high confidence interval, there shall be the possibility for the sharing member to receive an item in his work basket. This work basket should be visualized and the sharing member has to make a decision first before the data set is being processed further.
Possibility to overrule "Ownership"

## Description

As a CX member I want to have the possibility to "overrule" Service provider  proposals or undefined data  regarding

BPN typification (LSA)
Address data
Name data
Identifier data
especially for own company data, because there will be constellations where the output of the service provider is wrong.

For this I need functionality which will be described in the course of this concept work.

Define possible/additional check steps beside the GR release step for having the chance to intervene at an earlier stage
Feedback (e.g. in the form of an error code) in case of no possible assignment of the data record or contradictory information [relevant data fields in staging area?!]

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by zygokaktus** [comment]
obsolete here but topic still not fully covered , so there might be work to do later in a new issue
