### ISSUE TITLE
App registration of the golden record. The operator must provide the customer his GATE-URL.

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#407]
## Description
As a golden record provider I want an automated process how a sharing member gets his own gate. The sharing member needs to automatically get the information which GATE-URL and endpoints it needs to integrate.
As a sharing member I want to automatically receive all necessary information (GATE-URL, credentials, etc.) after subscribing to the golden record service in the marketplace.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by zygokaktus** [comment]
obsolete
