### ISSUE TITLE
Concept & implementation of BP Predecessor/Successor

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#408]
https://jira.catena-x.net/browse/CXAR-1094
Details in GitHub TBD

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by maximilianong** [comment]
Closing it there and reopening in Catena-X e.V. board (#125)
