### ISSUE TITLE
Realization of concept of Confidence Level (Data Ownership)

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#409]
https://jira.catena-x.net/browse/CXAR-1017 
Details in GitHub TBD

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by HeyHardy** [comment]
data model could is here.
https://github.com/eclipse-tractusx/bpdm/issues/631

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by zygokaktus** [comment]
Done  for reference implementation

Operator to provide + prove "real life " solution
