### ISSUE TITLE
MIW improve DID document generation and verification

### ISSUE THREAD

**Issue by ma3u** [eclipse-tractusx/sig-release#427]
# Catena-X only supports JsonWebSignature2020
 
* org.eclipse.tractusx.ssi.lib.model.proof.jws.JWSSignature2020 as single supported **type**
* org.eclipse.tractusx.ssi.lib.model.proof.ed21559.Ed25519Signature2020 is obsolete for proofs?
* any other types?
 
 
## Proofs
 
* **proofPurpose** existence and value are currently not checked when parsing a credential, e.g. during validation
* *verificationMethod* is not retrieved based on **proofPurpose** value (first one found is used)
 
 
#### SSI Lib
 
* validate structure when parsing
    * if VC check that **proofPurpose** exists with value *assertionMethod*
    * if VP check that **proofPurpose** exists with value *authentication*
* retrieve *verificationMethod* based on **proofPurpose** value (*assertionMethod* | *authentication*)
 
 
#### MIW
 
* generation of DID Documents with correct verification realtionships
* generation of VC/VP with the correct **proofPurpose**
* migrate/replace existing DID Documents to correct structure containing the appropriate relationships

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
