### ISSUE TITLE
BPDM Certificate Management KIT + data model standardization 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-release#428]
## Description
This feature is an addition to what already started with this feature in PI11: 
https://github.com/eclipse-tractusx/sig-release/issues/266

- The endpoints have been set up and implemented. On the technical side, we are working on enabling the EDC and finalizing the framework agreement for exchanging certificate data.
- We need to standardize the data model using the SAMM modeling language.
- All the work done in the last PI will be packaged into a KIT and made available to the open-source community.
- In the upcoming PI, we will test the API with a solution/data provider. If any changes are needed, we will plan for adoption.

- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/12
- [x] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/32
- [ ] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/22
- [ ] https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/27

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog), maybe there is an impact section needed?

**Comment by jjeroch** [comment]
@maximilianong  please check the ticket status

**Comment by maximilianong** [comment]
Moving this to 24.12.

**Comment by stephanbcbauer** [comment]
@maximilianong this feature was already refined some time ago and the status could be set to backlog?

**Comment by maximilianong** [comment]
Done
