### ISSUE TITLE
EDC - Concept for a "Return Channel"

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#432]

**Comment by SebastianOpriel** [comment]
@stefan-ettl Maybe this discussion could also be kept in mind: https://github.com/International-Data-Spaces-Association/ids-specification/issues/148

**Comment by SebastianOpriel** [comment]
@lgblaumeiser you closed as completed. Can you please refer to the commit/PR solving this issue?
