### ISSUE TITLE
PURIS Mini App (FOSS Applicaton) R24.03

### ISSUE THREAD

**Issue by PhillipNalesny** [eclipse-tractusx/sig-release#438]
## Description

The PURIS Mini App is an application to make the PURIS standards useable for PURIS users. 

Benefit Hypothesis
In order to have the Fraunhofer FOSS Application ready for release, it needs to reach Quality Gate 5. Therefore it will have the needed maturity to be useful for PURIS Users.

Beneficiaries

PURIS Team to have it ready for release
PURIS Users to have well working software
## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
@PhillipNalesny  please clean up the ticket - the release if already closed/over.

**Comment by tom-rm-meyer-ISST** [comment]
Release has been handled with #510. Thus, I close the ticket
