### ISSUE TITLE
ESS Bottom Up

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#451]
## Description

This Feature implements the ESS Use Case in a bottom up approach. A company where an incident has been detected broadcasts the supply chain in an upwards direction (supplier - customer) about the incident. The OEM is notified regarding the incident initiated from the incident company. 

## Impact

-  irs product:
   - On incident and any tier level:  identifies and collects the customer BPNL to be notified regarding the incident . 
- ESS Incident App
   -  recursive incident reporting along the supply chain and the release process at company level

## Additional information 
- [Concept](https://confluence.catena-x.net/display/IRS/%5BTRI-1417%5D+IRS%3A+ESS+Use+Case+-+Bottom-Up+Approach?src=contextnavpagetreemode)

## Clarification 
- Bottom up approach is already implemented. What is currently missing is the integration with incident app responsible for notification of customers and notification release process.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
