### ISSUE TITLE
Adapt the DGK Client API according to the new EDC Management API

### ISSUE THREAD

**Issue by dg-tsy** [eclipse-tractusx/sig-release#466]
## Description
**As a** Data Governance Kit Team,
**We need to** adapt the DGK Client API according to the new EDC Management API 
**So that** DGK is compatible with the latest EDC changes.

**Note:** Update the KIT documentation (e.g. Development View) as well.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
