### ISSUE TITLE
R24.03 Simple Data Exchanger (SDE) - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#492]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/34
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by ciprianherciu** [comment]
### Compliance Verification
Gaia-X compliance - Not applicable.
GDPR compliance - No changes to R23.12
Interoperability Check - Please find the updated table here: https://confluence.catena-x.net/pages/viewpage.action?pageId=69434953
Data Sovereignty Check - No Changes for R23.12
Confirmation of published CX Standards - SDE does not suggest any standard on its own. But it is using the relevant AIM Standards.
Verification of foreseen CX Standards - SDE does not suggest any standard on its own. But it is using the relevant AIM Standards.

**Comment by AjayRaturi123** [comment]
**Documentation**

1. **Arc42** - Arc42.md document updated with below points:-
- Essential Features 
- Interfaces/APIs
- App routing
https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/docs/Arc42.md

2. **Administrators Guide**  - No Changes.
**SDE FE** -  https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/README.md
**SDE BE** - 

3. **End-User manual** 
**SDE FE** - Updated the UI changes screenshots and details as per new implementations.
https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/docs/user-guide/README.md
**SDE BE** -

4. **Interface documentation**

**Comment by AjayRaturi123** [comment]
**Security Checks**

**Thread Modelling Analysis**
https://confluence.catena-x.net/pages/viewpage.action?pageId=62831498

**Static Application Security Testing** 
**SDE FE** - [DFT_Frontend_19_Feb_2024.pdf](https://github.com/eclipse-tractusx/sig-release/files/14340080/DFT_Frontend_19_Feb_2024.pdf)
**SDE BE** - 

**Dynamic Application Security Testing** 
**SDE FE** - 
**SDE BE** - 
Attached SDE Frontend and SDE Backend scans with no critical/ high findings. Please review and approve.

**Secret Scans** 

**Software Composition Analysis**
**SDE FE** -
<img width="1501" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/104556215/b310aaef-9e17-4f51-9391-94f8823da002">
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397406:33078655:33048228:33063878:::::4405591:
**SDE BE**-

**Container Scans** 
**SDE FE**- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/actions/runs/7966566281
**SDE BE**-

**Infrastructure as Code** 
**SDE FE**- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/actions/runs/7966459571
**SDE BE**-

**Comment by AjayRaturi123** [comment]
**### Test Results**
1. **E2E Integration**  - 

2. **User Journey** -

**Comment by ciprianherciu** [comment]
@jjeroch Could You please approve the User Journey of SDE?

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release.
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by Gitleena** [comment]
SCA: **Approved**

Note- A medium-level issue has been identified that necessitates accurate configuration of Spring Security to ensure proper protection against file permissions.

**Comment by RoKrish14** [comment]
SAST: **Approved**
SCA: **Approved**
DAST: **Approved**

**Comment by ciprianherciu** [comment]
@vialkoje Please approve the documentation part

**Comment by ciprianherciu** [comment]
User Journey has no changes, no need for approval

**Comment by RolaH1t** [comment]
QG review held as per plan
additional completed items will be documented by @RolaH1t an comitter on 21-Feb
System team to assign TRG responsible

**Comment by RoKrish14** [comment]
Container scan: **Approved**

**Comment by ciprianherciu** [comment]
@RoKrish14 Container scans are passed.
Open Topics:
- Documentation
- Data Sov
- Tractus-X Release Guidelines
-  Compliant with the Style Guide

**Comment by hzierer** [comment]
Since it is not stated explicitly anywhere, is it safe to assume to check the version **2.3.5**?
@RolaH1t @adityagajbhiye9 @ajithsimons

**Comment by ciprianherciu** [comment]
@hzierer Yes, it is 2.3.5

**Comment by jjeroch** [comment]
Findings

- Policy Creation overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
- Policy Update overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
- Policy table misses details of the usage policies
- Policy Overlays: would strongly suggest to work much more with "body2" type - the letters are quite huge
- for the manual upload the stored policies should be ideally usable
- the SDE should refer in the developer docu that every creator can freely decide which policies are set for each data set - thats a possible security issue/against company compliance and need to get validated be the user company
- usability: there is the PCF section added; no matter which use case I select on the "home" page I always can see the PCF chapter - whats the idea behind that?

@ciprianherciu I have a very limited possibility to fully test all views; reason: data are missing. Can you provide me an instance where I can see more due to existing data?

**Comment by ciprianherciu** [comment]
@vialkoje Please approve the Data Sovereignty and documentation

**Comment by hzierer** [comment]
all [TRG checks](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/34) completed successfully

**Comment by ciprianherciu** [comment]
@jjeroch 
The following topics will be addressed now:
- Policy Creation overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
- Policy Update overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
- Policy Overlays: would strongly suggest to work much more with "body2" type - the letters are quite huge
for the manual upload the stored policies should be ideally usable

The Following topics will be considered for the next PI:
- Policy table misses details of the usage policies

For the Following topics we would like to receive more information and will create a short meeting for it
- the SDE should refer in the developer docu that every creator can freely decide which policies are set for each data set - thats a possible security issue/against company compliance and need to get validated be the user company
- usability: there is the PCF section added; no matter which use case I select on the "home" page I always can see the PCF chapter - whats the idea behind that?

**Comment by jjeroch** [comment]
> Findings
> 
> * Policy Creation overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
> * Policy Update overlay talks about "define how long you wanna share the data" - that is wrong, the user cant define it
> * Policy table misses details of the usage policies
> * Policy Overlays: would strongly suggest to work much more with "body2" type - the letters are quite huge
> * for the manual upload the stored policies should be ideally usable
> * the SDE should refer in the developer docu that every creator can freely decide which policies are set for each data set - thats a possible security issue/against company compliance and need to get validated be the user company
> * usability: there is the PCF section added; no matter which use case I select on the "home" page I always can see the PCF chapter - whats the idea behind that?
> 
> @ciprianherciu I have a very limited possibility to fully test all views; reason: data are missing. Can you provide me an instance where I can see more due to existing data?

additional to the made findings - following questions have raised

<img width="1493" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/4e601666-3410-4f1d-b82e-8d1e15365f5f">
"**PCF exchange request for approval**" - the description says "for approval" while I can not approve anything; I also do not see what was pushed; only that "something" was pushed. Difficult user interaction

---

**Data provider contracts**
=> overview is missing important data; what kind of contracts are this, description; poilicies; who is the consumer?

---

**Data consumer contracts**
=> overview is missing important data; what kind of contracts are this, description; under which poilicies do I consume?; who is the provider?

---

**Consumer PCF Exchange** 
no information which data got exchanged and with whom

---

**Comment by vialkoje** [comment]
Documentation existing and looking consistent. Expert approval granted

Data sovereignty requirements unchanged. Expert approval granted.

Please consider the Sovereignty QG-Requirements for Release 24.05 !

**Comment by RolaH1t** [comment]
@ciprianherciu we urgently need your conclusion with @jjeroch on StyleGuide pls

**Comment by ciprianherciu** [comment]
@RolaH1t the agreed changes are already in PR and are waiting for an approval.

**Comment by ciprianherciu** [comment]
@jjeroch 
The topics agreed upon were merged:
- overlay in creation of policy  does not specify anything about how long to share the data
- the body Type 2 was updated as specified
- for the specification in regards with the creator role and companies limitation, we have added the information in the creation of the policy overlay

In regards with the documentation of the known issues in the changelog, the PR is still waiting for approval. 
Could You please confirm that the changes are as expected. 
Once the the documentation is done we will let you know

**Comment by jjeroch** [comment]
@ciprianherciu can you please share the release version tag - I can only see the main branch.
"Main" ist not your release version...or ist it?
Pls let me know; want to ensure that I review the correct version which actually runs into @RolaH1t his release 24.03.

**Comment by Siegfriedk** [comment]
@RolaH1t & @ciprianherciu i'm doing the release notes, whats the status here?

**Comment by ciprianherciu** [comment]
@jjeroch can You please help us with the approval?

**Comment by RolaH1t** [comment]
@jjeroch & @ciprianherciu last call for a decision here.
Pls provide your approval or a crisp problem description for the release note by 10am to @Siegfriedk , Thx!
@mabige fyi

**Comment by jjeroch** [comment]
@RolaH1t & @ciprianherciu 
content wise its fine; but I see two major issues:

- the formulated known knowns are not correct - changeLogs should not be formulated as question, BUT as statement of the actual open issue
- the changeLog includes mentioned PCF changes; eventhrough they are not released. The changeLog of the release version should not include any "non release" topics - clear statement: the team is handling the versioning and branching in a not proposed way - might be even wrong

**Comment by ciprianherciu** [comment]
@RolaH1t The changes mentioned by @jjeroch were corrected.
The PR which contains only adjustment to the Change Log is in approval by a commiter.
@Siegfriedk please give us the chance ti get it approved and merged

**Comment by ciprianherciu** [comment]
@RolaH1t @Siegfriedk the PR was merged.
Please consider closing the QG 4 for SDE

**Comment by RolaH1t** [comment]
all pre-conditions now fulfilled;
QG approval granted.
