### ISSUE TITLE
R24.03 Item Relationship Service (IRS) - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#494]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
* Release [4.5.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.5.2)
* IRS Chart [irs-helm-6.14.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/irs-helm-6.14.2)

**Leading product repository:** 
[IRS Repos](https://github.com/eclipse-tractusx/item-relationship-service)

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- Note: @wjost requested approval
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- Requested Jens Weiss for approval based on R23.12
- [x] **Interoperability** checks performed
- Note: Business Hours on 19.2.2024
- [x] **Data Sovereignty** checks performed
- Note: Business Hours on 19.2.2024
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- Note: Requested @vialkoje for review and approval
- [x] **Administrators Guide** up-to-date
- Note: Requested @vialkoje for review and approval
- [x] **End-User manual** up-to-date
- Note: Requested @vialkoje for review and approval
- [x] **Interface documentation** up-to-date
- Note: Requested @vialkoje for review and approval

# Security Checks

- [x] **Threat Modeling Analysis** passed
- Note: Requested SecOps team for approval on base of R23.12
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] #526
- [x] **Secret Scans** passed
- Note: Secret scans no issues - requested @DnlZF for approval 
- [x] **Software Composition Analysis** (SCA) passed
- @klaudiaZF @ZFLokesh @RoKrish14 @Tim.herres
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/item-relationship-service/issues/422
- [x] Compliant with the **Style Guide**
  - Note: Requested @jjeroch for approval  

# Test Results

- [x] **E2E Integration Test** passed
- Note: @ds-alexander-bulgakov covering approval of E2E with test management
- [x] **User Journey** approved
- Note: @kelaja approval based on approval of R23.12 without any changes 

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by mkanal** [comment]
Good morning @jjeroch,
The IRS does not provide an UI. For this reason, it is not necessary to check the style guide. Would you please confirm this as an expert in this issue. Thank you very much
Martin

**Comment by mkanal** [comment]
Good morning @vialkoje,

The Tractus-X Release Guidelines Check is pending for QG4 R24.3.
I would like to ask you for your review and subsequent approval of the QG4 ACs for documentation. 
If a personal appointment is required, please let me know. In this case, I will send you suggested dates. 

Tractus-X Release Guidelines Check Release 24.3:
•	https://github.com/eclipse-tractusx/sig-release/issues/494

Documentation:

[Docu](https://eclipse-tractusx.github.io/item-relationship-service/docs/)
[Arc24 documentation]( https://eclipse-tractusx.github.io/item-relationship-service/docs/#_architecture_documentation_arc42)
[Administrators Guide](https://eclipse-tractusx.github.io/item-relationship-service/docs/#_administration_guide)
End-User manual // IRS does not provide any UI
[Interface documentation]( https://eclipse-tractusx.github.io/item-relationship-service/docs/api-specification/api-specification.html) 
[Interface documentation](https://irs.int.demo.catena-x.net/api/swagger-ui/index.html?configUrl=/api/api-docs/swagger-config) 

Thank you very much 
Martin

**Comment by mkanal** [comment]
**@kelaja please update the status based on the following information:**

- [ ]  "User Journey approved": User Journey has not changed since release 23.12. For this reason, the approval of the User Journey is based on the approval given by BO of R23.12. 
- [ ] GDPR compliance confirmed - There is no change since release 23.12 regarding the processing ans storing of GDPR related data (personal data, data protection + privacy DPP) For this reason, the approval of the User Journey is based on the approval given by GDPR experts of R23.12. 
 
 fyi @jzbmw

**Comment by mkanal** [comment]
@wjost,
kindly ask for your approval regarding Gaia-X compliance. There are no changes between 24.3 and already approved version 23.12.
Thank you very much
Martin

**Comment by wjost** [comment]
For Release R24.03 we do not support Targus-Release auf GXDCH. Hence „Gaia-X compliance“  is still on the level of  R23.12. I confirm this release is GAIA-X compliant.

**Comment by mkanal** [comment]
# Interoperability checks
Preparation for Business Hour 19.2.2024 17:30 - 18:15
Participants @jzbmw & @mkanal 
https://confluence.catena-x.net/display/PL/2024-02-12+InterOp+for+TraceX+and+IRS

**Comment by mkanal** [comment]
#Static Application Security Testing (SAST) scans passed

#Dynamic Application Security Testing (DAST) tests passed

 #Secret Scans passed

#Software Composition Analysis (SCA) passed
## VeraCode 

![image](https://github.com/eclipse-tractusx/sig-release/assets/100209308/eb4ab208-ebd8-4ecb-a997-79ba103886cf)


#Container Scans passed

#Infrastructure as Code (IaC) scans passed

**Comment by mkanal** [comment]
## Data Sovereignty checks performed

Hello @vialkoje 

there seems to be no official DS Guidlines for the R34.3. Can you please give us an approval based on 23.12. There were no changes to R23.12 in IRS: Please approve. 
https://github.com/eclipse-tractusx/sig-release/issues/494
https://github.com/eclipse-tractusx/sig-release/issues/506
Thank you very much
Martin

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja  : please approve for "E2E Integration Test passed"

**Comment by almadigabor** [comment]
Hey! I'm done with the first round of checks and opened 2 issues that needs to be fixed. You can see more detail [here](https://github.com/eclipse-tractusx/item-relationship-service/issues/422).

**Comment by vialkoje** [comment]
Documentation available and looking consistent - Expert Approval granted

**Comment by mkanal** [comment]
![image](https://github.com/eclipse-tractusx/sig-release/assets/100209308/4e7d0529-a015-4e04-9839-115a63096caa)

**Comment by jzbmw** [comment]
As PO I assure that no changes from an earlier release of the Interoperability aspects exists

**Comment by RolaH1t** [comment]
2 minor findings wrt TRGs => QG approval postponed
Expect fix within cw 8.

**Comment by almadigabor** [comment]
Hey, I've closed the QG issue as all substasks have been fixed. I approve the QG. The new versions are:

AppVersion: `4.5.1`
Chart version: `6.14.1`

**Comment by RoKrish14** [comment]
SAST: **Approved**
SCA: **Approved**
DAST: **Approved**
Secret Scans: **Approved**

IAC: **Pending**
Container Scanning: **Pending**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release.
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by mkanal** [comment]
Hello @RolaH1t & @kelaja 
all QG Gate criterias are approved by experts. IRS teams provide the following hotfix version. 

https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/irs-helm-6.15.0
https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.5.1

Kindly ask to close this ticket. 
fyi @jzbmw 
Thank you very much
Martin

**Comment by mkanal** [comment]
> SAST: **Approved** SCA: **Approved** DAST: **Approved** Secret Scans: **Approved**
> 
> IAC: **Pending** Container Scanning: **Pending**

Hello @RoKrish14 
are there any vulnerabilities or open topics why IAC and container scanning is in pending state?
Thank you very much
Martin

**Comment by RoKrish14** [comment]
@ds-mwesener @ds-mmaul presented me with the security dashboard to look at the results.

Container Scans: **Approved**
IAC: **Approved**

**Comment by mkanal** [comment]
Hello 

> @ds-mwesener @ds-mmaul presented me with the security dashboard to look at the results.
> 
> Container Scans: **Approved** IAC: **Approved**

Thank you very much.

**Comment by mkanal** [comment]
Hello  @RolaH1t  and @kelaja 
all Q-Gate criteria are approved from experts. 
Please recheck and close this issue.
Thank you very much 
Martin

**Comment by RolaH1t** [comment]
QG4 approval granted. Congrats!
