### ISSUE TITLE
R24.03 Knowledge Agent - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#495]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
Helm Chart Version: 1.11.16
App Version: 1.11.16

**Leading product repository:** https://github.com/eclipse-tractusx/knowledge-agents-edc
# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/knowledge-agents/issues/93
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by TomBuchertTSystems** [comment]
@vialkoje : Please confirm that documentation is up to date.

https://eclipse-tractusx.github.io/docs-kits/kits/knowledge-agents/adoption-view/intro

**Comment by TomBuchertTSystems** [comment]
@kelaja : Please conform GDPR and GAIA X compliance (no changes)

**Comment by TomBuchertTSystems** [comment]
In my role as PO I hereby declare compliance with relevant published and foreseen CX Standards

**Comment by bosserf** [comment]
@TomBuchertTSystems and @kelaja : I herewith confirm/approve the user journey

**Comment by TomBuchertTSystems** [comment]
@vialkoje : For data sovereignity check we still follow the "old" q gate criteria for 24.03, right? If so yould you please approve as nothing changed? 

Best Regards,

Tom

**Comment by vialkoje** [comment]
Documentation existing and looking consistent. Data sovereignty requirements not changed for 24.03 - Expert assessment passed

Please make sure you consider the QG criteria for 24.05 -> https://confluence.catena-x.net/x/NTeJBg

**Comment by TomBuchertTSystems** [comment]
@BerndRothbrust Hey Dirk, could you please confirm that E2E tests are passed? Thank you very much!

**Comment by jjeroch** [comment]
> @jjeroch : Please confirm compliance with style guide (still no UI)

Confirmed

**Comment by TomBuchertTSystems** [comment]
@Siegfriedk: Please check conformity with Tractus X release guidelines. Thank you!

**Comment by Siegfriedk** [comment]
@TomBuchertTSystems the system team will take care of it. Pls communicate this ticket in the MS Team channel for devsecops / or office hour

**Comment by TomBuchertTSystems** [comment]
@szymonkowalczykzf : Please confirm validity of thread modelling. The architecture didn't change since the last q gate review. https://confluence.catena-x.net/display/cxsecurity/Knowledge+Agents

**Comment by TomBuchertTSystems** [comment]
@RoKrish14 Pleasw confirm validity of security checks as discussed in ourmeeting (all other than thread modelling). Thank you!

**Comment by drcgjung** [comment]
The latest SAST/SCA report is green

![Image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/df4ea22b-edc6-4eba-90ff-f39defafaa04)

**Comment by RoKrish14** [comment]
SAST: **Approved**
SCA: **Approved**
DAST: **Approved**
IAC: **Approved**
Secret Scans: **Approved**
Container Scanning: **Approved**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release.
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by HiHenrik** [comment]
According to team no interoperability relevant changes for this release, therefore expert approval granted for interoperability

**Comment by almadigabor** [comment]
Hey! I'm done with the TRG checks and approve the QG from my side with one remark. The helm upgradeability has to be implemented for knowledge agents edc until the next release. Related issue: https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/179
