### ISSUE TITLE
R24.03 BPDM Golden Record / BPN Service - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#496]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/bpdm/issues/757
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by nicoprow** [comment]
No Secrets in Github Scans:
<img width="965" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/10ac1713-444f-4bf2-a7fb-1fb0b7ff8998">

No Github Code scanning alerts:
<img width="958" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/d16329a0-63cf-4161-a137-377a3ddc0384">


No Dependabot Alerts:
<img width="965" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/9f61d6c5-4324-4470-bc60-890129d359cd">

**Comment by nicoprow** [comment]
Veracode passed:
<img width="766" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/73c64657-1de1-4071-80ef-a082e74ba39a">

<img width="824" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/4ee1b42d-9d71-4b9f-8b4f-253f97e5a3f5">

One medium composition vulnerability:
<img width="1194" alt="veracode compositions" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/bc38df25-1cc6-49b7-936f-b88c741a410f">

2 Triage Flaws, both mitigation proposed, one approved. (But flaws seem to be duplicates anyway): 
<img width="1423" alt="Bildschirmfoto 2024-02-08 um 10 50 12" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/982dda48-a219-4984-b847-b8210fd03016">

**Comment by nicoprow** [comment]
Threat Modeling passed and assessment currently in the process of being merged:
https://github.com/eclipse-tractusx/bpdm/pull/737
https://github.com/eclipse-tractusx/bpdm/pull/740

**Comment by nicoprow** [comment]
Interface documentation up to date for current release version:
https://github.com/eclipse-tractusx/bpdm/tree/release/5.0.x/docs/api

**Comment by RoKrish14** [comment]
SAST: Approved
SCA: Approved
Trivy: Approved
KICKS: Approved

**Comment by nicoprow** [comment]
DAST no high or above issues:

Gate: https://www.netsparkercloud.com/websites/dashboard/9372f73eb7d24ca41db1b059018933cc/?scanGroupId=6b67c661-b788-44db-2f1f-b0c701e8f2f9
Pool: https://www.netsparkercloud.com/websites/dashboard/9372f73eb7d24ca41db1b059018933cc/?scanGroupId=48809087-5bb1-4773-3453-b0c2024239f4

**Comment by RoKrish14** [comment]
Secret Scanning: **Approved**
DAST: **Approved**

**Comment by rybtim** [comment]
No significant changes to last time related Gaia-X Compliance and GDPR @kelaja

**Comment by rybtim** [comment]
We herby confirm that we considered (as good as possible) all relevant CX-Standards as well as that we reviewed the content of upcoming STAN Request as good as possible @kelaja

**Comment by rybtim** [comment]
E2E Test passed
https://jira.catena-x.net/browse/TEST-1739 
Overall Status
https://confluence.catena-x.net/x/sgA1Bw

**Comment by alexKeppler** [comment]
@kelaja User Journey approved

**Comment by ThomasObermeyer** [comment]
No major architecture changes in the current release - interoperability check approved.

@kelaja

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

Re-assessment was done on Wednesday 25th Jan 2024. No open critical & high findings remains.
Documentation of the assessment will be available under BPDM/docs/Security_Assessment.md

**Comment by FaGru3n** [comment]
Hi all, 

think there are some infos not shared within this issue would suggest:

> **Version to be included in Eclipse Tractus-X release**: _version placeholder_
> 
> **Leading product repository:** _repository link_

Leading repo: https://github.com/eclipse-tractusx/bpdm

Version: 5.0.0 Am i correct?

Thanks in advance.

**Comment by vialkoje** [comment]
could you please add the links to the documentation documents to check ? 

Arc24 documentation 
Administrators Guide 
End-User manual 
Interface documentation -> I found that one already

**Comment by nicoprow** [comment]
> Hi all,
> 
> think there are some infos not shared within this issue would suggest:
> 
> > **Version to be included in Eclipse Tractus-X release**: _version placeholder_
> > **Leading product repository:** _repository link_
> 
> Leading repo: https://github.com/eclipse-tractusx/bpdm
> 
> Version: 5.0.0 Am i correct?
> 
> Created TRG Guideline Check Issue for bpdm repo: [eclipse-tractusx/bpdm#757](https://github.com/eclipse-tractusx/bpdm/issues/757)
> 
> Thanks in advance.

Yes that is correct. Chart version is 4.0.0

**Comment by nicoprow** [comment]
> could you please add the links to the documentation documents to check ?
> 
> Arc24 documentation Administrators Guide End-User manual Interface documentation -> I found that one already

Arc24: https://github.com/eclipse-tractusx/bpdm/tree/release/5.0.x/docs/arc42
Admin Guide: https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/docs/OPERATOR_VIEW.md
End-User Manual: We don't have an UI, so no End-User. There is a guide for integrating services however: https://github.com/eclipse-tractusx/bpdm/blob/release/5.0.x/docs/ADOPTION_VIEW.md
Interface Documentation: https://github.com/eclipse-tractusx/bpdm/tree/release/5.0.x/docs/api

**Comment by rybtim** [comment]
Hi security team,
can you please check our scans.
@BANANAS1337 @RoKrish14 @PiotrStys @DnlZF 
Thanks

**Comment by RoKrish14** [comment]
> Hi security team, can you please check our scans. @BANANAS1337 @RoKrish14 @PiotrStys @DnlZF Thanks

Hi @rybtim 
What has changed since last security checks?

1. https://github.com/eclipse-tractusx/sig-release/issues/496#issuecomment-1935741174
2. https://github.com/eclipse-tractusx/sig-release/issues/496#issuecomment-1938481208

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja  : please approve for "E2E Integration Test passed"

**Comment by rybtim** [comment]
STYLE Guide: No changes to last release. No UI for Golden Record Service

**Comment by RolaH1t** [comment]
QG review as per plan 21-Feb:
pending topics are DataSov & Documentation, as well as TRGs
Approval postponed until topics addressed; no follow-up mtg required.

**Comment by vialkoje** [comment]
Documentation Existing and looking consistent. Sovereignty requirements fulfilled as tehre are no specific requirements for 24.03. Expert Approval granted

**Comment by RolaH1t** [comment]
all pre-conditions fulfilled and QG approval granted!
Congrats!

**Comment by RolaH1t** [comment]
Critical Update:
QG approval withdrawn  until clarification of Postgresql DB issue => @HeyHardy @nicoprow @Siegfriedk 
reference: violation of TRG 5.07

**Comment by RolaH1t** [comment]
final conclusion: TRG 5.07 still violated (postgresql DB version 14.x) but successfully tested.
this is covered in overall release note 24.03
QG closed with these conditions.
