### ISSUE TITLE
R23.04 BPDM Country Risk - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#497]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: Chart Version: **3.0.9** App Version: **1.3.0**

**Leading product repository:** [*vas-country-risk*](https://github.com/eclipse-tractusx/vas-country-risk)

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**] https://github.com/eclipse-tractusx/vas-country-risk/issues/88
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by fabiodmota** [comment]
After some emails exchanged with @jjeroch and Werner Jost, the responsible, it was concluded that our product already has its app registered in the marketplace and, being a VAS, does not require any extra action for the Gaia-X compliance confirmed point.

**Comment by fabiodmota** [comment]
Documentation for @vialkoje 

For Interfaces Documentation
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#interfaces
https://github.com/eclipse-tractusx/vas-country-risk-backend/tree/main/docs/swagger
 
 
Admin and User Guide:
Backend repo:
https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/README.md
https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/INSTALL.md
https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/docs/User-Guide.md
Frontend repo:
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/README.md
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/INSTALL.md
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/User-Guide.md
Kit: https://eclipse-tractusx.github.io/docs-kits/kits/Business%20Partner%20Kit/Success%20Stories/Country%20Risk%20Score%C2%A0/

**Comment by fabiodmota** [comment]
Repo urls

https://github.com/eclipse-tractusx/vas-country-risk
https://github.com/eclipse-tractusx/vas-country-risk-backend

Veracode Scans can be checked 

![image](https://github.com/eclipse-tractusx/sig-release/assets/107047355/6ec3bbbc-06ef-4616-8e88-1cb4c3579c51)

Trivy scans can be checked 

https://github.com/eclipse-tractusx/vas-country-risk/actions/workflows/trivy.yml

https://github.com/eclipse-tractusx/vas-country-risk-backend/actions/workflows/trivy.yml

**Comment by BANANAS1337** [comment]
SAST and SCA approved

**Comment by RoKrish14** [comment]
DAST passed

For the below checks, lets connect. Because I don't have the visibility to security dashboard.
Trivy:  Container Scans
KICKS:  Infrastructure as Code (IaC)

**Comment by BANANAS1337** [comment]
Secret Scanning approved

**Comment by vialkoje** [comment]
Documentation existing and looking consistent - Data sovereinty requirements unchanged for 24.03 - Expert Assessment passed.

Please consider the Data Sovereignty Criteria for 24.05 -> https://confluence.catena-x.net/x/NTeJBg

**Comment by RoKrish14** [comment]
Trivy: Container Scans : : **Approved**
KICKS: Infrastructure as Code (IaC): : **Approved**

**Comment by leonschand** [comment]
E2E test completed successfully. Please approve @phirabu

**Comment by jjeroch** [comment]
Findings:

**High - check needed**
- I can access the country-risk app with an user which does not have any app roles assigned

---
---

**Medium - not blocking**
- no info why I can only update own ratings, not company ratings
<img width="245" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/12ac9e35-ec58-4ce9-bc21-197f28b98828">

---

**Medium - not blocking**
- instead of showing in page success, please use snackbar (top right) option. You can find it as an shared-component element
<img width="359" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/472e19dc-958d-4277-9300-41d4d588abf0">

---

**Medium - not blocking**
- same as above applies for "Save ratings" as well - please check if you used it anywhere else and fix it for all

---

**Medium - not blocking**
- export to csv seems to not work
<img width="306" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/e6dcdf0f-dad5-4d47-b7c4-57f55c96007c">

---

**Medium - not blocking**
- table arrangement not useful - Rating has a unneeded width; same for country (where you could use Alpha2Code) - where actually fields such as company name and rating company are not displayed and even on hover the text is not getting displayed
<img width="1134" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/6e79e8cc-f276-48e0-8532-4a431ffba67d">

**Comment by leonschand** [comment]
@kelaja  As there were no significant changes which relates to GDPR, we can take the declaration from R.3.1. See Jira Ticket https://jira.catena-x.net/browse/CXRM-1025

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

Re-assessment was done on Wednesday 31st Jan 2024. No open critical & high findings remains.
Documentation of the assessment is available under vas_country_risk -> docs -> threat_model

**Comment by rybtim** [comment]
We herby confirm that we considered (as good as possible) all relevant CX-Standards as well as that we reviewed the content of upcoming STAN Request as good as possible @kelaja

**Comment by ThomasObermeyer** [comment]
From a pure Interoperability perspective, this VAS service does not need to be interoperable, since it is a value add on provided based on BPDM data provided by the operating company. There is not true interoperability requirement between compatible app providers at this point in time.

However, Catena-X architecture framework components (EDC and oAUTH) mechanisms have been applied, so there is no objection from an Enterprise Architecture perspective.

Approved!

**Comment by fabiodmota** [comment]
> Findings:
> 
> **High - check needed**
> 
> * I can access the country-risk app with an user which does not have any app roles assigned
> 
> **Medium - not blocking**
> 
> * no info why I can only update own ratings, not company ratings
> 
> <img alt="image" width="245" src="https://private-user-images.githubusercontent.com/94133633/304365629-12ac9e35-ec58-4ce9-bc21-197f28b98828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTc3NjAsIm5iZiI6MTcwNzk5NzQ2MCwicGF0aCI6Ii85NDEzMzYzMy8zMDQzNjU2MjktMTJhYzllMzUtZWM1OC00Y2U5LWJjMjEtMTk3ZjI4Yjk4ODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NGM2MjRjMTBjMTM0Mzk5YWZjMzk0YTA1Yzc5YjhjMTBkMWRiODVlYzJmODVkZTI5MDczNWNlNDhjMTA1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fAat6mKjJIHcx7gYgaArHNL7I30Wkltg55oehYV8LM">
> **Medium - not blocking**
> 
> * instead of showing in page success, please use snackbar (top right) option. You can find it as an shared-component element
> 
> <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/94133633/304365920-472e19dc-958d-4277-9300-41d4d588abf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTc3NjAsIm5iZiI6MTcwNzk5NzQ2MCwicGF0aCI6Ii85NDEzMzYzMy8zMDQzNjU5MjAtNDcyZTE5ZGMtOTU4ZC00Mjc3LTkzMDAtNDFkNGQ1ODhhYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWQ2YzhlOGU4ZmQ1MjQyYTEzMzBlNDFiNGUyYmIzZGVjNTY2ZGI3OTZiMjg0MzllYzVmOTc3MzMzMmFjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YTaVRhTtTHai96NRoGtsXPLdMG2A8IhE5No7lG8MJIg">
> **Medium - not blocking**
> 
> * same as above applies for "Save ratings" as well - please check if you used it anywhere else and fix it for all
> 
> **Medium - not blocking**
> 
> * export to csv seems to not work
> 
> <img alt="image" width="306" src="https://private-user-images.githubusercontent.com/94133633/304366386-e6dcdf0f-dad5-4d47-b7c4-57f55c96007c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTc3NjAsIm5iZiI6MTcwNzk5NzQ2MCwicGF0aCI6Ii85NDEzMzYzMy8zMDQzNjYzODYtZTZkY2RmMGYtZGFkNS00ZDQ3LWI3YzQtNTdmNTVjOTYwMDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTRmNWI0MDhjN2Y1NzI4ZWQ0MjUyZTA4NmNlMTNjNDBjY2UzY2JmNjM2ZjhlNjI2ZjVkMjUzMDk0YTkzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MN-3RXUN150njs-GqE0sLq68LvChDGP903jwLOFO3lE">
> **Medium - not blocking**
> 
> * table arrangement not useful - Rating has a unneeded width; same for country (where you could use Alpha2Code) - where actually fields such as company name and rating company are not displayed and even on hover the text is not getting displayed
> 
> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/94133633/304366874-6e79e8cc-f276-48e0-8532-4a431ffba67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTc3NjAsIm5iZiI6MTcwNzk5NzQ2MCwicGF0aCI6Ii85NDEzMzYzMy8zMDQzNjY4NzQtNmU3OWU4Y2MtZjI3Ni00OGUwLTg1MzItNGE0MzFmZmJhNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDExNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2I0ZjNlMDA3NGNhOTUzNDg2ZDE1N2U0Yzk3OTQ0ODQxYjZiODA4YTAxYTJiNmE1MGExOWJlNWI4M2FjMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RTXiyDy4Ek-ibP0FsKf2dBdiY-FkTl2r9PxLqEVJor4">

Hi @jjeroch 

So i created a issue for the High Findings and one for the Medium findings

- https://github.com/eclipse-tractusx/vas-country-risk/issues/85
- https://github.com/eclipse-tractusx/vas-country-risk/issues/74

For the High Findings a Pull Request is already created with the solution https://github.com/eclipse-tractusx/vas-country-risk/pull/87 everything can be checked on the country risk url https://country-risk-dashboard.int.demo.catena-x.net/

**Comment by FaGru3n** [comment]
> **Version to be included in Eclipse Tractus-X release**: _version placeholder_

Hi all, 

generated https://github.com/eclipse-tractusx/vas-country-risk/issues/88 for QG-Checks

which version should be checked?

**Comment by RolaH1t** [comment]
Interim Status für Q check on 19.Feb.2024:
**OPEN**
-TRGs
-StyleGuide
-E2E Tests
-DataSOV

**APPROVED**
-GAIA-X
-GDPR
-CX Standards
-InterOP (partially not applicable for VAS)
-ARC42
-Admin & User-Guide
-Interface Docu
-Threat Model
-SAST
-DAST
-SCA
-Secrets
-Container Scans
-IaC
-User Journey

**Comment by fabiodmota** [comment]
> > **Version to be included in Eclipse Tractus-X release**: _version placeholder_
> 
> Hi all,
> 
> generated [eclipse-tractusx/vas-country-risk#88](https://github.com/eclipse-tractusx/vas-country-risk/issues/88) for QG-Checks
> 
> which version should be checked?

The current version is of the charts are 3.0.9 but once we have the fix accepted by @jjeroch commented above https://github.com/eclipse-tractusx/sig-release/issues/497#issuecomment-1948285787 i will release a new version 

So the latest is https://github.com/catenax-ng/tx-vas-country-risk-frontend/releases/tag/country-risk-3.0.9

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by RolaH1t** [comment]
CountryRisk team will provide latest code version to address high finding wrt StyleGuide.
Afterwards TRG checks will be finalized and SEC scans have to be repeated.
Gate Approval postponed until those actions are complete.

**Comment by RoKrish14** [comment]
Rescan requested by @fabiodmota 

SAST: **Approved**
SCA: **Approved**
DAST: **Approved**
Secret Scans: **Approved**
IAC: **Approved**
Container Scans: **Approved**

**Comment by jjeroch** [comment]
High finding was resolved; the medium findings are moved to 24.05. release for fix

**Comment by FaGru3n** [comment]
QG-Checks done, thanks for the work @fabiodmota and dedicated information are shared in separate issue.

**Comment by fabiodmota** [comment]
After all checks on QG a version was released contained all the fixes and aprovall pull requests

https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/country-risk-3.0.11
https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/v1.3.1

**Comment by RolaH1t** [comment]
> After all checks on QG and after approval a version was released contained all the fixes and pull requests done:
> 
> chart version: https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/country-risk-3.0.11 app version: https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/v1.3.1

thx for the info - and pls clarify:
this new version is more than welcome, but CANNOT be included in 24.03 package as it has not been E2E-tested. So it it good to be available in the BPDM repo and already prepared for 24.05. Let @Siegfriedk know!
