### ISSUE TITLE
R24.03 SD Factory - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#500]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: https://github.com/eclipse-tractusx/sd-factory/releases/tag/v2.1.10

**Leading product repository:** https://github.com/eclipse-tractusx/sd-factory

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/sd-factory/issues/92 https://github.com/eclipse-tractusx/sig-release/issues/500#issuecomment-1968710520
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by wjost** [comment]
For Release 24.3 it was decided that we do not switch to Targus Release of GXDCH but remain to the initial v.20.10 release. Hence nothing has to be adapted on portal, SD-Factory and MIW. This way SD Factory is GAIA-X compliant for Release 24.3

However, when switching to Targus Release changes are needed. Then it has to be assured Portal, SD-Factory and MIW do fit together.

**Comment by ciprianherciu** [comment]
Thread Modelling Analysis passed
 Static Application Security Testing (SAST) scans passed
 Dynamic Application Security Testing (DAST) tests passed
 Secret Scans passed
 Software Composition Analysis (SCA) passed
 Container Scans passed
 Infrastructure as Code (IaC) scans passed

**Comment by RoKrish14** [comment]
@ciprianherciu : Were these Security checks approved by any security team members?

**Comment by ciprianherciu** [comment]
@RoKrish14 
Security scans looks good from our side, 
Could You please review and approve?

**Comment by RoKrish14** [comment]
SAST: **Approved**
SCA: **Approved**
DAST: **Approved**
Secret Scanning: **Approved**

**Comment by RoKrish14** [comment]
@ciprianherciu : For Trivy and KICKS results, please connect me to someone with committer rights who could show me the results in the security tab.

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by ciprianherciu** [comment]
@guenterban , please approve the security checks still needed

**Comment by ciprianherciu** [comment]
@vialkoje Please approve the documentation

**Comment by ciprianherciu** [comment]
@wjost can the user journey be approved? 
The E2E tests were done in this: https://jira.catena-x.net/browse/TEST-1744

**Comment by wjost** [comment]
I do not see in the mentioned test case  https://jira.catena-x.net/browse/TEST-1744 where SD factory is involved?
This is only about the SSI flow, but not about SD creation.

**Comment by ciprianherciu** [comment]
Since no changes to GaiaX E2E test is passed as well

**Comment by RoKrish14** [comment]
Container scan: **Approved**
IAC: **Approved**

**Comment by ciprianherciu** [comment]
@RoKrish14 Thank You very much for Your help. There is one more scan which was not specified. The Thread Modelling Analysis. Can You please check that as well?

**Comment by ciprianherciu** [comment]
@RolaH1t Container scan and IAC approved:
Open Topics:
-  Documentation
- Thread Modelling Analysis
- Tractus-X Release Guidelines

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release.
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by RoKrish14** [comment]
@ciprianherciu : Done ✔️

**Comment by ciprianherciu** [comment]
@vialkoje Please approve the documentation

**Comment by evegufy** [comment]
[TRG check](https://github.com/eclipse-tractusx/sd-factory/issues/92) approval granted for the newly released [app version 2.1.10 with chart version 2.1.12](https://github.com/eclipse-tractusx/sd-factory/releases/tag/v2.1.10).
TRG checks performed on [version 2.1.9 with chart version 2.1.11](https://github.com/eclipse-tractusx/sd-factory/releases/tag/v2.1.9).

**Comment by vialkoje** [comment]
Documentation Existingnand looking consistent.

Administrator and End-User documentation is pointing "arbitrarily" to the ARC42 docu. I'd recommend thinking about the trget audience and providing appropriate structures for them to fulfill their information need.

Overall the information is provided in some structure. Expert Approval granted therefore.

Requirements for data sovereignty unchanged. Expert approval granted.
Please make sure you consider the Data sovereignty requirements for 24.05.

**Comment by ciprianherciu** [comment]
@kelaja @RolaH1t all the points are closed. Ticket can be closed

**Comment by RolaH1t** [comment]
all pre-conditions fulfilled now => QG approval granted!
Congrats!
