### ISSUE TITLE
R24.03 Digital Twin Registry - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#501]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
helm version: digital-twin-registry-0.3.31 
Image version: 0.3.23

**Leading product repository:** https://github.com/eclipse-tractusx/sldt-digital-twin-registry

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/326
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by tunacicek** [comment]
Gaia-X compliance: 
@kelaja : No changes since Release 23.12 -> Could you please tick this checkbox?
Gaia-X compliance is not relevant for the decentral Digital Twin Registry.

**Comment by tunacicek** [comment]
@kelaja :
GDPR Compliance: 
No changes since Release 23.12 
https://github.com/eclipse-tractusx/sig-release/files/13279611/Catena-X.GDPR.Declaration.and.Requirements_V23.12_DTR.xlsx

**Comment by tunacicek** [comment]
Data Sovereignty Check: 
@vialkoje : Could you please tick this checkbox? 
No significant changes since Release 23.12.
See also Description for R24.03
![image](https://github.com/eclipse-tractusx/sig-release/assets/115143031/3fbef4db-ab8d-482e-b292-498f75b4ce91)

**Comment by tunacicek** [comment]
**Documentation**

- [ ] Arc42
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/docs/README.md

- [ ] Administrator`s Guide (User assistance):
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/b
lob/main/README.md

- [ ] End-User Manual (User assistance):
End-user of the services is the developer who uses the API endpoints. Hence there is a openapi.yaml-file in the repository of the services serves as the documentation.
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/backend/src/main/resources/static/aas-registry-openapi.yaml
Also there is a detailed documentation available: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/docs/README.md
Since the Digital Twin Registry is now decentral deployed there is no User Interface provided anymore.
N/A → no User Interface / no Frontend for this Service

- [ ] Interfaces Documentation:
As the Digital Twin Registry is deployed decentralized we point to the openapi.yaml within the repo:
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/backend/src/main/resources/static/aas-registry-openapi.yaml

@vialkoje : No significant changes since Release 23.12. Could you please check and approve the checkboxes?

**Comment by tunacicek** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/116

**Comment by tunacicek** [comment]
Compliant with the Style Guide:
Since the Digital Twin Registry is now provided as decentralized service there is no User Interface provided any more.
N/A → no User Interface / no Frontend for this Service
@jjeroch : Could you please check and approve it?

**Comment by thomas-henn** [comment]
> Verification of foreseen CX Standards: @thomas-henn : Could you please confirm? See also previous task for R23.12: #113

Yes, Digital Twin Registry is compliant with relevant published CX Standards.

**Comment by tunacicek** [comment]
Security Checks - Dynamic Application Security Testing (DAST):
Invicti scan has been made - the results can be seen here: https://www.netsparkercloud.com/scans/report/402e16cbf3844a45620eb111027ece2d/

@PiotrStys : Could you please review and approved it?

**Comment by PiotrStys** [comment]
Hi @tunacicek, 
DAST approved.

**Comment by tunacicek** [comment]
Security Check- Secret scanning:

Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/gitleaks.yml

@DnlZF Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Static Application Security Testing (SAST):
One high finding which is mitigated.
See the results here:
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1397650:30762582:30732796:30748446::4406303

@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Software Composition Analysis (SCA):
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397650:30762582:30732796:30748446:::::4406303:
@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - nfrastructure as Code
KICS is activated: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/kics.yml
@RoKrish14 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Test Results - E2E Integration Test
Tests done: See result here:
https://jira.catena-x.net/browse/CXSOLUTION-489

**Comment by RoKrish14** [comment]
@tunacicek : As discussed- 

SAST: **Approved**
SCA: **Approved**
IAC: **Approved**
Secret Scanning: **Approved**

**Comment by jjeroch** [comment]
> Compliant with the Style Guide: Since the Digital Twin Registry is now provided as decentralized service there is no User Interface provided any more. N/A → no User Interface / no Frontend for this Service @jjeroch : Could you please check and approve it?

confirmed

**Comment by vialkoje** [comment]
Expert Approval granted for Documentation and data sovereignty.

**Comment by RolaH1t** [comment]
InterOP
Threat Modeling & Container Scans
TRGs
QG approval postponed until topics addressed / no follow-up mtg required.

**Comment by RoKrish14** [comment]
Discussed with @tunacicek
Container Scans: **Approved**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release (23.12).
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by tomaszbarwicki** [comment]
QG checks completed: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/326

**Comment by RolaH1t** [comment]
Congrats:
all conditions for QG approval now fulfilled!
