### ISSUE TITLE
R24.03 Discovery Finder - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#502]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**:
helm: discoveryfinder-0.1.18
Image version: 0.2.7

**Leading product repository:** https://github.com/eclipse-tractusx/sldt-discovery-finder

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/110
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by tunacicek** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made.
@kelaja : Could you please tick this checkbox?

**Comment by tunacicek** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12.

**Comment by tunacicek** [comment]
Verification of foreseen CX Standards:
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/117

**Comment by tunacicek** [comment]
**Documentation**

- [ ] Arc42
MD files in Tractus-X repo:
[Arc42: https://github.com/eclipse-tractusx/sldt-discovery-finder/tree/main/docs](https://github.com/eclipse-tractusx/sldt-discovery-finder/tree/main/docs)

- [ ] Administrator`s Guide (User assistance):
MD files in Tractus-X repo:
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/README.md

- [ ] End-User Manual (User assistance):
End-user of the services is the developer who uses the API endpoints. Hence the swagger-ui of the services serves as the documentation.
https://semantics.int.demo.catena-x.net/discoveryfinder/swagger-ui/index.html
Also there is a detailed documentation available: https://github.com/eclipse-tractusx/sldt-discovery-finder/tree/main/docs

- [ ] Interfaces Documentation:
Link to swagger UI documentation:
https://semantics.int.demo.catena-x.net/discoveryfinder/swagger-ui/index.html

@vialkoje : Could you please check and approve the checkboxes?

**Comment by tunacicek** [comment]
Security Checks:
No changes sincw Release 23.12.
See also Security Assessment diagram:
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/docs/documentation.md#:~:text=INSTALL.md.-,Security,-Assessment

@guenterban : Could you please check and approve it?

**Comment by tunacicek** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/120

**Comment by tunacicek** [comment]
Compliant with the Style Guide:
N/A → no User Interface / no Frontend for this Service

@jjeroch : Could you please check and approve it?

**Comment by thomas-henn** [comment]
> User Journey : @thomas-henn : Could you please confirm? See also previous task for R23.12: #120

Yes, user journey of Discovery Finder is aligned along with e.g. Digital Twin Registry, BPN Discovery and Semantic Hub.

**Comment by tunacicek** [comment]
Security Checks - Dynamic Application Security Testing (DAST):
Invicti scan has been made - the results can be seen here: https://www.netsparkercloud.com/scans/report/b49918c6505a46783ef3b11101e9d7e0/

@PiotrStys : Could you please review and approved it?

**Comment by PiotrStys** [comment]
Hi @tunacicek,
DAST approved.

**Comment by tunacicek** [comment]
Security Check- Secret scanning:

Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/workflows/gitleaks.yml

@DnlZF Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Static Application Security Testing (SAST):
See the results here:
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1739409:32851565:32821223:32836873::5382776

@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Software Composition Analysis (SCA):
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1739409:32851565:32821223:32836873:::::5382776:
@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - nfrastructure as Code
https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/workflows/kics.yml
@RoKrish14 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Test Results - E2E Integration Test
Tests done: See result here:
https://jira.catena-x.net/browse/CXSOLUTION-489

**Comment by RoKrish14** [comment]
@tunacicek : As discussed- 

SAST: **Approved**
SCA: **Approved**
IAC: **Approved**
Secret Scanning: **Approved**

**Comment by jjeroch** [comment]
> Compliant with the Style Guide: N/A → no User Interface / no Frontend for this Service
> 
> @jjeroch : Could you please check and approve it?

confirmed

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by RolaH1t** [comment]
Open:
InterOP
ThreatModeling & Container Scans
TRG
QG approval postponed until topics addressed / no follow-up mtg required.

**Comment by RoKrish14** [comment]
Discussed with @tunacicek
Container Scans: **Approved**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release (23.12).
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by HiHenrik** [comment]
According to team no interoperability relevant changes for this release, therefore expert approval granted for interoperability

**Comment by tomaszbarwicki** [comment]
QG checks completed: https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/110

**Comment by RolaH1t** [comment]
QG approval granted!
Congrats, Roland
