### ISSUE TITLE
R24.03 Discovery Service (BPN Finder) - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#503]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
Helm Chart Version: [0.1.18](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.1.18)
App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.1.18/charts/bpndiscovery/Chart.yaml#L28)

**Leading product repository:** https://github.com/eclipse-tractusx/sldt-bpn-discovery

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/sldt-bpn-discovery/issues/109
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by tunacicek** [comment]
Gaia-X compliance:
@kelaja : No changes since Release 23.12 -> Could you please tick this checkbox?
Gaia-X compliance is not relevant for the Discovery Finder.

**Comment by tunacicek** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made.
@kelaja : Could you please tick this checkbox?

**Comment by tunacicek** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12.

**Comment by tunacicek** [comment]
Verification of foreseen CX Standards:
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/121

**Comment by tunacicek** [comment]
**Documentation**

- [ ] Arc42
MD files for arc42-documentation in Tractus-X repo:
https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/main/docs

- [ ] Administrator`s Guide (User assistance):
MD files in Tractus-X repo:
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/main/README.md

- [ ] End-User Manual (User assistance):
End-user of the services is the developer who uses the API endpoints. Hence the swagger-ui of the service serves as the documentation.
https://semantics.int.demo.catena-x.net/bpndiscovery/swagger-ui/index.html
Also there is a detailed documentation available: https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/main/docs

- [ ] Interfaces Documentation:
Link to swagger UI documentation:
[https://semantics.int.demo.catena-x.net/bpndiscovery/swagger-ui/index.html](https://semantics.int.demo.catena-x.net/bpndiscovery/swagger-ui/index.html)

@vialkoje : Could you please check and approve the checkboxes?

**Comment by tunacicek** [comment]
Security Checks- Thread Modelling Analysis:
No changes since Release 23.12.
See also Security Assessment diagram:
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/main/docs/documentation.md#:~:text=Security-,Assessment,-Data%20Flow%20Diagram

@guenterban : Could you please check and approve it?

**Comment by tunacicek** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/124

**Comment by tunacicek** [comment]
Compliant with the Style Guide:
N/A → no User Interface / no Frontend for this Service

@jjeroch : Could you please check and approve it?

**Comment by thomas-henn** [comment]
> Verification of foreseen CX Standards: @thomas-henn : Could you please confirm? See also previous task for R23.12: #121

Yes, Discovery Finder is compliant with relevant published CX Standards

**Comment by thomas-henn** [comment]
> User Journey : @thomas-henn : Could you please confirm? See also previous task for R23.12: #124

Yes, user journey of BPN Discovery is aligned along with e.g. Digital Twin Registry, Discovery Finder and Semantic Hub.

**Comment by tunacicek** [comment]
Security Checks - Dynamic Application Security Testing (DAST):
Invicti scan has been made - the results can be seen here: https://www.netsparkercloud.com/scans/report/87f6d8d3119b4e596344b111023574bc/

@PiotrStys : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Check- Secret scanning:

Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/workflows/gitleaks.yml

@DnlZF Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Static Application Security Testing (SAST):
Please see the results here:
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1739409:30762590:30732804:30748454::5382776

One medium risk which is mitigated.

@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Software Composition Analysis (SCA):
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1739409:30762590:30732804:30748454:::::5382776:
@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Software Composition Analysis (SCA):
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1739413:32851550:32821208:32836858:::::5382788:
@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - nfrastructure as Code
https://github.com/eclipse-tractusx/sldt-bpn-discovery/actions/workflows/kics.yml
@RoKrish14 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Test Results - E2E Integration Test
Tests done: See result here:
https://jira.catena-x.net/browse/CXSOLUTION-489

**Comment by RoKrish14** [comment]
@tunacicek : As discussed- 

SAST: **Approved**
SCA: **Approved**
IAC: **Approved**
Secret Scanning: **Approved**

**Comment by jjeroch** [comment]
> Compliant with the Style Guide: N/A → no User Interface / no Frontend for this Service
> 
> @jjeroch : Could you please check and approve it?

confirmed

**Comment by vialkoje** [comment]
Expert Approval granted for Documentation and data sovereignty.

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by RolaH1t** [comment]
Open:
InterOP
ThreatModeling & Container Scans
TRG
QG approval postponed until topics addressed / no follow-up mtg required.

**Comment by RoKrish14** [comment]
Discussed with @tunacicek 
Container Scans: **Approved**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release (23.12).
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by HiHenrik** [comment]
According to team no interoperability relevant changes for this release, therefore expert approval granted for interoperability

**Comment by FaGru3n** [comment]
Hi all are this the proper information for the QG-Checks?

> Product Owner: @bs-sili
> Dev SPOC: @tunacicek
> Helm Chart Version: [0.2.3](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.2.3)
> App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.2.3/charts/bpndiscovery/Chart.yaml#L28C1-L28C18)

Issue created https://github.com/eclipse-tractusx/sldt-bpn-discovery/issues/109

**Comment by FaGru3n** [comment]
QG checks done.

**Comment by RolaH1t** [comment]
QG4 approval granted. Congrats!
