### ISSUE TITLE
R24.03 Semantic Hub - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#505]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
helm version: semantic-hub- 0.1.35
Image version: 0.2.16

**Leading product repository:** https://github.com/eclipse-tractusx/sldt-semantic-hub

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/243
- [x] Compliant with the **Style Guide**, fix will be delivered by @thomas-henn on release 24.05

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by tunacicek** [comment]
Gaia-X compliance:
@kelaja : No changes since Release 23.12 with respect to Gaia-X compliance -> Could you please tick this checkbox?

**Comment by tunacicek** [comment]
@kelaja :
GDPR Compliance:
No changes since Release 23.12
[Catena-X.GDPR.Declaration.and.Requirements_V2024.03_SemHub.xlsx](https://github.com/eclipse-tractusx/sig-release/files/14195390/Catena-X.GDPR.Declaration.and.Requirements_V2024.03_SemHub.xlsx)

**Comment by tunacicek** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made.
@kelaja : Could you please tick this checkbox?

**Comment by tunacicek** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12.
See also Description for R24.03
![image](https://github.com/eclipse-tractusx/sig-release/assets/115143031/6d478410-0e91-4d30-8879-2fd8c02678aa)

**Comment by tunacicek** [comment]
Verification of foreseen CX Standards:
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/125

**Comment by tunacicek** [comment]
**Documentation**

- [ ] Arc42
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/docs/documentation.md

- [ ] Administrator`s Guide (User assistance):
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/README.md

- [ ] End-User Manual (User assistance):
End-user of the services is the developer who uses the API endpoints. Hence the swagger-ui of the services serves as the documentation.
https://semantics.int.demo.catena-x.net/hub/swagger-ui/index.html
There is a rudimentary integration to the Cantena-X portal, for which an End User explanation available on Portal UI
https://portal.int.demo.catena-x.net/datamanagement

- [ ] Interfaces Documentation:
Link to swagger UI documentation:
https://semantics.int.demo.catena-x.net/hub/swagger-ui/index.html

@vialkoje : No significant changes since Release 23.12. Could you please check and approve the checkboxes?

**Comment by tunacicek** [comment]
Security Checks- Thread Modelling Analysis:
No changes sincw Release 23.12.
See also Security Assessment diagram:
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/docs/documentation.md#:~:text=s%20%3Fp%20%3Fo%20.%0A%7D-,Security,-Assessment

@guenterban : Could you please check and approve it?

**Comment by tunacicek** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/128

**Comment by thomas-henn** [comment]
> Verification of foreseen CX Standards: @thomas-henn : Could you please confirm? See also previous task for R23.12: #125

Semantic Hub is compliant with relevant published CX Standards

**Comment by thomas-henn** [comment]
> User Journey : @thomas-henn : Could you please confirm? See also previous task for R23.12: #128

Yes, user journey of Semantic Hub is aligned along with e.g. Digital Twin Registry, Discovery Services and Semantic Hub.

**Comment by tunacicek** [comment]
**Security Checks - Dynamic Application Security Testing (DAST):**
Invicti scan has been made - the results can be seen here: https://www.netsparkercloud.com/scans/report/098b72536de448934397b11101ec06f6/

@PiotrStys : Could you please review and approved it?

**Comment by PiotrStys** [comment]
Hi @tunacicek,
DAST approved.

**Comment by PiotrStys** [comment]
Hi @tunacicek,
DAST approved.

**Comment by tunacicek** [comment]
Security Check- Secret scanning:

Secret Scanning (gitleaks) is activated and available: https://github.com/eclipse-tractusx/sldt-semantic-hub/actions/workflows/gitleaks.yml

@DnlZF Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Static Application Security Testing (SAST):
See the results here:
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47240:1397649:32851557:32821215:32836865::4406299

@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - Software Composition Analysis (SCA):
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397649:32851557:32821215:32836865:::::4406299:
@BANANAS1337 : Could you please review and approved it?

**Comment by tunacicek** [comment]
Security Checks - nfrastructure as Code
https://github.com/eclipse-tractusx/sldt-semantic-hub/actions/workflows/kics.yml
@RoKrish14 : Could you please review and approved it?

**Comment by tunacicek** [comment]
General Checks - Compliant with the Style Guide
No changes since Release 23.12
UI is part of the Portal and considered there
https://portal.int.demo.catena-x.net/semantichub
@jjeroch : Could you please review and approve it?

**Comment by tunacicek** [comment]
Test Results -  E2E Integration Test
Tests done: See result here: 
https://jira.catena-x.net/browse/A1SLDT-1505

**Comment by RoKrish14** [comment]
@tunacicek : As discussed- 

SAST: **Approved**
SCA: **Approved**
IAC: **Approved**
Secret Scanning: **Approved**

**Comment by jjeroch** [comment]
> General Checks - Compliant with the Style Guide No changes since Release 23.12 UI is part of the Portal and considered there https://portal.int.demo.catena-x.net/semantichub @jjeroch : Could you please review and approve it?

@tunacicek we have a open defect from last release. We approved last release with the condition that the defect is getting solved in release 24.03. - whats the status. It looks still "undone" - https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/157

**Comment by tunacicek** [comment]
> > General Checks - Compliant with the Style Guide No changes since Release 23.12 UI is part of the Portal and considered there https://portal.int.demo.catena-x.net/semantichub @jjeroch : Could you please review and approve it?
> 
> @tunacicek we have a open defect from last release. We approved last release with the condition that the defect is getting solved in release 24.03. - whats the status. It looks still "undone" - [eclipse-tractusx/sldt-semantic-hub#157](https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/157)

Hi @jjeroch  We updated in the backend to the newest sdk and enabled the diagram API again.  The adjustments need to be done on the Portal UI side. @ma3u Do you have any updates on the UI part?

**Comment by vialkoje** [comment]
Expert Approval granted for Documentation and data sovereignty.

**Comment by DirkBTSI** [comment]
INT test performed/documented.
E2E test performed/documented.
No high defect.
TM approved
@kelaja : please approve for "E2E Integration Test passed"

**Comment by RolaH1t** [comment]
Open:
InterOP
ThreatModeling & Container Scans
StyleGuide
TRG
QG approval postponed until topics addressed / no follow-up mtg required.

**Comment by RoKrish14** [comment]
Discussed with @tunacicek
Container Scans: **Approved**

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

No significant changes detected since last release (23.12).
No open critical & high finding remaining for this release.

Documentation of the assessment will be moved out to the GitHub repositories of the Products before the next release.

**Comment by HiHenrik** [comment]
According to team no interoperability relevant changes for this release, therefore expert approval granted for interoperability

**Comment by carslen** [comment]
TRG checks completed.

**Comment by RolaH1t** [comment]
@tunacicek any update or conclusion on StyleGuide/UI? This is the only blocker from QG approval...

**Comment by FaGru3n** [comment]
Hi all,

will this be also in your interest?

> - [ ] Compliant with the **Style Guide**, fix will be delivered by @thomas-henn on release 24.05

@thomas-henn please provide a information / draft for the current release note.

Thanks in advance.

**Comment by RolaH1t** [comment]
yes, @thomas-henn , no changes to our alignment yesterday.
but in order to pass this current QG here we need two things:
1) a short "OK" from @jjeroch that she approves this approach for Release 24.03 and
2) your draft description of the "knownknown" which will remain unresolved for 24.03
Thx

**Comment by jjeroch** [comment]
> @FaGru3n: With the support of @jjeroch and @mkanal the issue is under [eclipse-tractusx/portal-frontend#446](https://github.com/eclipse-tractusx/portal-frontend/issues/446) Currently in clarification if this can be solved for release 24.05.

Hi, its a must with 24.05.
I think it was really a miss to approach the ticket in the given time. Now after we offered to take it over again; a different team was approached. Thats not ideal. However we can not change this anymore but should improve in future.
24.03. approved

**Comment by RolaH1t** [comment]
all pre-conditions fulfilled, QG approval granted.
Congrats.
