### ISSUE TITLE
[Digital Twin Kit] Release Checks

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sig-release#509]
This issue tracks all relevant release checks for KITs.

## Release Info

As the release scope isn't clear yet, the scope of changes to the kit can't yet be estimated but will be added when standards are in approval. 

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business value** statement present
- [ ] **Semantic Model Standards** submitted and published
- [ ] **Business process** documentation available
- [ ] **Architecture documentation** available
- [ ] **Access and usage policies** documented

__Optional:__

- [ ] **Tutorials** available
- [ ] **White Paper** available

# Development View

- [ ] **API specification and protocols** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Sample data** available
- [ ] **Reference implementation** available
- [ ] **Architecture documents** available

# Operation View

- [ ] **Setup guide** available

# General Checks

- [ ] **Developer journey** approved
- [ ] **CHANGELOG** maintained

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by HFocken** [comment]
No KIT PR, thereby not included in 24.05 release

**Comment by arnoweiss** [comment]
The PR was created, reviewed and merged - just not linked here. Please refer to:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/850

**Comment by danielmiehle** [comment]
@arnoweiss thanks for the hint! we included the update in the release...
