### ISSUE TITLE
R24.03 Digital Product Pass DPP BatteryPass - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#511]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
App Version: [v2.1.3](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.1.3)
Chart Version: [2.1.4](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/digital-product-pass-2.1.4)

**Leading product repository:** https://github.com/eclipse-tractusx/digital-product-pass

QG4 Review Date: 21.02.2024

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

# Security Checks

- [x] **Thread Modelling Analysis** passed
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled
      - https://github.com/eclipse-tractusx/sig-infra/issues/440
      - https://github.com/eclipse-tractusx/digital-product-pass/issues/180
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by matbmoser** [comment]
We have a release candidate: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.1.1

The TRGs were check for compliance in the following ticket: https://github.com/eclipse-tractusx/digital-product-pass/issues/180

The Security Scans are all passed including Veracode (SCA and Code Scan). I have requested today the review from the Security Team.

Also requested the Documentation review from our repository.

**Comment by matbmoser** [comment]
Little remark here: https://github.com/eclipse-tractusx/digital-product-pass/issues/224

There was a frontend import missing, so the basic E2E test of scanning a QR code was not working. We added it to the release v2.1.1 in order for the E2E tests to be passed. 

The security scans have been done again and since nothing has changed they are passed. 

Today I had a meeting with @szymonkowalczykzf to talk about the Threat Modelling and this was informed there. He will add the security thread modelling in our repo in docs/security

**Comment by BANANAS1337** [comment]
SCA and SAST approved

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved. 

Re-assessment was done on Wednesday 7th Feb 2024. All finding are properly addressed and mitigated. 
Documentation of the assessment will be uploaded soon to the Docs part of the Product Repo.

**Comment by matbmoser** [comment]
Thank you @BANANAS1337 and @szymonkowalczykzf! @RoKrish14 can you do the review to the IaC, Container Scan and DAST?

**Comment by jjeroch** [comment]
@matbmoser - updates needed

Findings:

-  please update the radio button used for the policy selection. The shared component is not used till now - https://eclipse-tractusx.github.io/portal-shared-components/?path=/story/form--radio;additionally to the radio button itself, the text value color is wrong
<img width="209" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/cde96a01-4833-4e35-aa1c-20553c6bac24">

- wrong button design used - please use the buttons as per the shared component shared - https://dpp.int.demo.catena-x.net/passport/CX:M4GP456:IMR18650V1
<img width="222" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/2dbca18f-e497-47a4-9c47-4d8975d8d9e7">

- shared component overlay design not used - update needed. Shared component: https://eclipse-tractusx.github.io/portal-shared-components/?path=/docs/modal--docs
<img width="489" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/eec5dba4-a776-488f-a0e1-f5a6784c1248">


Functional Findings:

- the policy rule is not human readable; can you please setup a real policy rule; the one I can see there seems to be a fake rule. I can not find the actual ODRL details 
- Even after "Confirming" the negotiation; the application ask for re-negotiation all the time again whenever I refresh - please check.
- System Help missing - where can I find the system documentation/enduser help?


Heads-up: the battery pass will not pass the 24.05. tests with the current implementation. Please review the Data Sovereignty Guidelines for 24.05. carefully to be able to pass 24.05.

**Comment by matbmoser** [comment]
Hi @jjeroch!

Thank you for your feedback! 

Here are some points I can answer: 

- _"Even after "Confirming" the negotiation; the application ask for re-negotiation all the time again whenever I refresh - please check"_
      -  There is no cached data, we are not allowed to do that, therefore the **intended/expected** functionality of the application is when we refresh the page, we request again the Passport and re do the negotiation.
- _"System Help missing - where can I find the system documentation/enduser help"?_
            - It is located in the right corner of the screen:
            ![image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/7e203581-dc98-4393-93ae-94f0bb14822c)
            - It is all documented in the end user guide (which is referenced in our readme, liked to the commit version pop up): https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/user%20manual/User%20Manual%20Product%20Viewer%20App.md

**Comment by jjeroch** [comment]
> Hi @jjeroch!
> 
> Thank you for your feedback!
> 
> Here are some points I can answer:
> 
> * _"Even after "Confirming" the negotiation; the application ask for re-negotiation all the time again whenever I refresh - please check"_
>   -  There is no cached data, we are not allowed to do that, therefore the **intended/expected** functionality of the application is when we refresh the page, we request again the Passport and re do the negotiation.
> * _"System Help missing - where can I find the system documentation/enduser help"?_
>   - It is located in the top right corner of the screen:
>   ![image](https://private-user-images.githubusercontent.com/71728767/305050146-7e203581-dc98-4393-93ae-94f0bb14822c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTY4MzUsIm5iZiI6MTcwODAxNjUzNSwicGF0aCI6Ii83MTcyODc2Ny8zMDUwNTAxNDYtN2UyMDM1ODEtZGM5OC00MzkzLTkzYWUtOTRmMGJiMTQ4MjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE3MDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYWJlZjA1YThmMWQyODNmYmI2OTYwYTQ2YjVkNzRmODY1Y2ZiZmE1Zjk0MjIzZjZkODAxYjFjZmEyYTNmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ieXhmkYUdP4l1qeauKt45TOIfG8nb-EdTL1lzef-p04)
>   - It is all documented in the end user guide (which is referenced in our readme): https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/user%20manual/User%20Manual%20Product%20Viewer%20App.md

Likely meeting is needed...
Click on "Help" the portal product documentation is getting displayed - not the DPP product documentation

Regarding the negotiation - lets move this to an email conversation. I like to understand the "not intended" part. To be just very transparent => the actual user will need/want this to work

**Comment by matbmoser** [comment]
Just want to add a status update here: 

We released a hotfix version with the necessary frontend changes to comply with the Style guidelines from Catena-X:

- https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.1.2

The visuals are shown in our latest user manual: https://github.com/eclipse-tractusx/digital-product-pass/blob/16aeaf1efab7cb5eeee497865e1a9871e65a20f8/docs/user%20manual/User%20Manual%20Product%20Viewer%20App.md

We solved the functional aspects like adding the End User link to the help button for the release commit. Also we can visualize in detail the odrl attributes from the policy. Additionally the open points requested in the [UX review](https://github.com/eclipse-tractusx/sig-release/issues/511#issuecomment-1944577957) were resolved.

We kindly ask @RoKrish14 or @BANANAS1337 to re-check the security scans, nothing should have changed, since we only changed the visualization of the loading page component, and some little frontend details.

Also asking here again @vialkoje to review our Documentation since our review is in wednesday next week and we are running out of time.

We will re-run the E2E tests and resolve the open points until the day of the release.

## Snapshot of the new policy acceptance dialog:

![image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/6c025c44-59d6-476c-9141-7f403a8e59d6)

**Comment by vialkoje** [comment]
could you please add the links to the documentation documents to check ? 

Arc24 documentation 
Administrators Guide 
End-User manual 
Interface documentation

**Comment by matbmoser** [comment]
I sended them per email but I can also send it here:

Arc24 documentation: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/arc42/Arc42.md

Administrators Guide: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/admin%20guide/Admin_Guide.md

End-User manual: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/user%20manual/User%20Manual%20Product%20Viewer%20App.md

Interface documentation: https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass/2.1.2

**Comment by RoKrish14** [comment]
[v2.1.2]

SAST: **Approved**
SCA: **Approved**
Secret Scanning: **Approved**
DAST: **Approved**
Container Scanning: **Approved**
IAC: **Approved**

**Comment by matbmoser** [comment]
It was missing to move this ticket to Expert Review. I adjusted it to the current status of the ticket.

**Comment by matbmoser** [comment]
We needed to re-release the tag because there was a mistake in the header licenses:
https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.1.3

The issue was raised here: https://github.com/eclipse-tractusx/digital-product-pass/issues/231

And it needed to be updated because of legal reasons. BASF was also removed from the license as detailed and approved in this PR: https://github.com/eclipse-tractusx/digital-product-pass/pull/232

There was no code changes, just documentation. We just request the security team @RoKrish14 to see the diff and re-approve the Security Aspects: https://github.com/eclipse-tractusx/digital-product-pass/compare/v2.1.2...v2.1.3

In this release is also included the comments in the .trivyignore that were required to get the security approval before.

**Comment by RoKrish14** [comment]
[v2.1.3]

SAST: **Approved**
SCA: **Approved**
Secret Scanning: **Approved**
DAST: **Approved**
Container Scanning: **Approved**
IAC: **Approved**

**Comment by thorstendikmann** [comment]
Confirming "Compliant with relevant published CX Standards".
The application follows Catena-X standards, most relevant:

- [CX-0001 EDC Discovery API](https://catena-x.net/de/standard-library)
- [CX-0002 Digital Twins in Catena - X](https://catena-x.net/de/standard-library)
- [CX-0003 SAMM Semantic Aspect Meta Model](https://catena-x.net/de/standard-library)
- [CX-0006 Registration and initial onboarding](https://catena-x.net/de/standard-library)
- [CX-0008 Relevant standards for conformity assessments](https://catena-x.net/de/standard-library)
- [CX-0013 Identity of Member Companies](https://catena-x.net/de/standard-library)
- [CX-0014 Employees and Technical Users](https://catena-x.net/de/standard-library)
- [CX-0015 IAM & Access Control Paradigm](https://catena-x.net/de/standard-library)
- [CX-0016 Company Attribute Verification](https://catena-x.net/de/standard-library)
- [CX-0017 Company Role by the Connector](https://catena-x.net/de/standard-library)
- [CX-0018 Eclipse Data Space Connector (EDC)](https://catena-x.net/de/standard-library)
- [CX-0049 DID Document](https://catena-x.net/de/standard-library)
- [CX-0050 Framework Agreement Credential](https://catena-x.net/de/standard-library)
- [CX-0051 Summary Credential](https://catena-x.net/de/standard-library)

plus additionally

- [CX-0005 Item Relationship Service API](https://catena-x.net/de/standard-library)

and for the data model:

- [CX-0034 Data Model Battery Pass](https://catena-x.net/de/standard-library)
- [CX-0095 Data Model Transmission Pass](https://catena-x.net/de/standard-library)
- [CX-0103 Aspect Model Digital Product Passport](https://catena-x.net/de/standard-library)

Furthere details are listed in the [CX-0096 Triangle For Digital Product Pass](https://catena-x.net/de/standard-library).

**Comment by thorstendikmann** [comment]
Confirming // Internal documentation
- Gaia-X compliance confirmed [CMP-1081]
- GDPR compliance confirmed (personal data, data protection + privacy DPP)  [CMP-1082]
- User Journey approved (by BO)  [CMP-1092] and [TEST-1754]
- E2E Integration Test passed [CMP-1091] and [TEST-1754]

**Comment by thorstendikmann** [comment]
Confirming
- Compliant with the Style Guide // feedback of @jjeroch (feel free to comment :) )
- Data Sovereignty checks performed // see [CMP-1089], while continuing to follow the R3.2 DS guardrails, even improving on visual components and BPN Auth

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

Re-assessment was done on Wednesday 7th Feb 2024. All finding are properly addressed and mitigated.
Documentation of the assessment was updated in the Confluence - [Security Assessment - Product Passport Application - Catena-X - IT Security - Confluence](https://protect-de.mimecast.com/s/LtwHC28yYVup8gkOBCmFL52?domain=urldefense.com)

It will be uploaded later to the Docs part of the Product Pass Repo.

**Comment by MonaBschaden** [comment]
As discussed earlier: since everything is the same as before approval it is approved

**Comment by DirkBTSI** [comment]
INT test not performed/not documented.
E2E test performed/documented.
No high defect.
TM - approval open

**Comment by hzierer** [comment]
System team check concluded successfully https://github.com/eclipse-tractusx/digital-product-pass/issues/180

Small issue with documentation in github needs clarification, but this should not affect the release

**Comment by matbmoser** [comment]
> INT test not performed/not documented. E2E test performed/documented. No high defect. TM - approval open
> 
> Updated 24-02-21 INT test performed/documented. TM approved @kelaja : please approve for "E2E Integration Test passed"

I will include that as approved too

**Comment by matbmoser** [comment]
Thank you @vialkoje!!

Marking Documentation as Approved then! Thank you very much everyone for the review!

**Comment by RolaH1t** [comment]
all pre-conditions fulfilled;
QG approval granted!
Congrats!
