### ISSUE TITLE
[IRS] Release Checks R24.3

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#518]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 
[4.5.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.5.0)

**Leading product repository:** 
[IRS Repos](https://github.com/eclipse-tractusx/item-relationship-service)

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [ ] **Gaia-X** compliance confirmed
- [ ] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [ ] **Interoperability** checks performed
- [ ] **Data Sovereignty** checks performed
- [ ] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [ ] **Arc24** documentation up-to-date
- [ ] **Administrators Guide** up-to-date
- [ ] **End-User manual** up-to-date
- [ ] **Interface documentation** up-to-date

# Security Checks

- [ ] **Thread Modelling Analysis** passed
- [ ] **Static Application Security Testing** (SAST) scans passed
- [ ] **Dynamic Application Security Testing** (DAST) tests passed
- [ ] **Secret Scans** passed
- [ ] **Software Composition Analysis** (SCA) passed
- [ ] **Container Scans** passed
- [ ] **Infrastructure as Code** (IaC) scans passed

# General Checks

- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled
- [ ] Compliant with the **Style Guide**

# Test Results

- [ ] **E2E Integration Test** passed
- [ ] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by RoKrish14** [comment]
Possible duplicate #494 ?

**Comment by mkanal** [comment]
Duplicates https://github.com/eclipse-tractusx/sig-release/issues/494
