### ISSUE TITLE
[OSim KIT] Release Checks

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sig-release#520]
This issue tracks all relevant release checks for KITs.

## Release Info

> Please provide information on what you want to be included in the Eclipse Tractus-X release.
> If you are not owner of this issue, please provide the information as comment to the issue.
> 
> If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.
> 
> If changes are already live, also point out the PRs witch included the changes for this version if possible.
> Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.
> 

This contribution contains updates to the most recent standard releases as an update to the already released _1.0.0_.

- Adoption View
  - Business process for scenario related data exchange
  - MaterialFlowScenarioRequest aspect model
- Development View:
  - requestScenarioFeedback API
  - receiveScenarioFeedback API
  - pushScenarioState API

- [653](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/653)

# General

- [x] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification**
- [ ] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by theodorisinger** [comment]
I'm the contact in the OSim Team

**Comment by maximilianong** [comment]
Pull request reviewed. Please have a look in the change request on the pr.

**Comment by dominikoeh** [comment]
Change request has been worked on as requested.

There are markdown linting issues in this pull request for files outside the scope of the Kit, due to linting errors in other Kits. Please advise, if this presents an issue for the release of this Kit

**Comment by maximilianong** [comment]
The linting issues will not stop us from merging as long as they are not coming from your content :D

**Comment by kelaja** [comment]
PR merged: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/653
