### ISSUE TITLE
[Manufacturing as a Service] Release Checks

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sig-release#522]
This issue tracks all relevant release checks for KITs.

## Release Info

> Please provide information on what you want to be included in the Eclipse Tractus-X release.
> If you are not owner of this issue, please provide the information as comment to the issue.
> 
> If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.
> 
> If changes are already live, also point out the PRs witch included the changes for this version if possible.
> Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.
> 

This is the first version of the Manufacturing as a Service KIT. It includes the Adoption View.

- [652](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/652)

# General

- [x] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [x] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by danielmiehle** [comment]
@dominikoeh please fix the requested changes in the PR by 04.03.2024 (EOB) so that we can perform the final checks and prepare the release communication.
