### ISSUE TITLE
Onboarding Service Provider UI

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#524]
*Summary*

The current existing prototype implementation of the Onboarding Service Provider flow is supposed to get updated based on the final design.

[https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=8391-1119&mode=design&t=sSFdZh89CrP8VkWG-0]

 

Background information:

The "Onboarding Service Provider UI" describes the page within the portal which is supposed to cover a registration approval screen where the Terms and Conditions can get accepted ("step 4"). On this page, the stored company data are displayed for verification by the user.

In addition, the user can change the company participation role(s) and must then accept the corresponding terms and conditions for the selected role. One, multiple or all available roles can be selected by the user. After selecting a role, the corresponding entries and checkboxes for the Terms & Conditions are displayed. The Terms & Conditions must be confirmed for each role individually before the process can be completed.

 

*The page contains the following content:*
 * Headline
 * Subheadline Section 1
 * Info text about the company details
 * Label /Value: Company Name
 * Label /Value: Street & Number
 * Label /Value: ZIP Code
 * Label /Value: City
 * Label /Value: Region
 * Label /Value: Country
 * Copy
 * Subheadline Section 2
 * Info text
 * Role entries with checkbox
 * Role description per role
 * Terms & Conditions per role with checkbox and link per term/condition as well as link to full text (opens in new browser window)
 * "confirm"-button with info text (button is inactive / grayed out as long as at least one role has not been selected and all terms & conditions belonging to the selected role have not been accepted via checkbox)

 

After confirming the selection of roles and terms & conditions via the "confirm" button, the user is redirected to a confirmation page.

 

*Confirmation Page:*

On this page, the user receives confirmation of the successful receipt of the registration and an overview of the current review status. 

The confirmation page consists of the following elements:
 * Headline
 * Subheadline
 * Info text
 * Subheadline
 * Status with label /value of last update
 * Overview of review steps with processing status (transfer from stock)
 * Back to home" button (change to start page)

 

*Error Cases:*

After confirming the selection of roles and terms & conditions via the "confirm" button, various error cases may occur:

 

*A. Server error (500)*
In this case the registration process cannot be completed. The user will be given the options to either retry the submit attempt or go back to the previous page and resubmit the data.

The error page consists of the following components:
 * Error number with error title
 * Info text about the error
 * Label with button (retry)
 * Label with link (back)
 * Info text with helpdesk and administrator mail contacts

 

*B. Data cannot be loaded from the backend.*

This can apply to the user data, the role data or both data areas at the same time.

In these cases, information texts are displayed for the respective area with the advice to reload the page.

In addition, a note is displayed for each error via the info box system.

This contains a description of the error and an administrator contact for assistance.

 

*C. The data cannot be processed*

In this case, an error message and the mail contacts to the helpdesk and administrator are displayed near the "Confirm" button.

---

### Tickets

- [x] https://github.com/eclipse-tractusx/portal-frontend/issues/483
- [x] https://github.com/eclipse-tractusx/portal-frontend/issues/484
- [x] https://github.com/eclipse-tractusx/portal-frontend/issues/485
- [x] https://github.com/eclipse-tractusx/portal-frontend/issues/486

**Comment by stephanbcbauer** [comment]
Hello @jjeroch , @evegufy  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by jjeroch** [comment]
This feature is completely delivered with 24.05. closing the ticket. Documentation was done as well
