### ISSUE TITLE
SDE Gateway ticket - Testing 24.03 SDE

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#527]
## Description
The SDE version which will be release for 24.03 is ready for UI review.

In order to access the version a resubscription to the Managed SDE is necessary.
 

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by ciprianherciu** [comment]
### Changed
- New access and usage policies added
- Documents updated
### Fixed
- Axios library issue fixed
- Duration restriction removed.
- Purpose policy “ID 3.1 Trace” updated.
- Framework agreement added in Usage Policy.
- Help link linked to the release tag.
- Page blank issue during navigation fixed.

**Comment by jjeroch** [comment]
Old and incorrect created ticket.
The reporter got requested to close it but didnt do it till now. I will now close the ticket
