### ISSUE TITLE
Quality KIT Release Checks

### ISSUE THREAD

**Issue by ClaudiaKilian** [eclipse-tractusx/sig-release#528]
This issue tracks all relevant release checks for KITs.

## Release Info

Relevant for release 2403 and included in Update page_adoption-view.md for KIT release 2403 --> Quality KIT 1.2.0 PR #643

>> Area Benefits:
Advantages slide converted to table
Advantage example slide make-over

>> Area Sematic model:
Deleted the detailed tables for each aspect model to make it more compact

>> Area Business process:
Deletion of picture "Levels" only link to Catena-X website directly
Deletion of link to policy as word document instead add of link to PDF on Catena-X website

>> Area Standards:
Added Link to EDC standard to list

>> Change Log:.
Creation of new change log entry for release changes

>> Included Fix PR https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/638
deleted the 2 files

- [PR #643](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/643)

# General

- [x] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

Content stayed mainly the same see also change log and beginning of ticket and PR

**Comment by ClaudiaKilian** [comment]
> @ClaudiaKilian please set the checkmarks of the content / artifacts that the KIT provides.

Checkmarks set @maximilianong

**Comment by jjeroch** [comment]
@ClaudiaKilian  & @danielmiehle please check once the ticket details. I am assuming that the ticket is related to 24.03. If thats the case, please update the milestone on the right hand side
<img width="267" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/f9d31f92-b914-4bcd-93d2-9b03fbb645f1">

As soon as this is done; the status needs to get adjusted as well.
Dont forget to close the ticket at the end of the process

**Comment by kelaja** [comment]
handled separately in PR - closing this issue
