### ISSUE TITLE
[Agents KIT] Release Checks

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#534]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.
Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.

- [PR number](pr-url)

# General

- [ ] **CHANGELOG** available and maintained

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [ ] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by maximilianong** [comment]
Thanks for fixing the linter issues.
On this KIT are no content changes (mail communication with @TomBuchertTSystems)

FYI @kelaja / @RolaH1t 
Please take this to the 'no changes' section in the release notes.

**Comment by jjeroch** [comment]
@TomBuchertTSystems   & @maximilianong  please check once the ticket details. I am assuming that the ticket is related to 24.03. If thats the case, please update the milestone on the right hand side
<img width="267" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/f9d31f92-b914-4bcd-93d2-9b03fbb645f1">

As soon as this is done; the status needs to get adjusted as well.
Dont forget to close the ticket at the end of the process

**Comment by kelaja** [comment]
handled separately in PR - closing this issue
