### ISSUE TITLE
[Connector Kit] Release Checks

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sig-release#536]
This issue tracks all relevant release checks for KITs.

## Release Info

There's a structural overhaul of the Connector Kit. It now links to a lot of outside resources in the tractusx-edc and eclipse-edc documentations. The Management API walkthrough was moved into the tractusx-edc documentation.

This PR introduced the recent version.
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/558

# General

- [ ] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [x] **Tutorials** available
- [x] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [x] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [x] **Reference Implementation** available

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [x] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by danielmiehle** [comment]
@arnoweiss thank you for PR and streamlining the Connector KIT. Some suggestions / remarks from our side:

We could not find any information about the following artifacts. They are not mandatory for KITs in the network service area. However, you checked them in this ticket. Should we uncheck them?

- Business Value
- Semantic Model
- Access Usage Policies

Suggestions: 
Doest make sense to link to the following documents in your KIT?

- Link to e2e tutorial --> https://eclipse-tractusx.github.io/docs/tutorials/e2e
- Link to whitepaper --> https://catena-x.net/fileadmin/_online_media_/231006_Whitepaper_EnablementServices.pdf

**Comment by maximilianong** [comment]
@arnoweiss @stefan-ettl @stephanbcbauer 
Friendly reminder - Please fix the requested changes by 04.03.2024 (EOB) so that we can perform the final checks and prepare the release communication. Thanks!

**Comment by arnoweiss** [comment]
Added another PR
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/730
