### ISSUE TITLE
[Certificate Management KIT] Release Checks

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/sig-release#537]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.
Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.

- [684](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684)

# General

- [X] **CHANGELOG** available and maintained

# Adoption View

- [X] **Vision and Mission** statement present
- [X] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [X] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [X] **Notice** CC BY 4.0 licence statement available

# Development View

- [X] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [X] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [X] **Reference Implementation** available

# Operation View

- [X] **Setup Guide** available (e.g., installation guides)
- [X] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by maximilianong** [comment]
**Feedback to adoption view** - please adjust your checkmarks:

Logic / schema (not available but not necessary)
Semantic Models (not available now but not necessary)
Business Process (not available but not necessary)
Access and Usage Policies documented (not available now but not necessary)
White Paper available (not available but not necessary)
Tutorials (not available but not necessary)

**Feedback to development view** - please adjust your checkmarks:

 Protocols available (not available but not necessary)
 Sample Data available (not available but not necessary)

**Comment by maximilianong** [comment]
Please switch the position of the left navigation:
1. Adoption
2. Development
3. Operation

**Comment by jjeroch** [comment]
@SujitMBRDI   & @maximilianong  please check once the ticket details. I am assuming that the ticket is related to 24.03. If thats the case, please update the milestone on the right hand side
<img width="267" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/f9d31f92-b914-4bcd-93d2-9b03fbb645f1">

As soon as this is done; the status needs to get adjusted as well.
Dont forget to close the ticket at the end of the process
