### ISSUE TITLE
Data Governance Kit - Release Checks

### ISSUE THREAD

**Issue by dg-tsy** [eclipse-tractusx/sig-release#542]
This issue tracks all relevant release checks for KITs.

## Release Info

I want to provide the documentation for Data Governance Kit which will include adoption view, operation view and development view and will have the relevant API specifications.

The link to the Pull request is available below

- [PR 701](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/701)

# General

- [ ] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [ ] **Semantic Models** linked and described _- Not Required_
- [ ] **Logic / Schema** available and described _- Not Required_
- [ ] **Business Process** documentation available _- Not Required_
- [ ] **Access and Usage Policies** documented _- Not Required_
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models) _- Not Required_
- [ ] **Tutorials** available _- Not Required_
- [ ] **White Paper** available _- Not Required_
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol) _- Not Required_
- [ ] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available _- Not Required_

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides) _-  No installation required_
- [ ] **Deployment Script** available (e.g., helm charts) _- No deployment required_

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by maximilianong** [comment]
@dg-tsy please set the checkmarks for the content that you provided with your PR.

**Comment by dg-tsy** [comment]
@maximilianong I have updated few checkmarks and mentioned where the topics are not relevant for DGK. 

One question I do have regarding "API Specification published on SwaggerHub" checkmark - 

I have uploaded the OpenAPIs.yaml to my Swagger account for now, but I would need to upload those to the "eclipse-tractusx-bot" account. How can I do this? Do I need some special access for it?

**Comment by jjeroch** [comment]
@dg-tsy & @danielmiehle please check once the ticket details. Release 24.03. is over, but the status is still "in progress" and ticket is not closed. Please adjust

**Comment by danielmiehle** [comment]
@kelaja @RolaH1t: What is the defined release process? I assumed that the release management team is responsible for closing the tickets, correct?

**Comment by kelaja** [comment]
handled separately in PR - closing this issue
