### ISSUE TITLE
[ESS] Release Checks

### ISSUE THREAD

**Issue by birgitZF** [eclipse-tractusx/sig-release#547]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

- First kit release for ESS (Enironment and Social Standards) use case

- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/709

- PR 709

# General

- [ ] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by maximilianong** [comment]
@birgitZF can you please set the checkmarks for the artifacts / content that you provided with the KIT

**Comment by birgitZF** [comment]
@maximilianong I am not sure with some of the checkmarks, e.g. Logic / Schema, we have pnly got one standard: essINcident - data model
@maximilianong when is the deadline? I still have open questions about the table format to @stephanbcbauer

**Comment by maximilianong** [comment]
Final pull request needs to be done til the 04.03.2024

Should we setup one meeting to clarify? 
Because I have some concerns if this is already a real KIT or still a preview of a KIT. Maybe we can have this discussion aswell.

**Comment by birgitZF** [comment]
PR created 04.03.2024
https://github.com/catenax-eV/product-standardization-prod/pull/125

**Comment by jjeroch** [comment]
@birgitZF  & @maximilianong  please check once the ticket details. I am assuming that the ticket is related to 24.03. If thats the case, please update the milestone on the right hand side
<img width="267" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/f9d31f92-b914-4bcd-93d2-9b03fbb645f1">

As soon as this is done; the status needs to get adjusted as well.
Please note: if this is an issue ticket for Post-Consortia; the milestone should stay empty

**Comment by birgitZF** [comment]
@jjeroch, you are right, the kit is for 24.3. I have no authorization to edit the right hand side, there is no settings- button for me
@maximilianong , can you change the label for me, please?

**Comment by kelaja** [comment]
handled separately in PR
