### ISSUE TITLE
[Quality KIT] 2405 Release Checks

### ISSUE THREAD

**Issue by ClaudiaKilian** [eclipse-tractusx/sig-release#553]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.
Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.

- [PR number](pr-url)

# General

- [x] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [x] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [x] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by ClaudiaKilian** [comment]
PR #2 R2405 Quality KIT

**Comment by HFocken** [comment]
Please correct link asap - this one goes somewhere else... https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/817 is this the correct one? please confirm asap!

**Comment by HFocken** [comment]
Not included in 24.05. release due to missing PR.
