### ISSUE TITLE
[Connector Kit] Release Checks

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sig-release#556]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.
Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.

https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/792

# General

- [ ] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [x] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [x] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [x] **Reference Implementation** available

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [x] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by arnoweiss** [comment]
fix markdownlint
```text
docs-kits/kits/Connector Kit/Adoption View/adoption-view.md:8 MD0[25](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/runs/8145867583/job/22263090486#step:6:26)/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Adoption View"]
docs-kits/kits/Connector Kit/Adoption View/adoption-view.md:79:122 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Adoption View/adoption-view.md:93:119 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Adoption View/adoption-view.md:160:1 MD053/link-image-reference-definitions Link and image reference definitions should be needed [Unused link or image reference definition: "dsp-url"] [Context: "[dsp-url]: https://docs.intern.../"]
docs-kits/kits/Connector Kit/Development View/architecture.md:24 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Architecture"]
docs-kits/kits/Connector Kit/Development View/architecture.md:46:91 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Development View/architecture.md:53:118 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Development View/specifications.md:6 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Specifications"]
docs-kits/kits/Connector Kit/Development View/specifications.md:23:115 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Development View/specifications.md:24:172 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Operation View/operation-view.md:6 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Operation View"]
docs-kits/kits/Connector Kit/Operation View/operation-view.md:[33](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/runs/8145867583/job/22263090486#step:6:34):109 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/Operation View/operation-view.md:40:65 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
docs-kits/kits/Connector Kit/page_changelog.md:64:5 MD047/single-trailing-newline Files should end with a single newline character
```

**Comment by arnoweiss** [comment]
Make sure the page actually shows up

**Comment by HFocken** [comment]
Please add PR asap - reviews are ongoing until the end of the week!

**Comment by arnoweiss** [comment]
added to description

**Comment by danielmiehle** [comment]
@arnoweiss and team, thanks for the KIT update. PR is already reviewed and merged. Therefore I will close this ticket.
