### ISSUE TITLE
SDE: Maintenance 24.08

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#567]
## Description

This issue is **not aiming for new or extended functionalities**, but assuring all changes are implemented, that are required to ensure the compatibility/interoperability with depending components.

The required changes are depending on the features changes of the depending components, selected during the upcoming PI Planning. The full extent of required changes can only be defined, after all other features requests are approved and finalized in the PI Planning.

The preliminary maintenance changes might include:

- Adaptation of changes of depending components (see Dependencies below)
- Adaptation of new sub-components of depending components
- Adaptation of changes to the semantic models
- Adaptation of new release guidelines for 24.08
- Solving upcoming security issues to fullfil acceptance criteria
- Additional maintenance to pass new quality gates

## Required enablers

Depending on the selected feature changes of the PI Planning.

## Business value

As this is not a feature, it does not provide direct business value, but cares for not losing existing business value, by making sure existing business applications will work with the updated components as well.

## Test scenarios

The existing test scenarios shall be passed as expected, as the functional scope of the component is not changed.

## Acceptance criteria

- Ensured compatibility with depending components based on integration/E2E tests
- Security issues are solved
- Quality Gate has to be passed

## Feature estimation

Not yet possible due to the dependency on the PI Planning.

## Developer team

*t.b.d.*

## Dependencies

- [Eclipse Dataspace Connector (EDC)](https://github.com/eclipse-tractusx/tractusx-edc)
- [Decentralized Digital Twin Registry (dDTR)](https://github.com/eclipse-tractusx/sldt-digital-twin-registry)
- [Managed Identity Wallet (MIW)](https://github.com/eclipse-tractusx/managed-identity-wallet)
- [SLDT Semantic Models](https://github.com/eclipse-tractusx/sldt-semantic-models)
- Policy Hub: relates to: https://github.com/eclipse-tractusx/sig-release/issues/581

**Comment by jjeroch** [comment]
Attention @ciprianherciu : **Upcoming PI Planning Preparation**

As we gear up for the forthcoming PI Planning session, it is crucial that all features under consideration align with our established Feature Quality Standards and Definition of Done (DoD) guidelines. To ensure your feature is thoroughly prepared and stands a strong chance of being prioritized, please provide comprehensive documentation that includes the following components:

1. Feature Summary: An executive overview that encapsulates the essence and objectives of the feature.
2. Change Description:
- High-Level Overview: A succinct synopsis of the proposed changes and their overarching impact.
- Detailed Analysis: An in-depth exploration of the specific alterations, including a clear exposition of the anticipated impact on existing systems.
3. Impacted Components: A list identifying all system components that will be affected by the feature implementation, accompanied by a brief explanation of the nature of the impact.
4. Acceptance Criteria: A set of clearly defined conditions that must be met for the feature to be considered complete and acceptable.
5. Test Scenarios: A detailed outline of test cases that cover all functional paths of the feature to ensure robust validation and verification.

Please note that any feature submissions lacking these essential elements will not be eligible for consideration in the upcoming PI Planning. It is imperative that your documentation is both thorough and precise to facilitate a smooth and effective planning process.

---

Additionally to that, the milestone was deleted as well as I like to ask you to correct the ticket title. The release will be given as part of the PI planning

**Comment by stephanbcbauer** [comment]
was presented in open planning ⇾ contributors and committer are involved.

**Comment by stephanbcbauer** [comment]
Hello @ciprianherciu  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by ciprianherciu** [comment]
- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ]  Please check whether the status (backlog, work in progress ...) is set correctly
- [ ]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ]  Please comment on the current status of the feature
- [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

**Comment by stephanbcbauer** [comment]
Hello @ciprianherciu  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by ciprianherciu** [comment]
- Adaptation for PCF Use Case (Submodel Version 7.0.0)
- EDC v 0.7.2 adaptation

**Comment by Sebastian-Wurm** [comment]
@ciprianherciu : is this already done?

**Comment by stephanbcbauer** [comment]
@ciprianherciu This was a feature for milestone 24.08. Is this an ongoing topic? Is it closed? Moved?
