### ISSUE TITLE
Check if Project "Release Planning" is automatically assigned when a new feature is created using the feature template

### ISSUE THREAD

**Issue by mabige** [eclipse-tractusx/sig-release#568]
## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by FaGru3n** [comment]
FYI additional info for workflows to the github project could be reviewed under:
https://github.com/orgs/eclipse-tractusx/projects/26/workflows

![image](https://github.com/eclipse-tractusx/sig-release/assets/121097161/3dc9ec08-db79-4c7c-9875-94b890fdd9ff)
