### ISSUE TITLE
Streamline Release Process documentation

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-release#572]
## Topic to be covered

- [ ] Website "Versions" nav item (needed?)
- [ ] Process definition in Tractus-X (issues labels responsible persons)
- [ ] Remove duplicate descriptions (sig-release vs. tractus-x-release, website)
- [ ] How does Tractus-X support the Association process?
- [ ] Find consensus in committer group (mailing list, and/or matrix committer room + "sounding meeting")

## Additional info

- #519 
- https://github.com/eclipse-tractusx/tractus-x-release/blob/main/RELEASE.md
- https://eclipse-tractusx.github.io/release-information

FYI @stephanbcbauer

**Comment by RolaH1t** [comment]
working assumption @stephanbcbauer & @RolaH1t (21-Mar):
Release-Info must be available in TWO locations:
1) highlevel intro and "pick-up" of users on homepage (github.io page)
2) SIG Release repository => here with all details

**Comment by RolaH1t** [comment]
consolidation approach aligned with @stephanbcbauer and @Siegfriedk:
![image](https://github.com/eclipse-tractusx/sig-release/assets/135834369/f2a4e085-d143-476d-b917-b5b57b47066a)

Detailed text building blocks will follow

**Comment by RolaH1t** [comment]
Thanks to @Siegfriedk this issue can be closed as resolved, once the following PR`s are merged:
https://github.com/eclipse-tractusx/tractus-x-release/pull/26
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/852
https://github.com/eclipse-tractusx/sig-release/pull/662

**Comment by SebastianBezold** [comment]
Hey @RolaH1t and @Siegfriedk,

to be honest, I would have appreciated, if you had based your work on top of #662. There has been a lot fo effort put in, not only by me, but also by other contributors adding comments to improve the contents.
