### ISSUE TITLE
[DCM-KIT] Release Checks

### ISSUE THREAD

**Issue by nhaenis** [eclipse-tractusx/sig-release#580]
This issue tracks all relevant release checks for KITs.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.
Please refer to TRG 8.03 for the classification of mandatory and optional artefacts.

- Pull Request [836](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/836)

# General

- [x] **CHANGELOG** available and maintained

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by ClosedSourcerer** [comment]
This Issue concerns PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/836

**Comment by nhaenis** [comment]
@danielmiehle, due to the absence of Max:

Can you please confirm to us that this issue and the associated PR will be taken into account for the next KIT release and will go through the Q-Gate checks? As far as I know, we didn't have to do anything more than create the issue and link the PR, but we haven't received any feedback on it so far.

@ClosedSourcerer will then take over the issue + PR for the release process during my absence.

Thank you

**Comment by danielmiehle** [comment]
Nice Update! Review done - please address requested minor changes. Thanks!

**Comment by ClosedSourcerer** [comment]
Requested Changes have been implemented.

**Comment by HFocken** [comment]
Merged!
