### ISSUE TITLE
BPDM Golden Record Release Checks

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#590]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: * App Version 6.0.1 HelmChart 5.0.1*

**Leading product repository:** [*repository link*](https://github.com/eclipse-tractusx/bpdm)

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/bpdm/issues/908

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ThomasObermeyer** [comment]
@kelaja - performed a delta review with the team. No major changed as far as interoperability is concerned.

**Interoperability EA Approved**

**Comment by rybtim** [comment]
@guenterban For Golden Record R.24.05 no changes related threat modelling analysis necessary. https://github.com/eclipse-tractusx/bpdm/blob/main/docs/Security_Assessment.md analysis made for R.24.03 still apply. Could you please release?

**Comment by hzierer** [comment]
Can you please assign a committer to the [QG check](https://github.com/eclipse-tractusx/bpdm/issues/908) - if possible someone not being part of BPDM...

**Comment by guenterban** [comment]
threat modelling analysis approved

**Comment by alexKeppler** [comment]
User Journey approved by BO. Thanks for your efforts!

**Comment by cbrugg** [comment]
INT Tests partially aborted due to EDC Setup Efforts. E2E Tests serve as alternative and are successfully performed. Data Sov Tests were performed "best effort". Not applicable Testcases are being discussed today afternoon.
Testmanagement approves with the mentioned restrictions.

**Comment by RolaH1t** [comment]
QG review 15-5:
data sov review scheduled 15-5 / no blocker expected
TRGs 95% complete / only IP clearance pending (TRG 7.07)
Testing approved
no follow-up mtg required => unless an issue due to legal TRG 7.07 occurs

**Comment by KMA-2019** [comment]
@vialkoje , @cbrugg , @rybtim as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.**
No blocking issues for current Rel 24.05 but main items to be considered for next release(s): 

- Note: **additional tests (from customer perspective) only partially possible**
- special situation as **one data exchange partner is always the OpCo**
- **no UI**: configuration of policies only in the backend, mechanism: Data Consumer on Sharing Member side will need to store company rules; whenever negotiation takes place: read data offer via API from OpCo, insert the known policy one on sharing member side to negotiate - if not matching, no negotiation (EDC Functionality)
- **ContractReference Constraint**: technically could be supported but not used (see point that one data exchange partner is always the OpCo) -> clarification of process for future release
- **no validation of the Schema** "profile": "cx-policy:profile2405", incomplete policy not tested / not possible to test

**Comment by vialkoje** [comment]
is there an evaluation of the QG-Checklist available ? https://confluence.catena-x.net/x/NTeJBg

**Comment by rybtim** [comment]
> is there an evaluation of the QG-Checklist available ? https://confluence.catena-x.net/x/NTeJBg

@vialkoje  Data Sov was documented in our Jira Test execution https://jira.catena-x.net/browse/TEST-1991. What else is necessary?

**Comment by RolaH1t** [comment]
Great. So completion of TRG checks is the final topic...

**Comment by hzierer** [comment]
all TRG check completed successfully

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by nicoprow** [comment]
Updated app and chart to newest patch version (6.0.1 and 5.0.1 respectively)

**Comment by stephanbcbauer** [comment]
Hello @nicoprow , @hzierer , @rybtim , @HeyHardy , @RolaH1t  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by rybtim** [comment]
> Hello @nicoprow , @hzierer , @rybtim , @HeyHardy , @RolaH1t
> 
> Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?
> 
> * [ ]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
> * [ ]  Please check whether the status (backlog, work in progress ...) is set correctly
> * [ ]  Please comment on the current status of the feature
> * [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
> * [ ]  Is there a spillover planned?
> 
> If you need any clarification, please get in touch, thank you very much.
> 
> Stephan

Hi Stephan, this was not a feature just our quality gate issue for R24.05 for the Golden Record. Quality gate was passed so I losed the issue.
