### ISSUE TITLE
[EcoPass KIT]: [Release 24.08] Updated Data Models to latest standardized versions available

### ISSUE THREAD

**Issue by catroest** [eclipse-tractusx/sig-release#591]
## Description
The EcoPass KIT has some updates that were pending in comparative to the R24.05.
The following things need to be updated:
Application includes updates from:
- Integration of BPDM
- Battery Pass Data Model v6.0.0
- Digital product pass data model 5.0.0
- Transmission Pass v3.0.0
- Update EDC version v0.7.0

Data Modeling
- Data model updates/bug fixes (DPP, Battery, Transmission, E-Drive, Material)

## Objectives

- [X] Update the EcoPass KIT with the latest models
- [X] Reference and update the addons in the EcoPass KIT:  https://github.com/eclipse-tractusx/sig-release/issues/651

## Impact
- No Impact

## Additional information 
- [X] I'm willing to contribute to this feature

### Committers
- @matbmoser 
- @saudkhan116 

### Related Issues:
- https://github.com/eclipse-tractusx/sig-release/issues/651

### Related PRs:
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/952

**Comment by catroest** [comment]
@jocbra

**Comment by stanfaldin** [comment]
Hi @catroest ,
if not already mentioned in your description, can you check if you can add some of those points to raise the quality of that feature ...

- Feature author defined: The designated point of contact for any questions related to the feature during the refinement, planning and development phase (e.g., subject matter expert). Not necessarily responsible for the technical implementation of a feature.
- Feature desciption is available
- Required enablers are defined and aligned (e.g., architecutre, infrastructure, compliance)
- Key dates and milestones are defined using GitHub milestone declaration
- Business value is defined
- Test scenarios, test cases and test data are available
- Accpetance criteria are defined
- Feature estimation available (based on story points)
- Developer team for feature implementation defined
- Dependencies with other products or issues are identified and categorized via GitHub labels
- Known riks are properly adressed
- No open questions left
- First implementation issues are defined ...

Many Thanks

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ for KIts responsible commiters are already defined

**Comment by stephanbcbauer** [comment]
Hello @matbmoser 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by catroest** [comment]
Status update: content is being planned

**Comment by stephanbcbauer** [comment]
Hello @matbmoser 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by matbmoser** [comment]
@stephanbcbauer I have updated this ticket to reflect the latest changes and also the status of the ticket. Linked the PRs and the committers which are responsible for it.

**Comment by matbmoser** [comment]
I was not aware this issue existed, because of this I did not comment in here:

> Hello [@matbmoser](https://github.com/matbmoser)
> 
> In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
> 
> Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
> 
> If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
> 
> Thank you and best regards.

**Comment by matbmoser** [comment]
Merged the PR
