### ISSUE TITLE
R24.05 Simple Data Exchanger (SDE) - Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#593]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/41

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ThomasObermeyer** [comment]
@kelaja renewed interoperability based on provided information.
Under the assumption the E2E tests with SAP, SupplyOn and Siemens are successful, then the solution is interoperable according to our guidelines.

**Interoperability EA approved**

**Comment by AjayRaturi123** [comment]
**Security Checks**

**Thread Modelling Analysis** :-
https://confluence.catena-x.net/pages/viewpage.action?pageId=62831498
@guenterban Added the document link; please approve.

**Comment by AjayRaturi123** [comment]
**Test Results**

1. **E2E Integration -** 

2. **User Journey -** No changes for Release R24.03 on User Journey.

**Comment by AjayRaturi123** [comment]
**Data Sovereignty** 

- For data sovereignty we have implemented Policy Hub which should assure that the Data Sovereignty standards are followed . E2E tests are executed for the same according to standards. 

E2E Test - https://jira.catena-x.net/browse/TEST-1983 

@vialkoje Please review and approve.

**Comment by ciprianherciu** [comment]
@almadigabor Please confirm that the TRG;s were followed for SDE

**Comment by ciprianherciu** [comment]
@guenterban the Thread Modeling Report can be Found here: 
https://confluence.catena-x.net/pages/viewpage.action?pageId=62831498
There are no changes from last Release (24.03).

Please helps us approve it

**Comment by ciprianherciu** [comment]
Product Owner: Ciprian Herciu
Dev SPOC: Aditya Gajbhiye
Helm Chart Version: 0.1.7
App Version: 2.3.8

**Comment by ciprianherciu** [comment]
### Data Provider (Applications FOSS & COTS incl. Broker)
- [ ] A data offer (contract Offer) MAY consist of an access policy and MUST include at least one usage policy.
      - [ ]The access policy MUST use CX Standardized credentials.
      - [ ] A usage policy MUST refer to at least one Verifiable Credential(Framework Agreement)* (hereinafter referred to as VC). The currently available credentials can be viewed in the [CX-0050 standard](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_September23/CX-0050-FrameworkAgreementCredential-v.1.0.0.pdf). The usage policy MUST refer to a confirmed framework agreement which covers the desired scope of data (e.g. traceability, quality,...). It MUST reference the agreement either as a whole or additionally dedicated predefined elements (e.g. purpose - defined in CX-0018 standard) of the framework agreement.
      - [ ]In case the data provider is enabled to create contract offers, the data provider MUST be enabled to configure contract offer policies.
- [ ]The application MUST use the BPN-L of the data provider when providing data via the DSP connector (e.g. EDC or managed EDC).
- [ ]The provider of the connector MUST ensure the provision of data via the DSP protocol adhering to the released version of [CX-0018 standard](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_September23/CX-0018-EclipseDataConnector_EDC_-v.2.0.1.pdf). For example, using the Eclipse Data Space Connector on [Tractus X](https://github.com/eclipse-tractusx/tractusx-edc).
      - [ ]This provider also MUST ensure that the data provider is uniquely identifiable through its associated BPN-L.
      - [ ]This BPN-L must be used by this provider to identify the data.

### Data Consumer (Applications FOSS & COTS incl. Broker)
- [ ]The provider of the connector MUST ensure the consumption of data via the DSP protocol adhering to the released version of [CX-0018 standard](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_September23/CX-0018-EclipseDataConnector_EDC_-v.2.0.1.pdf). For example, using the Eclipse Data Space Connector on [Tractus X](https://github.com/eclipse-tractusx/tractusx-edc). 
      - [ ]The application MUST ensure that the consumer of the data is uniquely identifiable through its associated BPN-L.
      - [ ]This BPN-L must be used by this application to identify the data.
- [ ]The application MUST use the BPN-L of consumer of the data when consuming data via the DSP connector (e.g. EDC or managed EDC).
- [ ]A user of an application MUST be enforced to act within the constraints of the framework agreement by appropriate means (legal, technical,...).
- [ ]To agree to one or multiple contract offers for a queried data asset, the selection of the appropriate offer MUST be done through the consuming application ensuring to follow company-defined rules and regulations for a user of that application.

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - Approved
All required recommendations are addressed, solutions implemented.

**Comment by ciprianherciu** [comment]
@vialkoje above we have answered how Data Sov checklist.
Please approve the Data Sov, or contact us for more questions

**Comment by almadigabor** [comment]
Hey @ciprianherciu! I've prepared the [TRG check issue](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/41). Before we start we need another committer who joins me to do the checks together. Can you provide me one? Thanks!

**Comment by ciprianherciu** [comment]
Helm Chart Version: 0.1.7
App Version: 2.4.0

For a second committer as discussed with @RolaH1t at the moment is not a must have.
As long as You feel comfortable to make the checks by yourself, it will be accepted in the QG

**Comment by cbrugg** [comment]
SDE Application INT Tests done / Data Sov Tests done / E2E Tests Done
PCF Exchange SDE E2E/INT Tests ongoing / Data Sov Tests done
Data Sov was discussed. Only one Testexecution is enough.

**Comment by RolaH1t** [comment]
QG review 15-May
data sov expert approval outstanding
user journey approval expected on short notice
TRG review pending; committers approached
no follow-up mtg required, will monitor via issue

**Comment by vialkoje** [comment]
As checklist ios answered and tests ran thorugh the expert approval for sovereignty is granted

**Comment by ciprianherciu** [comment]
The User Journey was approved by Christoph Langdon

**Comment by KMA-2019** [comment]
@vialkoje , @cbrugg , @ciprianherciu as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.**
Based on Angelika Dodels Test Execution, no blocking issues for current Rel 24.05 but some items to be considered for next release(s): 

- Note: additional tests (from customer perspective) **fully possible**
- **ContractReference Constraint** currently not implemented 
- **Declining a specific contract offer based on an unwanted Usage Policy is not possible, i.e. same options will re-appear again upon re-visiting page
- **validation of the Schema** "profile": "cx-policy:profile2405" not fully checked  during test (required to ensure interop with other apps)

**Comment by mabige** [comment]
@kelaja  
All seems be done. Pls. approve.

**Comment by Niels1511** [comment]
User Journey approved.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by almadigabor** [comment]
Hey all, a patch has been released, so the new versions approved by me in terms of TRGs are the following:

Helm Chart Version: 0.1.9
App Version: v2.4.1
