### ISSUE TITLE
R24.05 Managed Service Orchestrator - Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#594]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** N/A
- [x] **Data Sovereignty** N/A

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey**  N/A

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by tomaszbarwicki** [comment]
QG Checks created: https://github.com/eclipse-tractusx/managed-service-orchestrator/issues/133

**Comment by sharathshivprasad** [comment]
Data Sovereignty: There are no changes from last release regarding the data Sovereignty for managed service Orchestrator.

**Comment by sharathshivprasad** [comment]
Threat modelling Document: https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+Auto+Setup+API

**Comment by sharathshivprasad** [comment]
For User Journey, no changes from last release

**Comment by ciprianherciu** [comment]
At the moment on blocked because of the [TEST-2003](https://jira.catena-x.net/browse/TEST-2003)

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - approved - no changes from last release:
All recommendation already completed and implemented.

**Comment by ciprianherciu** [comment]
Data Sovereignty is not applicable for MSO. Please approve @vialkoje

**Comment by RolaH1t** [comment]
QG review 15-May
testing blocked / issue addressed and monitored => code update with version increase necessary
parallel activities: obtain feedback for data sov, interop, user journey & threat modelling
TRG review can be initiated based on final version
? follow-up mtg required

**Comment by mabige** [comment]
@RolaH1t is this "data sov & interop considered not applicable; same as user journey" already a  documented decision or is it required to get expter approval?

@ciprianherciu

**Comment by cbrugg** [comment]
As discussed in Daily Testmanagement Approval is given if Issues are declared as Known Knowns and adressed in R24.08.

**Comment by RolaH1t** [comment]
Hi @ciprianherciu 
do we still expect a code update for MSO here (as assumed in the QG review last week)?
or are you going to update the changelog with the knownknown referring to the testing issue?
In both cases I kindly ask you to complete the TRG checks for the final version with @tomaszbarwicki please.

note to @mabige `s question: there is no additional actions required regarding data sov, interop or user journey based on our decision in the QG review.

**Comment by almadigabor** [comment]
I checked the last remaining issue and trusting @tomaszbarwicki did all the other checks I approve the TRG QG checks with the following versions:

Helm Chart Version: 1.5.9
App Version: 1.5.6

**Comment by ciprianherciu** [comment]
@RolaH1t all the TRG's are approved.

**Comment by ciprianherciu** [comment]
@RolaH1t could we consider MSO for a conditional release?
We have mentioned the Known Know in our product change log:
For MSO: The retrieval and processing of the DIM Technical User credentials for automatic configuration and set-up of the EDC connector could not be fully tested. So the full functionality cannot be guaranteed.

Could You please give us the approval for the conditional release?

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by ciprianherciu** [comment]
> yes @ciprianherciu I just verified the text in product changelog. with TM approval above and TRGs fulfilled => pls check the box on top and let me know, so QG shall be fine

Done! Thank You!
