### ISSUE TITLE
R24.05 SD Factory - Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#595]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** N/A
- [x] **Data Sovereignty** N/A

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/sd-factory/issues/134

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by tomaszbarwicki** [comment]
QG Checks created: https://github.com/eclipse-tractusx/sd-factory/issues/134

**Comment by sharathshivprasad** [comment]
• Data Sovereignty is not applicable to SD-Factroy, since we do not store any data.

**Comment by sharathshivprasad** [comment]
[A1IDSES-1576](https://jira.catena-x.net/browse/A1IDSES-1576) - SDF - Integration Testing
[A1IDSES-1577](https://jira.catena-x.net/browse/A1IDSES-1577) - SDF - Internal integration Testing

**Comment by ciprianherciu** [comment]
As stated for the previous releases the following checks are not relevant for SD Factor:
- Interoperability checks performed
- Data Sovereignty checks performed

No Changes from previous versions
- User Journey no changes from 24.03
- Thread Modeling: https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+IDS+Essential+Services%3A+SD+Factory

The E2E test for SD factory is covered by the onboarding of any company.
As long as the onboarding works SD Factory is E2E tested

**Comment by ciprianherciu** [comment]
Product Owner: Ciprian Herciu
Dev SPOC: Aditya Kumar
Helm Chart Version: 2.1.17
App Version: 2.1.11

**Comment by ciprianherciu** [comment]
@vialkoje as for other release Data Sov is not relevant for SD Factory.
Please approve that out of Data Sov perspective.

**Comment by cbrugg** [comment]
INT Tests done. No explicit E2E Tests planned as it is implicitly tested. @ciprianherciu can you give more details on this? Which tests in the E2E Test cover this part? 
SDE Data Sov Tests see https://github.com/eclipse-tractusx/sig-release/issues/593

**Comment by ciprianherciu** [comment]
@cbrugg the Portal E2E Tests (https://jira.catena-x.net/browse/TEST-1895)covers the SD Factory Testing.
If the registration works, than SD Factory works

**Comment by cbrugg** [comment]
Thank you for clarifying @ciprianherciu in that case we can approve from Testmanagement side as all tests have been successfully performed.

**Comment by RolaH1t** [comment]
QG review 15-May
Interop & DataSov considered not applicable
SEC approval expected on short notice
user journey approval expected as carry-over from March
TRG review pending; committers approached
no follow-up mtg required, will monitor via issue

**Comment by ciprianherciu** [comment]
@szymonkowalczykzf Could You please also approve this Thread Model Analysis as well?
https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+IDS+Essential+Services%3A+SD+Factory

**Comment by ciprianherciu** [comment]
Hello @wjost,
Could You please approve the "User Journey" of the SD Factory.
Portal Team  has performed the E2E test execution and it was successful. 
https://jira.catena-x.net/browse/TEST-1895
Please review and approve.

**Comment by szymonkowalczykzf** [comment]
> @szymonkowalczykzf Could You please also approve this Thread Model Analysis as well? https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+IDS+Essential+Services%3A+SD+Factory

Hello, Ciprian - could you please confirm if the application did not have any architectural changes since the last release including introduction of new application components ?

**Comment by ciprianherciu** [comment]
@szymonkowalczykzf I can confirm that no architectural changes were made  or new components were added!

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - approved
All required recommendations were already addressed and implemented. Adding to that no architectural changes and new components in the application since last release.

**Comment by almadigabor** [comment]
Hey, I approve the TRG issue. Thanks @RoKrish14 for participating in the checks! The versions are:

- app version: `2.1.12`
- chart version: `2.1.18`

**Comment by akelecevic** [comment]
Since @wjost is out of office, as a stand-in: User Journey - approved

**Comment by ciprianherciu** [comment]
@RolaH1t Last task is not also completed, QG Ticket can be closed

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland
