### ISSUE TITLE
Introduce tax jurisdiction code into data models and APIs

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#606]
## Description

Tax jurisdiction code attribute missing in the data model.

Tax jurisdiction codes are used to identify the specific jurisdiction(s) that a company belong to, particularly in bureaucratic processes such as tax returns and IRS forms. 

The tax jurisdiction code defines the tax authority to which taxes must be paid. The determining location is the location to which the asset was delivered.

A tax jurisdiction is a legally defined area that writes its own tax policies for businesses that operate within its borders. Basically, it’s a geographic area that has its own rules.

Tax jurisdictions can set their own rules about:
•	Registration thresholds
•	Which products are taxable, tax-free, or zero-rated supply 
•	Tax rates
•	Filing frequency and deadlines

A tax jurisdiction code is composed of smaller codes that represent the country, province, state, county, city, or district. In this way, the code captures how much tax from a single transaction should go to each tax authority.

In the US, codes are usually built in this way:
•	3 digits representing a state
•	2 digits representing a county
•	4 digits representing a city
•	3 digits representing a district

Put together, the tax jurisdiction code will be a string of numbers: State + county + city + district. The exact format and meaning of the digits can vary depending on the tax authority and the jurisdiction's structure.

Tax jurisdiction code is a legal requirement for USA, Canada and Brazil.

Pool / Gate data model and APIs MUST be adapted to include a tax jurisdiction code attribute in the physical postal address sub-object of a business partner (incl. legal entity, site and address). Pool and Gate API standardization documents must be adapted accordingly. 

Note that it might be required to introduce a code list for the tax jurisdiction code at a later point in time to encode, which tax jurisdictions are valid in which countries, regions, districts, cities or for which postal codes.

## Impact
- BPDM Gate and Pool API

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
Attention @rybtim  : **Upcoming PI Planning Preparation**

As we gear up for the forthcoming PI Planning session, it is crucial that all features under consideration align with our established Feature Quality Standards and Definition of Done (DoD) guidelines. To ensure your feature is thoroughly prepared and stands a strong chance of being prioritized, please provide comprehensive documentation that includes the following components:

1. Feature Summary: An executive overview that encapsulates the essence and objectives of the feature.
2. Change Description:
- High-Level Overview: A succinct synopsis of the proposed changes and their overarching impact.
- Detailed Analysis: An in-depth exploration of the specific alterations, including a clear exposition of the anticipated impact on existing systems.
3. Impacted Components: A list identifying all system components that will be affected by the feature implementation, accompanied by a brief explanation of the nature of the impact.
4. Acceptance Criteria: A set of clearly defined conditions that must be met for the feature to be considered complete and acceptable.
5. Test Scenarios: A detailed outline of test cases that cover all functional paths of the feature to ensure robust validation and verification.
6. Risks/Dependencies

Please note that any feature submissions lacking these essential elements will not be eligible for consideration in the upcoming PI Planning. It is imperative that your documentation is both thorough and precise to facilitate a smooth and effective planning process.

Please let me know in case you have any questions

**Comment by Grand-Thibault** [comment]
@rybtim  please add more to the description

**Comment by stephanbcbauer** [comment]
What is the concrete impact on portal? ⇾ Please clarify with portal

**Comment by rybtim** [comment]
Scope reduced, currently no mandatory changes for Portal.

**Comment by stephanbcbauer** [comment]
@rybtim @jjeroch please have call to clarify this. thx

**Comment by stephanbcbauer** [comment]
@rybtim added you as assignee because we need a contact person for every feature.

**Comment by zygokaktus** [comment]
test
