### ISSUE TITLE
EDC - Product Hardening

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#618]
## Description

As an EDC operator,

I want to operate EDC services, that a reliable and secure

In order to do so, efforts need to be spend to fix bugs and to generally harden the implementation against runtime threads. 

- [ ] Necessary efforts are identified and documented as an issue
- [ ] The defined measures identified in the issues are executed

Initial creator: @jimmarino

## Impact

If measures are identified, that could lead to breaking changes, a deliberate decision on how to proceed is taken within the committer community, breaking changes should be prevented wherever possible.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
2 Issues here - very generic and non specific ticket. No one would know what will happen here. And the statement of the "breaking changes" is not good. We will discuss this once and provide feedback again.

**Comment by jimmarino** [comment]
@jjeroch @lgblaumeiser  There should not be breaking changes for product hardening. The intent for this is:

- Reliability improvements
- Scalability improvements
- Gracefully handling and recovering from error conditions

**Comment by lgblaumeiser** [comment]
Hi @jimmarino , I absolutely agree, my thinking was in the direction, that when you improve, e.g., the handling of an error condition, the need might come up, to change the error code from lets say 500 to a 400 based on a new error condition identified that results out of wrong data sent by the client. As this changes the behavior of the endpoint, it could be classified as breaking, as a client could handle the original case and would have to react differently after the change.

I agree, that no major behavior change is expected, though.

**Comment by stephanbcbauer** [comment]
was presented in the open planning. milestone was not set yet, because it was unclear if the `open decision` label can be deleted now @jjeroch @lgblaumeiser

**Comment by stephanbcbauer** [comment]
Hello @lgblaumeiser  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11: Onoging activity, will be closed close to release with a documentation of issues closed during the development cycle.

**Comment by lgblaumeiser** [comment]
2024-06-11:

> * [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
> * [x]  Please check whether the status (backlog, work in progress ...) is set correctly
> * [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
> * [x]  Please comment on the current status of the feature:
            Ongoing activity, will be closed close to release with a documentation of issues closed during the development cycle.
> * [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
           @jimmarino : Please add links to related issues/PRs

**Comment by lgblaumeiser** [comment]
Will be closed with the Tractus-X connector release

**Comment by stephanbcbauer** [comment]
Hello @lgblaumeiser 

In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by lgblaumeiser** [comment]
Hi @paullatzelsperger @wolf4ood @ndr-brt 

can you add links to PR which you would rate under this category, so that we can close the issue, thanks!

**Comment by wolf4ood** [comment]
Adding some:

- https://github.com/eclipse-tractusx/tractusx-edc/pull/1396

**Comment by ndr-brt** [comment]
- https://github.com/eclipse-tractusx/tractusx-edc/pull/1369
- https://github.com/eclipse-tractusx/tractusx-edc/pull/1382
- https://github.com/eclipse-tractusx/tractusx-edc/pull/1329
