### ISSUE TITLE
EDC - Concept for improving secret storing for DMA users

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#627]
Upstream EDC The users of the DMA can define secrets aliases in data addresses and data destinations to later be resolved by the EDC. In EDC deployments that integrate with hashicorp vault, users of the EDC can also have access to the vault instance and store their secrets by themselves. However, this is not the case for cloud stores such as AWS Secrets Manager or Azure Vault. There could be a way to enable users to store their secrets in such vaults.

Initial creator: @rafaelmag110

**Comment by stefan-ettl** [comment]
Upstream Issue created: https://github.com/eclipse-edc/Connector/issues/4090

**Comment by rafaelmag110** [comment]
Can this be assigned to me?

**Comment by bscholtes1A** [comment]
> Can this be assigned to me?

hello @rafaelmag110 code is done and will be proposed very soon in the EDC project.

**Comment by lgblaumeiser** [comment]
PR: https://github.com/eclipse-edc/Connector/pull/4138

**Comment by lgblaumeiser** [comment]
Hi @rafaelmag110 , can you define what the term DMA user means?

**Comment by rafaelmag110** [comment]
Hi @lgblaumeiser 
By "user of the DMA" I meant someone how is granted access to the API without being the operator of an EDC connector. In such cases, where a "user" only has access to the API, he might not have the means to store a secret in the respective EDC vault.

**Comment by rafaelmag110** [comment]
Hi @stephanbcbauer and @lgblaumeiser 
This feature was added to the upstream EDC Connector with the following PR: https://github.com/eclipse-tractusx/sig-release/issues/627
It was shipped in upstream EDC v0.6.4: https://github.com/eclipse-edc/Connector/releases/tag/v0.6.4
It was shipped in TractusX EDC v0.7.2 with the upgrade of the upstream EDC Connector dependency to v0.7.0.

My initial requirement has been fulfilled.

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature
* [x]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
