### ISSUE TITLE
R24.05 - [Country Risk] Release Checks

### ISSUE THREAD

**Issue by leonschand** [eclipse-tractusx/sig-release#637]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 2.0.0 

**Country Risk**:
- Country Risk Chart: [Country Risk-4.0.2](https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/country-risk-4.0.2)
**Leading product repository:** https://github.com/eclipse-tractusx/vas-country-risk

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled see https://github.com/eclipse-tractusx/vas-country-risk/issues/176

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by guenterban** [comment]
Country Risk Threat Modelling Analysis R.24.05 approved

**Comment by FaGru3n** [comment]
Hi all, just want to inform you that i raised the TRG Check QG-Issue under https://github.com/eclipse-tractusx/vas-country-risk/issues/176.

So to be alligned could you please tell me and committer from outside the project itself, who can help us with the QG-Check itself?

--> Please assign a committer 😉 

Thanks in advance.

**Comment by evegufy** [comment]
> Hi all, just want to inform you that i raised the TRG Check QG-Issue under [eclipse-tractusx/vas-country-risk#176](https://github.com/eclipse-tractusx/vas-country-risk/issues/176).
> 
> So to be alligned could you please tell me and committer from outside the project itself, who can help us with the QG-Check itself?
> 
> --> Please assign a committer 😉
> 
> Thanks in advance.

@FaGru3n I'll conduct the review

**Comment by FaGru3n** [comment]
> 
> **Version to be included in Eclipse Tractus-X release**: _version placeholder_
> 

Hi all, which version should be checked ?

**Comment by fabiodmota** [comment]
> > **Version to be included in Eclipse Tractus-X release**: _version placeholder_
> 
> Hi all, which version should be checked ?

apiVersion: v2
name: country-risk
type: application
version: 4.0.0
appVersion: "2.0.0-alpha"

the version is this at the moment , if issues or fixes are needed we will increment according

**Comment by cbrugg** [comment]
INT / E2E Tests performed successfully. Data Sov Tests outstanding. Thank You!

**Comment by alexKeppler** [comment]
User Journey approved by BO. Thanks for your efforts!

**Comment by evegufy** [comment]
QGChecks done, a couple of issues were created but nothing major blocking the release.

**Comment by RolaH1t** [comment]
QG review 14-May
TRG optimizations ongoing
Only Data Sov test executions outstandig
no follow-up call required

**Comment by FaGru3n** [comment]
checked the TRG checkbox

**Comment by KMA-2019** [comment]
@vialkoje , @cbrugg , @leonschand as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.**
No blocking issues for current Rel 24.05 but main items to be considered for next release(s): 

- Note: **additional tests (from customer perspective) only partially possible**
- currently implemented scenario is **consumption of pool data only** , needs **re-assessment** once download/export functionality shall be offered
- UI shows catalog items available for negotiation: **View permissions restricted to CompAdmin Role** but only generic description, i.e. **missing transparency on underlying (usage) policies prior to triggering negotiation** -> todo: enhance Catalog Item View with Usage Policies
- **ContractReference Constraint**: technically could be supported but not used (see point that one data exchange partner is always the OpCo for currently implemented scenario)
- **no validation of the Schema** "profile": "cx-policy:profile2405"

**Comment by fabiodmota** [comment]
> @vialkoje , @cbrugg , @leonschand as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.** No blocking issues for current Rel 24.05 but main items to be considered for next release(s):
> 
> * Note: **additional tests (from customer perspective) only partially possible**
> * currently implemented scenario is **consumption of pool data only** , needs **re-assessment** once download/export functionality shall be offered
> * UI shows catalog items available for negotiation: **View permissions restricted to CompAdmin Role** but only generic description, i.e. **missing transparency on underlying (usage) policies prior to triggering negotiation** -> todo: enhance Catalog Item View with Usage Policies
> * **ContractReference Constraint**: technically could be supported but not used (see point that one data exchange partner is always the OpCo for currently implemented scenario)
> * **no validation of the Schema** "profile": "cx-policy:profile2405"

Thanks for the approval @KMA-2019 , as discussed on call i created already issue for country risk https://github.com/eclipse-tractusx/vas-country-risk/issues/190 that needs to be attended for the next release

**Comment by cbrugg** [comment]
Data Sov Tests performed.
Testmanagement Approval is hereby given. Thank you for your efforts!

**Comment by RolaH1t** [comment]
Hi @fabiodmota may I ask you to add the version info on the very top of this issue
and to also check the boxes for data sov and testing (based on the given comments).
I will then fully approve the QG in consequence,
Roland

**Comment by fabiodmota** [comment]
> Hi @fabiodmota may I ask you to add the version info on the very top of this issue and to also check the boxes for data sov and testing (based on the given comments). I will then fully approve the QG in consequence, Roland

Hi @RolaH1t , I just updated the correct versions with everything that was done and corrected for this QG, including validated TRGs! Now we are good to finalize.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland
