### ISSUE TITLE
[Knowledge Agents] Release Checks

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#641]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

**Version to be included in Eclipse Tractus-X release**: 1.12.19

**Leading product repository:** *[repository link](https://github.com/eclipse-tractusx/knowledge-agents)*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/knowledge-agents/issues/122

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by TomBuchertTSystems** [comment]
@bosserf : Can you please conform user journey?

**Comment by TomBuchertTSystems** [comment]
Requested appointment for data sovereignty review by @vialkoje

**Comment by TomBuchertTSystems** [comment]
Requested approval for interoperability by Per-Henrik Addicks

**Comment by bosserf** [comment]
@TomBuchertTSystems and @kelaja : I herewith give my approval/confirmation regarding the User Journey

**Comment by ThomasObermeyer** [comment]
@kelaja  According to team no interoperability relevant changes for this release, therefore expert approval granted for interoperability

**Comment by vialkoje** [comment]
Data sovereignty:
The business applications have to establish the control plane before accessing the knowledge agents as the dataplane implementation. therefore all topics regarding usage of BPN-L, policy definitions, company-rules and so forth have to be done by the application itself before accessing the knowledge agent API. All relevant QG-criteria are therefore not relevant for this implementation as it only acts as a different way of organizing and transferring the data - that uses an access token provided by the DSP-Sovereign data exchange protocol. Expert approval granted

**Comment by almadigabor** [comment]
Hey, I've created the [TRG check issue](https://github.com/eclipse-tractusx/knowledge-agents/issues/122). I will need a volunteer committer who does the checks alongside with me. Can you please find me someone? Thanks!

**Comment by cbrugg** [comment]
INT Tests done. E2E Tests planned to finish today. Data Sov not relevant. Lets discuss in the QG.

**Comment by RolaH1t** [comment]
QG review 17-May
Thread modelling in progress / architecture improved, no major changes
TRG checks completely open, based on final version (PR in progress)
Test completion expected 17-May
final version => 1.12.19
no follow-up mtg required

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - approved - all previous finding addressed - no major changes to the architecture / new components added.

**Comment by cbrugg** [comment]
E2E Tests also successfully done.
Testmanagement approval is hereby given! Thank you for your efforts!

**Comment by RolaH1t** [comment]
Hi @almadigabor we trust you are processing the TRG checks on this product.
As this is the only topic missing, I can approved the QG fully once completed.
Thx Roland

**Comment by almadigabor** [comment]
Hey @RolaH1t, as we were waiting for the Eclipse IP check issues to be processed this got a bit delayed. Now we managed to merge the last PRs, create the releases and now I can proceed with the checks.

**Comment by almadigabor** [comment]
I'm done with the first round of checks. There is one issues open regarding critical security findings in the knowledge-agents repository by CodeQL. https://github.com/eclipse-tractusx/knowledge-agents/issues/128

Once they are addressed, I can approve and close the TRG checks issue.

**Comment by almadigabor** [comment]
As the security findings were false positives as they've already been fixed, the last check is also marked. I approve the QG with the following versions:

App version: 1.12.19
Chart version: 1.12.19

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by FaGru3n** [comment]
Hi @RolaH1t and @kelaja guess could be closed, many thanks for your work.

**Comment by stephanbcbauer** [comment]
Hello @TomBuchertTSystems  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by bosserf** [comment]
Hi @TomBuchertTSystems, kannst Du das hier bitte noch kommentieren? Danke!
Rolf

**Comment by mabige** [comment]
@bosserf  @TomBuchertTSystems just close this QG issue.
The QG was approved by Roland w/o pending issues. 

The checklist from @stephanbcbauer is essential for incomplete features, but does not apply in case of approved QGs. 
Seems to be a mistake.

**Comment by stephanbcbauer** [comment]
Since this is an old issue and was already approved -> Status Done
