### ISSUE TITLE
[Agent KIT] Release Checks

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#642]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** *1.12.19*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- [PR number](pr-url)

# General

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [ ] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by HFocken** [comment]
Please confirm that this is the valid PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/872 and link it above (current link leads to void).

**Comment by danielmiehle** [comment]
Merged!
