### ISSUE TITLE
Data feedback concept, change-log, types of notifications etc. implementation

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#643]
## General:
In principle, it is expected that feedback regarding process progress and results data will be provided along the GR process steps.
This feedback should be made available to the CX member both for direct technical integrations and in parallel via an UI.
This option  of having an UI is particularly important for SMEs that do not integrate backend systems for master data management and are reliant on a consolidated, user-friendly presentation of input, output, status and metadata.
 
The business requirements   have been collected and aggregated in a data feedback concept and were already incorporated in the E2E Standard CX-0076 in a generic way.
 
In the course of the concept creation the business requirements have been challenged  against current status regarding  both representation in the data model and technical implemenantion of the backend (reference implementation) to identify ond document gaps.
 
Cofinity-X as the BPDM core service provider is working on improving the current data feedback options and especially on the UI, based on the requirements of standard CX-0076.
For this we anticipate required enhancements of the current technical FOSS components like GATE or sharing state controller.
As the details  for this are not yet available this feature is meant for potential activities in this context, depending on the Cofinity-X development progress.
Prerequisite for these activities is that the CX Portal is not affected.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by rybtim** [comment]
[PI13 feature scope - Data feedback concept change-log types of notifications-v10-20240409_160059.pdf](https://github.com/eclipse-tractusx/sig-release/files/14919727/PI13.feature.scope.-.Data.feedback.concept.change-log.types.of.notifications-v10-20240409_160059.pdf)

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ please make clear it is not an UI feature. Please also add a mark that the backend and if the portal can be still work

**Comment by stephanbcbauer** [comment]
As discussed in open planning, this feature will stay in Inbox until there is a handover to the related expert group. Please reach out, when the handover is done and the expert group is ready to work on the feature. Please also keep my  [comment](https://github.com/eclipse-tractusx/sig-release/issues/643#issuecomment-2046862930) in mind.

Don't just start with the feature. Clarification is still needed. Same for:

- #600 
- #599  
- #605  

Thx

**Comment by stephanbcbauer** [comment]
@rybtim added you as assignee because we need a contact person for every feature.

**Comment by stephanbcbauer** [comment]
Didn't think about it before, but since the feature is still in Inbox, the open decision label is not needed. Opinions?

**Comment by stephanbcbauer** [comment]
Discussed with @zygokaktus shouldnt be on Tractus-X

**Comment by stephanbcbauer** [comment]
@zygokaktus Can you please create an issue in your BPDM ExpertGoup Repository? and Copy the information into this issue? After this, we can delete this issue here in Tractus-X. Fine for you?

**Comment by zygokaktus** [comment]
As mentioned in the feature description:
It is just a placeholder for anticipated adjustments of the concept, due to new functionality being developed by the provider, based on separate github issues.

Currently known candidates for such changes are:
https://github.com/eclipse-tractusx/sig-release/issues/727
https://github.com/eclipse-tractusx/sig-release/issues/738
https://github.com/eclipse-tractusx/sig-release/issues/726

As the current status of these named issues is not transparent we will need feedback from the issue owner to evaluate also the status for the concept activities itself

**Comment by maximilianong** [comment]
Will close it here and moved it to the Catena-X e.V. board (#43)
