### ISSUE TITLE
TEST [FOSS NAME] Release Security 23.12

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#65]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  
    - Analysis completed (operations excluded):
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - No high threats acceptable

  _Artifact Repository:_
  
    - Risk Register (decentral on Catena-X confluence)

  _Contact:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**

  - Code must be scanned weekly with Veracode tool
  - Medium risks require mitigation statement
  - High and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Contact:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)

  - All findings assessed
  - High & Very high findings mitigated
  - Evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Contact:_
  
    - Security Team: SEC3 SEC4

- [ ] **Secret scanning**

  - Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Contact:_
  
     - Security Team: SEC1

- [ ] **Software Composition Analysis (SCA)**
  - Dependencies must be scanned with Veracode tool with regards to vulnerability
  - High and above not accepted
  - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Contact:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**

    - All containers in GitHub Packages must be scanned
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Contact:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
    - IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Contact:_
  
    - Security Team: SEC2

**Comment by RolaH1t** [comment]
[Test Evidence 1.xlsx](https://github.com/eclipse-tractusx/sig-release/files/12817678/Test.Evidence.1.xlsx)

**Comment by RolaH1t** [comment]
![Test Evidence 2](https://github.com/eclipse-tractusx/sig-release/assets/135834369/e51125ec-182f-46f7-98ea-0a16b7e2137d)
Evidence for Threat modeling attached
