### ISSUE TITLE
Behaviour Twin KIT (new) Release Checks

### ISSUE THREAD

**Issue by afederl** [eclipse-tractusx/sig-release#653]
## Release Info

The new Behaviour Twin KIT should be included in the Eclipse Tractus-X release.
This KIT provides guidance for Behaviour Twin use-cases like "Remaining useful Life" and "Health Indicator".
It integrates the following two KITs which must hereby be marked as deprecated and removed from further releases:

- Remaining useful Life KIT (RuL)
- Health Indicator KIT (HI)

*Version to be included in Eclipse Tractus-X release:** *24.05*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

# General

## Must be provided:

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

## Must be provided:

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **Notice** CC BY 4.0 license statement available

## Not relevant:

- **Semantic Models** linked and described
- **Logic / Schema** available and described
- **White Paper** available

# Development View

## Must be provided:

- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.

## Not relevant:

- **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- **Protocols** available (e.g., dataspace protocol)
- **Sample Data** available
- **Reference Implementation** available

# Operation View

- there will be no operation view

**Comment by HFocken** [comment]
Please include relevant PR and add milestone 24.05 (we almost overlooked this one because it was not flagged for 24.05) - at the latest until the end of this week.

**Comment by danielmiehle** [comment]
Merged!
