### ISSUE TITLE
[ECO-Pass KIT] Release Checks

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/sig-release#656]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

### Added:
- Add new route to ECO-Pass APIs
- Add Electric Drive Passport model v1.0.0
- Add Chemical Material Passport model v1.0.0
- Add passport creation instruction
### Updated:
- Update example JSON Objects
- Update Figures
- Update Semantic Models sections
- Update DPP model version to v4.0.0
- Update BP model version to v5.0.0
- Update Transmission pass model to v2.0.0
- Update attribute names
### Removed:
- Remove direct links to standards
- Typos
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** 1.4.0

- [DevelopmentView](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/791)
- [AdoptionView](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/790)
- [OperationView](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/789)

# General

- [x] **CHANGELOG** available and maintained
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by HFocken** [comment]
Review of KITs currently ongoing - please provide PR and link it to ticket - deadline for our review is the end of this week.

**Comment by LuisRickert** [comment]
added links to PRs

**Comment by danielmiehle** [comment]
Thanks for the updates. Ready for merge!

**Comment by danielmiehle** [comment]
Merged!
