### ISSUE TITLE
[DCM-kit] Clarification suggestion for DCM Standard document CX-0128 v1.0.0- Material Demand API

### ISSUE THREAD

**Issue by pdequick** [eclipse-tractusx/sig-release#658]
## Description
One sentence in the standard introduces ambiguity (p22; 4.1.2.2) . "_This means that the customer
needs to collect all demands for all factories and send them aggregated as one MaterialDemand to the supplier."_
This sentence may be understood as if aggregation implies loosing detail on customer, or demand category for example. It implies a "total aggregation", it is not the spirit.

## Expected behavior
The standard should avoid any ambiguity. Specifically, there should be alignement with the sentence written in the standard "_For the combination of the attributes supplier , customer and materialNumberCustomer in the object MaterialDemand , there MUST NOT be more than one MaterialDemand object in existence"_ 
Suggestion for rephrasing: T_his means that the customer may have to perform some agregation operation to insure such unicity_.

## How to reproduce
N/A

**Comment by Frank-Globisch** [comment]
Thanks for this helpful feedback how to improve our common standard :-)

**Comment by MWADCM** [comment]
Thank you for this Feedback. I think we should discuss this DCM internally first in order to ensure that we are all on the same page. 
For this issue I´m not really sure if prerequisites for a Feature is fulfilled.
Open for Discussion at Friday DCM Expert Group Meeting.

**Comment by jschu1** [comment]
so things start going... nice. 
As a base you should consider a working mode up next. 

1. get an alignment where ideas are clustered and collected (your team backlog) 
2. get an alignment on possible clusters 
3. check priorities (no standard changes except for emergency-actions in the next release(s)) 
4. allign a cadence (eg. 2 or 4 weeks) 
5. create a backlog to be worked on in the next cadence / 4 (or 2?) weeks 
6. decide which sub-group works on which topic (always with minimum 1 former consortium member) 
7. see where you can track and report your progress on that 
8. report the results after 4 (or 2?) weeks, decide what to do with it 
9. discuss improvements on the relations between you, other teams and your working mode 
10. plan the next cadence of work
11. prioritize backlog creation and work on topics on base of the priorities for the DCM EG which are : 
     

**> Save the standard – it was in heavy development and needs time to rest, stabilize 
> Extend the KIT: it’s THE entry support for the Use Case 
> Help, the use case to scale 
> Do anything possible for the expert group to enable and foster the building of data-chains via digital twins**

@LukasSchmetz @MWADCM will reference to that in the next EG meeting, I think.

**Comment by jschu1** [comment]
... + wait vor v.2.0 to be released as the foundation for your future activities - this here is v.1.0
