### ISSUE TITLE
R24.05 Digital Twin Registry (dDTR) - Release Checks

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-release#666]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
helm: digital-twin-registry-0.4.11
Image version: 0.4.3

**Leading product repository:** *https://github.com/eclipse-tractusx/sldt-digital-twin-registry*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by agg3fe** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12
See also Description for R24.03
![303013700-3fbef4db-ab8d-482e-b292-498f75b4ce91](https://github.com/eclipse-tractusx/sig-release/assets/136346074/3713aaef-dcb5-4f2b-81e9-b1bc49846e76)

**Comment by agg3fe** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made.
[HiHenrik](https://github.com/HiHenrik) : Could you please tick this checkbox?

**Comment by agg3fe** [comment]
Security Checks- Thread Modelling Analysis:
No changes since Release 23.12.
See also Security Assessment diagram:
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/main/docs#security-assessment:~:text=Security-,Assessment,-Data%20flow%20diagram

@guenterban : Could you please check and approve it?

**Comment by agg3fe** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/116

**Comment by agg3fe** [comment]
Security scanning: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/security/code-scanning
KICS: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/kics.yml
Trivy: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/actions/workflows/trivy.yml

**Comment by agg3fe** [comment]
@kelaja A self review of the TRGs have been done and everything looks good.

**Comment by thomas-henn** [comment]
Yes, I hereby confirm that the requirements for the "User Journey" of the Digital Twin Regsitry are fulfilled.

**Comment by guenterban** [comment]
Thread Modelling Analysis approved

**Comment by vialkoje** [comment]
as the digital twin registry follows the generic patterns for a data source and allows the correct configuration using the EDC the data sovereignty requirements are fulfilled and the expert approval is granted.

**Comment by agg3fe** [comment]
[cbrugg](https://github.com/cbrugg): Could you please provide the approval for E2E integration tests passed.

**Comment by cbrugg** [comment]
E2E Tests as well as INT Tests have been performed successfully. Thank You!

**Comment by RolaH1t** [comment]
**Interoperability** update:
if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any.
(note: capacity of approving experts is very limited at this advanced point of time)

**Comment by RolaH1t** [comment]
??? where can the evidence for successful TRG checks be found ? add link please!

**Comment by agg3fe** [comment]
> @thomas-henn seems your self assessment on Interoperability is the only outstanding item before we can fully approve the QG. Thx, Roland

Hi @RolaH1t Yes right. I just wanted to make sure that the interoperability also looks good. So Here by I confirm that we are aligned with interoperability and we do not have any changes in it since the past releases. Thanks, Sahil

**Comment by agg3fe** [comment]
> ??? where can the evidence for successful TRG checks be found ? add link please!

Hi @RolaH1t , Actually we did not create any ticket or separate checklist as evidence for TRG completion. We just had a look at every TRG together with Tuna and validated that every TRG is followed.
Should we create a ticket separately, the way it was done previously?

**Comment by RolaH1t** [comment]
> > ??? where can the evidence for successful TRG checks be found ? add link please!
> 
> Hi @RolaH1t , Actually we did not create any ticket or separate checklist as evidence for TRG completion. We just had a look at every TRG together with Tuna and validated that every TRG is followed. Should we create a ticket separately, the way it was done previously?

Hi @agg3fe this would be the "extra mile" but is not a hard pre-requisite. We take your confirmation with @tunacicek for granted.

**Comment by RolaH1t** [comment]
> > @thomas-henn seems your self assessment on Interoperability is the only outstanding item before we can fully approve the QG. Thx, Roland
> 
> Hi @RolaH1t Yes right. I just wanted to make sure that the interoperability also looks good. So Here by I confirm that we are aligned with interoperability and we do not have any changes in it since the past releases. Thanks, Sahil

perfect! pls check the relevant box so I can fully approve QG!

**Comment by agg3fe** [comment]
> > > @thomas-henn seems your self assessment on Interoperability is the only outstanding item before we can fully approve the QG. Thx, Roland
> > 
> > 
> > Hi @RolaH1t Yes right. I just wanted to make sure that the interoperability also looks good. So Here by I confirm that we are aligned with interoperability and we do not have any changes in it since the past releases. Thanks, Sahil
> 
> perfect! pls check the relevant box so I can fully approve QG!

Thank you. Done.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by stephanbcbauer** [comment]
Hello @agg3fe  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by agg3fe** [comment]
> Hello @agg3fe
> 
> Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?
> 
> * [ ]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
> * [ ]  Please check whether the status (backlog, work in progress ...) is set correctly
> * [ ]  Please comment on the current status of the feature
> * [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
> * [ ]  Is there a spillover planned?
> 
> If you need any clarification, please get in touch, thank you very much.
> 
> Stephan

Hi @stephanbcbauer Our features from 24.05 release are completed and all related activities are done including the updates in "Release 24.05 View" inside "Release Planning" board. Please let me know if you expect anything more from our team.

**Comment by agg3fe** [comment]
As the task is complete and approval is granted, closing the issue. please reopen or let us know incase something.
