### ISSUE TITLE
R24.05 Semantic-Hub - Release Checks

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-release#667]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
helm: semantic-hub-0.2.3
Image version: 0.3.2

**Leading product repository:** *[repository link](https://github.com/eclipse-tractusx/sldt-semantic-hub)*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by agg3fe** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made from Interoperability perspective.
[HiHenrik](https://github.com/HiHenrik) : Could you please tick this checkbox?

**Comment by agg3fe** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/128

**Comment by agg3fe** [comment]
Trivy Scan: https://github.com/eclipse-tractusx/sldt-semantic-hub/actions/workflows/trivy.yml
KICS: https://github.com/eclipse-tractusx/sldt-semantic-hub/actions/workflows/kics.yml
Code Scanning: https://github.com/eclipse-tractusx/sldt-semantic-hub/security/code-scanning

**Comment by agg3fe** [comment]
@kelaja A self review of the TRGs have been made and everything looks good.

**Comment by agg3fe** [comment]
Test Results - E2E Integration Test
Tests done: See result here:
https://jira.catena-x.net/browse/A1SLDT-1505

**Comment by guenterban** [comment]
Thread Modelling Analysis approved

**Comment by agg3fe** [comment]
[cbrugg](https://github.com/cbrugg): Could you please provide the approval for integration tests passed.

**Comment by cbrugg** [comment]
I can confirm that the INT Tests for the Semantic Hub have been performed. E2E Test was not scheduled as only API Tests are performed. Thank You.

**Comment by vialkoje** [comment]
as the semantic hub is not organizing a data transfer between partners - instead it's a common repository for models - the sovereignty principles are fulfilled appropriately. Expert approval granted

**Comment by RolaH1t** [comment]
QG review 14-May
Interoperability approval outstanding
TRG crosscheck will be performed cw20; no blockers
no follow-up mtg required

**Comment by RolaH1t** [comment]
**Interoperability** update:
if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any.
(note: capacity of approving experts is very limited at this advanced point of time)

**Comment by agg3fe** [comment]
> **Interoperability** update: if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any. (note: capacity of approving experts is very limited at this advanced point of time)

@RolaH1t There are no major changes from interoperability perspective in this release. Here's the link to previous approval https://github.com/eclipse-tractusx/sig-release/issues/505#issuecomment-1954699066

**Comment by RolaH1t** [comment]
thanks @agg3fe 
please check the relevant box on top

**Comment by RolaH1t** [comment]
??? where can the evidence for successful TRG checks be found ? add link please!

**Comment by agg3fe** [comment]
> ??? where can the evidence for successful TRG checks be found ? add link please!

A self review was done by me and Tuna.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by stephanbcbauer** [comment]
Hello @agg3fe  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by agg3fe** [comment]
As the task is complete and approval is granted, closing the issue. please reopen or let us know incase something.
