### ISSUE TITLE
R24.05 Discovery Finder - Release Checks

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-release#668]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
helm: discoveryfinder-0.2.5
Image version: 0.3.1

**Leading product repository:** *https://github.com/eclipse-tractusx/sldt-discovery-finder*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by agg3fe** [comment]
Interoperability Check:
Interoperability was ensured to Release 23.12. Since then no changes have been made from Interoperability perspective.
per-henrik.addicks@sap.com : Could you please tick this checkbox?

**Comment by agg3fe** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12.

**Comment by agg3fe** [comment]
Security Checks- Threat Modelling Analysis:
No changes since Release 23.12.
See also Security Assessment diagram:
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/docs/documentation.md#:~:text=INSTALL.md.-,Security,-Assessment

@guenterban : Could you please check and approve it?

**Comment by agg3fe** [comment]
User Journey :
@thomas-henn : Could you please confirm?
See also previous task for R23.12: https://github.com/eclipse-tractusx/sig-release/issues/120

**Comment by agg3fe** [comment]
@kelaja A self review of the TRGs have been done and everything looks good.

**Comment by agg3fe** [comment]
Trivy Scan: https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/runs/8962171090
Security scan: https://github.com/eclipse-tractusx/sldt-discovery-finder/security/code-scanning

**Comment by thomas-henn** [comment]
Yes, I hereby confirm that the requirements for the "User Journey" of the Discovery Finder are fulfilled.

**Comment by agg3fe** [comment]
[cbrugg](https://github.com/cbrugg): Could you please provide the approval for E2E integration tests passed.

**Comment by cbrugg** [comment]
I can confirm that the E2E Tests for the Discovery Finder have been performed. Thank You.

**Comment by RolaH1t** [comment]
QG review 14-May
Interoperability & DataSov approvals outstanding
TRG crosscheck will be performed cw20; no blockers
SEC (thread modelling) update expected 14-May
no follow-up mtg required

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - Based on the old assessment - all required recommendations were adressed.
Could you please confirm that no functional changes / implementation of new application component was done since the last release ?

I would also like to have a meeting so that we can update the currently existing diagrams and move the report to the App Repo - but it can wait after the QG.

Please confirm the above so that I could proceed with the approval.

**Comment by vialkoje** [comment]
the discovery finder is not secured via data sovereignty policies as the expectation is, that the data in the discovery finder is not subject to sovereignty requirements of the partners. It is secured via access tokens though. Expert Approval granted

**Comment by RolaH1t** [comment]
**Interoperability** update:
if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any.
(note: capacity of approving experts is very limited at this advanced point of time)

**Comment by agg3fe** [comment]
> **Interoperability** update: if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any. (note: capacity of approving experts is very limited at this advanced point of time)

@RolaH1t There are no major changes from the interoperability perspective in this release. Here's the link for previous approval https://github.com/eclipse-tractusx/sig-release/issues/502#issuecomment-1954697847

**Comment by RolaH1t** [comment]
thanks @agg3fe
please check the relevant box on top

**Comment by agg3fe** [comment]
> ??? where can the evidence for successful TRG checks be found ? add link please!

A self review was done by me and Tuna.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by stephanbcbauer** [comment]
Hello @agg3fe  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by agg3fe** [comment]
As the task is complete and approval is granted, closing the issue. please reopen or let us know incase something.
