### ISSUE TITLE
[Item Relationship] R24.5 Release Checks

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#670]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

# RELEASE 
- HELM Charts [7.1.3](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.1.3)
- Release [5.1.3](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.1.3) 

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 7.1.3

**Leading product repository:** https://github.com/eclipse-tractusx/item-relationship-service

# Link 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/511

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
  _Data Sov Tests in progress: Final alignment on Wednesday. https://jira.catena-x.net/browse/TEST-1915_ 

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/item-relationship-service/issues/609
- [x] UUX Checks  Compliant with the Style Guide - Not applicable. 
> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
 _https://jira.catena-x.net/browse/TEST-1887 Done_
 _https://jira.catena-x.net/browse/TEST-1892 Done_
 _https://jira.catena-x.net/browse/TEST-1888 Done_
 **Findings:** 
- no findings 
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- https://confluence.catena-x.net/display/PL/Release+Management+%3D%3E+24.05+ONE+PAGER

**Comment by mkanal** [comment]
@jjeroch  could you please confirm, that no uux review is required for the IRS. Thank you very much.

**Comment by jzbmw** [comment]
User Journey is approved from BO Perspective.

**Comment by mkanal** [comment]
Good morning @guenterban, @bs-jokri, @pablosec,

in both products (Trace-X FOSS and IRS) there are no relevant system-related changes compared to R23.12 and R24.3. For this reason, we request the release of the QGC "Threat Modeling Analysis passed" based on version R23.12 & R24.3.
If you come to a different conclusion, we will be happy to provide you with dates for the threat modeling analysis.


Sig-Release: 
Trace-X: https://github.com/eclipse-tractusx/sig-release/issues/611
IRS: https://github.com/eclipse-tractusx/sig-release/issues/670

Thank you very much 
IRS and Trace-X Team

**Comment by mkanal** [comment]
Good morning @almadigabor,

would you please again support the Team IRS regarding TRG checks for the upcoming release R24.5? 

Thank you very much

Martin

**Comment by guenterban** [comment]
Threat Modeling Analysis approved

**Comment by vialkoje** [comment]
is there a sovereignty check already conducted considering these criteria https://confluence.catena-x.net/x/NTeJBg ? I'd expect as you are using the edc - the only relevant part is the use of the correct BPN for accessing or providing data on the one side and the check for company-rules for accepting offers on the consumer side... I could nevertheless not validate that assumption

**Comment by almadigabor** [comment]
I've opened the TRG checks issue. https://github.com/eclipse-tractusx/item-relationship-service/issues/609

**Comment by mkanal** [comment]
> is there a sovereignty check already conducted considering these criteria https://confluence.catena-x.net/x/NTeJBg ? I'd expect as you are using the edc - the only relevant part is the use of the correct BPN for accessing or providing data on the one side and the check for company-rules for accepting offers on the consumer side... I could nevertheless not validate that assumption.



- [x] The provider of the connector MUST ensure the consumption of data via the DSP protocol adhering to the released version of [CX-0018 standard](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_September23/CX-0018-EclipseDataConnector_EDC_-v.2.0.1.pdf). For example, using the Eclipse Data Space Connector on [Tractus X](https://github.com/eclipse-tractusx/tractusx-edc). 
- [x] The application MUST ensure that the consumer of the data is uniquely identifiable through its associated BPN-L.
- [x] This BPN-L must be used by this application to identify the data.
- [x] The application MUST use the BPN-L of consumer of the data when consuming data via the DSP connector (e.g. EDC or managed EDC).
- [x] A user of an application MUST be enforced to act within the constraints of the framework agreement by appropriate means (legal, technical,...).
- [x] To agree to one or multiple contract offers for a queried data asset, the selection of the appropriate offer MUST be done through the consuming application, ensuring to follow company-defined rules and regulations for a user of that application.

**Comment by cbrugg** [comment]
E2E Tests were successfully performed. INT Tests need to be documented/updated. Data Sov Tests outstanding. Thank You!

**Comment by RolaH1t** [comment]
QG review 14-May:
data sov in progress; no blockers expected
TRG completion expected 14-May; successful collaboration across products & with SystemTeam
minor version expected for final release (5.1.3 & 7.1.3)

**Comment by ds-mwesener** [comment]
[Tractus-X Release Guidelines](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/item-relationship-service/issues/609

Release Checks approved ✅

**Comment by RolaH1t** [comment]
@vialkoje for IRS only data sov conclusion is outstanding. Are you fine with @mkanal `s comments and can you approve?

**Comment by vialkoje** [comment]
> which uses the SAP DIM to only consu



> @vialkoje irs is a data consumer. We consume complete data via the EDC which uses the SAP DIM to only consume data for BPNLs.

@mkanal : could you shortly explain on "how are the company rules put into the IRS by the user/admin of the IRS ? What happens if there are multiple acceptable policies ? -> what is the heuristic for selecting the right one and will the consuming party be aware about it ? thanks for clarifying !

**Comment by cbrugg** [comment]
As IRS is implicitly tested via Trace X App E2E tests passed successfully.
INT Tests were performed "Best Effort" and documented. Due to Testdata Issues some tests were instable and focus was on Unit/Component and Moduletests. 
Testmanagement approval given.

**Comment by KMA-2019** [comment]
@vialkoje , @cbrugg , @mkanal as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.**
No blocking issues for current Rel 24.05 but main items to be considered for next release(s): 

- Note: **additional tests (from customer perspective) not possible** as no frontend available yet (checks only in Insomnia in connection with EDC)
- current concept only handles **one standard policy per DC BPN**, not possible to configure separately for different partner BPNs (e.g. wrt "ContractReference" Constraint)
- **no validation of the Schema** "profile": "cx-policy:profile2405", can currently use old / outdated policy namespaces without error --> planned interface with Policy Hub, requires check of dev dependencies

**Comment by vialkoje** [comment]
> * 
> 
> * current concept only handles **one standard policy per DC BPN**, not possible to configure separately for different partner BPNs (e.g. wrt "ContractReference" Constraint)

what happens if there are multiple acceptable offers ? 
can you shortly describe how the acceptability of an offer is configured by the consuming company ?

**Comment by ds-jhartmann** [comment]
@vialkoje
> what happens if there are multiple acceptable offers ?

IRS first filters the EDC offers for the wanted asset (e.g. Digital Twin Registry or Submodel Data) if there are multiple offers for the search, IRS will start a negotiation with all of them. 
During the negotiation initiation, IRS then validates the policy of the offer with the policy configured for this BPN in IRS. If this policy matches, IRS starts the EDC negotiation, if not the negotiation will fail on IRS side. 
In case one of the offers has a matching policy, IRS will use this offer, if none of the offers have matching policies, IRS will abort the negotiation. If more than one offer has a matching policy, IRS will take the first successful response.

> can you shortly describe how the acceptability of an offer is configured by the consuming company ?

We don't configure directly which policy to use. The accepted policy for a BPN is added to the IRS policy store (either by configuration or via IRS policy store API).
The policies for the BPN of the provider are then validated with the policy of the offer. If the policy of the offer matches one of the policies configured for the BPN, IRS accepts the offer.

**Comment by RolaH1t** [comment]
ready to approve QG as soon as data sov is closed-out via @ds-jhartmann , @mkanal and @vialkoje

**Comment by vialkoje** [comment]
Configuration of acceptable policies in the IRS has to be communicated to the consuming entity - along with the fact to arbitrarily chose the first acceptable offer if multiple exist. Please point me to the documentation where this is described. Technically everything is implemented. Expert approval granted.

**Comment by ds-jhartmann** [comment]
Thank you @vialkoje, we will address this and make our documentation clearer on this matter.

@RolaH1t all QG checks are done and approved. I kindly ask for the final approval.

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by stephanbcbauer** [comment]
Hello @mkanal  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by mkanal** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Ticket will be closed.
