### ISSUE TITLE
R24.05 Portal - Release Checks 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-release#671]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 2.0.0 [RELEASED]

**Portal**:
- Portal Chart: [portal-2.0.0](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-2.0.0)
- Portal Frontend: [v2.0.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v2.0.0)
- Portal Backend: [v2.0.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v2.0.0)
- Portal Assets: [v2.0.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v2.0.0)
- Portal Frontend Registration: [v2.0.0](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v2.0.0)

IAM:
- CentralIdP: [3.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-3.0.0)
- SharedIdP: [3.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-3.0.0)

**Leading product repository**: https://github.com/eclipse-tractusx/portal

For the **QG Review the latest available Release Candidate (RC) version is to be checked**, the RC versions will be kept up to date in the following:

**Portal**:
- Portal Chart: [portal-2.0.0-RC8](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-2.0.0-RC8)
- Portal Frontend: [v2.0.0-RC7](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v2.0.0-RC7)
- Portal Backend: [v2.0.0-RC8](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v2.0.0-RC8)
- Portal Frontend Registration: [v2.0.0-RC1](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v2.0.0-RC1)
- Portal Assets: [v2.0.0-RC1](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v2.0.0-RC1)

IAM:
- CentralIdP: [3.0.0-rc.3](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-3.0.0-rc.3)
- SharedIdP: [3.0.0-rc.3](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-3.0.0-rc.3)

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/portal/issues/313

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed https://github.com/eclipse-tractusx/sig-release/issues/671#issuecomment-2122485625

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

https://github.com/eclipse-tractusx/sig-release/issues/671#issuecomment-2134476126

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by evegufy** [comment]
Reviewing committer is @fabiodmota, thanks for taking that over!
I'll inform you in a couple of weeks once you can start with the review

**Comment by ThomasObermeyer** [comment]
no changes to interoperability since last review (release 24.03)

Approved! @kelaja

**Comment by pablosec** [comment]
Security assessment performed on 2024-05-15 by @szymonkowalczykzf and me.

Threat modeling/risk assessment will be finalized next week, no major risks to be expected. Will update here, as soon as threat modeling has passed.

**Comment by fabiodmota** [comment]
QG Checks done for:

- https://github.com/eclipse-tractusx/portal-iam/issues/120
- https://github.com/eclipse-tractusx/portal-frontend/issues/779
- https://github.com/eclipse-tractusx/portal-backend/issues/733
- https://github.com/eclipse-tractusx/portal/issues/313

**Comment by fabiodmota** [comment]
QG done for the repo https://github.com/eclipse-tractusx/portal-assets
https://github.com/eclipse-tractusx/portal-assets/issues/315:
- All checks done with only the copyright header open, it's a small topic and not a blocker.

**Comment by evegufy** [comment]
> QG done for the repo https://github.com/eclipse-tractusx/portal-assets
> 
> * [R24.05 Portal Assets - Release Checks portal-assets#315](https://github.com/eclipse-tractusx/portal-assets/issues/315)
> 
> All checks done with only the copyright header open, it's a small topic and not a blocker.

same for https://github.com/eclipse-tractusx/portal-frontend-registration/issues/170

**Comment by cbrugg** [comment]
INT Tests need to be documented. E2E Tests ongoing. Testmanagement Approval cannot be given at this time.

**Comment by RolaH1t** [comment]
QG review 17-May:
data sov outstanding
TRGs at 90% / SEC outstanding => will be completed, once testing finalized and final version available
SEC incl Thread Modelling approval expected cw21
Test completion expected early cw21 / no roadblocks
User Journey approval expected after test completion by @jjeroch

**Comment by RolaH1t** [comment]
@evegufy you may already want to check the data sov box based on relevant comment

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - Approved - Assessment was reviewed and updated, all finding addressed previously.

**Comment by fabiodmota** [comment]
> QG done for the repo https://github.com/eclipse-tractusx/portal-assets
> 
> * [R24.05 Portal Assets - Release Checks portal-assets#315](https://github.com/eclipse-tractusx/portal-assets/issues/315)
> 
> All checks done with only the copyright header open, it's a small topic and not a blocker.

Checks completed for all involved repositories with the exception of security, which will be taken over by @RoKrish14 once the last release candidate was released:
- https://github.com/eclipse-tractusx/portal-frontend/issues/779
- https://github.com/eclipse-tractusx/portal-backend/issues/733
- https://github.com/eclipse-tractusx/portal/issues/313
- https://github.com/eclipse-tractusx/portal-assets/issues/315
- https://github.com/eclipse-tractusx/portal-frontend-registration/issues/170
 
For https://github.com/eclipse-tractusx/portal-iam/issues/120 all checks (also security) are completed.

**Comment by jjeroch** [comment]
Test successfully closed and user journey approved by the product owner

**Comment by evegufy** [comment]
@RolaH1t  **Finalized versions released**

**Portal**:
- Portal Chart: [portal-2.0.0](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-2.0.0)
- Portal Frontend: [v2.0.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v2.0.0)
- Portal Backend: [v2.0.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v2.0.0)
- Portal Assets: [v2.0.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v2.0.0)
- Portal Frontend Registration: [v2.0.0](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v2.0.0)

IAM:
- CentralIdP: [3.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-3.0.0)
- SharedIdP: [3.0.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-3.0.0)

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland
