### ISSUE TITLE
R24.05 Policy Hub - Release Checks

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-release#672]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: [1.0.0](https://github.com/eclipse-tractusx/policy-hub/releases/tag/policy-hub-1.0.0) [**RELEASED**]

**Leading product repository**: https://github.com/eclipse-tractusx/policy-hub

For the **QG Review the latest available Release Candidate (RC) version is to be checked**, the RC versions will be kept up to date in the following: [1.0.0-rc.1](https://github.com/eclipse-tractusx/policy-hub/releases/tag/policy-hub-1.0.0-rc.1)

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/policy-hub/issues/127

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

https://github.com/eclipse-tractusx/sig-release/issues/672#issuecomment-2127936567

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by evegufy** [comment]
Reviewing committer is @tom-rm-meyer-ISST, thanks for taking that over!
I'll inform you in a couple of weeks once you can start with the review

**Comment by ThomasObermeyer** [comment]
no changes to interoperability in comparison to last release.

QGate approved!

**Comment by pablosec** [comment]
Security Assessment done on 2024-05-15 by @szymonkowalczykzf and me.  
Threat Modeling can be marked as passed, as there are not security-relevant changes to the architecture compared to the last assessment.

**Comment by cbrugg** [comment]
INT Tests need to be documented. E2E Tests ongoing. Testmanagement Approval cannot be given at this time.

**Comment by RolaH1t** [comment]
QG review 17-May
data sov pending
only documentation of tests open / expected 17-May
TRG review completely outstanding
User journey approval expected by @jjeroch after test documentation complete

**Comment by vialkoje** [comment]
no use of EDC and policies for access of the policy elements. therefore sovereignty requirements are not applicable - if the assumption on sovereignty for this data exchange is feasible. Expert approval granted

**Comment by RolaH1t** [comment]
@evegufy data sov considered completed

**Comment by jjeroch** [comment]
User Journey Approved

**Comment by cbrugg** [comment]
INT Tests documented and E2E Tests successful.
TM approves. Thank you for your efforts!

**Comment by evegufy** [comment]
@RolaH1t all done (already 2 days ago):
**Version to be included in Eclipse Tractus-X release**: [1.0.0](https://github.com/eclipse-tractusx/policy-hub/releases/tag/policy-hub-1.0.0) [**RELEASED**]

**Comment by RolaH1t** [comment]
Congrats!
QG fully approved with all prerequisites fulfilled.
Thanks for all your efforts.
