### ISSUE TITLE
[PURIS KIT] Release Checks

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sig-release#675]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** *0.2.0*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/869

# General

- [x] **CHANGELOG** available and maintained
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented _(as part of Software Development View)_
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [x] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by danielmiehle** [comment]
Merged!
