### ISSUE TITLE
CX-ART Issue Linking TEST

### ISSUE THREAD

**Issue by mabige** [eclipse-tractusx/sig-release#68]
## Additional information 

- [ ] I'm willing to contribute to this feature

## Planned issues from the component repositories

either direkt link in Feature destribtion
- [ ] https://github.com/eclipse-tractusx/sig-release/issues/68
- [ ] Issue Link from a componet repository  https://github.com/eclipse-tractusx/sig-release/issues/68
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/416 componted info 

or metinionig function as a comment in the issue itself
https://github.com/eclipse-tractusx/sig-release/issues/68#issuecomment-1748431222

**Comment by FaGru3n** [comment]
related to https://github.com/eclipse-tractusx/sig-release/issues/68

**Comment by gabyertl** [comment]
> ## Description
> ## Impact
> ## Additional information
> * [ ]  I'm willing to contribute to this feature
> 
> ## Planned issues from the component repositories
> either direkt link in Feature destribtion
> 
> * [ ]  [Test 3 Issue Linking #68](https://github.com/eclipse-tractusx/sig-release/issues/68)
> * [ ]  Issue Link from a componet repository  [Test 3 Issue Linking #68](https://github.com/eclipse-tractusx/sig-release/issues/68)
> 
> or metinionig function as a comment in the issue itself

Could we add more links to this feature

**Comment by FaGru3n** [comment]
General Infomation 
E.g. for a feature:


- Everyone can create a feature.
- Existing features can be edited by commiter or the creator of the feature
- Feature contexts (e.g. Labels, Milstones, ...) can be changed by any contributor

Permission Rules guided by Eclipse Foundation:
- Referenced at Eclipse Foundation Handbook, Chapter [Access to GitHub Repositories](https://www.eclipse.org/projects/handbook/#resources-github-access)
 
- based on GitHub’s [Repository roles for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)

**Comment by FaGru3n** [comment]
`eclipse-tractusx/sig-release#68` will look like eclipse-tractusx/sig-release#68 

in the same repo also possible to link directly with `#68` will look like #68 

from team / component repo it could be linked with `eclipse-tractusx/sig-release#68` to reference the feature

[Docs: ](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests)
