### ISSUE TITLE
R24.05 TX-EDC - Release Checks

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#683]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled --> https://github.com/eclipse-tractusx/sig-release/issues/687

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by stefan-ettl** [comment]
User Journey approved by PO because there is no BO for the EDC.

**Comment by RolaH1t** [comment]
**Interoperability** update:
if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any.
(note: capacity of approving experts is very limited at this advanced point of time)

**Comment by stefan-ettl** [comment]
Interoperability checks performed
Data Sovereignty checks performed

Checked and aligned with T.O. and @vialkoje.

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - Passed
Assessment was reviewed, implemented changes did not bring any new threats.
All previously created recommendations were already addressed.

**Comment by cbrugg** [comment]
EDV v0.7.2 outstanding. Testmanagement Approval cannot be given at this time for this version. 
INT Test for 0.7.1 successful.

**Comment by RolaH1t** [comment]
QG review 17-May
InterOp confirmed with evidence
data sov outstanding
testing of v7.0.2 expected cw21
final version will be v0.7.2

**Comment by vialkoje** [comment]
Expert approval granted as the functional requirements of the EDC are tested for appropriateness to the sovereignty requirements but are not subject to the sovereignty QG-Checklist referenced here: https://confluence.catena-x.net/x/NTeJBg

**Comment by cbrugg** [comment]
@RolaH1t this will happen as discussed with @stefan-ettl in the PO Sync yesterday once the version actually exists and was successfully tested by PURIS as planned for today.

**Comment by RolaH1t** [comment]
based on latest info: EDC will remain v0.7.1 for this Release.
@cbrugg please  re-confirm (as above) TM approval for this version.
@stefan-ettl please check the relevant box on top so full QG approval can be given
Thx
@mabige fyi

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @lgblaumeiser  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by lgblaumeiser** [comment]
Hi @stefan-ettl , can we close this issue? By definition, as the release has been done, this should be not relevant anymore, right?

**Comment by stefan-ettl** [comment]
Yes, can be closed pls.
