### ISSUE TITLE
BDRS Release Checks 24.05

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#688]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: [0.0.4](https://github.com/eclipse-tractusx/bpn-did-resolution-service/releases/tag/0.0.4)

**Leading product repository:** https://github.com/eclipse-tractusx/bpn-did-resolution-service

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed 

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled --> https://github.com/eclipse-tractusx/sig-release/issues/689

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed (successful run is [here](https://github.com/eclipse-tractusx/bpn-did-resolution-service/actions/runs/9126628965/job/25095338626))
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by stefan-ettl** [comment]
User Journey approved by PO because there is no BO for the BDRS.

**Comment by RolaH1t** [comment]
**Interoperability** update:
if your QG approval was not obtained by now via the communicated channels, please **perform a self-assessment** and document your results here. reference approval(s) of previous Release(s) - if applicable - and point out significant modifications relevant for InterOp - if any.
(note: capacity of approving experts is very limited at this advanced point of time)

**Comment by stefan-ettl** [comment]
Interoperability checks performed
Data Sovereignty checks performed

Checked and aligned with T.O. and @vialkoje.

**Comment by szymonkowalczykzf** [comment]
Threat Modeling - Passed
No Critical or High findings were identified during the assessment performed on 16.05.2024
Documentation of the security assessment will be uploaded to the application repository within next few days.

**Comment by cbrugg** [comment]
INT Tests need to be documented. To my knowledge BDRS is already actively used during E2E Tests (similar to DIM).

**Comment by RolaH1t** [comment]
QG review 17-May
data sov outstanding @vialkoje 
no follow up mtg required

**Comment by vialkoje** [comment]
no policies '/ contracts used for this service - therefore no dedicated data sovereignty check as mentioned here required: https://confluence.catena-x.net/x/NTeJBg the functional requirements of the service adequately reflect the requirements for sovereignty. Expert approval granted

**Comment by RolaH1t** [comment]
@stefan-ettl once you update the data sov checkbox on top I can fully approve QG here,
Roland

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @paullatzelsperger , @lgblaumeiser  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan
