### ISSUE TITLE
[Business Partner KIT] Release Checks

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/sig-release#690]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

### Added

- ./.

### Changed

- Changed banner image file location and converted .png image to .svg
- Updated changes in Gate, Pool and Orchestrator Open API documents.
- Updated development view

### Removed

- remove duplicate content from Business Partner KIT

**Version to be included in Eclipse Tractus-X release:24.05** *v5.0.0*

- [886](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/886)

# General

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [ ] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by danielmiehle** [comment]
Merged!
