### ISSUE TITLE
BPN issuing optimization 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-release#699]
## Description
The general BPN (business partner number) is structured that way:

<img width="1671" alt="Bildschirmfoto 2024-06-06 um 13 42 07" src="https://github.com/eclipse-tractusx/sig-release/assets/83761111/04989f80-b21f-4c13-89fc-73c36d1aecac">

E.G.: BPNL 1234 5678 90ZZ

This is defined in the standard: CX - 0010 Business Partner Number

But its not defined how the checksum is / should be generated.

The current reference implementation generates the checksum solely based on the 'identifier', in accordance with ISO 7064 MOD 1271-36. This feature should be enhanced to include both the prefix and the classification, in addition to the identifier, for checksum generation.

**Acceptance criteria:**

- [x] BPN checksum will be generated by prefix+classification+identifier

**Dependencies:**
Just inside the BPDM product 

## Additional information 

- [x] I'm willing to contribute to this feature with development resources (@nicoprow / @SujitMBRDI / +more)

**Comment by maximilianong** [comment]
> This would invalidate any BPNs issued by the operating company and is thus a breaking change. Have we talked to the operating company about that?

Yes they are aware and support this feature.

Would be nice if we could adjust / extend the standard with this guidance. I will bring this to the expert group.

**Comment by maximilianong** [comment]
To adapt the standard I will create a change request in Houston and I will create a issue in the GitHub of the Catena-X association to track it.

@Sebastian-Wurm will contribute to do the changes in the standard.

**Comment by stephanbcbauer** [comment]
Hello @nicoprow, @maximilianong,
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Inbox`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by maximilianong** [comment]
Hi @stephanbcbauer this is one of those features we discussed in our last committee meeting. We did not present this in the open planning meeting for 24.08 but we saw this during the PI as a relevant feature, developed it and merged it. So it will be in the release 24.08.

**Comment by maximilianong** [comment]
This is part of the 24.08 release.
