### ISSUE TITLE
CX-0128 DCM: Provide automated tests (Test Suite)

### ISSUE THREAD

**Issue by tobzahn** [eclipse-tractusx/sig-release#702]
## Description
In order to improve standard compliance and interoperability of solutions, automated tests for the Catena-X DCM standard (CX-0128) should be provided. There should be a test suite, that could be used by software vendors, participating companies and developers to test their API implementations against the standard. This would ensure compliance with the standard and avoid mistakes during the implementation. Furthermore, this would ensure compatibility across vendors.

## Impact
Only CX-0128 is affected.
This topic should be discussed in the DCM working group.

See also #701

**Comment by LukasSchmetz** [comment]
Will be done via feature #773 for DCM KIT

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
