### ISSUE TITLE
EDC - Stub for Management API

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#716]
## Description

In order to provide means for app developer who provide apps that depend on the EDC management api to support an app development that can react fast on changes and additions in the management API, a test stub is needed that allows to define proper test cases that allow to ensure keeping the contract between the app and the EDC. App developers need a continuous feedback whether their usage of the management api is correct and changes are detected early, so that they can adapt in the api.

The feature is besides the concrete stub that can be used by app developers also a concept on how the stub is provided, how it is developed and provided to users, and an agreement, that the stub is kept in synch with the current development of the management api.  

## Impact

Without this feature, the efforts to execute quality assurance and to stay in synch with the latest EDC development are quite high. The issue is, that with the high frequency in which the EDC is developing, dependent components need to be enabled to stay in synch easily. If this is not the case, we run into trouble, that updating the EDC becomes a nightmare in the Catena-X data space.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jimmarino** [comment]
We have a prototype of this.

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is available

**Comment by lgblaumeiser** [comment]
De-Prioritized for 24/12

**Comment by lgblaumeiser** [comment]
Hi @rafaelmag110, some weeks ago, you mentioned, that there waas some progress on this item. What do you think, is this ready to be closed for now?

**Comment by rafaelmag110** [comment]
Hi @lgblaumeiser 
Indeed a stub for the EDC management API was implemented and is being delivered as of now as a docker image under [tractusx/mock-connector](https://hub.docker.com/r/tractusx/mock-connector).
One supporting piece of documentation was also delivered [here](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/development/mock-edc.md) which is a starting point for other projects to adopt contract based testing.

As written in final part of the mentioned documentation, there are some improvements to be made to make the adoption easier.

As this issue doesn't have any concrete acceptance criteria, it is difficult to confirm if all intended work was concluded. I say we close this and address the improvement points on a different issue.

**Comment by lgblaumeiser** [comment]
Thanks @rafaelmag110, perhaps something to publish on the blog, I'll think about it, but for now, I close this as your last comment basically also gives all the information for developers to start with.
