### ISSUE TITLE
EDC - Whitepaper on BPN DID usage within the Catena-X data space

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#717]
## Description

Currently, the Catena-X data space requires a centrally managed BDRS service, that is required to translate between a BPN and the corresponding DID during data exchange. Due to this dependency on a central service during data exchange, this is a non-optimal solution concerning data sovereignty. Therefore, the goal of this feature is to discuss potential alternatives, that would enable data exchange without the need of a central mapping table service.

As this would question potentially fundamental decisions within the Catena-X data space, a careful comparison of options, their advantages and disadvantages and their consequence on the data sovereignty as well as the concrete impact on the operation of the participation in the data space has to be provided to allow a discussion based on facts. In addition, an implementation plan, that outlines feature evolvement over time (e.g., several releases) describes a path with minimal impact during the transition.

## Impact

As this is a whitepaper, it has no immediate impact. 

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by lgblaumeiser** [comment]
Hi @jimmarino , does this reflect what you had in mind when we discussed this morning?

**Comment by jimmarino** [comment]
@lgblaumeiser Yes, it's good enough to start with.

**Comment by arnoweiss** [comment]
Willing to contribute

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is available

**Comment by matbmoser** [comment]
Love this feature! I would love to support there!

**Comment by lgblaumeiser** [comment]
Questions for investigation:

1. App uses - which apps use BPNS? How is the Discovery service used?
2. Operational uses, e.g. onboarding?
3. How do companies use BPNS?

**Comment by arnoweiss** [comment]
Are you referring to the BPNS (Business Partner Number Site) or BPNs (Business Partner Numbers) in general?

**Comment by jimmarino** [comment]
> Are you referring to the BPNS (Business Partner Number Site) or BPNs (Business Partner Numbers) in general?

BPNs (numbers)

**Comment by Sebastian-Wurm** [comment]
I volunteer as reviewer of the whitepaper.

**Comment by lgblaumeiser** [comment]
Actually, the whitepaper is worked on in the Catena-X orga for now, as it is targeted to Catena-X stakeholder. We keep the issue in the open space for now, as the paper is intended to be a public thing, but it is more the conclusion drawn of the whitepaper that will impact the public space in Eclipse Tractus-X.

**Comment by lgblaumeiser** [comment]
Whitepaper has been finalized. It is available in the Catena-X repository. It will be made available in the Connectivity KIT soon. But this is another issue to be created.

**Comment by dom-reuter** [comment]
@lgblaumeiser Would you be so kind as to post a link to the document here?

**Comment by lgblaumeiser** [comment]
Non-public link (only available for Catena-X member company employees): https://github.com/catenax-eV/cx-ex-dataspace-connectivity/blob/main/docs/bpn-did-resolution/moving-to-DID-identifiers.md
