### ISSUE TITLE
IC | Enhancements of KITs due to new / enhanced standards

### ISSUE THREAD

**Issue by eckardg** [eclipse-tractusx/sig-release#725]
## Description

We plan to enhance some of our existing standards. This will also result in corresponding adaptions of the Industry Core KIT. Currently it is not yet clear which standard changes will make it into rel. 24.12.
In addition, it might be necessary to adapt the KIT to the new framework policy.

Please find below a list of the topics we are working on. Some of them might find their way into a standard for 24.12.

This issue represents the updated Industry Core KIT to version 3.0.0 for release 24.12.

The following changes are currently planned:

- Enable Data Access on Demand
- Historization of BOMs
- Standardize Notifications
- Guideline on using Digital Twins in use cases
- Versioning / Changes of Digital Twins and Aspect Models
- Selective BOM access to specific partners
- Propagation of information along the value chain
- Generalization of Data Access on Demand

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is needed

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
