### ISSUE TITLE
[Portal]: EDC Config Details are not shared with the managed-EDC-Provider

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#731]
## Description
The EDC config details are not shared with the manged-EDC-provider. 
Till that feature is not working, a managed-EDC-provider can only receive those details via the customer directly and the Managed Service Orchestrator can not process the request automatically. 

Is it possible to have multiple users with the same roles?  
For example, two technical users which have for example "Identity Wallet Management" or "Dataspace Discovery"?

If this is possible, we will need a better understanding on how to recognize which technical users will be configured for which service.

## Expected behavior
The EDC config details are shared with the manged-EDC-provider and MSO can use the EDC config details so it can be processed automatically.

## How to reproduce
- Reset and resubscribe to verify the technical user creation and sharing the edc config details
- New subscription of a new company which to test if the data is shared

**Comment by ciprianherciu** [comment]
@evegufy @jjeroch This issue is a blocker for MSO.
Without the technical users credentials, MSO will not work resulting in Automatic Subscription will not work.

**Comment by ciprianherciu** [comment]
@MaximilianHauer it worked, thank You!
We would also like to know :

Is it possible to have multiple users with the same roles?
For example, two technical users which have for example "Identity Wallet Management" or "Dataspace Discovery"?

If this is possible, we will need a better understanding on how to recognise which technical users will be configured for which service.

**Comment by MaximilianHauer** [comment]
@ciprianherciu  can you exactly describe what your goal is ? this would help to understand your issue/approach.

**Comment by stephanbcbauer** [comment]
@ciprianherciu This was a feature for milestone 24.08. Is this an ongoing topic? Is it closed? Moved?

**Comment by MaximilianHauer** [comment]
closing it due to lack of feedback and the initial fault was solved.
