### ISSUE TITLE
Pool: Create site endpoint with legal entity reference

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-release#739]
## Description

This feature involves the creation of a new endpoint within the siteController to handle the creation of both LegalEntity and Site entities using the same address when the LegalAndSiteMainAddress is specified as the address type. Additionally, the BPNA (Business Partner Number Assignment) will be linked to both the LegalEntity and the Site entity.

Risk:
No risk - This a technical endpoint that will help the operator.
No effect on sharing members.

**Currently:
At the moment you cannot create a site which has the legalmainadress as the sitemainadress.**

Objective:
To streamline the process of creating and linking LegalEntity and Site entities with the same address and associating the BPNA with both entities through a new endpoint in the siteController.

**Acceptance Criteria:**

- Endpoint is created
- When LegalAndSiteMainAddress is specified as the address type, the endpoint creates both a LegalEntity and a Site entity with the provided address.
- The BPNA is linked to the newly created LegalEntity.
- The BPNA is also linked to the newly created Site entity.
- The endpoint returns a success response with the details of the created LegalEntity and Site entity.
- In case of failure, an appropriate error message is returned.

## Additional information 

- [x] I'm willing to contribute to this feature
Contribution will be done by @dilipdhankecha2530 
Committers to support this are @SujitMBRDI / @nicoprow

**Comment by stephanbcbauer** [comment]
After a brief consultation with Sebastian, the feature is set to 'backlog' status. Associated committer is also fine with it.

**Comment by maximilianong** [comment]
Done & merged (details: https://github.com/eclipse-tractusx/bpdm/pull/981).
Thanks to @dilipdhankecha2530 and @nicoprow !
