### ISSUE TITLE
Eclipse Data Space Connector (EDC) Release 23.12 Documentation

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#74]
# Release Documentation 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code** https://github.com/eclipse-tractusx/tractusx-edc/issues/885

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [x] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [x] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by stefan-ettl** [comment]
No new EDC package for 23.12 - therefore no change from 23.09 to 23.12.

**Comment by vialkoje** [comment]
Documentation not changed - expert approval granted based on the existing assessment on 23.09

**Comment by kelaja** [comment]
@stefan-ettl is there an UX?
@COROANN kindly add the system Team QG-Ticket

**Comment by stefan-ettl** [comment]
@kelaja this part is n/a for EDC as we do not have a Frontend in TX-EDC.

**Comment by kelaja** [comment]
@COROANN kindly add the system Team QG-Ticket

**Comment by SebastianBezold** [comment]
> No new EDC package for 23.12 - therefore no change from 23.09 to 23.12.

Hi @stefan-ettl, so this means, the release `0.5.1` will be included in Tractus-X `23.12`?
Should I anyways have a look at the most recent `0.5.3` release regarding release guidelines?

**Comment by stefan-ettl** [comment]
Hi @SebastianBezold yes it would be the Patch Version 0.5.3. We only fixed some bugs in comparison to 0.5.1.

**Comment by SebastianBezold** [comment]
Ok cool. I'll quickly go through and check if there have been new things, that still need to be adapted. Saw an outdated `SECURITY.md` already 😁. Maybe i'll just provide a PR for it.

Check overview: eclipse-tractusx/tractusx-edc#885

**Comment by SebastianBezold** [comment]
Hi @stefan-ettl,

I am already done, but found some issues, that should be easy to solve though. 
They are all linked in the issue mentioned earlier. Could you have a look with your team please?

**Comment by RolaH1t** [comment]
Deadline Noon today! Go Go Go and move the issue to next status, when done!

**Comment by stefan-ettl** [comment]
Hi @SebastianBezold 
all mentioned issues have been resolved in https://github.com/eclipse-tractusx/tractusx-edc/issues/885

**Comment by mabige** [comment]
@kelaja 


https://github.com/eclipse-tractusx/tractusx-edc/issues/885 was closed. 

Done

**Comment by FaGru3n** [comment]
Hi @stefan-ettl the checkbox here "source-code" can be closed by issue creator @kelaja 

the qg-checklist https://github.com/eclipse-tractusx/tractusx-edc/issues/885 from @SebastianBezold i have closed, after on your reply.

FYI as contributor to Eclipse Tractus-X you also have the following "Triage" permissions within the GitHub Organisation
https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization
