### ISSUE TITLE
[R24.08] [Item Relationship Service] Release Checks

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#740]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Link 
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/719
- relates to eclipse-tractusx/sig-release/issues/821
- relates to eclipse-tractusx/sig-release/issues/740
- relates to eclipse-tractusx/sig-release/issues/741

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: [5.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.4.0)

**HELM Charts**: [HELM 7.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.4.0)

**Leading product repository:** https://github.com/eclipse-tractusx/item-relationship-service/

# Compliance Verifications

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled >> Checklist https://github.com/eclipse-tractusx/item-relationship-service/issues/817

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks
_There are no Consortium checks for Rel 24.08 and following. Everything is described in the TRG. (Security is TRG 08) 
It is the task of the committers to check this if necessary_

- [x]  ~**Threat Modeling Analysis** passed~
  - [x] trg-8-01 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01
  - [x] trg-8-02 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02
  - [x] trg-8-03 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03
  - [x] trg-8-04 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by mkanal** [comment]
Good morning @vialkoje,

Data Sovereignty Q-Gate Criteria for Release 24.08

IRS has the role Data Consumer only. 
Kindly ask for QG approval for Data Sovereignty .

- [x] The provider of the connector MUST ensure the consumption of data via the DSP protocol adhering to the released version of CX-0018 standard. For example, using the Eclipse Data Space Connector on Tractus-X. 
	- [x] The application MUST ensure that the consumer of the data is uniquely identifiable through its associated BPN-L.
	- [x] This BPN-L must be used by this application to identify the data.
- [x] The application MUST use the BPN-L of consumer of the data when consuming data via the DSP connector (e.g. EDC or managed EDC).
- [x] A user of an application MUST be enforced to act within the constraints of the framework agreement by appropriate means (legal, technical,...).
- [x] To agree to one or multiple contract offers for a queried data asset, the selection of the appropriate offer MUST be done through the consuming application, ensuring to follow company-defined rules and regulations for a user of that application.

**Comment by mkanal** [comment]
@ther3sa 
[IRS] Item Relationship Service Release Checks R24.8

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description.

**Comment by jzbmw** [comment]
User Journey herby aproved

**Comment by ther3sa** [comment]
QG Review 23-July

- Missing version Link: Version to be included in Eclipse Tractus-X release: version placeholder
- TRGs outstanding
- User Journey approved by @jzbmw
- E2E test is pending

**Comment by mkanal** [comment]
Status Update: 
- [x] Changed: Add release version 
- [x] TRGs Checks done https://github.com/eclipse-tractusx/item-relationship-service/issues/817
- [x] User Journey approved by @jzbmw
- [ ] E2E test is pending

fyi @ther3sa

**Comment by ds-kgassner** [comment]
Hi @ther3sa ,

all release checks have been successfully completed, including the E2E tests. The test execution details can be found here: https://catena-x.atlassian.net/browse/CXTM-926

![grafik](https://github.com/user-attachments/assets/a46826e2-3897-45e8-b8c2-c2913e50e123)

We kindly request approval for the 24.8 release for the Item Relationship Service.

Kind regards,
the IRS team

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts! :)
