### ISSUE TITLE
[R24.08] [Trace-X] Release Checks

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#741]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Link 
- https://github.com/eclipse-tractusx/traceability-foss/issues/1070
- relates to https://github.com/eclipse-tractusx/item-relationship-service/issues/719
- relates https://github.com/eclipse-tractusx/sig-release/issues/821
- relateshttps://github.com/eclipse-tractusx/sig-release/issues/740
- relateshttps://github.com/eclipse-tractusx/sig-release/issues/741

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**:  [13.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/13.0.1)

**HELM Charts** [helm-charts-1.3.43](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/helm-charts-1.3.43)

**Leading product repository:** [traceability-foss](https://github.com/eclipse-tractusx/traceability-foss/)

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled >> Checklist https://github.com/eclipse-tractusx/traceability-foss/issues/1222

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks
_There are no Consortium checks for Rel 24.08 and following. Everything is described in the TRG. (Security is TRG 08) 
It is the task of the committers to check this if necessary_

- [x]  ~**Threat Modeling Analysis** passed~
  - [x] trg-8-01 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01
  - [x] trg-8-02 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02
  - [x] trg-8-03 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03
  - [x] trg-8-04 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by mkanal** [comment]
Good morning @vialkoje,

Data Sovereignty Q-Gate Criteria for Release 24.08

Trace-X has the role Data Consumer and Data Provider. 
Kindly ask for QG approval for Data Sovereignty.

Data Provider 
- [x] A data offer (contract Offer) MAY consist of an access policy and MUST include at least one usage policy.
	- [x] The access policy MUST use CX Standardized credentials.
	- [x] A usage policy MUST refer to at least one Verifiable Credential(Framework Agreement)* (hereinafter referred to as VC). The currently available credentials can be viewed in the CX-0050 standard. The usage policy MUST refer to a confirmed framework agreement which covers the desired scope of data (e.g. traceability, quality,...). It MUST reference the agreement either as a whole or additionally dedicated predefined elements (e.g. purpose - defined in CX-0018 standard) of the framework agreement.
- [x] In case the data provider is enabled to create contract offers, the data provider MUST be enabled to configure contract offer policies.
- [x] The application MUST use the BPN-L of the data provider when providing data via the DSP connector (e.g. EDC or managed EDC).
- [x] The provider of the connector MUST ensure the provision of data via the DSP protocol adhering to the released version of CX-0018 standard. For example, using the Eclipse Data Space Connector on Tractus X.
- [x] This provider also MUST ensure that the data provider is uniquely identifiable through its associated BPN-L.
- [x] This BPN-L must be used by this provider to identify the data.


Data Consumer
- [x] The provider of the connector MUST ensure the consumption of data via the DSP protocol adhering to the released version of CX-0018 standard. For example, using the Eclipse Data Space Connector on Tractus-X. 
	- [x] The application MUST ensure that the consumer of the data is uniquely identifiable through its associated BPN-L.
	- [x] This BPN-L must be used by this application to identify the data.
- [x] The application MUST use the BPN-L of consumer of the data when consuming data via the DSP connector (e.g. EDC or managed EDC).
- [x] A user of an application MUST be enforced to act within the constraints of the framework agreement by appropriate means (legal, technical,...).
- [x] To agree to one or multiple contract offers for a queried data asset, the selection of the appropriate offer MUST be done through the consuming application, ensuring to follow company-defined rules and regulations for a user of that application.

**Comment by mkanal** [comment]
@ther3sa

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description.

**Comment by jzbmw** [comment]
User Journey herby approved

**Comment by ther3sa** [comment]
QG Review 23-July
- Missing version Link: Version to be included in Eclipse Tractus-X release: version placeholder
- TRGs 95%  done. Pending TRGs 1.02; 4.02; 4.05; 4.07 and 8.04 
- User Journey approved by @jzbmw
- E2E test is pending

**Comment by mkanal** [comment]
Status Update 
- [x] Add version Link
- [x] TRGs  done. 
- [x] User Journey approved by @jzbmw
- [ ] E2E test is pending

fyi @ther3sa

**Comment by ds-crehm** [comment]
E2E-Tests finished with two findings:
- https://github.com/eclipse-tractusx/traceability-foss/issues/1318 - will be fixed for release
- https://github.com/eclipse-tractusx/traceability-foss/issues/1122 - will be added to Known Knowns

**Comment by ds-mwesener** [comment]
Updated app version https://github.com/eclipse-tractusx/traceability-foss/releases/tag/13.0.1 and helm chart version https://github.com/eclipse-tractusx/traceability-foss/releases/tag/helm-charts-1.3.43

**Comment by ds-mwesener** [comment]
Hi @ther3sa we have successfully completed the release. I kindly ask for final approval. Thanks in advance.

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
