### ISSUE TITLE
[R24.08] [Simple Data Exchanger] Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#742]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
App Version: 2.4.3
Helm Chart Version: 0.1.12

**Leading product repository:** *repository link*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/51
https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

# Test Results

- [x] **E2E Integration Test** passed

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description

**Comment by ther3sa** [comment]
QG Review 23-July

* Leading product repository Link is missing
* TRG Check needs to be done
* User Journey needs to be approved
* E2E test is pending

**Comment by ciprianherciu** [comment]
@ther3sa  If I understood correctly the TRG which we should follow for 24.08 are those ones: https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ther3sa** [comment]
Could you set the check for the e2e test and could you give me an update on how far you are with the TRGs and the user journey?

**Comment by ther3sa** [comment]
I have a question. Does this issue only affect the Managed simples data exchanger SDE? Is there an additional issue for the frontend and the backend? :)
See table https://github.com/eclipse-tractusx/sig-release/issues/821

**Comment by ther3sa** [comment]
@almadigabor  could you give me an update on how far you are with the TRGs? :)

**Comment by ciprianherciu** [comment]
> I have a question. Does this issue only affect the Managed simples data exchanger SDE? Is there an additional issue for the frontend and the backend? :) See table #821

Hello Theresa, it is for all of them. The issue is for the entire SDE.

In regards with the TRG it is in progress more than half is done

**Comment by ther3sa** [comment]
> > I have a question. Does this issue only affect the Managed simples data exchanger SDE? Is there an additional issue for the frontend and the backend? :) See table #821
> 
> Hello Theresa, it is for all of them. The issue is for the entire SDE.
> 
> In regards with the TRG it is in progress more than half is done

okay thank you for your update :)

**Comment by almadigabor** [comment]
Hey @ther3sa! Working on it, hopefully I'll be done a couple of hours. Who's doing TRG 9.01 UI/UX styleguide checks? I'm not really familiar with the topic.

**Comment by ther3sa** [comment]
> Hey @ther3sa! Working on it, hopefully I'll be done a couple of hours. Who's doing TRG 9.01 UI/UX styleguide checks? I'm not really familiar with the topic.

thanks for the update :) 

@stephanbcbauer do you know who can do the TRG 9.1 UI/UX style guide check?

**Comment by ciprianherciu** [comment]
@ther3sa  when is the last day for the QG approvals?

**Comment by ther3sa** [comment]
> @ther3sa when is the last day for the QG approvals?

Today is the last day for QG approval

**Comment by ther3sa** [comment]
> > > @ther3sa when is the last day for the QG approvals?
> > 
> > 
> > Today is the last day for QG approval
> > We will finish it today. for all three products until EoB

Okay thank you for your update :)

**Comment by almadigabor** [comment]
I approve the QG with the following versions:

Helm Chart Version: 0.1.12
App Version: 2.4.3

**Comment by ther3sa** [comment]
@almadigabor I received an email, but I can no longer see your comment. 
Are the TRGs ready? Could you check the box then? 
Is the TRG 9.01 UI consistency/styleguide for UI not needed here either?

**Comment by almadigabor** [comment]
Needed to recheck something, so I deleted the comment. I approve the QG now with the following versions:

Helm Chart Version: 0.1.12
App Version: 2.4.3

**Comment by ther3sa** [comment]
Could you check the TRG in the description. After that I can give my approval :)

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
