### ISSUE TITLE
[R24.08] [Managed Service Orchestrator] Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#743]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*
 Helmchart version  1.6.0 
AppVersion - 1.5.7
**Leading product repository:** *repository link*

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/managed-service-orchestrator/issues/183
https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Test Results

- [x] **E2E Integration Test** passed
User Journey** N/A

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by evegufy** [comment]
Please note that there was the following update to the issue template (see https://github.com/eclipse-tractusx/sig-release/pull/750#issuecomment-2219591340 for additional information), please take that into account for R24.08

> Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description.

**Comment by ther3sa** [comment]
QG-Review 23-July

* TRG Check needs to be done
* User Journey needs to be approved
* E2E test is pending

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ther3sa** [comment]
Could you set the check for the e2e test and could you give me an update on how far you are with the TRGs?

**Comment by ther3sa** [comment]
@almadigabor could you give me an update on how far you are with the TRGs? :)

**Comment by ther3sa** [comment]
I have a question.
The TRG 9.01 UI consistency/styleguide for UI is not checked. Is this on purpose, because no committer has checked it or was the check forgotten?

**Comment by ciprianherciu** [comment]
@ther3sa  MSO does not have a UI

**Comment by ther3sa** [comment]
> @ther3sa MSO does not have a UI

okay thank you :)

**Comment by ther3sa** [comment]
@ciprianherciu  Can you update the version in the description to the newest. Then I will give my approval. :)

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts  :)
