### ISSUE TITLE
[R24.08] [SD Factory] Release Checks

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#744]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
AppVersion - 2.1.13
Helmchart version - 2.1.21

**Leading product repository:** *repository link*

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/sd-factory/issues/202
https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Test Results

- [x] **E2E Integration Test** passed
User Journey** - N/A no user journey approval needed
# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by evegufy** [comment]
Please note that there was the following update to the issue template (see https://github.com/eclipse-tractusx/sig-release/pull/750#issuecomment-2219591340 for additional information), please take that into account for R24.08

> Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description

**Comment by ther3sa** [comment]
QG Review 24-July
- Version listed ✓
- TRG Check needs to be done
- User Journey needs to be approved
- E2E test is pending

**Comment by ciprianherciu** [comment]
Hello @ther3sa,

SD Factory is a component which  is used for Onboarding Organization in Portal.
Since SD Factory is only a step with which the User does not interact, a user journey approval is not needed.

As E2E, SD Factory does not have a separate test. As long as the onboarding of the companies is working, SD Factory is tested and working.

Because of this, the only open point I see for SD Factory for Release Check are the TRG Checks.

Thank You.

**Comment by ther3sa** [comment]
okay thank you for your update :)

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ther3sa** [comment]
@ciprianherciu How are you getting on with your TRGs? :)

**Comment by ther3sa** [comment]
@almadigabor could you give me an update on how far you are with the TRGs? :)

**Comment by almadigabor** [comment]
Checks are done from my side and approve the QG with the following versions:

Helm Chart Version: 2.1.21
App Version: 2.1.13

**Comment by ther3sa** [comment]
> Checks are done from my side and approve the QG with the following versions:
> 
> Helm Chart Version: 2.1.21 App Version: 2.1.13

Thank you :)

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
