### ISSUE TITLE
EDC - Faster Startup

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#756]
## Description

We have the requirement to start the EDC as fast as possible to fulfill our internal requirements. With the following resource specs, the EDC needs around 40-50 seconds to start, and we don’t want to give him more Cores because most of the time he is idling around which would be then a waste of resources: CPU: 1 Core (AMD EPYC 7763), RAM: 3 GB.

Requestor: @florianrusch-zf 

## Impact

No impact on external dependencies as this is a technical issue during startup. No behavior change to the outside world except for faster availability.

**Comment by lgblaumeiser** [comment]
Discussion in weekly today: 

- Multiple aspects, like, e.g., database connection setup
- Depends on the EDC configuration
- Concrete goals are missing, what is acceptable

Proposal: Get more into details of what is expected and which approaches there are concerning optimization

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is available

**Comment by lgblaumeiser** [comment]
De-Prioritized, no work planned for 24/12

**Comment by lgblaumeiser** [comment]
PRs in this context:
- https://github.com/eclipse-edc/Connector/pull/4587
- https://github.com/eclipse-edc/Connector/pull/4590
- https://github.com/eclipse-edc/Connector/pull/4593
- https://github.com/eclipse-edc/Connector/pull/4600
-

**Comment by lgblaumeiser** [comment]
Some improvements done. Optimizations are onoging tasks, therefore the issue is closed, as the work will not be tracked on this level anymore.
