### ISSUE TITLE
[R24.08] [Semantic-hub] Release Checks

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sig-release#761]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 
helm: semantic-hub-0.3.1
Image version: 0.40

**Leading product repository:** *[repository link](https://github.com/eclipse-tractusx/sldt-semantic-hub)*

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

~~- [ ] **Interoperability** checks performed~~
~~- [ ] **Data Sovereignty** checks performed~~

# General Checks

- [x] [eclipse-tractusx/sldt-semantic-hub#285]

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

~~- [ ] **Threat Modeling Analysis** passed~~

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by evegufy** [comment]
Please note that there was the following update to the issue template (see https://github.com/eclipse-tractusx/sig-release/pull/750#issuecomment-2219591340 for additional information), please take that into account for R24.08

> Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

**Comment by tunacicek** [comment]
> Please note that there was the following update to the issue template (see [#750 (comment)](https://github.com/eclipse-tractusx/sig-release/pull/750#issuecomment-2219591340) for additional information), please take that into account for R24.08
> 
> > Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

Hi @evegufy , thanks for the hint. This issue was created based on the updated template and includes the changes.

**Comment by tunacicek** [comment]
Data Sovereignty Check:
@vialkoje : Could you please tick this checkbox?
No significant changes since Release 23.12.

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description

**Comment by ther3sa** [comment]
QG Review 23-July

- Version listed ✓
- TRG Check is 100% but needs to be checked 
- User Journey needs to be approved
- E2E test is pending

**Comment by thomas-henn** [comment]
Yes, user journey of Semantic Hub is aligned along with, e.g. Digital Twin Registry.

**Comment by ther3sa** [comment]
> Yes, user journey of Semantic Hub is aligned along with, e.g. Digital Twin Registry.

Perfect, for the transparency, could you set the check for the user journey

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ther3sa** [comment]
Can you check the TRG, as these are 100% complete. After that I can give my approval.

**Comment by agg3fe** [comment]
> Can you check the TRG, as these are 100% complete. After that I can give my approval.

Hi @ther3sa , Checks are now complete from our side. You can provide the approval. Thank you.

**Comment by ther3sa** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
