### ISSUE TITLE
[Circularity KIT]: Add "Core" to Glossary

### ISSUE THREAD

**Issue by florianstern** [eclipse-tractusx/sig-release#763]
## Description
 Add definition for "Core" in context of remanufacturing. 

## Impact
 Glossary will get another Row.

## Additional information 

- [x ] I'm willing to contribute to this feature

Committer: Committer @danielmiehle , @maximilianong

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer needed

**Comment by florianstern** [comment]
I have the definition ready, but probably would need help to add it to the Glossary Table via PR
