### ISSUE TITLE
Simple Data Exchanger (SDE) Release 23.12 Documentation Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#78]
# Release Documentation 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code** https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/21

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [x] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [ ] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by sachinargade123** [comment]
-    Source Code :
      SDE FE - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend
      SDE BE - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend
-    Architecture Documents Arc 42 - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/docs/Arc42.md
-    Administrator`s Guide (User assistance) 
SDE BE - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/InstallationGuide.md
SDE. FE - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/README.md

-    End-User Manual (User assistance)
SDE Frontend :- https://github.com/catenax-ng/tx-managed-simple-data-exchanger-frontend/blob/main/docs/user-guide/README.md
SDE Backend :- https://github.com/catenax-ng/tx-managed-simple-data-exchanger-backend/blob/main/README.md
-    Interfaces Documentation - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/modules/sde-core/src/main/resources/sde-open-api.yml
-    UX consistency -  Done as per UX Guidelines from Cat-X.

**Comment by hzierer** [comment]
System Team Release Guideline checks tracked in [eclipse-tractusx/managed-simple-data-exchanger#21](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/21)

**Comment by hzierer** [comment]
@MehranRoshandel @adityagajbhiye9 can you please specify the versions to check for QG4? And I assume we first need some PRs from catena-x -> tractus-x as the catena-x repos are several commits ahead

**Comment by hzierer** [comment]
Overview of the open (or not yet merged) issues found in the checks:
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/22
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/23
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/40
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/issues/69
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/issues/71

**Comment by adityagajbhiye9** [comment]
> Overview of the open (or not yet merged) issues found in the checks:
> 
> * [values.yaml should not set insecure default passwords managed-simple-data-exchanger#22](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/22)
> * [[TRG 5.07] postgresql version is not on the aligned version managed-simple-data-exchanger#23](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/23)
> * [{TRG 7.02] Missing license and copyright header managed-simple-data-exchanger-frontend#40](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/40)
> * [Dockerfile: UID 1001 and "useradd -r ..." are mutally exclusive managed-simple-data-exchanger-backend#69](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/issues/69)
> * [[TRG 7.01] outdated notice.md file managed-simple-data-exchanger-backend#71](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/issues/71)

We already fixed above the issues.

**Comment by adityagajbhiye9** [comment]
> @MehranRoshandel @adityagajbhiye9 can you please specify the versions to check for QG4? And I assume we first need some PRs from catena-x -> tractus-x as the catena-x repos are several commits ahead
AppVersion:2.3.0
Chart Version: 1.0.0
After merging PR ,release tag will be 2.3.0

**Comment by MehranRoshandel** [comment]
This is correct; we are still waiting for the open PRs to merge.
https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/pull/68
https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/pull/38
The expected version is 2.3.0

**Comment by kelaja** [comment]
- **Source Code** -> WiP in QG-Review on 23rd Nov, final version 2.3.0
- **Architecture Documents** -> @vialkoje kindly check upront in [ng-repo](https://dtag.webex.com/dtag-en/url.php?frompanel=false&gourl=https%3A%2F%2Fgithub.com%2Fcatenax-ng%2Ftx-managed-simple-data-exchanger-frontend%2Fblob%2Fmain%2Fdocs%2FArc42.md)
- **Administrator`s Guide** -> @vialkoje kindly check
- **End-User Manual** -> @vialkoje kindly check
- **Interfaces Documentation** -> @vialkoje kindly check
- **UX consistency** -> @jjeroch no changes in the UX

**Comment by hzierer** [comment]
Found one additional issue:
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/41

**Comment by adityagajbhiye9** [comment]
> Found one additional issue:
> 
> * [[TRG 7.05] Missing legal decuments in Docker image managed-simple-data-exchanger-frontend#41](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/issues/41)

Updated the legal documents for docker image.

**Comment by kelaja** [comment]
@hzierer kindly check again the comment from @adityagajbhiye9

**Comment by jjeroch** [comment]
UX Validation Feedback:

**Following change (findings of the last release) is/are missing:**

- [ ] Suggestion: If the user selected one or several useCases on the "home" page, add the information of the selected useCases in all other sub-pages to ensure that the user is aware that a filtering is active.

 

**Successfully tested:**

- [x] Suggestion: inside the "create data" page I suggest to add a link to the submodel description page ">> more details regarding the different submodel attributes"
- [x]  Inside the "Help" page (navigation on the left hand side) anchors/hyperlinks are suggested to enable the user to jump directly to the respective submodel description

<br>
<br>

<img width="839" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/04f3b892-9026-429d-984d-74b40041eda5">

**Comment by MehranRoshandel** [comment]
Good morning @jjeroch, Thanks we can implement the suggestions in this PI

**Comment by AjayRaturi123** [comment]
**Source Code :**
**SDE FE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/releases/tag/v2.3.0
**SDE BE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/releases/tag/v2.3.0

**Architecture Documents Arc 42** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/docs/Arc42.md

**Administrator`s Guide (User assistance)**
**SDE BE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/INSTALL.md
**SDE FE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/README.md

**End-User Manual (User assistance)**
**SDE Frontend** :- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/docs/user-guide/README.md
**SDE Backend** :- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/README.md

**Interfaces Documentation** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/modules/sde-core/src/main/resources/sde-open-api.yml

**UX consistency** - Done as per UX Guidelines from Cat-X.

@vialkoje Please review and approve.

**Comment by vialkoje** [comment]
everything available as expected. expert approval granted

**Comment by hzierer** [comment]
> [Most checks](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/21) (24/30) from system team side are ok in the meantime, too. Except for those which are blocked by the not yet released helm chart. (PR is still in draft state)

The remaining 3 checks are currently blocked by [managed-simple-data-exchanger/issues/26](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/issues/26)

**Comment by hzierer** [comment]
System Team Release Guideline checks have been finished successfully

**Comment by MehranRoshandel** [comment]
Thanks,
@kelaja please close the Ticket https://github.com/eclipse-tractusx/sig-release/issues/78

**Comment by kelaja** [comment]
@RolaH1t  
The release notes must mention the following regarding UX:
- the reload will cause additional time duration for loading UX-content
- single selects are not implemented

**Comment by kelaja** [comment]
@jjeroch kindly leave your comment here, regarding SDE UX

**Comment by jjeroch** [comment]
Update on my findings based on the newest SDE Version:

UX Validation Feedback:

**Following change (findings of the last release) is/are missing:**

- [ ] Suggestion: If the user selected one or several useCases on the "home" page, add the information of the selected useCases in all other sub-pages to ensure that the user is aware that a filtering is active.

 

**Successfully tested:**

- [x] Suggestion: inside the "create data" page I suggest to add a link to the submodel description page ">> more details regarding the different submodel attributes"
- [x]  Inside the "Help" page (navigation on the left hand side) anchors/hyperlinks are suggested to enable the user to jump directly to the respective submodel description
- [x] left hand side navigation is always reloading when the user selects any navigation item. Instead its expected to stay in place and only reload the actual page content right beside. You can have a look at the portal - we are doing the same with our top navigation
- [x] select should only allow single select but actually allows multiple selection

<br>
<br>

**Findings relevant for the ChangeLog of Release 23.12.:**
- [ ] Duration restriction need to get removed, this is not a valid policy rule
- [ ] Purpose policy rule wrong. Instead of “ID 3.0 Trace” it must be “ID 3.1 Trace”
- [ ] Usage Policy is missing the framework agreement which is mandatorily needed for UseCase specific data offers
- [ ] Help link navigates to GitHub docu “main” – this is a bad implementation behavior, never use main use the actual release tag
otherwise the documentation will not fit to the actual application deployed as soon as main gets further developed

**Comment by MehranRoshandel** [comment]
Thanks, Julia,
We will document the findings in the changelog.

**Comment by MehranRoshandel** [comment]
We have updated the change logs as requested:
https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/CHANGELOG.md

**Comment by MehranRoshandel** [comment]
@kelaja please close this ticket
