### ISSUE TITLE
Improve initial wallet insert and credential creation

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-release#781]
## Description

The process through which the initial wallet - for the Operator which needs to be created manually- is added to the Portal as well as the creation of the BPNL and Membership credentials for this initial wallet by the SSI Credential Issuer should be improved.
In the current state it requires direct interaction on database level to some extent.

The benefit is that the Operator would not need to go through the steps mentioned in the following documents:
- [initial-wallet-setup](https://github.com/eclipse-tractusx/portal-assets/blob/v2.1.0/docs/developer/Technical%20Documentation/Operator%20Wallet%20Setup/Initial%20Setup.md)
- [initial-credential-setup](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.1.0/docs/technical-documentation/operator-credential-creation/initial-credential-setup.md)

## Impact

No interface dependencies

## Additional information 

- [x] I'm willing to contribute to this feature

- https://github.com/eclipse-tractusx/portal-backend/issues/1003
- https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/250
- https://github.com/eclipse-tractusx/portal-frontend/issues/1203
- https://github.com/eclipse-tractusx/portal/issues/449

**Comment by jjeroch** [comment]
Decision: please add some benefits as well as the affected role inside the dataspace

**Comment by evegufy** [comment]
Committers:
@evegufy 
@Phil91 
@ntruchsess 
@oyo
