### ISSUE TITLE
[PURIS KIT] 24.08 Release Checks

### ISSUE THREAD

**Issue by dominikoeh** [eclipse-tractusx/sig-release#784]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** *0.3.0*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/986

# General

- [x] **CHANGELOG** available and maintained
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [x] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [x] **Reference Implementation** available
- [x] **Access and Usage Policies** documented

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [x] **Deployment Script** available (e.g., helm charts)

# Helpful Links

## Standards

The relevant standards can be found in the [Catena-X Association Standard Library](https://catenax-ev.github.io/docs/next/standards/overview)\:

- [CX-0118 Delivery Information Exchange 2.0.0](https://catenax-ev.github.io/docs/next/standards/CX-0118-ActualDeliveryInformationExchange)
- [CX-0120 Short-Term Material Demand Exchange 2.0.0](https://catenax-ev.github.io/docs/next/standards/CX-0120-ShortTermMaterialDemandExchange)
- [CX-0121 Planned Production Output Exchange](https://catenax-ev.github.io/docs/next/standards/CX-0121-PlannedProductionOutputExchange)
- [CX-0122 Item Stock Exchange 2.0.0](https://catenax-ev.github.io/docs/next/standards/CX-0122-ItemStockExchange)
- [CX-0145 Days of Supply Exchange 1.0.0](https://catenax-ev.github.io/docs/next/standards/CX-0145-DaysofsupplyExchange)

**Comment by dominikoeh** [comment]
cc @jSchuetz88

**Comment by matbmoser** [comment]
Puris Kit is merged!

**Comment by jSchuetz88** [comment]
Hi @dominikoeh,

thank you for all your efforts :), as the PR has been approved and already merged, I changed the status to done.
