### ISSUE TITLE
[EcoPass KIT] Release Checks

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-release#785]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** *version placeholder*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/952
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/995
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/999
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1000

# General

- [x] **CHANGELOG** available and maintained
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [x] **Logic / Schema** available and described
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [x] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [x] **Tutorials** available
- [x] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [x] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [x] **Protocols** available (e.g., dataspace protocol)
- [x] **Sample Data** available
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [x] **Reference Implementation** available

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [x] **Deployment Script** available (e.g., helm charts)

# Features

- [x] https://github.com/eclipse-tractusx/sig-release/issues/591
- [x] https://github.com/eclipse-tractusx/sig-release/issues/649
- [x] https://github.com/eclipse-tractusx/sig-release/issues/651

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by jSchuetz88** [comment]
Hi @matbmoser 
this Release Check refers to PR [#785](https://github.com/eclipse-tractusx/sig-release/issues/785)? 

As the PR has already been approved and merged, please provide an update of the Changelog which reflects these latest changes.

**Comment by matbmoser** [comment]
Hi @jSchuetz88, sure I can provide a proper changelog 👍🏻 I have also revised the TRGs there, all fine 💯

**Comment by matbmoser** [comment]
The only thing that I believe is missing is the link to the whitepaper link -> #649

**Comment by matbmoser** [comment]
Ok I approved the whitepaper PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/995

I also saw it was missing to add the tutorial in the adoption view, so I created a bugfix PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/999

**Comment by matbmoser** [comment]
I have added the latest information about tutorials, verification etc. in the Adoption view as required.

**Comment by matbmoser** [comment]
@jSchuetz88  I have written the changelog for the KIT: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1000 Please review

**Comment by matbmoser** [comment]
Ok KIT change log is merged: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1000

I think we are done here @ther3sa

**Comment by jSchuetz88** [comment]
Hi @matbmoser,

thank you for all your efforts :), as all of the PRs have been approved and already merged, I changed the status to done.
