### ISSUE TITLE
[DCM KIT] Release Checks

### ISSUE THREAD

**Issue by LukasSchmetz** [eclipse-tractusx/sig-release#786]
> This issue tracks all relevant release checks for your KIT.
> 
> Important
> 
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).
> 
> ## Release Info
> Please provide information on what you want to be included in the Eclipse Tractus-X release. If you are not owner of this issue, please provide the information as comment to the issue. Have your prepared content reviewed by a professional peer group before submitting it for committer approval. Best practice: have a professional Peer review your prepared content before you submit for expert approvals. Please link the open or merged PR that includes the changes.
> 
> **Version to be included in Eclipse Tractus-X release:** _version placeholder_
> 
> * KIT semantic version of change log.
> * Date of KIT publication must be aligned with overall release date.
> 
> If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.
> * [DCM PR #981](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/981)
> * [DCM PR #984](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/984)
> * [DCM PR #985](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/985)
> 
> If changes are already live, also point out the PRs witch included the changes for this version if possible.
> 
> # General
> * [x]  **CHANGELOG** available and maintained
> * [ ]  [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled
> 
> # Adoption View
> * [x]  **Vision and Mission** statement present
> * [x]  **Business Value** statement present
> * [x]  **Semantic Models** linked and described
> * [x]  **Logic / Schema** available and described
> * [x]  **Business Process** documentation available
> * [x]  **Access and Usage Policies** documented
> * [x]  **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
> * [ ]  **Tutorials** available
> * [ ]  **White Paper** available
> * [x]  **Notice** CC BY 4.0 licence statement available
> 
> # Development View
> * [x]  **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
> * [ ]  **Protocols** available (e.g., dataspace protocol)
> * [x]  **Sample Data** available
> * [x]  **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
> * [ ]  **Reference Implementation** available
> 
> # Operation View
> * [ ]  **Setup Guide** available (e.g., installation guides)
> * [ ]  **Deployment Script** available (e.g., helm charts)
> 
> # Helpful Links
> * [CX-0128 Demand and Capacity Management Data Exchange 2.0.0]

**Comment by LukasSchmetz** [comment]
@ClosedSourcerer: Can you please have a look if anything is missing to have the release ticket? Thanks.

**Comment by LukasSchmetz** [comment]
@jSchuetz88 We urgently need support for the Eclipse IP Clearance for PR #981 mentioned above. Already requested in the PR support from @danielmiehle  and @maximilianong  but still pending and it was mentioned it takes 14 days. Thanks.

**Comment by ClosedSourcerer** [comment]
> @ClosedSourcerer: Can you please have a look if anything is missing to have the release ticket or if we can already tick some checkboxes? Thanks.



> > # General
> > 
> > * [X]   **CHANGELOG** available and maintained
> > * [ ]   [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

They change all the time, so I am not signing this off.

> > 
> > # Adoption View
> > 
> > * [X]   **Vision and Mission** statement present
> > * [X]   **Business Value** statement present
> > * [X]   **Semantic Models** linked and described
> > * [X]   **Logic / Schema** available and described
> > * [X]   **Business Process** documentation available
> > * [X]   **Access and Usage Policies** documented
> > * [X]   **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
> > * [ ]   **Tutorials** available
> > * [ ]   **White Paper** available
> > * [X]   **Notice** CC BY 4.0 licence statement available

According to the TRGs this needs to be everywhere, not just within the adoption view and according to the tempalte the adoption view does not exist.

> > 
> > # Development View
> > 
> > * [X]   **API Specification** published
> > * [ ]   **Protocols** available (e.g., dataspace protocol)
> > * [X]   **Sample Data** available
> > * [X]   **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
> > * [ ]   **Reference Implementation** available

FOSS Application references, however since it has no released package for 24.08 I do not consider it a reference implementation

> > 
> > # Operation View
> > 
> > * [ ]   **Setup Guide** available (e.g., installation guides)
> > * [ ]   **Deployment Script** available (e.g., helm charts)

Within the FOSS repository

> > 
> > # Helpful Links
> > 
> > * [CX-0128 Demand and Capacity Management Data Exchange 2.0.0]

And just fyi: Nothing really plays nicely together. The Eclipse Foundation Rules, the association release process, the KIT template, this release checklist. There are HUUUUUGE gaps everywhere and sometimes even direct contradictions ;) (Business View vs. Adoption View)

**Comment by jSchuetz88** [comment]
Hi @LukasSchmetz ,

thank you for all your efforts :), as all three PRs has been approved and already merged, I changed the status to done.

**Comment by LukasSchmetz** [comment]
Hi @jSchuetz88 small fix still outstanding in PR #1010 to move Onboaring Content to the right place in Eclipse Tractus-X
