### ISSUE TITLE
Simple Data Exchanger (SDE) Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#79]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by MehranRoshandel** [comment]
@sachinargade123, please add the evidence of all security checks here

**Comment by kelaja** [comment]
@sachinargade123 kindly see the contact information here to assign the ticket after PR is closed:
https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621

**Comment by kelaja** [comment]
@sachinargade123, please add the evidence of all security checks here. @MehranRoshandel

**Comment by AjayRaturi123** [comment]
1. **Threat Modelling Analysis results**
https://confluence.catena-x.net/pages/viewpage.action?pageId=62831498  
@guenterban  Added the document link; please approve.

2. **Static Application Security Testing (SAST)**
@PiotrStys Please review and approve.
**SDE FE** - https://analysiscenter.veracode.com/auth/index.jsp#HomeAppProfile:47240:1397406
[DFT_Frontend_05_Dec_2023.pdf](https://github.com/eclipse-tractusx/sig-release/files/13558381/DFT_Frontend_05_Dec_2023.pdf)
**SDE BE** - https://analysiscenter.veracode.com/auth/index.jsp#HomeAppProfile:47240:1407267
[DFT_Backend_05_Dec_2023.pdf](https://github.com/eclipe-tractusx/sig-release/files/13558398/DFT_Backend_05_Dec_2023.pdf)

3. **Dynamic Application Security Testing (DAST)**
<img width="1496" alt="Invicti" src="https://github.com/eclipse-tractusx/sig-release/assets/104556215/03ec9a2c-9a73-42e9-a316-79de345ed950">
@PiotrStys Attached SDE Backend and SDE Frontend scans with no critical/ high findings. Please review and approve.

4. **Secret scanning**
No High/Critical findings in Veracode found. Attached the above veracode report.
@DnlZF Please check gitguardian from your side as well and approve.

5.  **Software Composition Analysis (SCA)**
@Gitleena Please review and approve.
**SDE FE** - 
<img width="1496" alt="SCA_SDEFrontend" src="https://github.com/eclipse-tractusx/sig-release/assets/104556215/7d55adfb-dc14-4eda-89c1-fb82ceba9aae">
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1397406:31165671:31135802:31151452:::::4405591:
**SDE BE** - 
<img width="1496" alt="SCA_SDEBackend" src="https://github.com/eclipse-tractusx/sig-release/assets/104556215/c6a2d66c-2a76-4c48-920e-d6052008b156">
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsSCA:47240:1407267:31176064:31146193:31161843:::::4428438:

6. **Container Scan conducted**
@scherersebastian Please review and approve.
**SDE FE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/actions/runs/7094742271
**SDE BE** - https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/actions/runs/7098879209

7. **Infrastructure as Code**
@scherersebastian Please review and approve.
**SDE FE** -  https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/actions/runs/7094478320
**SDE BE** -  https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/actions/runs/7098879208

**Comment by MehranRoshandel** [comment]
@kelaja Evidences have already been added by @AjayRaturi123. Now we can close all QG tickets

**Comment by scherersebastian** [comment]
KICS / IaC passed.
Please check your container scan findings:
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/security/code-scanning
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/security/code-scanning

**Comment by DnlZF** [comment]
Hi,
there is one open GitGuardian finding (without feedback):
https://dashboard.gitguardian.com/workspace/226265/incidents/5153035
**-> Secret scanning not approved**

Best regards
Daniel

**Comment by DnlZF** [comment]
Hi,

now there are no more open GitGuardian findings.
-> Secret scanning approved

Best regards
Daniel

**Comment by kelaja** [comment]
@PiotrStys kindly check on SAST and DAST for SDE

**Comment by PiotrStys** [comment]
Hello, 

No high/critical vulnerabilities reported back by Invicti.
**DAST scanning passed.**

@kelaja, please note, as I already mentioned on a few occassions, I am not the correct team member to approve SAST findings.

Kind regards, 
Piotr

**Comment by kelaja** [comment]
@PiotrStys thanks a lot for the assessment, who else is then the right contact? (confluence contact list)[https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621] link works only for consortia members!

**Comment by BANANAS1337** [comment]
SAST approved by Tim

**Comment by scherersebastian** [comment]
Trivy / container scans passed

**Comment by mabige** [comment]
@kelaja seems to be done. Pls. approve and close.

@RolaH1t
