### ISSUE TITLE
[R24.08] [TX-EDC] Release Checks

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#791]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 0.7.3

**Leading product repository:** https://github.com/eclipse-tractusx/tractusx-edc

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled -> https://github.com/eclipse-tractusx/sig-release/issues/792

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by lgblaumeiser** [comment]
@cbrugg: I learned from @stefan-ettl, that you did some integration tests with the EDC in the past. Who is taking over this responsibility for the current release?

**Comment by lgblaumeiser** [comment]
User Jounrney checked, as this is not relevant for the EDC component.

**Comment by lgblaumeiser** [comment]
Execution of
- Interoperability tests
- Data sovereignity tests
- Thread Modelling Analysis

to be clarified, information expected from @ds-meberle

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description

**Comment by lgblaumeiser** [comment]
Removed Compliance Verifications and Security Checks from Description as proposed in the comment above.

**Comment by ther3sa** [comment]
QG Review 23-July

- Version listed ✓
- TRG Check outstanding ✓
- User Journey checked by @lgblaumeiser, because its not relevant for the edc component ✓
- E2E test is pending

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by lgblaumeiser** [comment]
@ther3sa , as you closed the other release issue, do you close this one, too?

**Comment by ther3sa** [comment]
After I have checked, I can give you my approval. 

Congrats: Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts:)
