### ISSUE TITLE
[R24.08] [BDRS] Release Checks

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#793]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 0.5.2

**Leading product repository:** https://github.com/eclipse-tractusx/bpn-did-resolution-service

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled -> https://github.com/eclipse-tractusx/sig-release/issues/794

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Test Results

- [ ] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by lgblaumeiser** [comment]
User Journey approved by me as there is no special user journey defined for the component

**Comment by lgblaumeiser** [comment]
Execution of

- Interoperability tests
- Data sovereignity tests
- Thread Modelling Analysis

to be clarified, information expected from @ds-meberle

**Comment by lgblaumeiser** [comment]
E2E Tests are executed automatically by all other tests, as it is part of company onboarding and every edc that is executed during the test phase. If these tests are successful, the E2E Integration tests will be considered as passed by me.

**Comment by ther3sa** [comment]
Hi, 
as discussed in today's open meeting and referring to today's email, please remove the check topics for Interoperability, Data Sovereignty and Threat Modeling in your description

**Comment by lgblaumeiser** [comment]
Removed Compliance Verifications and Security Checks from Description as proposed in the comment above.

**Comment by ther3sa** [comment]
Before I give my approval, could you please check whether your issue is entered in the right place in the table?
[Release Checks - Summary check](https://github.com/eclipse-tractusx/sig-release/issues/821)

**Comment by stephanbcbauer** [comment]
> Not sure, what you mean by right place in the table, @ther3sa, it is a component and it was updated, is there anything else?

Yes, this was the question. Updated, Added or Unchanged :) The categories for our Tractus-X changelog. But you already menbtioned it as updated :)

**Comment by ther3sa** [comment]
Based on this information I'm happy to give you my approval. 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
