### ISSUE TITLE
[R24.08] [PURIS] Release Checks

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-release#795]
> [!IMPORTANT]
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: *version placeholder*

**Leading product repository:** *https://github.com/eclipse-tractusx/puris/*

**Quality Gate Issue:** https://github.com/eclipse-tractusx/puris/issues/498

**Helm / Versioning**:
- **chart name**: puris
- **chart version**: 2.7.0 (int tested)
- **app version**: 2.1.0 (int tested)

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X.

~~- [ ] **Interoperability** checks performed~~
~~- [ ] **Data Sovereignty** checks performed~~

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

~~- [ ] **Threat Modeling Analysis** passed~~

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ther3sa** [comment]
QG Review 24-July
- Please remove Int and Sov test from the check list
- Please remove threat modeling Analysis from the check list
- Please list your version to be included in Eclipse Tractus-X release
- Please create a Quality Gate Checklist issue 
- User Journey needs to be approved
- E2E test is pending

**Comment by tom-rm-meyer-ISST** [comment]
> QG Review 24-July
> 
> * Please remove Int and Sov test from the check list
> * Please remove threat modeling Analysis from the check list
> * Please list your version to be included in Eclipse Tractus-X release
> * Please create a Quality Gate Checklist issue
> * User Journey needs to be approved
> * E2E test is pending

Updated, removals has been marked as strikethrough.

Quality Gate Ticket has been linked from downwards and now been added here. Versions are going to be reported

Question @ther3sa : Are consortia BOs going to approve the user journey again? How to handle it in future? Will it be the Committee Lead?

**Comment by rauschg** [comment]
User journey is confirmed by the BO role

**Comment by ther3sa** [comment]
> Question @ther3sa : Are consortia BOs going to approve the user journey again? How to handle it in future? Will it be the Committee Lead?

We are currently working out how user journeys will be handled in the future.

**Comment by ther3sa** [comment]
TRGs must be checked and please put your current App and helm chart version in the description. 
After that I will be happy to give my approval. :)

**Comment by tom-rm-meyer-ISST** [comment]
Quality Gate passed (self-assessment): https://github.com/eclipse-tractusx/puris/issues/498

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
