### ISSUE TITLE
Simple Data Exchanger (SDE) Release 23.12 Test Results Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#80]
# Release Test Results 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **E2E System Integrations Tests**

  -  To pass the Consortia Gate 4, evidence has to be made available that all test criteria up to and including TRL 4 & TRL 6 have been achieved.
  - Expected evidence = outputs of TRL 4 and TRL 6.
  - Test Management has mapped and described all mandatory tests for Consortia Quality Gates [HERE](https://confluence.catena-x.net/x/WQpHAw)(Source only accessible for Catena-X Consortia members in current transition phase).
  - Please focus on the columns "Derived Criteria" and "Outputs"  
  - Document your test results in Catena-X JIRA XRAY
  - Use the fields “DoD” and “Status” (story & solution level) to approve requirements.
  - Interim test results are required after Tests of each Sprint, this is pre-requisite to participate in E2E test phase

  _Contact:_
    - TEST MANAGEMENT

- [x] **Approval of User Journey**

  - CX Business Owner confirms: All acceptance criteria met (as defined in PI documentation)
  Relevant evidence is available

  _Artifact Repository_
    - [Jira Solution Level](https://jira.catena-x.net/projects/CXSOLUTION/summary)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practise_
    - PO to obtain BO approval prior to Gate review.
    - BO therefore to evaluate progress by participation at iteration demos.
    - BOs provide E2E test cases.
    - BOs welcome to act as tester.
    - BOs expected to participate in System Demo.

  _Contacts:_
    - FOSS Product Owners &
    - CX Business Owners

**Comment by MehranRoshandel** [comment]
@sachinargade123 please add the link to the integration and E2E tests to here

**Comment by sachinargade123** [comment]
- E2E System Integrations Tests - [A1SDS-2682](https://jira.catena-x.net/browse/A1SDS-2682) , [A1SDS-2693](https://jira.catena-x.net/browse/A1SDS-2693) , 	[TEST-1361](https://jira.catena-x.net/browse/TEST-1361) (Same is Updated in Test status Confluence Page)
  - Approval of User Journey - No changes for Release 3.2 on User Journey.

**Comment by MehranRoshandel** [comment]
@sachinargade123 please ask Steffen Pötsch to approve the user Journey

**Comment by MehranRoshandel** [comment]
This the aproval of Steffen Pötsch for the User Journy

![Image](https://github.com/eclipse-tractusx/sig-release/assets/101404316/aa4dd6fc-a001-4e4e-9cdb-04c570c47982)

**Comment by MehranRoshandel** [comment]
E2E Test is also done: see here: https://jira.catena-x.net/browse/TEST-1361

**Comment by BerndRothbrust** [comment]
OK from TM -> Your Task now @kelaja

**Comment by kelaja** [comment]
done in QG-Review

**Comment by MehranRoshandel** [comment]
@kelaja, the User Journey is still open.
There are some minor changes. I have already asked @jjeroch to check it. She will be back tomorrow and will check it.
@sachinargade123 @dvasunin please add the evidence of changes here

**Comment by kelaja** [comment]
![Image](https://github.com/eclipse-tractusx/sig-release/assets/73890462/992045bf-52de-4f32-9467-14bfb401c0f6)
