### ISSUE TITLE
[Business Partner KIT] Release Checks 24.08

### ISSUE THREAD

**Issue by Unsharm** [eclipse-tractusx/sig-release#807]
## Release Info

Business Partner KIT Release check 24.08 placeholder

**Version to be included in Eclipse Tractus-X release:** *6.0.0*

- eclipse-tractusx/eclipse-tractusx.github.io/pull/988
 

# General

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [ ] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by jSchuetz88** [comment]
Hi @Unsharm ,

thank you for all your efforts :), as the PR has been approved and already merged, I changed the status to done.
