### ISSUE TITLE
EDC - Establish TCK proof of compliance for Tractus-X EDC versions

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#808]
## Description

The interoperability of different EDC versions is a central question for a continuous development of the Catana-X dataspace. In order to enable a technical proof of compliance with the relevant protocols, the Dataspace Protocol (DSP) and the Decentralized Claims Protocol (DCP), a TCK based testing approach needs to be established, which allows to technically proof the compatibility of a certain connector version towards the expectations of the corresponding protocol version.

The TCK has to provide the ability to test an EDC towards different versions of the protocols.

## Impact

No impact on other components

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Committer available, no impact on other components

**Comment by lgblaumeiser** [comment]
Blocked, as the Eclipse Dataspace Working Group needs to finalize the first specification of the Dataspace Protocol. The tests for the TCK will be derived directly from concrete clauses of the spec. The upcoming spec is expected to be formally different as it should be fit for ISO standardization. That does not mean, that it will be different content wise, but the derivation of test cases requires the final form to be efficient.

**Comment by lgblaumeiser** [comment]
Moved to state "Not in release" as it cannot be expected that we get something from upstream in time

**Comment by lgblaumeiser** [comment]
I close this issue for now, as the content is not valuable enough to keep it open, instead, we will create a new issue, as soon as there is something available upstream.
