### ISSUE TITLE
[New Model] [R24.12] Traceability KIT: Special Characteristics

### ISSUE THREAD

**Issue by Jochen-Fischer** [eclipse-tractusx/sig-release#818]
### Introduction of “Special Characteristics”
Special Characteristics of a product that do not have adequate robustness, which are difficult to maintain during production. Which lead to immediate consequences if they product, can be identified as special Characteristics.

Special Characteristics are suitable for communicating, product quality and securing in the supply chain.
 
Special Characteristics are Characteristics that require increased care in order to avoid production issues and ensure the quality of the products.

Special Characteristics are defined and recorded with the supplier during development.

Special Characteristics are divided into three categories:
•	Legal / relevant to legislation / homologation,
•	Safety
•	Function

All products with safety or legal relevant properties, markings or functions are traceability and compliance relevant.
Special Characteristics are also mentioned on VDA organization. More details can be found on this page: https://webshop.vda.de/QMC/de/besondere-merkmale-bm-042020

### Target
Data on the special characteristics are collected within the supply chain, but not systematically forwarded to the OEM. The aim is to improve data exchange and consistency for special characteristics.
•	Data collection and provision for critical components
•	Data collection for a limited period of time, when required, in the event of quality problems or as part of industrialization.

Catena-X is to be used for data exchange within the supply chain. Since traceability must be ensured for special characteristics, it is advisable to supplement the Catena-X Use Cases Industry Core | Traceability with an additional functionality (additional aspect model) for the special characteristics. The special characteristics will be directly linked to the digital twin. 

The new aspect model "Special Characteristics" is to be developed in the working group, agreed upon and defined as a new standard for Catena-X.

### Key Benefits
The key benefits are the same as for every standard aspect model.

Data exchange within the Catena-X network on the basis of the standard date model.

Problem ### Statement
Special Characteristics must be checked by the OEM for quality and compliance purposes. To do this check, data about the Special Characteristics must be exchanged between the partners.

The exchange between supplier and OEM is currently done on single data exchange with special data format accepted by the partners. That means every data exchange has its single implementation.

### Proposed Solution
A solution to solve the problem is to create a standard data model (aspect model) to exchange data for Special Characteristics. 

This aspect model is linked to digital twins. This means, the new aspect model is using already existing Catena-X standards like Industry Core and Traceability.

The VDA has already defined a data model for Special Characteristics. This VDA standard could be an idea for a Catena-X standard for the Special Characteristics aspect model.

### Implementation Plan
The new aspect model will be discussed and worked out in the Traceability working group. The discussion on this topic has already started with a kick-off meeting. Next step will be to define a working model and working session to develop the aspect model. 

### Cost and Resources
No external cost estimated. 
Input and review are expected from the expert group. 

### Contact Information
BMW 
Jochen Fischer
[Jochen.fa.Fischer@bmw.de](mailto:Jochen.fa.Fischer@bmw.de)

### Additional Information
Committers to support are:
@danielmiehle , @maximilianong 
Cointributor: 
@Grand-Thibault

**Comment by stephanbcbauer** [comment]
Get feedback from the technical committee 4 modelling (TC4M)

**Comment by RicardoSchlatter** [comment]
I would recommend to change the title to:
"[R24.12] Traceability KIT: Special Characteristics"

**Comment by RicardoSchlatter** [comment]
Pleas also add the label "kit". This work will mean to extend the Traceability KIT.

**Comment by stephanbcbauer** [comment]
Release Planning: This is "just" the adaptation of the KIT, implementing/adapting the reference implementation will start next release -> Please already create the related Issue
