### ISSUE TITLE
[R24.12] Traceability: New Logistics KIT

### ISSUE THREAD

**Issue by RicardoSchlatter** [eclipse-tractusx/sig-release#819]
## Description

Releasing KIT for logistics, content so far: vision, mission and benefits, digital twin for transport unit and transport itself as well as matching aspect models like "PackingList" and "ShippingData". Seems to be as draft and transfer-vehicle to continue work on this topic in new setup in association.

## Additional information 

- [ ] I'm willing to contribute to this feature

Committers:
@danielmiehle , @maximilianong

**Comment by stephanbcbauer** [comment]
@RicardoSchlatter, @Grand-Thibault  did we already talk about this feature? Is this somehow a placeholder? Or is it planned for R24.12? Friendly reminder, right now, since the status is NOT Backlog, the feature wouldn't be presented in tomorrow's planning.

**Comment by RicardoSchlatter** [comment]
Hello Stephan,

Wir wollen das Feature für den R24.12 doch bearbeiten.

Ich will eigentlich das Feature mit status Backlog haben...damit es morgen in der Liste erscheint.

vG,
Ricardo

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tunacicek** [comment]
duplicated issue: https://github.com/eclipse-tractusx/sig-release/issues/988
