### ISSUE TITLE
[Product] Release Checks - Summary check - R24.08

### ISSUE THREAD

**Issue by ther3sa** [eclipse-tractusx/sig-release#821]
## Help needed

Currently, we see a mismatch between already created [Product] Release Checks Issues and our expected Changelog.
The Changelog is much bigger than the number of issues. 

- [ ] **Are there issues missing? Please create the Issue if you want to be part of release 24.08 and add your new issue to the issue list.**
- [ ] **Please add also a comment if something is wrong, or if you updated/created an issue**

The changelog includes all Products where we see changes in the latest release compared to the changelog for 24.05.
It might also be the case, that the changelog is wrong, and we have too many entries. :) The Release column is just information. It's the date when the latest release was created.

We are aware of the fact, that some “lines” in our table are combined into one product. Still, we have more than issues.

- [ ] **Please check whether your product should be on the list or not.**
- [ ] **If your product is in the wrong table, and it should be for example in unchanged, let us know**

## Currently created Release check issues

- #740 
- #741 
- #743 
- #759
- #742 
- #760 
- #762
- #791 
- #793 
- #761 
- #748 
- #744 
- #764 
- #765 
- #767 
- #768 
- #795
- #823  
- #829 

### Added

| Component | Helm Chart (s) | App-/KIT Version (s) |
| :-------- | :-------------: | :------------------: |
| [BPDM Certificate Management](https://github.com/eclipse-tractusx/bpdm-certificate-management) | bpdm-certificate-management: [1.0.1-alpha.3](https://github.com/eclipse-tractusx/bpdm-certificate-management/releases/tag/bpdm-certificate-management-1.0.1-alpha.3) | n/a |
| [Knowledge Agents AAS Bridge](https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge) | aas-bridge: [1.13.7](https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/releases/tag/v1.13.7) | [1.13.7](https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/releases/tag/v1.13.7) |
| [Supply Chain Disruption Notifications Kit](https://eclipse-tractusx.github.io/docs-kits/category/supply-chain-disruption-notifications-kit) | n/a | [1.0.0](https://eclipse-tractusx.github.io/docs-kits/kits/Supply%20Chain%20Disruption%20Notifications%20KIT/Supply%20Chain%20Disruption%20Notifications%20Changelog) |
| [SSI Authority & Schema Registry](https://github.com/eclipse-tractusx/ssi-authority-schema-registry) | ssi-asr: [1.0.0](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/releases/tag/ssi-asr-1.0.0) | [1.0.0](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/releases/tag/v1.0.0) |

### Updated

| Component | Helm Chart (s) | App-/KIT Version (s) |
| :-------- | :-------------: | :------------------: |
| [BPDM Kit](https://eclipse-tractusx.github.io/docs-kits/category/business-partner-kit) | n/a | [6.0.0](https://eclipse-tractusx.github.io/docs-kits/kits/Business%20Partner%20Kit/Changelog) |
| [BPN DID Resolution Service (BDRS)](https://github.com/eclipse-tractusx/bpn-did-resolution-service) | [0.5.2](https://github.com/eclipse-tractusx/bpn-did-resolution-service/releases/tag/0.5.2) | [0.5.2](https://github.com/eclipse-tractusx/bpn-did-resolution-service/releases/tag/0.5.2) |
| [Circularity Kit](https://eclipse-tractusx.github.io/docs-kits/kits/Circularity_KIT/page-adoption-view) | n/a | [1.2.0](https://eclipse-tractusx.github.io/docs-kits/kits/Data%20Chain%20Kit/data%20chain%20kit%20changelog) |
| [DCM Kit](https://eclipse-tractusx.github.io/docs-kits/category/dcm-kit) | n/a | [1.1.0](https://eclipse-tractusx.github.io/docs-kits/kits/DCM-Kit/changelog) |
| [Digital Product Pass (DPP)](https://github.com/eclipse-tractusx/digital-product-pass) | digital-product-pass: [4.0.1](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1) | [4.0.1](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1) |
| [Digital Twin Kit](https://eclipse-tractusx.github.io/docs-kits/category/digital-twin-kit) | n/a | [2.0.1](https://eclipse-tractusx.github.io/docs-kits/kits/Digital%20Twin%20Kit/Digital%20Twin%20Kit%20Changelog) |
| [Digital Twin Registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry) | digital-twin-registry: [0.5.2](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/releases/tag/digital-twin-registry-0.5.2) | [0.5.0](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/releases/tag/v0.5.0) |
| [Discovery Finder](https://github.com/eclipse-tractusx/sldt-discovery-finder) | discoveryfinder: [0.3.1](https://github.com/eclipse-tractusx/sldt-discovery-finder/releases/tag/discoveryfinder-0.3.1) | [0.4.0](https://github.com/eclipse-tractusx/sldt-discovery-finder/releases/tag/v0.4.0) |
| [Discovery Service (BPN Finder)](https://github.com/eclipse-tractusx/sldt-bpn-discovery) | bpndiscovery: [0.3.1](https://github.com/eclipse-tractusx/sldt-bpn-discovery/releases/tag/bpndiscovery-0.3.1) | [0.4.0](https://github.com/eclipse-tractusx/sldt-bpn-discovery/releases/tag/v0.4.0) |
| [Eclipse Data Space Connector (Tractus-X EDC)](https://github.com/eclipse-tractusx/tractusx-edc) | [0.7.3](https://github.com/eclipse-tractusx/tractusx-edc/releases/tag/0.7.3) | [0.7.3](https://github.com/eclipse-tractusx/tractusx-edc/releases/tag/0.7.3) |
| [EcoPass Kit](https://eclipse-tractusx.github.io/docs-kits/category/eco-pass-kit) | n/a | [1.5.0](https://eclipse-tractusx.github.io/docs-kits/kits/Eco_Pass_KIT/changelog) |
| [ESS Kit](https://eclipse-tractusx.github.io/docs-kits/category/ess-kit) | n/a | [0.3.0](https://eclipse-tractusx.github.io/docs-kits/kits/ESS-Kit/ESS%20Kit%20Changelog) |
| [Golden Record Business Partner Number (BPN) Service](https://github.com/eclipse-tractusx/bpdm) | bpdm: [5.1.0](https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-5.0.3) | [6.1.0](https://github.com/eclipse-tractusx/bpdm/releases/tag/v6.1.0) |
| [Identity and Access Management (IAM)](https://github.com/eclipse-tractusx/portal-iam) | centralidp: [3.0.1](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-3.0.1)<br>sharedidp: [3.0.1](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-3.0.1) | keycloak: [23.0.7](https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-23-0-7) |
| [Industry Core KIT](https://eclipse-tractusx.github.io/docs-kits/category/industry-core-kit) | n/a | [1.1.0](https://eclipse-tractusx.github.io/docs-kits/kits/Industry%20Core%20Kit/Industry%20Core%20Kit%20Changelog) |
| [Item Relationship Service (IRS)](https://github.com/eclipse-tractusx/item-relationship-service) | item-relationship-service: [7.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.4.0) | [5.4.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.4.0) |
| [Knowledge Agents](https://github.com/eclipse-tractusx/knowledge-agents) | remoting-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/remoting-agent-1.13.22)<br>provisioning-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/provisioning-agent-1.13.22)<br>conforming-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/conforming-agent-1.13.22)<br>matchmaking-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/matchmaking-agent-1.13.22) | remoting-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/v1.13.22)<br>provisioning-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/v1.13.22)<br>conforming-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/v1.13.22)<br>matchmaking-agent: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/v1.13.22) |
| [Knowledge Agents EDC](https://github.com/eclipse-tractusx/knowledge-agents-edc) | agent-plane: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/agent-plane-1.13.22) | [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.13.22) |
| [Knowledge Agents EDC](https://github.com/eclipse-tractusx/knowledge-agents-edc) | agent-plane-azure-vault: [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/agent-plane-azure-vault-1.13.22) | [1.13.22](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.13.22) |
| [Managed Service Orchestrator](https://github.com/eclipse-tractusx/managed-service-orchestrator) | managed-service-orchestrator: [1.6.0](https://github.com/eclipse-tractusx/managed-service-orchestrator/releases/tag/managed-service-orchestrator-1.6.0) | [1.5.7](https://github.com/eclipse-tractusx/managed-service-orchestrator/releases/tag/v1.5.7) |
| [Managed Simple Data Exchanger (SDE)](https://github.com/eclipse-tractusx/managed-simple-data-exchanger) | sde: [0.1.12](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/releases/tag/sde-0.1.12) | frontend: [2.4.3](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/releases/tag/v2.4.3)<br>backend: [2.4.3](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/releases/tag/v2.4.3) |
| [PCF Exchange Kit](https://eclipse-tractusx.github.io/docs-kits/category/pcf-exchange-kit) | n/a | [1.2.0](hthttps://eclipse-tractusx.github.io/docs-kits/kits/PCF%20Exchange%20Kit/PCF%20Exchange%20Kit%20Changelog) |
| [Policy Hub](https://github.com/eclipse-tractusx/policy-hub) | policy-hub: [1.1.0](https://github.com/eclipse-tractusx/policy-hub/releases/tag/policy-hub-1.1.0) | [1.1.0](https://github.com/eclipse-tractusx/policy-hub/releases/tag/v1.1.0) |
| [Portal](https://github.com/eclipse-tractusx/portal) | portal: [2.1.0](https://github.com/eclipse-tractusx/portal/releases/tag/portal-2.1.0) | registration: [2.0.1](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v2.0.1)<br>frontend: [2.1.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v2.1.0)<br>backend: [2.1.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v2.1.0)<br>assets: [2.1.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v2.1.0) |
| [PURIS](https://github.com/eclipse-tractusx/puris) | puris: [2.7.0](https://github.com/eclipse-tractusx/puris/releases/tag/puris-2.7.0) | [2.1.0](https://github.com/eclipse-tractusx/puris/releases/tag/2.1.0) |
| [PURIS Kit](https://eclipse-tractusx.github.io/docs-kits/category/puris-kit) | n/a | [0.3.0](https://eclipse-tractusx.github.io/docs-kits/kits/PURIS%20Kit/PURIS%20Kit%20Changelog) |
| [Self Description (SD) Factory](https://github.com/eclipse-tractusx/sd-factory) | sdfactory: [2.1.21](https://github.com/eclipse-tractusx/sd-factory/releases/tag/sdfactory-2.1.21) | [2.1.13](https://github.com/eclipse-tractusx/sd-factory/releases/tag/v2.1.13) |
| [Semantic Hub](https://github.com/eclipse-tractusx/sldt-semantic-hub) | semantic-hub: [0.3.1](https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.3.1) | [0.4.0](https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/v0.4.0) |
| [SSI Credential Issuer](https://github.com/eclipse-tractusx/ssi-credential-issuer) | ssi-credential-issuer: [1.1.0](https://github.com/eclipse-tractusx/ssi-credential-issuer/releases/tag/ssi-credential-issuer-1.1.0) | [1.1.0](https://github.com/eclipse-tractusx/ssi-credential-issuer/releases/tag/v1.1.0) |
| [Trace-X Traceability Application](https://github.com/eclipse-tractusx/traceability-foss) | helm-charts: [1.3.43](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/helm-charts-1.3.43) | [13.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/13.0.1) |
| [Traceability Kit](https://eclipse-tractusx.github.io/docs-kits/category/traceability-kit) | n/a | [5.1.0](https://eclipse-tractusx.github.io/docs-kits/kits/Traceability%20Kit/Traceability%20Kit%20Changelog) |
| [OSIM Kit](https://eclipse-tractusx.github.io/docs-kits/category/osim-kit) | n/a | [3.0.0](https://eclipse-tractusx.github.io/docs-kits/kits/OSim%20Kit/OSim%20Kit%20Changelog) |

 
### Unchanged, untested
 
| Component | Helm Chart (s) | App-/KIT Version (s) |
| :-------- | :-------------: | :------------------: |
| [Managed Identity Wallet (MIW)](https://github.com/eclipse-tractusx/managed-identity-wallet) | nan | [v0.5.0](https://github.com/eclipse-tractusx/managed-identity-wallet/releases/tag/v0.5.0) | 
| [Country Risk](https://github.com/eclipse-tractusx/vas-country-risk) | country-risk: [4.0.2](https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/country-risk-4.0.2) | [1.3.1](https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/v1.3.1) |

**Comment by stephanbcbauer** [comment]
The PR for changelog preperation can be found here https://github.com/eclipse-tractusx/tractus-x-release/pullshttps://github.com/eclipse-tractusx/tractus-x-release/pull/34

**Comment by lgblaumeiser** [comment]
@ther3sa Please be aware, that the Eclipse Data Space Connector version for the release has been downgraded to 0.7.3.

**Comment by stephanbcbauer** [comment]
@ther3sa message from @ciprianherciu 
SDE, SD Factory and MSO already have a QG ticket.
E2E Data Exchange Test Service was and is part of MSO, we never had another Ticket for it.

**Comment by stephanbcbauer** [comment]
> @ther3sa message from @ciprianherciu SDE, SD Factory and MSO already have a QG ticket. E2E Data Exchange Test Service was and is part of MSO, we never had another Ticket for it.

thx @ciprianherciu we will delete E2E from the List in the Added section. Nothing todo for you in this case.

**Comment by stephanbcbauer** [comment]
> @ther3sa Please be aware, that the Eclipse Data Space Connector version for the release has been downgraded to 0.7.3.

Thanks @lgblaumeiser adapted :)

**Comment by evegufy** [comment]
Hi @ther3sa not certain why the following issues aren't reflected in the list (I opened them 2 weeks ago):
https://github.com/eclipse-tractusx/sig-release/issues/764
https://github.com/eclipse-tractusx/sig-release/issues/765
https://github.com/eclipse-tractusx/sig-release/issues/767
https://github.com/eclipse-tractusx/sig-release/issues/768

**Comment by stephanbcbauer** [comment]
> Hi @ther3sa not certain why the following issues aren't reflected in the list (I opened them 2 weeks ago): #764 #765 #767 #768

Thx @evegufy we use this [view](https://github.com/orgs/eclipse-tractusx/projects/26/views/17). Here, thy issue type is filtered. The issue type was not set automatically, that's why we missed your issues.

**Comment by mkanal** [comment]
Hi @ther3sa 
Item Relationship Service (IRS)
App version is https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.4.0
HELM version is https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.4.0
Thank you very much
Martin

**Comment by stephanbcbauer** [comment]
> Hi @ther3sa Item Relationship Service (IRS) App version is https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.4.0 HELM version is https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/item-relationship-service-7.4.0 Thank you very much Martin

Thx @mkanal -> adapted

**Comment by ther3sa** [comment]
@stephanbcbauer message from @matbmoser 

[R24.08] [Digital Product Pass] Release Checks #748 ->  will be updated to v4.0.1.

**Comment by stephanbcbauer** [comment]
i added the KITs information and versions in the table and also in the related PR

**Comment by ther3sa** [comment]
Updated app version 13.0.0 to 13.0.1 and helm chart version 1.3.42 to 1.3.43 for [Trace-X traceability Application](https://github.com/eclipse-tractusx/traceability-foss)

**Comment by ther3sa** [comment]
Updated app version 2.0.2 to 2.1.0. and helm chart version 2.6.3 to 2.7.0 for [PURIS](https://github.com/eclipse-tractusx/sig-release/issues/795) in the table. Needs to be changed in the PR

**Comment by jSchuetz88** [comment]
@ther3sa 
The Tracability Kit version must be changed from v5.2.0 to v5.1.0, as this seems to be a typo

**Comment by ther3sa** [comment]
> @ther3sa / @stephanbcbauer The Tracability Kit version must be changed from v5.2.0 to v5.1.0, as this seems to be a typo (see: https://eclipse-tractusx.github.io/docs-kits/next/kits/Traceability%20Kit/Traceability%20Kit%20Changelog)

done

**Comment by ds-meberle** [comment]
@ther3sa / @stephanbcbauer ( https://github.com/eclipse-tractusx/sig-release/issues/829 ) is missing in this overview. E2E Tests for BPDM successfully completed.

**Comment by stephanbcbauer** [comment]
adapted the table and combined different services, like portal ...

**Comment by nicoprow** [comment]
Adapted BPDM updated Helm chart version to 5.1.0 as per release check

**Comment by ciprianherciu** [comment]
- SDE: 
   - Helmchart version v 0.1.11 
   - App version v 2.4.2
- SD Factory: 
   - Helmchart version 2.1.21 
   - AppVersion  2.1.13
- MSO
   - Helmchart version  1.6.0 
   - AppVersion - 1.5.7

**Comment by stephanbcbauer** [comment]
> * SDE:
>   
>   * Helmchart version v 0.1.11
>   * App version v 2.4.2
> * SD Factory:
>   
>   * Helmchart version 2.1.21
>   * AppVersion  2.1.13
> * MSO
>   
>   * Helmchart version  1.6.0
>   * AppVersion - 1.5.7

thx, updated in the table

**Comment by ther3sa** [comment]
Updated Manged Simple Data Exchanger Helm Chart Versionfrom 0.1.11 to 0.1.12 and App Version: 2.4.2 to  2.4.3
