### ISSUE TITLE
MIW | E2E-testing for MIW with EDC >0.8.0

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/sig-release#822]
## Description
The purpose of this ticket is to place the need for a separate e2e test for MIW. 

Background information: MIW does not partipate in E2E-testing for 24.08 which is taking place with EDC version 0.7.3. and DIM wallet. For IATP support, MIW requires sts remote client and oauth2 client in EDC, which were introduced in EDC 0.8.0. 
On the other hand, currently no multi wallet support is possible (a concept for multi wallet support & BYOW is expected for R24.12.)

Under these circumstances a parallel test environment or a temporary use of the existing environment is needed in order to perform e2e tests for MIW which should cover the entire onboarding sequence where the wallet is a part of. 
 
The following components are required to cover the onboarding/registration sequence for e2e-tests:
- Portal
- BPDM service
- Issuer component
- MIW 
- BDRS
- SD-Factory
- GAIA-X clearinghouse (external component)
- EDC 0.8.0

Required steps: 
- decision for a separate test environment or usage of the existing environment temporarily for MIW
- deployment of necessary components
- configuration/adaptation of portal/issuer component to MIW
- upgrade/migration of products participationg in e2e-journey to EDC 0.8.0
- test coordination

## Impact
Additional effort for setting up components in a parallel test environment and performing tests. Using the existing environment would lead to a temporary unavailability for possible other tests .

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
@OSchlienz   not sure about this feature. Is it planned to present it in tomorrow's planning? It was never presented in a Refinement meeting. Did we miss something?

**Comment by evegufy** [comment]
The adjustments needed aren't limited to testing:
- **MIW needs to support still statuslist2021** --> relates to https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/224 and https://github.com/eclipse-edc/Connector/issues/4357
- relates to https://github.com/eclipse-tractusx/sig-release/issues/647

**Comment by matbmoser** [comment]
Added MIW label

**Comment by matbmoser** [comment]
Moved to backlog

**Comment by MaximilianHauer** [comment]
@stephanbcbauer  i assume based on the last discussions we will not find a contributor/committer for this topic ? should we close it ?

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer i assume based on the last discussions we will not find a contributor/committer for this topic ? should we close it ?

Fine for me… it's not deleted … in case we need it, we can reopen it. THX
