### ISSUE TITLE
[R24.08] [Knowledge Agents] Release Checks

### ISSUE THREAD

**Issue by obalandi** [eclipse-tractusx/sig-release#823]
> [!IMPORTANT]
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

**Version to be included in Eclipse Tractus-X release**: *1.13.22*

**Leading product repository:** https://github.com/eclipse-tractusx/knowledge-agents

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

- https://github.com/eclipse-tractusx/knowledge-agents/issues/151
- https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/230
- https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/issues/73 

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by drcgjung** [comment]
Integration and E2E Tests completed and documented here: https://github.com/eclipse-tractusx/knowledge-agents/issues/150

**Comment by bosserf** [comment]
@obalandi User Journey herewith approved

**Comment by ther3sa** [comment]
Could you set the check for the e2e test and user journey and could you give me an update on how far you are with the TRGs ?

**Comment by obalandi** [comment]
Hey @almadigabor, could you start with TRGs? Thx.

**Comment by ther3sa** [comment]
@almadigabor could you give me an update on how far you are with the TRGs? :)

**Comment by ther3sa** [comment]
@obalandi could you give me an update on how far the TRGs are done? :)

**Comment by obalandi** [comment]
We will be able to finish it on Monday (08/05), @almadigabor

**Comment by ther3sa** [comment]
> We will be able to finish it on Monday (08/05), @almadigabor

Okay, we will prepare everything and wait for you!
Could you please be through with the TRGs by **12 noon** and please write us once when you are through so that we can start directly. And please let us know if there are any changes to the version. 
Many thanks

**Comment by ther3sa** [comment]
@obalandi @almadigabor Will you be able to finish the TRGs by 12 noon?

**Comment by almadigabor** [comment]
Hey @ther3sa, I was out of office last week, haven't got the change to do the checks. As they are not done yet, I'll start now, and report back to you in the afternoon.

**Comment by ther3sa** [comment]
> Hey @ther3sa, I was out of office last week, haven't got the change to do the checks. As they are not done yet, I'll start now, and report back to you in the afternoon.

Thank you :)

**Comment by almadigabor** [comment]
Hey @ther3sa, All the checks are done from my side, except there are 3 critical security findings in the knowledge-agents repo [here](https://github.com/eclipse-tractusx/knowledge-agents/security/code-scanning?query=is%3Aopen+branch%3Arelease%2F1.13.22). As far as I remember these were already dismissed as false positives in the last release but I would need some confirmation from the team before I approve that. Once they are dealt with one way or another I would approve the QG from my side.

**Comment by bosserf** [comment]
@almadigabor I cannot see the linked findings (Error 404). Recall the "false positives" outcome although. Any chance to retrieve then?
@ther3sa fyi: Oz, Schorsch and Tom are on Holidays

**Comment by almadigabor** [comment]
Hi @bosserf, I've found the discussion where @drcgjung indeed hinted that these exact 3 alerts are false positives. Therefore I approve the QG and close this issue with a remark that this reappearing finding should be investigated until the next release. I've opened an [issue](https://github.com/eclipse-tractusx/knowledge-agents/issues/157) where it can be tracked at a later date.

**Comment by bosserf** [comment]
Cool. Good Job, Sherlock 👍 😎

**Comment by RoKrish14** [comment]
I approve that the findings are False Positive and TRG checks has been completed by @almadigabor.
@drcgjung : Please address the issue [#157 ](https://github.com/eclipse-tractusx/knowledge-agents/issues/157)as this was already present in the last release and we want to make sure that issue has been addressed completely.

**Comment by evegufy** [comment]
Hi @almadigabor, I don't quite understand the reasoning here why this should be a false positive, could you please explain it to me?:

When you have a look at the affected branches:

![image](https://github.com/user-attachments/assets/eda5fb83-9931-40c6-8178-9a216a27b22f)

You see that for the release branch of the last release, you fixed the finding with this PR https://github.com/eclipse-tractusx/knowledge-agents/pull/129.
But this change was apparently not integrated into the main branch since then and it it's also not part of the release branch of the new release.

IMO, the finding needs to get solved also in the new release branch and in the main branch.

**Comment by RoKrish14** [comment]
I have marked the CodeQL findings as False Positive with the reason "URLs to services are aquired during runtime. In this case URL is proxied through the EDC and hence no user input. Validation is done via sanitization of the input". 
Together with @almadigabor, I confirm the approval of Security TRG related to CodeQL findings.

**Comment by stephanbcbauer** [comment]
Cool thank you very much for your effort and discussion, @ther3sa approval? ;)

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
