### ISSUE TITLE
[R24.08] [BPDM] Release Checks

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/sig-release#829]
> [!IMPORTANT]
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

**Version to be included in Eclipse Tractus-X release**: 
App-Version: 6.1.0
Helm-Version: 5.1.0

**Leading product repository:** [eclipse-tractux/bpdm](https://github.com/eclipse-tractusx/bpdm)

# Compliance Verifications

Not applicable

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

Not applicable

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ds-meberle** [comment]
Planned E2E Tests for release 24.08 on Catena-X INT environment have been performed successfully. Thank You!

**Comment by ther3sa** [comment]
Could you please remove the checks for the Interoperability checks and Data Sovereignty checks as well as the Threat Modeling Analysis.

**Comment by ds-meberle** [comment]
@nicoprow if possible please also update the issue summary to "[R24.08] [BPDM] Release Checks"

**Comment by ther3sa** [comment]
Congrats: 
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
