### ISSUE TITLE
Managed Service Orchestrator Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#83]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [ ] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by MehranRoshandel** [comment]
@dvasunin  please add the reports of the security tools here

**Comment by sharathshivprasad** [comment]
Threat modelling Document:
https://confluence.catena-x.net/display/cxsecurity/Security+Assessment+-+Auto+Setup+API

Dynamic Application Security Testing:
Latest Invicti report : https://www.netsparkercloud.com/scans/report/025257ccf1234f26bee8b0c101f28769/
[scan-report-orchestrator.int.cx.dih-cloud.com-detailedscan-21_11_2023 02_59 PM.pdf](https://github.com/eclipse-tractusx/sig-release/files/13435685/scan-report-orchestrator.int.cx.dih-cloud.com-detailedscan-21_11_2023.02_59.PM.pdf)

Container Scan conducted:
Latest Trivy Scan Report: https://github.com/eclipse-tractusx/managed-service-orchestrator/actions/workflows/trivy.yml

Infrastructure as Code:
Latest KICS report: https://github.com/eclipse-tractusx/managed-service-orchestrator/actions/workflows/kics.yml

**Comment by PiotrStys** [comment]
Hi @sharathshivprasad,

Is this possible for you to verify this finding?

![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/d24be5e4-46bc-4718-82be-a71a450f3787)

Although Invicti did not mark it as "high", I am concerned about this finding..
How effortful would be for you to address it?
Please let me know.

Regards,
Piotr

**Comment by sharathshivprasad** [comment]
> Hi @sharathshivprasad,
> 
> Is this possible for you to verify this finding?
> 
> ![Image](https://user-images.githubusercontent.com/140413055/285438794-d24be5e4-46bc-4718-82be-a71a450f3787.png)
> 
> Although Invicti did not mark it as "high", I am a bit concerned about it. How effortful would be for you to address it? Please let me know.
> 
> Regards, Piotr

@dvasunin @adkumar1  Please have a look.

**Comment by dvasunin** [comment]
> Hi @sharathshivprasad,
> 
> Is this possible for you to verify this finding?
> 
> ![Image](https://user-images.githubusercontent.com/140413055/285438794-d24be5e4-46bc-4718-82be-a71a450f3787.png)

As far as I know, and this is marked in the controller code, '/internal/*' endpoints are dedicated for internal use only and are not exposed outside of cluster. This particular endpoint is supposed to return application details like JDBC string, but it shall be safe as this data does not leave (or shall not leave) the cluster

**Comment by PiotrStys** [comment]
> > Hi @sharathshivprasad,
> > Is this possible for you to verify this finding?
> > ![Image](https://user-images.githubusercontent.com/140413055/285438794-d24be5e4-46bc-4718-82be-a71a450f3787.png)
> 
> As far as I know, and this is marked in the controller code, '/internal/*' endpoints are dedicated for internal use only and are not exposed outside of cluster. This particular endpoint is supposed to return application details like JDBC string, but it shall be safe as this data does not leave (or shall not leave) the cluster

Hi @dvasunin,

Thank you for your input and explanation. 
My main intention was to bring the finding to your awareness so that you can make sure it is not a direct threat to your application. 
Other than that, please make sure to review the potential XSS findings before the next QG.

![image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/c5a4c018-6b84-45a2-9bb6-577e708fac0e)
**DAST Passed**

Thank you,
Piotr

**Comment by klaudiaZF** [comment]
Hi, @sharathshivprasad Can you please share a link for SCA?

Thank you in advance

**Comment by sharathshivprasad** [comment]
> Hi, @sharathshivprasad Can you please share a link for SCA?
> 
> Thank you in advance

Hello @klaudiaZF ,
Please find the latest veracode scan report.
Link: https://analysiscenter.veracode.com/auth/index.jsp#ViewReportsResultSummary:47240:1550110:30943369
Latest Report: 
[DetailedReport_DFT_AutoSetup_26_Nov_2023.pdf](https://github.com/eclipse-tractusx/sig-release/files/13470732/DetailedReport_DFT_AutoSetup_26_Nov_2023.pdf)

**Comment by klaudiaZF** [comment]
Hi All,

**SCA Passed**

<img width="831" alt="DFT_Autosetup" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/10d493a7-79e9-41a8-862e-361d3fa6143b">


@sharathshivprasad  Thank you
