### ISSUE TITLE
feat(bpdm-gate-pool): MVP hierarchy data model adjustment 

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/sig-release#833]
[GitHub Issue #754](https://github.com/eclipse-tractusx/sig-release/issues/754)

### User Story: Hierarchy Management for BPNLs in Catena-X Portal

**As a** Company Admin,  
**I want to** manage hierarchies for Business Partner Number Lists (BPNLs) in the Catena-X Portal,  
**so that** I can effectively organize and control the relationships between different BPNLs.

#### Acceptance Criteria:
1. **CRUD Operations:**
   - **Create:** Ability to create a new hierarchy type “Is Managed in Catena-X Portal By” with "valid from" and "valid to" attributes.
   - **Read:** Display all hierarchy types, including “Is Managed in Catena-X Portal By” with their details.
   - **Update:** Allow editing of existing hierarchies by changing the "valid from" and "valid to" dates.
   - **Delete:** Allow deletion of hierarchies when no longer needed.

2. **Hierarchy Types:**
   - Initial support for “Is Managed in Catena-X Portal By”.
   - Future implementation for additional types: “Is Registered Alternative For” and “Is Replaced By”.
   - Ensure that each BPNL can support multiple hierarchy types.

3. **Relationship Types:**
   - Implement relationship types “public” and “non-public”.
   - Default relationship type should be “non-public”.
   - Company Admins can set and change the relationship type of a BPNL-BPNL relation.

4. **Functional Requirements for the Pool and Gate Datamodel:**
   - Sequence for CRUD of hierarchies: **Portal UI ==> Portal Gate ==> Pool**.
   - Needed attributes: "valid to" and "valid from".
   - Initial hierarchy type: “Is Managed in Catena-X Portal By”.
   - Future hierarchy types: “Is Registered Alternative For”, “Is Replaced By”.
   - Support for multiple hierarchy types for each BPNL.
   - Relationship types: "public" and "non-public" (default: "non-public").
   - Admin roles: Full access to create and edit hierarchies.
   - Standard users: View-only access to hierarchies.

5. **Data Modeling and Integration:**
   - Adjust BPDM payload structure to include fields for new hierarchy types.
   - Ensure data model schema is updated to support the required hierarchy fields.

**Comment by Sebastian-Wurm** [comment]
@HeyHardy: This seems to be the implementation user story of the MVP. Shouldn't we move that from sig-release to bpdm?

**Comment by HeyHardy** [comment]
obsolete, work on here
https://github.com/eclipse-tractusx/bpdm/issues/1027

**Comment by nicoprow** [comment]
@HeyHardy since this issue is obsolete I will close it. Tell me if there is worth in keeping it open
