### ISSUE TITLE
Item Relationship Service (IRS) Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#86]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)** 

https://github.com/eclipse-tractusx/item-relationship-service/issues/237
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**

https://github.com/eclipse-tractusx/item-relationship-service/issues/237
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**

https://github.com/eclipse-tractusx/item-relationship-service/issues/237
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**

https://github.com/eclipse-tractusx/item-relationship-service/issues/237
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**

https://github.com/eclipse-tractusx/item-relationship-service/issues/237
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by mkanal** [comment]
@kelaja @guenterban 
PEN KeyCloak seems not to be working to successfully execute DAST tests. 
https://github.com/eclipse-tractusx/sig-infra/issues/346

**Comment by ds-jhartmann** [comment]
invicti scan passed with only medium and lower findings: https://www.netsparkercloud.com/scans/report/6addd8f3e5084e13a4c9b0b901f75d8c/
No new findings compared to last QG

**Comment by mkanal** [comment]
@guenterban 
Alignment took place by telephone on 13.11.2023. As there have been no changes since release 3.2, it is not necessary to update the Threat Modelling Analysis results

**Comment by ds-jhartmann** [comment]
**Secret scanning**
No secrets found in secret scan: https://github.com/eclipse-tractusx/item-relationship-service/security/secret-scanning

**Static Application Security Testing (SAST)**
32x the same medium finding, all are mitigated:
![image](https://github.com/eclipse-tractusx/sig-release/assets/57985712/42adf64f-c7b2-492c-a9cc-a7057f83cf1f)
![image](https://github.com/eclipse-tractusx/sig-release/assets/57985712/e918e2dd-0699-4c5f-b378-3a4603ffd865)

**Comment by mkanal** [comment]
Hi @kelaja  
kindly ask to close this ticket now. We have achieved all checks, is there anything more to do?
