### ISSUE TITLE
Item Relationship Service (IRS) Release 23.12 Compliance Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#88]
# Release Compliance 23.12

Source in Catena-X Confluence + Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ). (Source only accessible for Catena-X Consortia members in current transition phase)

- [x] **Gaia-X compliance** confirmed by dedicated expert.
  - Obtain approval from CX Gaia-X expert(s), prior to Gate review.
  - Provide info as early as possible; expect optimization loops based on feedback
  => check [linked PDF](https://confluence.catena-x.net/download/attachments/90498572/SD_Data_for_Onboarding.pdf?version=1&modificationDate=1690457195303&api=v2) summary for requirements (Source only accessible for Catena-X Consortia members in current transition phase).

  _Contact:_
     - Release Mangement

- [x] **GDPR compliance** confirmed
  (personal data; Data Protection & Privacy DPP)
  - assessment must be completed via Catena-X [GDPR questionnaire](https://confluence.catena-x.net/download/attachments/90498572/Catena-X%20GDPR%20Declaration%20and%20Requirements_V3.xlsx?version=1&modificationDate=1690457195339&api=v2) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - either the product/service doesn`t process any relevant data,
  - or - in case the assessment reveals potential issues - a more severe "Data Privacy Impact Assessment" shall be conducted (if applicable: robust mitigation actions must be completed)
  Provide evidence for GDPR compliance prior to Gate review. Previous assessments remain valid, as long as approach to handling of personal data was not changed.

   _Contact:_
     - Release Mangement

- [x] **Interoperability Check**

  Acceptance criteria are fulfilled as described in in the following area on confluence: [Interoperability Quality Gate Requirements](https://confluence.catena-x.net/x/DkwjB) (Source only accessible for Catena-X Consortia members in current transition phase.)

  - Approval will be documented centrally by Expert(s)

  - Obtain approval from Interoperability experts prior to Gate review.

  Therefore consult the [regular office hours](https://confluence.catena-x.net/x/fzkAAQ) as early as possible; expect optimization loops based on feedback. (Source only accessible for Catena-X Consortia members in current transition phase.)

  _Contact:_
    - SYSTEM ARCHITECT2

- [x] #351

  Acceptance criteria are fulfilled as described in in the following area on confluence:
  - [Data Sovereignty Guardrails for Release 3.2](https://confluence.catena-x.net/x/qPTeB) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - Approval will be documented centrally by Expert(s)
  - Obtain approval from Data Sovereignty experts prior to Gate review: Experts will schedule a review with your team.

  Expect optimization loops based on feedback.

  _Contact:_
    - SYSTEM ARCHITECT3,
    - SYSTEM ARCHITECT4

- [x] **Confirmation of _published_ CX Standards**
  
  Product Owner confirms:

  - The FOSS product under review is compliant to all relevant Catena-X Standards which are already published on the [Association website](https://catena-x.net/de/standard-library).
  - Failure to do so may ultimately make the reference implementation useless, as the mandatory CX Certification cannot be accomplished.

- [x] **Verification of _foreseen_ CX Standards**
  
  Product Owner confirms:

  - The content of upcoming CX Standardization Requests (STAN) has been reviewed and feedback was provided to the responsible PCA/BDA. As per current status, the FOSS product under review will be compliant as soon as the CX Standard is published. ([Info here](https://confluence.catena-x.net/x/XtyAAQ)) (Source only accessible for Catena-X Consortia members in current transition phase.)
  - Minimum: PCA/BDA have finalized all release-relevant Standardization Requests (STAN). Those have passed the CX Association`s technical committee (TC4S) and are pre-published on the website. Opt-out period in progress.
  - Best case: Association Board approval available and CX Standard is published on website.

**Comment by mkanal** [comment]
Hello  @jzbmw 
Verification of foreseen CX Standards
IRS standard CX-0005 and CX-0045 is ready for review. Please confirm

**Comment by jzbmw** [comment]
Herby I verify the CX Standards for the IRS

**Comment by mkanal** [comment]
No changes since last R3.2 release GDPR compliance confirmed together in meeting with Jens Weiss

**Comment by mkanal** [comment]
Felix Gerbig schrieb:
Hallo Martin, 

Ich denke wir können uns das Meeting sparen – an den Anforderungen zur Gaia-X Compliance hat sich bisher nichts geändert und ihr müsst als Anwendung nichts tun. 

Viele Grüße
Felix

**Comment by mkanal** [comment]
@kelaja 
Zuständigkeit QGates noch in Klärung Releasemanagement- (Eskalation ist erfolgt)
I will shift this ticket now to get more intrstructions how to deal with Data Sov Assessment,

**Comment by kelaja** [comment]
For Data Sovereignty POs can do a self-declaration if products have not undergone any significant changes.
See Links (available to Consortia Members only)
[2023-11-20 Stay informed](https://confluence.catena-x.net/display/PL/2023-11-20+Stay+informed) & [Release 23.12 & 24.03](https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621)

**Comment by mkanal** [comment]
![QualityGate](https://github.com/eclipse-tractusx/sig-release/assets/100209308/4de8ac66-a906-414a-97ff-587a2ae30aaf)

No significant changes since release 23.9 regarding data Data Sovereignty.
