### ISSUE TITLE
Knowledge Agent Release 23.12 Documentation Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#90]
# Release Documentation 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code**

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [ ] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [ ] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [x] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by TomBuchertTSystems** [comment]
No significant changes for this release. Focus for this release was on Agent KIT and new features that will not be released for 23.12

**Comment by kelaja** [comment]
@TomBuchertTSystems @vialkoje is this sufficient to approve the documentation Requirements for the Quality Gate?
Thanks & Rgds.
Kelaja

**Comment by kelaja** [comment]
@jjeroch kindly assess whether the UX from the Knowledge Agent can pass the QG :)

**Comment by TomBuchertTSystems** [comment]
Hey Kelaja, as I wrote we didn't change anything about the documentation which Jens approved for last Q Gate. KIT docu can be found here: https://eclipse-tractusx.github.io/docs-kits/next/category/agents-kit/

**Comment by kelaja** [comment]
@vialkoje kindly see @TomBuchertTSystems comment and decide on approval. Thx a lot & Regards

**Comment by jjeroch** [comment]
"UX consistency Style Guideline for User Interfaces" - n/a for the Knowledge Agent
@kelaja please update the status to "done" thanks!

**Comment by SebastianBezold** [comment]
Hi @kelaja and @drcgjung,

could you please clarify which of the "knowledge-" prefixed repos should be included in this release? I guess all of them right?

**Comment by vialkoje** [comment]
documenttaion available and looking consistent. expert approval granted for the documentation tasks

**Comment by SebastianBezold** [comment]
Release Guideline checks:

- eclipse-tractusx/knowledge-agents-edc#128

**Comment by SebastianBezold** [comment]
HI @drcgjung,

I can see a lot of open PRs at least on the knowledge-agents-edc repo. Could you please clarify if any of that is needed for the `23.12` release? Also, I cannot find a new "non-SNAPSHOT" release since `3.2`. Only chart releases. There is also no new Docker image with a non-SNAPSHOT image tag.

I guess it will be similar for all the other repos, right?

**Comment by drcgjung** [comment]
> HI @drcgjung,
> 
> I can see a lot of open PRs at least on the knowledge-agents-edc repo. Could you please clarify if any of that is needed for the `23.12` release? Also, I cannot find a new "non-SNAPSHOT" release since `3.2`. Only chart releases. There is also no new Docker image with a non-SNAPSHOT image tag.
> 
> I guess it will be similar for all the other repos, right?

@SebastianBezold thx for the heads up
- Only two repos will be released in 23.12: knowledge-agents-edc and knowledge-agents. (knowledge-agents-aas-bridge we did the initial contribution, but it is not functionally complete)
- For knowledge-agents-edc to release, could you please
  - Merge https://github.com/eclipse-tractusx/knowledge-agents-edc/pull/127
  - Create a new branch release/1.10.15, we would then create a PR with the removal of the SNAPSHOT version
  - Merge the removal PR and then tag the resulting commit
- For knowledge-agents to release, could you please
  - Merge https://github.com/eclipse-tractusx/knowledge-agents/pull/64
  -  Create a new branch release/1.10.15, we would then create a PR with the removal of the SNAPSHOT version
  - Merge the removal PR and then tag the resulting commit

Thx very much!

**Comment by SebastianBezold** [comment]
> > HI @drcgjung,
> > I can see a lot of open PRs at least on the knowledge-agents-edc repo. Could you please clarify if any of that is needed for the `23.12` release? Also, I cannot find a new "non-SNAPSHOT" release since `3.2`. Only chart releases. There is also no new Docker image with a non-SNAPSHOT image tag.
> > I guess it will be similar for all the other repos, right?
> 
> @SebastianBezold thx for the heads up
> 
> * Only two repos will be released in 23.12: knowledge-agents-edc and knowledge-agents. (knowledge-agents-aas-bridge we did the initial contribution, but it is not functionally complete)
> * For knowledge-agents-edc to release, could you please
>   
>   * Merge [fix: upgrade to TX-EDC 0.5.3 and resolve trivy/veracode issues. knowledge-agents-edc#127](https://github.com/eclipse-tractusx/knowledge-agents-edc/pull/127)
>   * Create a new branch release/1.10.15, we would then create a PR with the removal of the SNAPSHOT version
>   * Merge the removal PR and then tag the resulting commit
> * For knowledge-agents to release, could you please
>   
>   * Merge [fix: upgrade to Ontop 5.1.0 and resolve important trivy and veracode issues knowledge-agents#64](https://github.com/eclipse-tractusx/knowledge-agents/pull/64)
>   * Create a new branch release/1.10.15, we would then create a PR with the removal of the SNAPSHOT version
>   * Merge the removal PR and then tag the resulting commit
> 
> Thx very much!

`knowledge-agents-edc` [release branch](https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/release/1.10.15) created. I'll do the same for `knowledge-agents` in a sec

**Comment by SebastianBezold** [comment]
Hi @drcgjung,

release branch for `knowledge-agents` also created:

- `knowledge-agents`: https://github.com/eclipse-tractusx/knowledge-agents/tree/release/1.10.15
- `knowledge-agents-edc`: https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/release/1.10.15

I guess you can start preparing the releases.

**Comment by SebastianBezold** [comment]
Release Guideline checks done. The release itself is still missing for `knowledge-agents`, since there is an open IP check for ontop.
@drcgjung: If you can provide the updated `CHANGELOG.md` for both repos, I can also create the GitHub release

**Comment by drcgjung** [comment]
> Release Guideline checks done. The release itself is still missing for `knowledge-agents`, since there is an open IP check for ontop. @drcgjung: If you can provide the updated `CHANGELOG.md` for both repos, I can also create the GitHub release

changelog adapted (for knowledge-agents, I now took the ETA of the Eclipse IP check)

**Comment by SebastianBezold** [comment]
Knowledge Agent and Knowledge Agent EDC release done.

- https://github.com/eclipse-tractusx/knowledge-agents/releases/tag/v1.10.15
- https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.10.15
