### ISSUE TITLE
Establish interoperability tests between arbitrary connector versions

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#908]
# Overview

## Explain the topic in 2 sentences

Ensure interoperability between two arbitrary but built and for usage released connector versions.

## What's the benefit?

The risk, that regressions are built into a new version of the connector that implements an existing version of the Catena-X CX-0018 standard, will be minimized by providing an automated test suite that checks the interoperability with existing solution for a set of given test cases.

## What are the Risks/Dependencies ?

n/a

### Current implementation

Currently, the interoperability between two Eclipse Tractus-X connector implementations are based on the fact, that both versions implement the same DSP protocol version. With this feature, the ability to interoperate is made transparent by providing an interoperability test suite that allows to execute automated tests between two selectable but available connector versions.

### Proposed improvements

The implementation is built upon the work that is currently available https://github.com/eclipse-edc/CompatibilityTests which provides a DSP test suite that compares an existing version to the current main branch. This test suite needs to be enhanced with Catena-X specific test cases and made available in Eclipse Tractus-X to be executed on a defined set of version pairs for which the interoperability has to be ensured.

### Contributor

- Cofinity-X
- SAP

### Committer

- Andrea Bertagnolli

## User Stories

- tbd

## Acceptance Criteria

- [x] Test suite for interoperability tests exists and is part of the Eclipse Tractus-X EDC repository
- [x] A build automation exists that runs these tests on demand and if possible as part of a release process
- [ ] The interoperability test suite creates a test report which is attached as an artifact to releases and referred to in the change log information

## Test Cases

n/a as we talk about a test suite in this feature, which is executed but not tested.

## Architectural Relevance

The following items are ensured (answer: yes) after this issue is implemented:

- [X] This feature aligns with our current architectural guidelines
  - **Data Sovereignty:** All data sharing activities across company boundaries follow the [Catena-X Regulatory Framework](https://catenax-ev.github.io/docs/next/regulatory-framework/governance-framework), in particular the [Data Exchange Governance](https://catenax-ev.github.io/docs/next/regulatory-framework/20000ft/data-exchange-governance), and the [Dataspace Protocol](https://docs.internationaldataspaces.org/dataspace-protocol/overview/readme) via a compliant Connector (like the [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc) or similar, see [Connector KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/connector-kit))
    - [X] [CX-0010 Business Partner Number](https://catenax-ev.github.io/docs/next/standards/CX-0010-BusinessPartnerNumber)
    - [X] [CX-0013 Identity of Member Companies](https://catenax-ev.github.io/docs/next/standards/CX-0013-IdentityOfMemberCompanies)
    - [X] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
    - [X] [CX-0049 DID Document Schema](https://catenax-ev.github.io/docs/next/standards/CX-0049-DIDDocumentSchema)
    - [X] [CX-0050 Framework Agreement Credential](https://catenax-ev.github.io/docs/next/standards/CX-0050-FrameworkAgreementCredential)
    - [X] [CX-0149 Verified Company Identity](https://catenax-ev.github.io/docs/next/standards/CX-0149-Dataspaceidentityandidentification)
  - **Interoperability:** Digital Twins are used (compliant to the [Digital Twin KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/digital-twin-kit) and the [Industry Core KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/industry-core-kit))
    - [X] [CX-0001 EDC Discovery API](https://catenax-ev.github.io/docs/next/standards/CX-0001-EDCDiscoveryAPI)
    - [X] [CX-0002 Digital Twins in Catena-X](https://catenax-ev.github.io/docs/next/standards/CX-0002-DigitalTwinsInCatenaX)
    - [X] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
  - **Data Format:**
    - [X] The data model is based on a [published Semantic Model](https://github.com/eclipse-tractusx/sldt-semantic-models)
- [X] The impact on the overall system architecture has been assessed. The Feature does not require changes to the architecture or any existing standard? Please have a look here on the [overarching architecture](https://eclipse-tractusx.github.io/docs/tutorials/e2e/inform/architecture)
- [X] Potential risks or conflicts with existing architecture has been assessed

**Justification:** n/a

## Additional information

- [X] I am aware that my request may not be developed if no developer can be found for it. I'll try to contribute a developer (bring your own developer)

**Comment by ma3u** [comment]
Catena-X NEXT TAP7.2 also include these tests. So the test framework can be needed by this working group. Scheffler is lead.

**Comment by lgblaumeiser** [comment]
I close the issue as there is:
- The framework available upstream has been made available for the Tractus-X EDC release action
- The test suite is introduced in a way, that it always tests the current version to a configurable older version. That is different from the requirement, but it is sufficient, as it is not necessary to compare two released versions anymore. The functionality is capable of doing that, but not with currently implemented actions.
- The test reporting is cancelled for now, as there is a bigger issue on test reporting pngoing
