### ISSUE TITLE
Golden Record / BPN Service Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#95]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by rybtim** [comment]
Threat Modelling Analysis results were updated within last release 23.09 https://confluence.catena-x.net/x/Cm1HAw. No significant changes. Next update is planned in 24.03 with the upcoming breaking change of the generic endpoint and the implementation of the orchestrator. @kelaja

**Comment by rybtim** [comment]
Static Application Security Testing (SAST): No high risks found can you check @PiotrStys

**Comment by rybtim** [comment]
Dynamic Application Security Testing (DAST): The pen environment was setup for 21.12.2023 @PiotrStys can you check

**Comment by rybtim** [comment]
Software Composition Analysis (SCA): No high findings @klaudiaZF @Gitleena

**Comment by rybtim** [comment]
Container Scan conducted: No high findings @scherersebastian can you confirm

**Comment by rybtim** [comment]
Infrastructure as Code: No high findings @scherersebastian please confirm

**Comment by PiotrStys** [comment]
@rybtim, can you please provide the updated URL of the deployment?

**Comment by guenterban** [comment]
@kelaja: **Threat Modelling Analysis passed**

**Comment by SujitMBRDI** [comment]
> @rybtim, can you please provide the updated URL of the deployment?

Please find below links for deployed Pen environment
[https://argo.dev.demo.catena-x.net/applications/argocd/bpdm-pen?view=tree&resource=](https://argo.dev.demo.catena-x.net/applications/argocd/bpdm-pen?view=tree&resource=)
[https://business-partners-pen.dev.demo.catena-x.net/bridge/ui/swagger-ui/index.html](https://business-partners-pen.dev.demo.catena-x.net/bridge/ui/swagger-ui/index.html)
[https://business-partners-pen.dev.demo.catena-x.net/companies/test-company/ui/swagger-ui/index.html](https://business-partners-pen.dev.demo.catena-x.net/companies/test-company/ui/swagger-ui/index.html)
[https://business-partners-pen.dev.demo.catena-x.net/pool/ui/swagger-ui/index.html](https://business-partners-pen.dev.demo.catena-x.net/pool/ui/swagger-ui/index.html)

**Comment by PiotrStys** [comment]
@SujitMBRDI, @rybtim
Sorry but this is not clear enough to me. 

Are those URLs alternative deployments and is this enough to scan one of them?
I believe that so far we used the one below for assessments:
https://business-partners-pen.dev.demo.catena-x.net/pool

Does that seem to work for this QG as well?

**Comment by klaudiaZF** [comment]
Hi, can someone provide a link to project name in Veracode for SCA ?

**Comment by nicoprow** [comment]
> @SujitMBRDI, @rybtim Sorry but this is not clear enough to me.
> 
> Are those URLs alternative deployments and is this enough to scan one of them? I believe that so far we used the one below for assessments: https://business-partners-pen.dev.demo.catena-x.net/pool
> 
> Does that seem to work for this QG as well?

The last time we had two scans: One for the pool and one for the test-company subpath. These two would need to be executed again:

<img width="492" alt="grafik" src="https://github.com/eclipse-tractusx/sig-release/assets/95762387/6f7608cc-b7d5-4698-94a0-5fa4c9079e53">

**Comment by klaudiaZF** [comment]
Hi All,

**SCA passed**

<img width="834" alt="2023-11-27 13_46_33-Veracode Platform" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/85151731-fb77-4f2c-b2b7-b15c0ade909d">

**Comment by scherersebastian** [comment]
IaC/ KICS passed.
Container trivys scans passed
