### ISSUE TITLE
[R24.12] [Discovery Finder] Release Checks

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-release#971]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Responsible contacts**:

- Committer: @agg3fe , @tunacicek 
- ExpertGroup: @thomas-henn , @agg3fe , @tunacicek 
- Contributor contact: @agg3fe , @tunacicek 

**Version to be included in Eclipse Tractus-X release**:

helm: discoveryfinder-0.4.2
Image version: 0.5.2

**Leading product repository:** *[repository link](https://github.com/eclipse-tractusx/sldt-discovery-finder)*

## Compliance

- [x] Possible changes (through the new features) on related Catena-X standards are considered and addressed
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/176

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

## Functionality

**Hint: No features -> This release includes only Bugfix (CVEs)**
- [x] Feature works as expected and described
- [x] Backward compatibility maintained (depending Major/ Minor) 

## Performance

- [x] Memory and CPU usage is within acceptable limits oriented with goldilocks 

## Testing

- [x] Unit tests cover all new features
- [x] Integration tests are updated
- [x] E2E/Integration test passed
- [x] Regressions tests passed

## Feature summary

**Hint: No features implemented in this release. Only Bugfixes (CVEs)**

## Release Documentation

- [x] Release notes/Changelogs are updated (https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/v0.5.1/CHANGELOG.md)
- [x] Migration scripts/documentation are included if necessary (Ensure that any database or infrastructure migrations are included).

## Summary
**Hint: No features implemented in this release. Only Bugfixes (CVEs)**

## Helpful Links
- OpenAPI file: https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/v0.5.1/backend/src/main/resources/static/discovery-finder-openapi.yaml
- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by tunacicek** [comment]
Ee2 Tests:
No E2E Test is needed. Instead of, we tested our APIs on INT ENV successfully with our automated tests
See result: https://github.com/eclipse-tractusx/sldt-discovery-finder/actions/runs/11775588970

**Comment by ther3sa** [comment]
**QG Review**
Hi @tunacicek @agg3fe, 

I have a few questions regarding the current status:

- Could you give me an update on the checkbox performance?
- For clarity and documentation purposes, could you strike through the e2e test section since no e2e tests are required?
- Could you give me an update about the [TRG 1.05](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-05) architecture documentation because this TRG hasn’t been checked yet
- Lastly, I was wondering if there are no 'Known Knowns' for this issue?

Thank you for your help!

**Comment by tunacicek** [comment]
Hi @ther3sa, 
we released a new version which includes the new architecture structure. 
i updated release checks.

**Comment by ther3sa** [comment]
**Congrats**
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
