### ISSUE TITLE
BPDM Country Risk Release 23.12 Documentation Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#98]
# Release Documentation 23.12 

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ) (Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Source Code** https://github.com/eclipse-tractusx/vas-country-risk/issues/46
https://github.com/eclipse-tractusx/vas-country-risk-backend/issues/48

  - Code is centrally managed in Eclipse Tractus-X repository.
  - All active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled (with confirmation by DevSecOps SystemTeam).

  _Artefact Repo:_
    - [Eclipse Tractus-X](https://github.com/eclipse-tractusx)
    - FOSS [Infopage](https://confluence.catena-x.net/x/_AZHAw)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practice_
    - Consult the [regular office hours](https://catenax-ng.github.io/) as early as possible; expect optimization loops based on feedback.

  _Contact:_
    - DevSecOps System Team
  
- [x] **Architecture Documents**

  - Arc42 documentation completed for relevant product version.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X. Process the JIRA ticket and schedule an appointment with Expert to obtain approval prior to Gate review.
  - Provide link to documentation as early as possible and _mark changes_ to previous version (if applicable); expect optimization loops based on feedback.
  
  _Artefact Repo:_
    - [GitHub Readme how-to](https://confluence.catena-x.net/x/iVIAAQ) (Source only accessible for Catena-X Consortia members in current transition phase)

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Administrator`s Guide** (User assistance)

  - Admin Guide is available with the software at the same time
  - Admin Guide is correct and up to date; english is a must
  - The documentation is of appropriate maturity for any Operating Company with global business practice intentions.
  - In MarkDown format. Link to document available. Must point to leading repository within Tractus-X.
  
  _Best Practice_:

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that for example administrators get all the information they need to accomplish their tasks with the software. Refer to a administration guide, which covers "install/deploy, configure the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **End-User Manual** (User assistance)
  - End-User Manual is available with the software at the same time
  - End-User Manual is correct and up to date; english is a must
  - The documentation is of appropriate maturity to be handed over from the CX Consortia to any Operations Company with global business practice intentions.

  _Best Practice:_

    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - User assistance ensures that end users and others get all the information they need to accomplish their tasks with the software. Refer to a user guide, which covers "install/deploy, configure, and use the software" – as appropriate for the type of software and the information needs of the target group(s)
    - UI text and embedded help complete the User assistance.

  _Contact:_
    - SYSTEM ARCHITECT

- [x] **Interfaces Documentation**
  - API documentation contains all relevant interfaces for integration testing and is completed for relevant product version.
  - Link to document available.
  - Interface contract signed by all involved parties.

  _Best Practice:_
  
    - Process the issue and schedule an appointment with SYSTEM ARCHITECT to obtain approval prior to Gate review.
    - Provide link to documentation as early as possible and mark changes to previous version (if applicable); expect optimization loops based on feedback.
    - see [Open APIs](https://www.openapis.org/)

  _Contact:_ 
    - SYSTEM ARCHITECT

- [x] **UX consistency** Style Guideline for User Interfaces
  
    - Mandatory for FrontEnd modules where the IP is Open Source or owned by Catena-X.
    - User Interfaces are in line with the Catena-X Style Guidelines
      - user interface style review has been executed  (review owner: SYSTEM ARCHITECT5 UX)
      - review feedback (if existing) got incorporated
      - all findings are assessed
      - all findings (high/very high) are fixed or cleaned up (evidence by re-review)
      - approval of the application CX Style conformity is available (given by the review owner)

  _Best Practice:_
    - Obtain approval from Style Guideline Owner, prior to Gate review
    - use issue, include app URL & TestUser, assign to SYSTEM ARCHITECT5, expect review loop
    - [Style Components](https://portal.dev.demo.catena-x.net/_storybook/?path=/story)
    - [LINK](https://confluence.catena-x.net/x/DVIAAQ) to Style Guideline (Source only accessible for Catena-X Consortia members in current transition phase)
    - LINK to FrontEnd validations (will be added asap)
    - Please note, you can use the [official public available CX shared component library](https://www.npmjs.com/package/cx-portal-shared-components?activeTab=readme) (react supported) to easily develop applications that are in-line with the CX style guidelines

**Comment by fabiodmota** [comment]
Link for Source Code:
LeadingRepo :https://github.com/eclipse-tractusx/vas-country-risk
BackeEnd:  https://github.com/eclipse-tractusx/vas-country-risk-backend

Will be waiting for confirmation from DevSecOps SystemTeam for all active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled

**Comment by fabiodmota** [comment]
Arq42 Documentation: https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md
ticket from Arq42 changes that can be checked and have been validated 
Both Repos have Arq42 updated:
https://github.com/eclipse-tractusx/vas-country-risk/issues/40
https://github.com/eclipse-tractusx/vas-country-risk-backend/issues/30
PR created https://github.com/eclipse-tractusx/vas-country-risk/pull/37

waiting confirmation from SYSTEM ARCHITECT @vialkoje

**Comment by fabiodmota** [comment]
For Interfaces Documentation

https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#interfaces waiting confirmation from SYSTEM ARCHITECT @vialkoje

**Comment by fabiodmota** [comment]
Admin and User Guide:
Backend repo:
- https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/README.md
- https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/INSTALL.md
- https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/docs/User-Guide.md

Frontend repo:
- https://github.com/eclipse-tractusx/vas-country-risk/blob/main/README.md
- https://github.com/eclipse-tractusx/vas-country-risk/blob/main/INSTALL.md
- https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/User-Guide.md

Kit: https://eclipse-tractusx.github.io/docs-kits/kits/Business%20Partner%20Kit/Success%20Stories/Country%20Risk%20Score%C2%A0/

More Documentation regarding last QG release: 
https://confluence.catena-x.net/display/CORE/Country+Risk+Score+Dashboard

waiting confirmation from SYSTEM ARCHITECT @vialkoje

**Comment by Siegfriedk** [comment]
> Link for Source Code: LeadingRepo :https://github.com/eclipse-tractusx/vas-country-risk BackeEnd: https://github.com/eclipse-tractusx/vas-country-risk-backend
> 
> Will be waiting for confirmation from DevSecOps SystemTeam for all active and relevant [Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled @Siegfriedk

if you don't have any qg ticket in any of your repos, pls get in touch with the system team through our supportchannel

**Comment by SebastianBezold** [comment]
Release guideline checks tracked in the following issues:

- eclipse-tractusx/vas-country-risk#46
- eclipse-tractusx/vas-country-risk-backend#48

**Comment by SebastianBezold** [comment]
Hi @fabiodmota,

could you please clarify with versions of your apps should be released? Judging by the `CHANGELOG.md` files, it should be `v1.2.1`. should that be built from the latest main branch?
For your frontend, there is still the open PR eclipse-tractusx/vas-country-risk#43. Do you want to include this in the release?

**Comment by fabiodmota** [comment]
> Hi @fabiodmota,
> 
> could you please clarify with versions of your apps should be released? Judging by the `CHANGELOG.md` files, it should be `v1.2.1`. should that be built from the latest main branch? For your frontend, there is still the open PR [eclipse-tractusx/vas-country-risk#43](https://github.com/eclipse-tractusx/vas-country-risk/pull/43). Do you want to include this in the release?

Yes I'm waiting to this PR to be included since it includes Veracode vulnerability fixes and then it will be 1.2.1 according to changelog

**Comment by fabiodmota** [comment]
UPDATE: Once this https://github.com/eclipse-tractusx/vas-country-risk/pull/52 with stable version and all dependencies are accepted is merged we can release 1.2.1 according to CHANGELOG.md

**Comment by fabiodmota** [comment]
For topic UX consistency Style Guideline for User Interfaces, I await feedback from @jjeroch as soon as she is available, although there have been no changes in the FE since the last release made by this application.

**Comment by vialkoje** [comment]
Documentation for Architecture, User, Admin and interfaces existing. Expert approval granted

**Comment by RolaH1t** [comment]
> For topic UX consistency Style Guideline for User Interfaces, I await feedback from @jjeroch as soon as she is available, although there have been no changes in the FE since the last release made by this application.
> 
> Country Risk Url:
> 
> https://country-risk-dashboard.dev.demo.catena-x.net/ https://country-risk-dashboard.int.demo.catena-x.net/

@jjeroch CountryRisk ok from your side?

**Comment by fabiodmota** [comment]
> > For topic UX consistency Style Guideline for User Interfaces, I await feedback from @jjeroch as soon as she is available, although there have been no changes in the FE since the last release made by this application.
> > Country Risk Url:
> > https://country-risk-dashboard.dev.demo.catena-x.net/ https://country-risk-dashboard.int.demo.catena-x.net/
> 
> @jjeroch CountryRisk ok from your side?

Hi @jjeroch  , please check INT environment to be more consistent to last release https://country-risk-dashboard.int.demo.catena-x.net/ , represents last release for both frontend and backend app

**Comment by jjeroch** [comment]
Review UX.
Findings: all findings are medium - suggestion to create issue tickets for the next release.

1. Upload Rating Overlay
<img width="400" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/bc6a36a7-3e28-4ada-8439-0494d9bc77af">

- input and dropdown field headers should be left aligned
- mandatory fields should have an asterisk added (in red)
- the input field error message should not appear before the user even added any data
- if the display port is reduced - the overlay adjust to the given space which results to unreadable content and double scrolling possibilities. To be fixed - check with the component, the overlay should not shrink so much

2. Save Report Overlay
<img width="200" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/d247ec26-6a06-4c1c-a4ed-2f6adeaca54e">

- does not follow the official input field styling

3. About page is missing - this is already known by Fabio. @fabiodmota  by when will this page be available?

**Comment by fabiodmota** [comment]
> Review UX. Findings: all findings are medium - suggestion to create issue tickets for the next release.
> 
> 1. Upload Rating Overlay
> 
> <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/94133633/288055263-bc6a36a7-3e28-4ada-8439-0494d9bc77af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODM5ODksIm5iZiI6MTcwMTc4MzY4OSwicGF0aCI6Ii85NDEzMzYzMy8yODgwNTUyNjMtYmM2YTM2YTctM2UyOC00YWRhLTg0MzktMDQ5NGQ5YmM3N2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEzNDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTBhZTAwMzJjNTZjNGQ2ZDc4YWE5ZTljZDBjNzcwMmQxY2VjMTNhZjEzZWIwMDExNWY4NzA4MDM2MzVhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pve1kXGbOtqGZf_jOQGlYbHQ7_YUZ98bm-Eg522q_No">
> * input and dropdown field headers should be left aligned
> * mandatory fields should have an asterisk added (in red)
> * the input field error message should not appear before the user even added any data
> * if the display port is reduced - the overlay adjust to the given space which results to unreadable content and double scrolling possibilities. To be fixed - check with the component, the overlay should not shrink so much
> 
> 2. Save Report Overlay
> 
> <img alt="image" width="200" src="https://private-user-images.githubusercontent.com/94133633/288056398-d247ec26-6a06-4c1c-a4ed-2f6adeaca54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODM5ODksIm5iZiI6MTcwMTc4MzY4OSwicGF0aCI6Ii85NDEzMzYzMy8yODgwNTYzOTgtZDI0N2VjMjYtNmEwNi00YzFjLWE0ZWQtMmY2YWRlYWNhNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEzNDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWJhOWNjMGIyYjBkYjM4YjQwZGJhYjcyNDU5ZjcxZDdkMjFiZGRiMzE1NWM0ODhlNWQ3NzVhOTM2ZWY4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kp2GYpbaJyaxYJ6YDK_ALV9pUfQFUIk8YIRN7Sk_oRw">
> * does not follow the official input field styling
> 
> 3. About page is missing - this is already known by Fabio. @fabiodmota  by when will this page be available?

Thank you Julia, already created issues for next release based on your findings:

- https://github.com/eclipse-tractusx/vas-country-risk/issues/62 
- https://github.com/eclipse-tractusx/vas-country-risk/issues/63 
- https://github.com/eclipse-tractusx/vas-country-risk/issues/64 

Next week latest we can have the new page already deployed

**Comment by SebastianBezold** [comment]
Hi @fabiodmota,

you know, that a missing about page is a legal issue? This missing is a blocking issue from my point of view. The relevant TRG is know for long enough.
Ones you added that, you need to release a new version in my opinion and include this in the Tractus-X release

FYI: @RolaH1t, @kelaja

**Comment by RolaH1t** [comment]
I have adjusted the ticket status to "in prep" - based on Sebastian`s comment.
@SebastianBezold pls withdraw the "check in the box" => I don`t understand how this was granted, if not all relevant TRGs are fulfilled...
@fabiodmota pls resolve the issue(s) and contact Sebastian (System Team in general) for a new review

**Comment by SebastianBezold** [comment]
> I have adjusted the ticket status to "in prep" - based on Sebastian`s comment. @SebastianBezold pls withdraw the "check in the box" => I don`t understand how this was granted, if not all relevant TRGs are fulfilled... @fabiodmota pls resolve the issue(s) and contact Sebastian (System Team in general) for a new review

I was relying on this comment: https://github.com/eclipse-tractusx/vas-country-risk/issues/46#issuecomment-1826374982

**Comment by SebastianBezold** [comment]
New release with About section created: https://github.com/eclipse-tractusx/vas-country-risk/releases/tag/v1.3.0
