### ISSUE TITLE
[BPDM] Release Checks

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/sig-release#984]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Responsible contacts**:

- Committer(s): @nicoprow, @SujitMBRDI 
- ExpertGroup: @HeyHardy 

**Version to be included in Eclipse Tractus-X release**:

- App Version: 6.2.0
- Helm Chart Version: 5.2.0

**Leading product repository:** [bpdm](https://github.com/eclipse-tractusx/bpdm)

## Compliance

- [x] Possible changes (through the new features) on related Catena-X standards are considered and addressed
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled (see for details)

Product release issue:  eclipse-tractusx/sig-release#1082

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

## Functionality

- [x] Feature works as expected and described
- [x] Backward compatibility maintained (depending Major/ Minor) 

## Performance

- [x] Memory and CPU usage is within acceptable limits oriented with goldilocks 

## Testing

- [x] Unit tests cover all new features
- [x] Integration tests are updated
- [x] E2E/Integration test passed
- [x] Regressions tests passed

## Feature summary

Please provide a list of all features that have been developed in the current phase. This list is essential for several reasons:

- **Test Preparation:** Identifying new features will help in the creation of new end-to-end (E2E) tests and ensure that the relevant aspects are thoroughly tested.
- **Awareness:** It will raise awareness of the features that need to be prioritized during the testing process.
- **Board Management:** This will assist in keeping the project board organized and up-to-date.

By documenting these features, you will contribute to a smoother and more efficient release process.

> [!NOTE]
> Note: all features needs to be closed to get approval for release

| Feature | Test Status | Note |
|----------|----------|----------|
| Upload business partner data as .CSV #700 | Tested succesfully |  |
| New Legal Forms Data model #602 | Tested successfully |  |
| New Identifier Type Data model #605| Tested Successfully |  |
| Publish API specifications to API Hub https://github.com/eclipse-tractusx/bpdm/issues/1012 | successfully tested  |  |
| Adhere to Changes in TRG1 https://github.com/eclipse-tractusx/bpdm/pull/1010 |  successfully tested |  |

## Release Documentation

- [x] Release notes/Changelogs are updated
- [x] Migration scripts/documentation are included if necessary (Ensure that any database or infrastructure migrations are included).

## Summary

Please provide a short summary about the new values/benefits of the new features here:

## Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ther3sa** [comment]
**QG Review**

- To ensure transparency, could you please check off any topics that have already been worked on or completed?
- Are there no 'Known Knowns' for this issue? 

Thank you for your help!

**Comment by ther3sa** [comment]
Hi @nicoprow, @SujitMBRDI
could you give me an update on the current status of: 
- the TRGs
- the Release notes/Changelogs

Thank you. :)

**Comment by nicoprow** [comment]
> Hi @nicoprow, @SujitMBRDI could you give me an update on the current status of:
> 
>     * the TRGs
> 
>     * the Release notes/Changelogs
> 
> 
> Thank you. :)

We are currently updating the documentation of the repository in order to prepare for the release. Once the documentation is completely updated, we create the release including release notes. From there on most TRGs will be fulfilled or can be checked quickly. We are expecting to finish this up until end of this week

**Comment by ther3sa** [comment]
> > Hi @nicoprow, @SujitMBRDI could you give me an update on the current status of:
> > ```
> > * the TRGs
> > 
> > * the Release notes/Changelogs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you. :)
> 
> We are currently updating the documentation of the repository in order to prepare for the release. Once the documentation is completely updated, we create the release including release notes. From there on most TRGs will be fulfilled or can be checked quickly. We are expecting to finish this up until end of this week

Thank you for your update

**Comment by nicoprow** [comment]
BPDM 6.2.0/ BPDM Charts 5.2.0 released 

https://github.com/eclipse-tractusx/bpdm/releases/tag/v6.2.0
https://github.com/eclipse-tractusx/bpdm/releases/tag/bpdm-5.2.0

**Comment by ther3sa** [comment]
Hi there,

I wanted to check in and ask if you have an estimated timeline for completing the TRG checks.

Thanks in advance for your update!

**Comment by SujitMBRDI** [comment]
> Hi there,
> 
> I wanted to check in and ask if you have an estimated timeline for completing the TRG checks.
> 
> Thanks in advance for your update!

Hi @ther3sa,

We forgot to tick check box from issue here. 
But we already covered all TRG checks under issue [1082](https://github.com/eclipse-tractusx/bpdm/issues/1082) and mentioned about met conditions as well there.

**Comment by ther3sa** [comment]
Congrats 🎉
Quality Gate fully approved with all necessary pre-requisites fulfilled! 
Thanks for all your efforts :)
