### ISSUE TITLE
BPDM Country Risk Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#99]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by PiotrStys** [comment]
Hello, 

The Invicti scans have nor reported any high/critical vulnerabilities.


![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/54707deb-d2e4-4c74-b616-d580a0990c40)

**DAST Passed**

Regards,
Piotr

**Comment by kelaja** [comment]
@fabiodmota @enzio-bot  today is QGate, where are the links for the SEC Team colleagues?
Who to reach out to you can find [here](https://confluence.catena-x.net/pages/viewpage.action?pageId=90496621)

**Comment by fabiodmota** [comment]
Hi @kelaja 
Veracode:
Backend: https://analysiscenter.veracode.com/auth/index.jsp#HomeAppProfile:47240:1561104 
![image](https://github.com/eclipse-tractusx/sig-release/assets/107047355/a2c7453f-4ae4-4a37-a11f-8649280a940c)

Frontend: https://analysiscenter.veracode.com/auth/index.jsp#HomeAppProfile:47240:1585726
Not Yet passed waiting on PR https://github.com/eclipse-tractusx/vas-country-risk/pull/43

Trivy Kicks Git Guardian:
Backend: https://github.com/eclipse-tractusx/vas-country-risk-backend/actions
Frontend: https://github.com/eclipse-tractusx/vas-country-risk/actions

**Comment by Gitleena** [comment]
Hi All,

**SCA for product-vas-country-risk-backend is passed**

![image](https://github.com/eclipse-tractusx/sig-release/assets/128478249/6b1abe40-a0d7-4496-9428-5a2facea2557)

Please be aware of medium findings that are open:

![image](https://github.com/eclipse-tractusx/sig-release/assets/128478249/16e8ffe6-565a-4b56-a243-3dc8dc491cde)


**SCA for product-vas-country-risk-frontend is passed**

![image](https://github.com/eclipse-tractusx/sig-release/assets/128478249/7b3e3a3d-dc43-4221-8337-f3d7a0f5ce3c)

Please be aware of medium findings that are open:

![image](https://github.com/eclipse-tractusx/sig-release/assets/128478249/00c3bed8-68b8-490b-8e08-c1eaba1a7b08)

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:

![image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/1f791fc8-c52c-4532-b2b1-a7def3547b48)

-> **Secret scanning approved**

Best regards
Daniel

**Comment by klaudiaZF** [comment]
Hi All,

**SAST passed** for both frontend and backend

<img width="835" alt="product-vas-country-risk-backend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/105e1cc7-c6f0-42f0-8d8b-3acc23f438e9">

<img width="835" alt="product-vas-country-risk-frontend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/5067ab15-30cc-478c-9c25-86e1093af50a">

Just please keep in mind that we have few open medium findings:

<img width="947" alt="product-vas-country-risk-backend1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/f1165f54-7d9d-4c6f-a4d5-e61aa94858b3">

**Comment by scherersebastian** [comment]
trivy backend has findings, please check https://github.com/eclipse-tractusx/vas-country-risk-backend/security/code-scanning
kics passed

**Comment by scherersebastian** [comment]
As communicated with Fabio, trivy findings are fixed :)
Container Scan / trivy passed

**Comment by fabiodmota** [comment]
waiting on @guenterban for the Threat Modelling Analysis results to complete all validations

**Comment by guenterban** [comment]
**Threat Modelling Analysis appoved**
